---
permalink: api-automation/concept_verify_svm_workflow.html 
sidebar: sidebar 
keywords: verify, svms, clusters 
summary: '파일 공유 또는 LUN을 프로비저닝하기 전에 클러스터에 SVM(Storage Virtual Machine)이 생성되어 있는지 확인해야 합니다.' 
---
= 클러스터에서 SVM 확인
:icons: font
:imagesdir: ../media/


[role="lead"]
파일 공유 또는 LUN을 프로비저닝하기 전에 클러스터에 SVM(Storage Virtual Machine)이 생성되어 있는지 확인해야 합니다.

[NOTE]
====
워크플로우에서 ONTAP 클러스터가 Unified Manager에 추가되었으며 클러스터 키가 있다고 가정합니다. 클러스터에는 LUN 및 파일 공유를 프로비저닝하는 데 필요한 라이센스가 있어야 합니다.

====
. 클러스터에 SVM이 생성되었는지 확인합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
데이터 센터
 a| 
가져오기
 a| 
'/datacenter/svm/sSVM'//datacenter/svm/sSVM/\{key}'

|===
+
* 샘플 컬 *

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. SVM 키가 반환되지 않으면 SVM을 생성합니다. SVM을 생성하려면 SVM을 프로비저닝할 클러스터 키가 필요합니다. SVM 이름을 지정해야 합니다. 다음 단계를 수행합니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
데이터 센터
 a| 
가져오기
 a| 
'/datacenter/cluster/cluster''/datacenter/cluster/cluster/\{key}'

|===
+
클러스터 키를 가져옵니다.

+
* 샘플 컬 *

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. 출력에서 클러스터 키를 가져온 다음 SVM 생성을 위한 입력으로 사용합니다.
+
[NOTE]
====
SVM을 생성하는 동안 LUN 및 파일 공유를 프로비저닝하는 데 필요한 프로토콜(예: CIFS, NFS, FCP, 및 iSCSI를 지원합니다. SVM이 필요한 서비스를 지원하지 않으면 프로비저닝 워크플로우가 실패할 수 있습니다. 각 워크로드 유형에 대한 서비스도 SVM에서 활성화하는 것이 좋습니다.

====
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
데이터 센터
 a| 
게시
 a| 
'/datacenter/svm/sSVM'

|===
+
* 샘플 컬 *

+
SVM 객체 세부 정보를 입력 매개 변수로 입력합니다.

+
[listing]
----
curl -X POST "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" "{ \"aggregates\": [ { \"_links\": {}, \"key\": \"1cd8a442-86d1,type=objecttype,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\",
\"name\": \"cluster2\", \"uuid\": \"02c9e252-41be-11e9-81d5-00a0986138f7\" } ],
\"cifs\": { \"ad_domain\": { \"fqdn\": \"string\", \"password\": \"string\",
\"user\": \"string\" }, \"enabled\": true, \"name\": \"CIFS1\" },
\"cluster\": { \"key\": \"1cd8a442-86d1-11e0-ae1c-123478563412,type=object type,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\" },
\"dns\": { \"domains\": [ \"example.com\", \"example2.example3.com\" ],
\"servers\": [ \"10.224.65.20\", \"2001:db08:a0b:12f0::1\" ] },
\"fcp\": { \"enabled\": true }, \"ip_interface\": [ { \"enabled\": true,
\"ip\": { \"address\": \"10.10.10.7\", \"netmask\": \"24\" },
\"location\": { \"home_node\": { \"name\": \"node1\" } }, \"name\":
\"dataLif1\" } ], \"ipspace\": { \"name\": \"exchange\" },
\"iscsi\": { \"enabled\": true }, \"language\": \"c.utf_8\",
\"ldap\": { \"ad_domain\": \"string\", \"base_dn\": \"string\",
\"bind_dn\": \"string\", \"enabled\": true, \"servers\": [ \"string\" ] },
\"name\": \"svm1\", \"nfs\": { \"enabled\": true },
\"nis\": { \"domain\": \"string\", \"enabled\": true,
\"servers\": [ \"string\" ] }, \"nvme\": { \"enabled\": true },
\"routes\": [ { \"destination\": { \"address\": \"10.10.10.7\",
\"netmask\": \"24\" }, \"gateway\": \"string\" } ],
\"snapshot_policy\": { \"name\": \"default\" },
\"state\": \"running\", \"subtype\": \"default\"}"
----
+
JSON 출력에는 생성한 SVM을 확인하는 데 사용할 수 있는 작업 오브젝트 키가 표시됩니다.

. 쿼리에 작업 오브젝트 키를 사용하여 SVM 생성을 확인합니다. SVM이 성공적으로 생성되면 응답 시 SVM 키가 반환됩니다.
+
[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
'/management-server/jobs/\{key}'

|===

