---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: 공통 워크플로우를 통해 클라이언트 애플리케이션 개발자는 클라이언트 애플리케이션이 Active IQ Unified Manager API를 사용하여 일반적인 스토리지 관리 기능을 실행하는 방법의 예를 볼 수 있습니다. 이 섹션에서는 이러한 샘플 워크플로 중 일부를 다룹니다. 
---
= 스토리지 관리를 위한 공통 워크플로우
:icons: font
:imagesdir: ../media/


[role="lead"]
공통 워크플로우를 통해 클라이언트 애플리케이션 개발자는 클라이언트 애플리케이션이 Active IQ Unified Manager API를 사용하여 일반적인 스토리지 관리 기능을 실행하는 방법의 예를 볼 수 있습니다. 이 섹션에서는 이러한 샘플 워크플로 중 일부를 다룹니다.

워크플로는 일반적으로 사용되는 일부 저장소 관리 사용 사례와 사용할 샘플 코드를 설명합니다. 각 작업은 하나 이상의 API 호출로 구성된 워크플로 프로세스를 사용하여 설명됩니다.



== 워크플로에 사용되는 API 호출 이해

모든 REST API 호출에 대한 세부 정보가 포함된 Unified Manager 인스턴스에서 온라인 설명서 페이지를 볼 수 있습니다. 이 문서에서는 온라인 설명서의 세부 사항을 반복하지 않습니다. 이 문서의 워크플로 샘플에 사용되는 각 API 호출에는 문서 페이지에서 호출을 찾는 데 필요한 정보만 포함됩니다. 특정 API 호출을 찾은 후에는 입력 매개 변수, 출력 형식, HTTP 상태 코드 및 요청 처리 유형을 비롯한 전체 호출 세부 정보를 검토할 수 있습니다.

문서 페이지에서 호출을 쉽게 찾을 수 있도록 워크플로 내의 각 API 호출에 대해 다음 정보가 포함되어 있습니다.

* 범주: API 호출은 문서 페이지에서 기능적으로 관련된 영역이나 범주로 구성됩니다. 특정 API 호출을 찾으려면 페이지 하단으로 스크롤하여 해당 API 범주를 클릭합니다.
* HTTP 동사(호출): HTTP 동사는 리소스에 대해 수행되는 작업을 식별합니다. 각 API 호출은 단일 HTTP 동사를 통해 실행됩니다.
* 경로: 경로는 호출을 수행하는 과정에서 작업이 적용되는 특정 리소스를 결정합니다. 경로 문자열이 핵심 URL에 추가되어 리소스를 식별하는 전체 URL을 구성합니다.

