---
permalink: api-automation/concept_manage_psl.html 
sidebar: sidebar 
keywords: manage, performance, service, level 
summary: Active IQ Unified Manager에서 스토리지 공급자 API를 사용하여 성능 서비스 수준을 확인, 생성, 수정 및 삭제할 수 있습니다. 
---
= 성능 서비스 수준 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager에서 스토리지 공급자 API를 사용하여 성능 서비스 수준을 확인, 생성, 수정 및 삭제할 수 있습니다.



== 성능 서비스 수준을 봅니다

다음 방법을 사용하여 스토리지 워크로드에 할당할 성능 서비스 수준을 볼 수 있습니다. API는 시스템 정의 및 사용자가 생성한 모든 성능 서비스 수준을 나열하고 모든 성능 서비스 수준의 특성을 검색합니다. 특정 성능 서비스 수준을 쿼리하려면 성능 서비스 수준의 고유 ID를 입력하여 세부 정보를 검색해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/스토리지 공급자/성능 서비스 수준'

'/storage-provider/performance-service-levels/\{key}'

|===


== 성능 서비스 수준 추가

시스템 정의 성능 서비스 수준이 스토리지 워크로드의 SLO(서비스 수준 목표)를 충족하지 못하는 경우 다음 방법을 사용하여 맞춤형 성능 서비스 수준을 생성하고 이를 스토리지 워크로드에 할당할 수 있습니다. 생성하려는 성능 서비스 수준에 대한 세부 정보를 입력합니다. IOPS 속성의 경우 유효한 값 범위를 입력해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
게시
 a| 
'/스토리지 공급자/성능 서비스 수준'

|===


== 성능 서비스 수준을 삭제합니다

다음 방법을 사용하여 특정 성능 서비스 수준을 삭제할 수 있습니다. 워크로드에 할당된 경우 또는 사용 가능한 유일한 성능 서비스 레벨인 경우 성능 서비스 레벨을 삭제할 수 없습니다. 특정 성능 서비스 수준을 삭제하려면 입력 매개 변수로 성능 서비스 수준의 고유 ID를 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
삭제
 a| 
'/storage-provider/performance-service-levels/\{key}'

|===


== 성능 서비스 수준을 수정합니다

다음 메서드를 사용하여 성능 서비스 수준을 수정하고 해당 속성을 업데이트할 수 있습니다. 시스템 정의이거나 워크로드에 할당된 성능 서비스 수준은 수정할 수 없습니다. 특정 성능 서비스 수준을 수정하려면 의 고유 ID를 제공해야 합니다. 또한 업데이트할 IOPS 속성과 유효한 값을 입력해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
패치
 a| 
'/storage-provider/performance-service-levels/\{key}'

|===


== 성능 서비스 수준에 따라 집계 기능 보기

다음 방법을 사용하여 성능 서비스 수준에 따라 집계 기능을 쿼리할 수 있습니다. 이 API는 데이터 센터에서 사용할 수 있는 애그리게이트 목록을 반환하고 해당 애그리게이트에서 지원되는 성능 서비스 수준과 관련된 기능을 나타냅니다. 볼륨에서 워크로드를 프로비저닝하는 동안 특정 성능 서비스 수준을 지원하는 애그리게이트의 기능을 확인하고 해당 기능을 기준으로 워크로드를 프로비저닝할 수 있습니다. Aggregate를 지정하는 기능은 API를 사용하여 워크로드를 프로비저닝할 때만 사용할 수 있습니다. 이 기능은 Unified Manager 웹 UI에서 사용할 수 없습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/스토리지 공급자/집계 기능'

'/storage-provider/aggregate-capabilities/\{key}'

|===