---
permalink: api-automation/concept_async_run.html 
sidebar: sidebar 
keywords: job, objects, asynchronous, processes 
summary: Active IQ Unified Manager는 다른 API를 실행하는 동안 수행된 작업에 대한 정보를 검색하는 작업 API를 제공합니다. 작업 개체를 사용하여 비동기 처리가 작동하는 방식을 알아야 합니다. 
---
= 작업 객체 비동기 프로세스
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager는 다른 API를 실행하면서 수행된 작업에 대한 정보를 검색하는 jobs API를 제공한다. 작업 개체를 사용하여 비동기 처리가 작동하는 방식을 알아야 합니다.

일부 API 호출, 특히 리소스를 추가하거나 수정하는 데 사용되는 호출은 다른 호출보다 완료하는 데 시간이 오래 걸릴 수 있습니다. Unified Manager는 오래 실행되는 이러한 요청을 비동기식으로 처리합니다.



== 작업 개체를 사용하여 설명된 비동기 요청

비동기적으로 실행되는 API 호출을 수행한 후 HTTP 응답 코드 202는 요청이 성공적으로 유효성 확인 및 승인되었지만 아직 완료되지 않았음을 나타냅니다. 요청은 클라이언트에 대한 초기 HTTP 응답 후 계속 실행되는 백그라운드 작업으로 처리됩니다. 응답에는 고유한 식별자를 포함하여 요청을 고정하는 작업 객체가 포함됩니다.



== API 요청과 관련된 작업 객체를 쿼리합니다

HTTP 응답에서 반환된 작업 개체에는 여러 속성이 포함되어 있습니다. 상태 속성을 쿼리하여 요청이 성공적으로 완료되었는지 확인할 수 있습니다. 작업 오브젝트는 다음 상태 중 하나일 수 있습니다.

* '정상'입니다
* 경고
* partial_failures를 선택합니다
* "오류"


작업 개체를 폴링하여 작업의 터미널 상태를 감지할 때 성공 또는 실패 등 두 가지 방법을 사용할 수 있습니다.

* 표준 폴링 요청: 현재 작업 상태가 즉시 반환됩니다.
* 긴 폴링 요청: 작업 상태가 정상, 오류 또는 partial_failures로 이동하는 경우




== 비동기 요청의 단계입니다

다음 고급 절차를 사용하여 비동기 API 호출을 완료할 수 있습니다.

. 비동기 API 호출을 실행합니다.
. 요청을 성공적으로 수락했음을 나타내는 HTTP 응답 202 을 수신합니다.
. 응답 본문에서 작업 객체의 식별자를 추출합니다.
. 루프 내에서 작업 객체가 터미널 상태인 정상, 오류 또는 partial_failures에 도달할 때까지 기다립니다
. 작업의 터미널 상태를 확인하고 작업 결과를 가져옵니다.

