---
permalink: api-automation/concept_job_api.html 
sidebar: sidebar 
keywords: jobs, view 
summary: 관리 서버 범주 아래에 있는 작업 API를 사용하여 비동기 작업의 실행 세부 정보를 볼 수 있습니다. 
---
= 작업 및 시스템 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Management-server 범주에서 jobs API를 사용하여 비동기 작업의 실행 세부 정보를 볼 수 있습니다. '관리 서버' 범주의 '시스템' API를 사용하면 Active IQ Unified Manager 환경에서 인스턴스 세부 정보를 볼 수 있습니다.



== 작업 보기

Active IQ Unified Manager에서는 리소스를 추가 및 수정하는 등의 작업이 동기 및 비동기 API 호출에 의해 수행됩니다. 비동기 실행을 위해 예약된 호출은 해당 호출에 대해 만들어진 Job 개체에서 추적할 수 있습니다. 각 작업 오브젝트에는 식별을 위한 고유한 키가 있습니다. 각 작업 개체는 작업 진행률을 액세스하고 추적할 수 있도록 작업 개체 URI를 반환합니다. 이 API를 사용하여 각 실행의 세부 정보를 검색할 수 있습니다.

이 API를 사용하면 내역 데이터를 포함하여 데이터 센터의 모든 작업 객체를 쿼리할 수 있습니다. 기본적으로 모든 작업을 쿼리하면 웹 UI 및 API 인터페이스를 통해 트리거된 마지막 20개 작업의 세부 정보가 반환됩니다. 내장된 필터를 사용하여 특정 작업을 봅니다. 작업 키를 사용하여 특정 작업의 세부 정보를 쿼리하고 리소스에 대한 다음 작업 집합을 실행할 수도 있습니다.

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
(/management-server/jobs)
 a| 
모든 작업의 작업 세부 정보를 반환합니다. 정렬 순서가 없으면 마지막으로 제출한 작업 객체가 맨 위에 반환됩니다.



 a| 
관리 - 서버
 a| 
가져오기
 a| 
'/management-server/jobs/\{key}'

해당 작업의 특정 세부 정보를 보려면 작업 오브젝트의 작업 키를 입력합니다.
 a| 
특정 작업 오브젝트의 세부 정보를 반환합니다.

|===


== 시스템 세부 정보 보기

'/management-server/system' API를 사용하여 Unified Manager 환경의 인스턴스별 세부 정보를 쿼리할 수 있습니다. API는 시스템에 설치된 Unified Manager 버전, UUID, 공급업체 이름, 호스트 OS, 이름 등과 같은 제품 및 서비스에 대한 정보를 반환합니다. Unified Manager 인스턴스에서 실행 중인 서비스에 대한 설명 및 상태

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
(/management-server/system)
 a| 
이 API를 실행하는 데 필요한 입력 매개 변수가 없습니다. 현재 Unified Manager 인스턴스의 시스템 세부 정보가 기본적으로 반환됩니다.

|===