---
permalink: api-automation/concept_rest_services_offered_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: rest, services, offer, active iq, unified, manager 
summary: Active IQ Unified Manager API를 사용하기 전에 제공되는 REST 서비스 및 작업을 알고 있어야 합니다. 
---
= Active IQ Unified Manager에서 제공되는 REST 서비스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager API를 사용하기 전에 제공되는 REST 서비스 및 작업을 알고 있어야 합니다.

API 서버를 구성하는 데 사용되는 프로비저닝 및 관리 API는 읽기(GET) 또는 쓰기(POST, 패치, 삭제) 작업을 지원합니다. 다음은 API에서 지원하는 GET, 패치, POST 및 삭제 작업의 몇 가지 예입니다.

* Get:'Get/DataCenter/cluster/cluster'는 데이터 센터의 클러스터 세부 정보를 검색합니다. Get 작업에 의해 반환되는 최대 레코드 수는 1000개입니다.
+
[NOTE]
====
API를 사용하면 지원되는 속성별로 레코드를 필터링, 정렬 및 정렬할 수 있습니다.

====
* POST의 예: 'POST/DataCenter/svm/sSVM'은 맞춤형 SVM(Storage Virtual Machine)을 생성합니다.
* 패치 예: 'patch/datacenter/svm/sSVM/{key}'는 고유한 키를 사용하여 SVM의 속성을 수정합니다.
* 예: 삭제/storage-provider/access-endpoints/{key}'는 고유 키를 사용하여 LUN, SVM 또는 파일 공유에서 액세스 끝점을 삭제합니다.


API를 사용하여 수행할 수 있는 나머지 작업은 운영자, 스토리지 관리자 또는 애플리케이션 관리자 사용자의 역할에 따라 다릅니다.

[cols="2*"]
|===
| 사용자 역할 | REST 방식 지원 


 a| 
운영자
 a| 
데이터에 대한 읽기 전용 액세스. 이 역할을 가진 사용자는 모든 GET 요청을 실행할 수 있습니다.



 a| 
스토리지 관리자
 a| 
모든 데이터에 대한 읽기 액세스. 이 역할을 가진 사용자는 모든 GET 요청을 실행할 수 있습니다.

또한 패치, POST 및 삭제 요청을 실행하기 위한 쓰기 액세스 권한이 있어 관리, 스토리지 서비스 개체 및 스토리지 관리 옵션과 같은 특정 작업을 수행할 수 있습니다.



 a| 
응용 프로그램 관리자
 a| 
모든 데이터에 대한 읽기 및 쓰기 액세스 이 역할을 가진 사용자는 모든 기능에 대한 GET, 패치, POST 및 삭제 요청을 실행할 수 있습니다.

|===
모든 REST 작업에 대한 자세한 내용은 _Online API 설명서_를 참조하십시오.
