---
permalink: api-automation/concept_data_center_apis.html 
sidebar: sidebar 
keywords: manage, storage, objects, data center 
summary: 데이터 센터 범주의 REST API를 사용하여 클러스터, 노드, 애그리게이트, 스토리지 VM과 같은 데이터 센터의 스토리지 오브젝트를 관리할 수 있습니다. 볼륨, LUN, 파일 공유 및 네임스페이스. 이러한 API는 개체의 구성을 쿼리하는 데 사용할 수 있는 반면, 일부 API를 사용하면 이러한 개체를 추가, 삭제 또는 수정하는 작업을 수행할 수 있습니다. 
---
= API를 사용하여 데이터 센터의 스토리지 객체를 관리합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터센터 범주의 REST API를 사용하면 클러스터, 노드, 애그리게이트, 스토리지 VM과 같은 데이터 센터의 스토리지 객체를 관리할 수 있습니다. 볼륨, LUN, 파일 공유 및 네임스페이스. 이러한 API는 개체의 구성을 쿼리하는 데 사용할 수 있는 반면, 일부 API를 사용하면 이러한 개체를 추가, 삭제 또는 수정하는 작업을 수행할 수 있습니다.

이러한 API의 대부분은 필터링, 정렬 및 페이지 매김 지원을 통해 클러스터 간 집계를 제공하는 호출을 받습니다. 이러한 API를 실행하면 데이터베이스에서 데이터가 반환됩니다. 따라서 다음 획득 주기에 따라 새로 생성된 객체를 검색한 후 응답해야 합니다.

특정 개체의 세부 정보를 쿼리하려면 해당 개체의 고유 ID를 입력하여 세부 정보를 확인해야 합니다. 예를 들어, 스토리지 오브젝트의 메트릭 및 분석 정보는 를 참조하십시오 link:concept_metrics_apis.html["성능 메트릭 보기"].

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
API에 대한 curl 명령, 예제, 요청 및 응답은 Swagger API 인터페이스에서 사용할 수 있습니다. Swagger에 표시된 특정 매개 변수를 기준으로 결과를 필터링하고 주문할 수 있습니다. 이러한 API를 사용하면 클러스터, 볼륨 또는 스토리지 VM과 같은 특정 스토리지 개체의 결과를 필터링할 수 있습니다.

====


== 데이터 센터의 스토리지 오브젝트를 위한 API

[cols="3*"]
|===
| HTTP 동사 | 경로 | 설명 


 a| 
"내려가세요
 a| 
'/datacenter/cluster/cluster'

'/datacenter/cluster/clusters/\{key}'
 a| 
이 방법을 사용하여 데이터 센터 전체에서 ONTAP 클러스터의 세부 정보를 볼 수 있습니다. API는 클러스터의 IPv4 또는 IPv6 주소, 노드 상태, 성능 용량, HA(High Availability) 쌍 등의 노드 정보 및 클러스터가 모든 SAN 스토리지인지 여부를 표시합니다.



 a| 
"내려가세요
 a| 
'/datacenter/cluster/licenses/licenses/datacenter/cluster/licenses/licenses/\{key}'
 a| 
데이터 센터의 클러스터에 설치된 라이센스의 세부 정보를 반환합니다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 라이센스 키, 클러스터 키, 만료 날짜 및 라이센스 범위와 같은 정보가 반환됩니다. 라이센스 키를 입력하여 특정 라이센스의 세부 정보를 검색할 수 있습니다.



 a| 
"내려가세요
 a| 
'/datacenter/cluster/nodes'

'/datacenter/cluster/nodes/\{key}'
 a| 
이 방법을 사용하여 데이터 센터의 노드 세부 정보를 볼 수 있습니다. 노드의 클러스터, 노드 상태, 성능 용량, HA(고가용성) 쌍에 대한 정보를 볼 수 있습니다.



 a| 
"내려가세요
 a| 
'/datacenter/protocols/cifs/공유'

'/datacenter/protocols/cifs/공유/\{key}'
 a| 
이 방법을 사용하여 데이터 센터에서 CIFS 공유의 세부 정보를 볼 수 있습니다. 클러스터, SVM, 볼륨 세부 정보 외에도 액세스 제어 목록(ACL)에 대한 정보도 반환됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/protocols/nfs/export-policies'

'/datacenter/protocols/nfs/export-policies/\{key}'
 a| 
이 방법을 사용하여 지원되는 NFS 서비스에 대한 엑스포트 정책의 세부 정보를 볼 수 있습니다.

클러스터 또는 스토리지 VM에 대한 엑스포트 정책을 쿼리하고 NFS 파일 공유를 프로비저닝하기 위해 엑스포트 정책 키를 재사용할 수 있습니다. 작업 부하에 대한 내보내기 정책 할당 및 재사용에 대한 자세한 내용은 "'CIFS 및 NFS 파일 공유 프로비저닝'을 참조하십시오.



 a| 
"내려가세요
 a| 
'/datacenter/storage/aggregate'

'/datacenter/storage/aggregate/\{key}'
 a| 
이 방법을 사용하여 데이터 센터의 애그리게이트 컬렉션 또는 이러한 애그리게이트나 모니터링을 위한 특정 애그리게이트를 볼 수 있습니다. 클러스터 및 노드 세부 정보, 사용된 성능 용량, 사용 가능한 공간 및 사용된 공간, 스토리지 효율성 등의 정보가 반환됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/storage/LUNs'

'/datacenter/storage/LUNs/\{key}'
 a| 
이 방법을 사용하여 전체 데이터 센터에서 LUN 컬렉션을 볼 수 있습니다. 클러스터 및 SVM 세부 정보, QoS 정책, igroup 같은 LUN에 대한 정보를 볼 수 있습니다.



 a| 
"내려가세요
 a| 
'/datacenter/storage/qos/policies'

'/datacenter/storage/qos/policies/\{key}'
 a| 
이 방법을 사용하여 데이터 센터의 스토리지 오브젝트에 해당하는 모든 QoS 정책의 세부 정보를 볼 수 있습니다. 클러스터 및 SVM 세부 정보, 고정 또는 적응형 정책 세부 정보, 해당 정책에 해당하는 오브젝트 수와 같은 정보가 반환됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/storage/qtree'

'/datacenter/storage/qtree/\{key}'
 a| 
이 방법을 사용하여 모든 FlexVol 볼륨 또는 FlexGroup 볼륨의 데이터 센터 전체에서 qtree 세부 정보를 볼 수 있습니다. 클러스터 및 SVM 세부 정보, FlexVol 볼륨, 엑스포트 정책과 같은 정보가 반환됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/storage/volumes'

'/datacenter/storage/volumes/{key}'
 a| 
이 방법을 사용하여 데이터 센터의 볼륨 컬렉션을 볼 수 있습니다. 볼륨이 읽기-쓰기 유형인지, 데이터 보호 또는 로드 공유인지에 관계없이 SVM 및 클러스터 세부 정보, QoS 및 엑스포트 정책과 같은 볼륨 정보가 반환됩니다.

FlexVol 및 FlexClone 볼륨의 경우 해당 애그리게이트에 대한 정보를 볼 수 있습니다. FlexGroup 볼륨의 경우 쿼리는 구성요소 애그리게이트 목록을 반환합니다.



 a| 
"내려가세요

POST를 누릅니다

"삭제"

패치
 a| 
'/datacenter/protocols/san/igroup'

'/datacenter/protocols/san/igroup/{key}'
 a| 
특정 LUN 타겟에 액세스할 수 있는 권한이 있는 이니시에이터 그룹(igroup)을 할당할 수 있습니다. 기존 igroup이 있으면 할당할 수 있습니다. 또한 igroup을 생성하여 LUN에 할당할 수 있습니다.

이러한 방법을 사용하여 각각 igroup을 쿼리, 생성, 삭제 및 수정할 수 있습니다.

참고 사항:

* "POST:"igroup을 생성하는 동안 액세스를 할당할 스토리지 VM을 지정할 수 있습니다.
* 삭제: 특정 igroup을 삭제하려면 iGroup 키를 입력 매개 변수로 제공해야 합니다. LUN에 igroup을 이미 할당한 경우에는 해당 igroup을 삭제할 수 없습니다.
* '패치:' 특정 igroup을 수정하려면 igroup 키를 입력 매개 변수로 제공해야 합니다. 또한 업데이트할 속성과 해당 값을 입력해야 합니다.




 a| 
"내려가세요

POST를 누릅니다

"삭제"

패치
 a| 
'/datacenter/svm/sSVM'

'/datacenter/svm/sSVM/\{key}'
 a| 
이러한 방법을 사용하여 스토리지 가상 머신(스토리지 VM)을 확인, 생성, 삭제 및 수정할 수 있습니다.

* "POST:"입력 매개 변수로 생성하려는 스토리지 VM 객체를 입력해야 합니다. 사용자 지정 스토리지 VM을 생성한 다음 여기에 필요한 속성을 할당할 수 있습니다.
* 삭제: 특정 스토리지 VM을 삭제하려면 스토리지 VM 키를 제공해야 합니다.
* 패치: 특정 스토리지 VM을 수정하려면 스토리지 VM 키를 제공해야 합니다. 또한 업데이트할 속성과 해당 값을 입력해야 합니다.


|===

NOTE: 참고 사항:

스토리지 VM을 생성하는 동안 환경에서 SLO 기반 워크로드 프로비저닝을 설정한 경우 CIFS 또는 SMB, NFS, FCP, NFS, FCP 등 LUN 및 파일 공유에 대한 프로비저닝에 필요한 모든 프로토콜을 지원해야 합니다. 및 iSCSI를 지원합니다. 스토리지 VM이 필요한 서비스를 지원하지 않으면 프로비저닝 워크플로우가 실패할 수 있습니다. 각 워크로드 유형에 대한 서비스도 스토리지 VM에서 사용하도록 설정하는 것이 좋습니다.

환경에서 SLO 기반 워크로드 프로비저닝을 설정한 경우 스토리지 워크로드가 프로비저닝된 스토리지 VM을 삭제할 수 없습니다. CIFS 또는 SMB 서버가 구성된 스토리지 VM을 삭제하면 이 API는 로컬 Active Directory 구성과 함께 CIFS 또는 SMB 서버도 삭제합니다. 그러나 CIFS 또는 SMB 서버 이름은 Active Directory 서버에서 수동으로 삭제해야 하는 Active Directory 구성에 계속 포함됩니다.



== 데이터 센터의 네트워크 요소를 위한 API입니다

데이터 센터 범주의 다음 API는 작업 환경의 포트 및 네트워크 인터페이스, 특히 FC 포트, FC 인터페이스, 이더넷 포트 및 IP 인터페이스에 대한 정보를 검색합니다.

[cols="3*"]
|===
| HTTP 동사 | 경로 | 설명 


 a| 
"내려가세요
 a| 
'/datacenter/network/ethernet/ports'

'/datacenter/network/ethernet/ports/{key}'
 a| 
데이터 센터 환경의 모든 이더넷 포트에 대한 정보를 검색합니다. 포트 키를 입력 매개 변수로 사용하여 특정 포트의 정보를 볼 수 있습니다. 클러스터 세부 정보, 브로드캐스트 도메인, 상태, 속도 등의 포트 세부 정보 를 입력하고 포트의 활성화 여부를 검색합니다.



 a| 
"내려가세요
 a| 
'/datacenter/network/fc/interfaces'

'/datacenter/network/fc/interface/{key}'
 a| 
이 방법을 사용하여 데이터 센터 환경에서 FC 인터페이스의 세부 정보를 볼 수 있습니다. 인터페이스 키를 입력 매개 변수로 사용하면 해당 특정 인터페이스의 정보를 볼 수 있습니다. 클러스터 세부 정보, 홈 노드 세부 정보, 홈 포트 세부 정보 등의 정보가 검색됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/network/fc/ports'

'/datacenter/network/fc/ports/{key}'
 a| 
이 명령어는 데이터 센터 환경의 노드에 사용되는 모든 FC 포트에 대한 정보를 조회한다. 포트 키를 입력 매개 변수로 사용하여 특정 포트의 정보를 볼 수 있습니다. 클러스터 세부 정보, 포트 설명, 지원되는 프로토콜 및 포트 상태와 같은 정보가 검색됩니다.



 a| 
"내려가세요
 a| 
'/datacenter/network/ip/interfaces'

'/datacenter/network/ip/interfaces/{key}'
 a| 
이 방법을 사용하여 데이터 센터 환경에서 IP 인터페이스의 세부 정보를 볼 수 있습니다. 인터페이스 키를 입력 매개 변수로 사용하면 해당 특정 인터페이스의 정보를 볼 수 있습니다. 클러스터 세부 정보, IPspace 세부 정보, 홈 노드 세부 정보, 페일오버 활성화 여부 등의 정보가 검색됩니다.

|===