---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: /storage-provider/file-share API를 사용하여 데이터 센터 환경에서 CIFS 및 NFS 파일 공유 볼륨을 확인, 추가, 수정 및 삭제할 수 있습니다. 
---
= 파일 공유 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 센터 환경에서 '/storage-provider/file-share' API를 사용하여 CIFS 및 NFS 파일 공유 볼륨을 확인, 추가, 수정 및 삭제할 수 있습니다.

파일 공유 볼륨을 프로비저닝하기 전에 SVM이 지원 프로토콜을 통해 생성되고 프로비저닝되었는지 확인합니다. 프로비저닝 중에 PSL(Performance Service Levels) 또는 CDP(Storage Efficiency Policies)를 할당하는 경우 파일 공유를 생성하기 전에 PSL 또는 SRP를 생성해야 합니다.



== 파일 공유를 봅니다

다음 방법을 사용하여 Unified Manager 환경에서 사용 가능한 파일 공유 볼륨을 볼 수 있습니다. ONTAP 클러스터를 Active IQ Unified Manager의 데이터 소스로 추가하면 해당 클러스터의 스토리지 워크로드가 Unified Manager 인스턴스에 자동으로 추가됩니다. 이 API는 자동으로 파일 공유를 검색하고 Unified Manager 인스턴스에 수동으로 추가합니다. 이 API를 파일 공유 키로 실행하여 특정 파일 공유의 세부 정보를 볼 수 있습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/storage-provider/file-공유'

'/storage-provider/file-공유/\{key}'

|===


== 파일 공유를 추가합니다

다음 방법을 사용하여 SVM에 CIFS 및 NFS 파일 공유를 추가할 수 있습니다. 만들려는 파일 공유의 세부 정보를 입력 매개 변수로 입력해야 합니다. FlexGroup 볼륨을 추가하는 데 이 API를 사용할 수 없습니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
게시
 a| 
'/storage-provider/file-공유'

|===
[NOTE]
====
ACL(액세스 제어 목록) 매개 변수 또는 엑스포트 정책 매개 변수의 제공 여부에 따라 CIFS 공유 또는 NFS 파일 공유가 생성됩니다. ACL 매개 변수의 값을 제공하지 않으면 CIFS 공유가 생성되지 않고 기본적으로 NFS 공유가 생성되므로 모든 에 액세스할 수 있습니다.

====
* 데이터 보호 볼륨 생성 *: SVM에 파일 공유를 추가하면 기본적으로 마운트된 볼륨 유형은 "RW"(읽기-쓰기)입니다. 데이터 보호(DP) 볼륨을 생성하려면 'type' 매개 변수의 값으로 dp를 지정합니다.



== 파일 공유를 삭제합니다

다음 방법을 사용하여 특정 파일 공유를 삭제할 수 있습니다. 특정 파일 공유를 삭제하려면 파일 공유 키를 입력 매개 변수로 입력해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
삭제
 a| 
'/storage-provider/file-공유/\{key}'

|===


== 파일 공유를 수정합니다

다음 메서드를 사용하여 파일 공유를 수정하고 해당 속성을 업데이트할 수 있습니다.

특정 파일 공유를 수정하려면 파일 공유 키를 제공해야 합니다. 또한 업데이트할 속성과 해당 값을 입력해야 합니다.

[NOTE]
====
이 API를 한 번 호출할 때 하나의 속성만 업데이트할 수 있습니다. 여러 업데이트를 하려면 이 API를 여러 번 실행해야 합니다.

====
[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
패치
 a| 
'/storage-provider/file-공유/\{key}'

|===