---
permalink: api-automation/concept_view_workloads.html 
sidebar: sidebar 
keywords: view, storage, workloads 
summary: '여기에 나열된 API를 사용하여 데이터 센터의 모든 ONTAP 클러스터에 대한 스토리지 워크로드 통합 목록을 볼 수 있습니다. 또한, API는 Active IQ Unified Manager 환경에 프로비저닝된 스토리지 워크로드 수와 해당 용량 및 성능(IOPS) 통계를 간략하게 보여줍니다.' 
---
= API를 사용하여 스토리지 워크로드 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여기에 나열된 API를 사용하여 데이터 센터의 모든 ONTAP 클러스터에 대한 스토리지 워크로드 통합 목록을 볼 수 있습니다. 또한, API는 Active IQ Unified Manager 환경에 프로비저닝된 스토리지 워크로드 수와 해당 용량 및 성능(IOPS) 통계를 간략하게 보여줍니다.



== 스토리지 워크로드를 봅니다

다음 방법을 사용하여 데이터 센터의 모든 클러스터에서 모든 스토리지 워크로드를 볼 수 있습니다. 특정 열을 기준으로 응답을 필터링하는 방법에 대한 자세한 내용은 Unified Manager 인스턴스에서 사용할 수 있는 API 참조 설명서를 참조하십시오.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/스토리지 공급자/워크로드'

|===


== 스토리지 워크로드 요약 보기

다음 방법을 사용하여 각 성능 서비스 수준에서 관리되는 사용된 용량, 사용 가능한 용량, 사용된 IOPS, 사용 가능한 IOPS 및 스토리지 워크로드 수를 평가할 수 있습니다. 표시된 스토리지 워크로드는 모든 LUN, NFS 파일 공유 또는 CIFS 공유에 대해 수행할 수 있습니다. 이 API는 스토리지 워크로드 개요, Unified Manager에서 프로비저닝한 스토리지 워크로드 개요, 데이터 센터 개요, 할당된 성능 서비스 수준과 관련하여 데이터 센터의 총 공간, 사용된 공간 및 사용 가능한 공간 및 IOPS를 제공합니다. 이 API에 대한 응답으로 받은 정보는 Unified Manager UI에서 대시보드를 채우는 데 사용됩니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/storage-provider/워크로드-summary'

|===