---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: 이벤트 API를 사용하면 데이터 센터에서 모니터링되는 클러스터에 대해 생성되는 이벤트를 검색할 수 있습니다. 
---
= 이벤트 및 경고 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
'관리 서버' 범주의 '이벤트', '경고', '스크립트' API를 사용하면 Active IQ Unified Manager 환경의 알림과 관련된 이벤트, 알림 및 스크립트를 관리할 수 있습니다.



== 이벤트 보기 및 수정

Unified Manager는 ONTAP에서 Unified Manager가 모니터링 및 관리하는 클러스터에 대해 생성되는 이벤트를 수신합니다. 이러한 API를 사용하면 클러스터에 대해 생성된 이벤트를 보고 해당 이벤트를 확인 및 업데이트할 수 있습니다.

/management-server/events' API에 대한 get 메소드를 실행하면 내역 데이터를 포함하여 데이터 센터의 이벤트를 쿼리할 수 있습니다. 이름, 영향 수준, 영향 영역, 심각도, 특정 이벤트를 보려면 상태, 리소스 이름 및 리소스 유형 을 참조하십시오. 리소스 유형 및 영역 매개 변수는 이벤트가 발생한 스토리지 객체에 대한 정보를 반환하고 영향 영역은 가용성, 용량, 구성, 보안 등과 같이 이벤트가 발생한 문제에 대한 정보를 반환합니다. 성능과 보호 기능을 모두 제공합니다.

이 API에 대한 패치 작업을 실행하여 이벤트에 대한 해결 워크플로우를 활성화할 수 있습니다. 본인 또는 다른 사용자에게 이벤트를 할당하고 이벤트 수신을 확인할 수 있습니다. 리소스에 대한 단계를 수행하여 이벤트를 트리거한 문제를 해결할 때 이 API를 사용하여 이벤트를 Resolved로 표시할 수 있습니다.

이벤트에 대한 자세한 내용은 를 참조하십시오 link:../events/concept_manage_events.html["이벤트 관리"]

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
'/management-server/events'/management-server/events/{key}'
 a| 
모두 가져오기 메서드를 실행할 때 응답 본문은 데이터 센터의 모든 이벤트에 대한 이벤트 세부 정보로 구성됩니다. 특정 키로 이벤트 세부 정보를 검색할 때 특정 이벤트의 세부 정보를 보고 리소스에 대한 다음 작업 집합을 실행할 수 있습니다. 응답 본문은 해당 이벤트의 세부 정보로 구성됩니다.



 a| 
관리 - 서버
 a| 
패치
 a| 
'Management-server/events/{key}'
 a| 
이 API를 실행하여 이벤트를 할당하거나 상태를 확인됨 또는 해결됨 으로 변경합니다. 또한 이 메서드를 사용하여 사용자나 다른 사용자에게 이벤트를 할당할 수도 있습니다. 동기식 작업입니다.

|===


== 알림 관리

이벤트는 자동으로 연속적으로 생성됩니다. Unified Manager는 이벤트가 특정 필터 조건을 충족할 경우에만 알림을 생성합니다. 알림을 생성할 이벤트를 선택할 수 있습니다. '/management-server/alerts' API를 사용하면 특정 심각도 유형의 특정 이벤트 또는 이벤트가 발생할 때 알림을 자동으로 보내도록 알림을 구성할 수 있습니다.

알림에 대한 자세한 내용은 을 참조하십시오 link:../events/concept_manage_alerts.html["알림 관리"]

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
'/management-server/alerts''/management-server/alerts/{key}'
 a| 
경고 키를 사용하여 사용자 환경 또는 특정 알림에 있는 기존 경고를 모두 쿼리합니다. 알림 설명, 작업, 알림을 보낼 e-메일 ID, 이벤트, 심각도 등 사용자 환경에서 생성된 알림에 대한 정보를 볼 수 있습니다.



 a| 
관리 - 서버
 a| 
게시
 a| 
'/management-server/alerts'
 a| 
이 방법을 사용하면 특정 이벤트에 대한 알림을 추가할 수 있습니다. 경고 이름, 물리적 또는 논리적 리소스 또는 경고를 적용할 수 있는 이벤트, 경고가 설정되었는지 여부 및 SNMP 트랩을 발행하는지 여부를 추가해야 합니다. 알림 스크립트를 추가하는 경우 작업, 알림 이메일 ID, 스크립트 세부 정보 등과 같이 알림을 생성할 추가 세부 정보를 추가할 수 있습니다.



 a| 
관리 - 서버
 a| 
패치 및 삭제
 a| 
'Management-server/events/{key}'
 a| 
이러한 방법을 사용하여 특정 경고를 수정 및 삭제할 수 있습니다. 설명, 이름, 알림 설정 및 해제 등 다양한 속성을 수정할 수 있습니다. 알림이 더 이상 필요하지 않은 경우 알림을 삭제할 수 있습니다.

|===

NOTE: 알림을 추가할 리소스를 선택할 때는 클러스터를 리소스로 선택해도 해당 클러스터 내의 스토리지 객체가 자동으로 선택되지는 않습니다. 예를 들어, 모든 클러스터에 대한 모든 중요 이벤트에 대한 알림을 생성하는 경우 클러스터 중요 이벤트에 대한 알림만 받게 됩니다. 노드, 애그리게이트 등의 중요 이벤트에 대한 알림을 받지 못합니다.



== 스크립트 관리

'/management-server/scripts' API를 사용하면 경고가 트리거될 때 실행되는 스크립트와 알림을 연결할 수도 있습니다. 스크립트를 사용하여 Unified Manager에서 여러 스토리지 오브젝트를 자동으로 수정 또는 업데이트할 수 있습니다. 스크립트가 경고와 연결되어 있습니다. 이벤트가 경고를 트리거하면 스크립트가 실행됩니다. 사용자 지정 스크립트를 업로드하고 경고가 생성될 때 해당 스크립트를 테스트할 수 있습니다. 알림을 스크립트에 연결하여 Unified Manager의 이벤트에 대한 알림이 발생할 때 스크립트가 실행되도록 할 수 있습니다.

스크립트에 대한 자세한 내용은 을 참조하십시오 link:../events/concept_manage_scripts.html["스크립트 관리"]

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
'/management-server/scripts'
 a| 
이 API를 사용하여 사용자 환경의 모든 기존 스크립트를 쿼리합니다. 특정 스크립트만 보려면 표준 필터 및 작업별 순서를 사용합니다.



 a| 
관리 - 서버
 a| 
게시
 a| 
'/management-server/scripts'
 a| 
이 API를 사용하여 스크립트에 대한 설명을 추가하고 경고와 관련된 스크립트 파일을 업로드합니다.

|===