---
permalink: api-automation/concept_manage_sep.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policy 
summary: 스토리지 공급자 API를 사용하여 스토리지 효율성 정책을 확인, 생성, 수정 및 삭제할 수 있습니다. 
---
= 스토리지 효율성 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 공급자 API를 사용하여 스토리지 효율성 정책을 확인, 생성, 수정 및 삭제할 수 있습니다.

[NOTE]
====
다음 사항을 참고하십시오.

* Unified Manager에서 워크로드를 생성하는 동안 스토리지 효율성 정책을 할당할 필요는 없습니다.
* 정책이 할당된 후에는 워크로드에서 스토리지 효율성 정책을 할당 취소할 수 없습니다.
* ONTAP 볼륨에 중복제거 및 압축과 같은 일부 스토리지 설정이 지정된 워크로드의 경우, Unified Manager에서 스토리지 워크로드를 추가할 때 적용할 스토리지 효율성 정책에 지정된 설정으로 해당 설정을 덮어쓸 수 있습니다.


====


== 스토리지 효율성 정책을 봅니다

스토리지 워크로드에 할당하기 전에 다음 방법을 사용하여 스토리지 효율성 정책을 볼 수 있습니다. 이 API는 시스템 정의 및 사용자 생성 스토리지 효율성 정책을 모두 나열하고 모든 스토리지 효율성 정책의 특성을 검색합니다. 특정 스토리지 효율성 정책을 쿼리하려면 정책의 고유 ID를 입력하여 세부 정보를 검색해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
'/스토리지 공급자/스토리지 효율성 - 정책'

'/storage-provider/storage-Efficiency-policies/\{key}'

|===


== 스토리지 효율성 정책을 추가합니다

다음 방법을 사용하여 맞춤형 스토리지 효율성 정책을 생성하고 시스템 정의 정책이 스토리지 워크로드의 프로비저닝 요구사항을 충족하지 않는 경우 스토리지 워크로드에 할당할 수 있습니다. 생성할 스토리지 효율성 정책의 세부 정보를 입력 매개 변수로 입력합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
게시
 a| 
'/스토리지 공급자/스토리지 효율성 - 정책'

|===


== 스토리지 효율성 정책을 삭제합니다

다음 방법을 사용하여 특정 스토리지 효율성 정책을 삭제할 수 있습니다. 스토리지 효율성 정책이 워크로드에 할당되어 있거나 사용 가능한 유일한 스토리지 효율성 정책인 경우에는 스토리지 효율성 정책을 삭제할 수 없습니다. 특정 스토리지 효율성 정책을 삭제하려면 입력 매개 변수로 스토리지 효율성 정책의 고유 ID를 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
삭제
 a| 
'/storage-provider/storage-Efficiency-policies/\{key}'

|===


== 스토리지 효율성 정책을 수정합니다

다음 방법을 사용하여 스토리지 효율성 정책을 수정하고 해당 속성을 업데이트할 수 있습니다. 시스템 정의이거나 워크로드에 할당된 스토리지 효율성 정책은 수정할 수 없습니다. 특정 스토리지 효율성 정책을 수정하려면 스토리지 효율성 정책의 고유 ID를 제공해야 합니다. 또한 업데이트할 속성과 해당 값을 제공해야 합니다.

[cols="3*"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
패치
 a| 
'/storage-provider/storage-Efficiency-policies/\{key}'

|===