---
permalink: api-automation/concept_administration_apis.html 
sidebar: sidebar 
keywords: perform, administrative, tasks 
summary: 관리 범주의 API를 사용하여 백업 설정을 수정하고, 백업 파일 정보와 클러스터 인증서를 확인하고, ONTAP 클러스터를 Active IQ Unified Manager 데이터 소스로 관리할 수 있습니다. 
---
= API를 사용하여 관리 작업 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 범주의 API를 사용하여 백업 설정을 수정하고, 백업 파일 정보와 클러스터 인증서를 확인하고, ONTAP 클러스터를 Active IQ Unified Manager 데이터 소스로 관리할 수 있습니다.

[NOTE]
====
이러한 작업을 실행하려면 애플리케이션 관리자 역할이 있어야 합니다. Unified Manager 웹 UI를 사용하여 이러한 설정을 구성할 수도 있습니다.

====
[cols="3*"]
|===
| HTTP 동사 | 경로 | 설명 


 a| 
"내려가세요

패치
 a| 
'/admin/backup-settings'

'/admin/backup-settings'
 a| 
기본적으로 Unified Manager에 구성된 백업 스케줄의 설정을 보려면 'Get' 메서드를 사용합니다. 다음을 확인할 수 있습니다.

* 스케줄이 설정되었는지 여부를 나타냅니다
* 예약된 백업 빈도(매일 또는 매주)
* 백업 시간입니다
* 응용 프로그램에 보존되어야 하는 최대 백업 파일 수입니다


백업 시간이 서버 시간대에 있습니다.

데이터베이스 백업 설정은 기본적으로 Unified Manager에서 사용할 수 있으며 백업 일정을 만들 수는 없습니다. 그러나 패치 방식을 사용하여 기본 설정을 수정할 수 있습니다.



 a| 
"내려가세요
 a| 
'/admin/backup-file-info'
 a| 
Unified Manager에 대한 백업 스케줄이 수정될 때마다 백업 덤프 파일이 생성됩니다. 이 방법을 사용하여 수정된 백업 설정에 따라 백업 파일이 생성되었는지, 파일의 정보가 수정된 설정과 일치하는지 여부를 확인할 수 있습니다.



 a| 
"내려가세요
 a| 
'/admin/datasource-certificate'
 a| 
이 메서드를 사용하여 트러스트 저장소에서 데이터 소스(클러스터) 인증서를 볼 수 있습니다. ONTAP 클러스터를 Unified Manager 데이터 소스로 추가하기 전에 인증서 검증이 필요합니다.



 a| 
"내려가세요

POST를 누릅니다

패치

"삭제"
 a| 
'/admin/datasources/cluster'

"/admin/datasources/cluster/\{key}"
 a| 
'Get' 메서드를 사용하면 Unified Manager에서 관리하는 데이터 소스(ONTAP 클러스터)의 세부 정보를 검색할 수 있습니다.

새 클러스터를 Unified Manager에 데이터 소스로 추가할 수도 있습니다. 클러스터를 추가하려면 해당 호스트 이름, 사용자 이름 및 암호를 알아야 합니다.

Unified Manager에서 데이터 소스로 관리되는 클러스터를 수정 및 삭제하려면 ONTAP 클러스터 키를 사용합니다.

|===