---
permalink: api-automation/reference_authentication_errors.html 
sidebar: sidebar 
keywords: http, status, code, active iq, unified manager 
summary: API를 실행하거나 문제를 해결하는 동안 Active IQ Unified Manager API에서 사용되는 다양한 HTTP 상태 코드 및 오류 코드를 알고 있어야 합니다. 
---
= Active IQ Unified Manager에서 사용되는 HTTP 상태 코드입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
API를 실행하거나 문제를 해결하는 동안 Active IQ Unified Manager API에서 사용되는 다양한 HTTP 상태 코드 및 오류 코드를 알고 있어야 합니다.

다음 표에는 인증과 관련된 오류 코드가 정리되어 있습니다.

[cols="3*"]
|===
| HTTP 상태 코드입니다 | 상태 코드 제목 | 설명 


 a| 
200
 a| 
좋습니다
 a| 
동기 API 호출이 성공적으로 실행될 때 반환됩니다.



 a| 
201
 a| 
작성됨
 a| 
Active Directory 구성과 같은 동기 호출을 통해 새 리소스 생성



 a| 
202
 a| 
수락됨
 a| 
LUN 및 파일 공유 생성과 같은 프로비저닝 기능에 대한 비동기 호출을 성공적으로 실행할 때 반환됩니다.



 a| 
400
 a| 
잘못된 요청입니다
 a| 
입력 유효성 검사 실패를 나타냅니다. 사용자는 요청 본문의 유효한 키와 같은 입력을 수정해야 합니다.



 a| 
401
 a| 
권한이 없는 요청입니다
 a| 
리소스를 볼 수 있는 권한이 없습니다.



 a| 
403
 a| 
금지된 요청입니다
 a| 
연결하려는 리소스에 대한 액세스는 금지됩니다.



 a| 
404
 a| 
리소스를 찾을 수 없습니다
 a| 
연결하려는 리소스를 찾을 수 없습니다.



 a| 
405
 a| 
메서드가 허용되지 않습니다
 a| 
메서드가 허용되지 않습니다.



 a| 
429
 a| 
요청이 너무 많습니다
 a| 
사용자가 특정 시간 내에 너무 많은 요청을 보낼 때 반환됩니다.



 a| 
500입니다
 a| 
내부 서버 오류입니다
 a| 
내부 서버 오류입니다. 서버에서 응답을 가져오지 못했습니다. 이 내부 서버 오류는 영구적인 오류일 수도 있고 그렇지 않을 수도 있습니다. 예를 들어, 'Get' 또는 'Get All' 작업을 실행하고 이 오류를 수신하는 경우 최소 5회 이상 이 작업을 반복할 것을 권장합니다. 영구적인 오류인 경우 반환되는 상태 코드는 계속 500입니다. 작업이 성공하면 반환되는 상태 코드는 200입니다.

|===