---
permalink: reporting/concept_unified_manager_databases_accessible_for_reporting.html 
sidebar: sidebar 
keywords: unified manager, databases, access, custom, reporting 
summary: Unified Manager는 MySQL 데이터베이스를 사용하여 모니터링 중인 클러스터의 데이터를 저장합니다. 데이터는 MySQL 데이터베이스의 다양한 스키마로 유지됩니다. 
---
= 맞춤형 보고를 위해 액세스할 수 있는 Unified Manager 데이터베이스
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 MySQL 데이터베이스를 사용하여 모니터링 중인 클러스터의 데이터를 저장합니다. 데이터는 MySQL 데이터베이스의 다양한 스키마로 유지됩니다.

다음 데이터베이스의 모든 테이블 데이터를 사용할 수 있습니다.

[cols="2*"]
|===
| 데이터베이스 | 설명 


 a| 
netapp_model
 a| 
ONTAP 컨트롤러의 개체에 대한 데이터입니다.



 a| 
NetApp_모델_뷰
 a| 
보고서 도구 사용에 적합한 ONTAP 컨트롤러의 개체에 대한 데이터입니다.



 a| 
netapp_performance
 a| 
클러스터별 성능 카운터



 a| 
ocum
 a| 
Unified Manager 애플리케이션 데이터와 UI 필터링, 정렬, 일부 파생 필드 계산 지원 정보



 a| 
ocum_report 를 참조하십시오
 a| 
인벤토리 구성 및 용량 관련 정보에 대한 데이터입니다.



 a| 
ocum_report_bRT
 a| 
보고서 도구 사용에 적합한 재고 구성 및 용량 관련 데이터 보기



 a| 
OPM
 a| 
성능 구성 설정 및 임계값 정보



 a| 
스케일로토르
 a| 
Unified Manager 애플리케이션 상태 및 성능 문제에 대한 데이터



 a| 
vmware_model을 참조하십시오
 a| 
NetApp 스토리지에 호스팅된 데이터 저장소의 VMware 오브젝트 데이터



 a| 
vmware_model_view 를 참조하십시오
 a| 
NetApp 스토리지에서 호스트되는 데이터 저장소의 VMware 오브젝트 데이터 보기, 보고서 툴 사용에 적합



 a| 
vmware_성능
 a| 
NetApp 스토리지에 호스팅된 데이터 저장소의 VMware 성능 카운터 데이터

|===
보고서 스키마 역할을 가진 데이터베이스 사용자인 보고 사용자는 이러한 테이블의 데이터에 액세스할 수 있습니다. 이 사용자는 Unified Manager 데이터베이스에서 직접 보고 및 기타 데이터베이스 뷰에 대한 읽기 전용 액세스를 가집니다. 이 사용자는 사용자 데이터 또는 클러스터 자격 증명 정보가 포함된 테이블에 액세스할 수 있는 권한이 없습니다.
