---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: 'QoS(서비스 품질) 정책 그룹을 생성하여 포함된 워크로드의 IOPS(초당 I/O) 또는 처리량(MB/s) 제한을 제어할 수 있습니다. 워크로드가 기본 정책 그룹과 같이 설정된 제한이 없는 정책 그룹에 있거나 설정된 제한이 사용자의 요구 사항을 충족하지 않는 경우, 제한을 늘리거나 워크로드를 원하는 제한이 있는 새 정책 그룹 또는 기존 정책 그룹으로 이동할 수 있습니다.' 
---
= 스토리지 QoS로 워크로드 처리량을 제어하는 방법
:icons: font
:imagesdir: ../media/


[role="lead"]
QoS(서비스 품질) 정책 그룹을 생성하여 포함된 워크로드의 IOPS(초당 I/O) 또는 처리량(MB/s) 제한을 제어할 수 있습니다. 워크로드가 기본 정책 그룹과 같이 설정된 제한이 없는 정책 그룹에 있거나 설정된 제한이 사용자의 요구 사항을 충족하지 않는 경우, 제한을 늘리거나 워크로드를 원하는 제한이 있는 새 정책 그룹 또는 기존 정책 그룹으로 이동할 수 있습니다.

"기존" QoS 정책 그룹은 단일 볼륨 또는 LUN과 같은 개별 워크로드에 할당할 수 있습니다. 이 경우 워크로드는 최대 처리량 제한을 사용할 수 있습니다. QoS 정책 그룹도 여러 워크로드에 할당할 수 있으며, 이 경우 처리량 제한이 워크로드 간에 "공유"됩니다. 예를 들어, 3개의 워크로드에 할당된 9,000 IOPS의 QoS 제한은 결합된 IOPS가 9,000 IOPS를 초과하지 않도록 제한됩니다.

또한 개별 워크로드 또는 여러 워크로드에 "Adaptive" QoS 정책 그룹을 할당할 수 있습니다. 그러나 여러 워크로드에 할당된 경우에도 각 워크로드는 처리량 값을 다른 워크로드와 공유하는 대신 최대 처리량 제한을 받습니다. 또한 적응형 QoS 정책은 볼륨 크기 및 워크로드별로 처리량 설정을 자동으로 조정하여 볼륨 크기에 따라 IOPS와 테라바이트의 비율을 유지합니다. 예를 들어, 적응형 QoS 정책에서 최대값이 5,000 IOPS/TB로 설정된 경우 10TB 볼륨의 처리량은 최대 50,000 IOPS입니다. 나중에 볼륨 크기를 20TB로 조정하는 경우 적응형 QoS는 최대 100,000 IOPS로 조정합니다.

ONTAP 9.5부터 적응형 QoS 정책을 정의할 때 블록 크기를 포함할 수 있습니다. 따라서 워크로드가 매우 큰 블록 크기를 사용하고 궁극적으로 높은 처리량을 사용하는 경우, IOPS/TB 임계값에서 MB/s 임계값으로 정책이 효과적으로 변환됩니다.

공유 그룹 QoS 정책의 경우 정책 그룹에 있는 모든 워크로드의 IOPS 또는 MB/s가 설정된 한도를 초과할 경우 정책 그룹은 워크로드를 조절하여 작업을 제한함으로써 정책 그룹의 모든 워크로드의 성능을 저하시할 수 있습니다. 정책 그룹 임계치 조절에 의해 동적 성능 이벤트가 생성되는 경우 이벤트 설명에 관련된 정책 그룹의 이름이 표시됩니다.

Performance: All Volumes 뷰에서 영향을 받는 볼륨을 IOPS 및 MB/s로 정렬하여 이벤트가 발생한 가장 높은 사용률이 있는 워크로드를 확인할 수 있습니다. 성능/볼륨 탐색기 페이지에서 볼륨의 다른 볼륨 또는 LUN을 선택하여 영향을 받는 워크로드 IOPS 또는 MBPS 처리량 사용량과 비교할 수 있습니다.

노드 리소스를 과도하게 사용하는 워크로드를 보다 제한적인 정책 그룹 설정에 할당하면 정책 그룹은 워크로드를 조절하여 해당 노드의 리소스 사용을 줄일 수 있습니다. 그러나 작업 부하에서 더 많은 노드 리소스를 사용할 수 있도록 하려면 정책 그룹의 값을 늘릴 수 있습니다.

System Manager, ONTAP 명령 또는 Unified Manager 성능 서비스 수준을 사용하여 다음 작업을 비롯한 정책 그룹을 관리할 수 있습니다.

* 정책 그룹을 생성하는 중입니다
* 정책 그룹에서 워크로드 추가 또는 제거
* 정책 그룹 간에 워크로드 이동
* 정책 그룹의 처리량 제한을 변경합니다
* 워크로드를 다른 애그리게이트 및/또는 노드로 이동

