---
permalink: performance-checker/concept_collect_data_and_monitor_workload_performance.html 
sidebar: sidebar 
keywords: collect, data, monitor, workload, performance 
summary: Unified Manager는 5분마다 워크로드 작업을 수집 및 분석하여 성능 이벤트를 식별하고, 15분마다 구성 변경을 감지합니다. 이 기능은 5분 동안의 기간별 성능 및 이벤트 데이터를 최대 30일까지 유지하며 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대해 예측 가능한 지연 시간 범위를 예측합니다. 
---
= 데이터 수집 및 워크로드 성능 모니터링
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 5분마다 워크로드 작업을 수집 및 분석하여 성능 이벤트를 식별하고, 15분마다 구성 변경을 감지합니다. 이 기능은 5분 동안의 기간별 성능 및 이벤트 데이터를 최대 30일까지 유지하며 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대해 예측 가능한 지연 시간 범위를 예측합니다.

Unified Manager는 분석을 시작하기 전에, 그리고 워크로드 분석 페이지와 이벤트 세부 정보 페이지에 I/O 응답 시간에 대한 지연 시간 예측을 표시할 수 있도록 최소 3일간의 워크로드 활동을 수집해야 합니다. 이 활동이 수집되는 동안 지연 시간 예측은 워크로드 활동에서 발생하는 모든 변경 사항을 표시하지 않습니다. Unified Manager는 3일간의 활동을 수집한 후 오전 12시에 24시간마다 지연 시간 예측을 조정하여 워크로드 활동 변화를 반영하고 보다 정확한 동적 성능 임계값을 설정합니다.

Unified Manager가 워크로드를 모니터링하는 처음 4일 동안에는 마지막 데이터 수집 이후 24시간이 경과해도 지연 시간 차트에 해당 워크로드의 지연 시간 예측이 표시되지 않습니다. 마지막 컬렉션 이전에 감지된 이벤트는 계속 사용할 수 있습니다.

[NOTE]
====
DST(일광 절약 시간)는 시스템 시간을 변경하여 모니터링되는 워크로드의 성능 통계에 대한 지연 시간 예측을 변경합니다. Unified Manager가 즉시 지연 시간 예측을 수정하기 시작하므로, 완료하는 데 약 15일이 소요됩니다. 이때 Unified Manager를 계속 사용할 수 있지만, Unified Manager에서는 지연 시간 예측을 사용하여 동적 이벤트를 감지하므로 일부 이벤트는 정확하지 않을 수 있습니다. 시간 변경 전에 감지된 이벤트는 영향을 받지 않습니다.

====