---
permalink: performance-checker/concept_understand_events_from_adaptive_qos_policies.html 
sidebar: sidebar 
keywords: understand, events, adaptive, qos, policies, defined, block, size 
summary: 적응형 QoS 정책 그룹은 볼륨 크기에 따라 처리량 상한 또는 하한 을 자동으로 확장하며, 볼륨 크기에 따라 IOPS와 TB의 비율을 유지합니다. ONTAP 9.5부터 QoS 정책에 블록 크기를 지정하여 MB/s 임계값을 동시에 효과적으로 적용할 수 있습니다. 
---
= 블록 크기가 정의된 적응형 QoS 정책의 이벤트 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
적응형 QoS 정책 그룹은 볼륨 크기에 따라 처리량 상한 또는 하한 을 자동으로 확장하며, 볼륨 크기에 따라 IOPS와 TB의 비율을 유지합니다. ONTAP 9.5부터 QoS 정책에 블록 크기를 지정하여 MB/s 임계값을 동시에 효과적으로 적용할 수 있습니다.

적응형 QoS 정책에 IOPS 임계값을 할당하면 각 워크로드에서 발생하는 작업 수만 제한됩니다. 워크로드를 생성하는 클라이언트에 설정된 블록 크기에 따라 일부 IOPS에는 훨씬 더 많은 데이터가 포함되므로 작업을 처리하는 노드에 부담이 훨씬 커집니다.

워크로드에 대한 MB/s 값은 다음 공식을 사용하여 생성됩니다.

[listing]
----
MB/s = (IOPS * Block Size) / 1000
----
워크로드가 평균 3,000 IOPS이고 클라이언트의 블록 크기가 32KB로 설정된 경우 이 워크로드에 대한 유효 MB/s는 96입니다. 이 동일한 워크로드가 평균 3,000 IOPS이고 클라이언트의 블록 크기가 48KB로 설정된 경우 이 워크로드에 대한 유효 MB/s는 144입니다. 블록 크기가 클 경우 노드가 50% 더 많은 데이터를 처리하고 있음을 알 수 있습니다.

블록 크기가 정의된 다음 적응형 QoS 정책과 클라이언트에서 설정된 블록 크기를 기반으로 이벤트가 트리거되는 방식을 살펴보겠습니다.

정책을 생성하고 블록 크기 32KB로 최대 처리량을 2,500 IOPS/TB로 설정합니다. 이 경우 사용된 용량이 1TB인 볼륨의 경우 MB/s 임계값을 80MB/s(2500 IOPS * 32KB)/1000으로 효과적으로 설정합니다. 처리량 값이 정의된 임계값보다 10% 작은 경우 Unified Manager에서 경고 이벤트를 생성합니다. 이벤트는 다음과 같은 상황에서 생성됩니다.

|===
| 사용된 용량 2+| 처리량이 이 수를 초과하면 이벤트가 생성됩니다. 


|  | IOPS | MB/s 


 a| 
1TB
 a| 
2,250 IOPS
 a| 
72MB/s



 a| 
2TB입니다
 a| 
4,500IOPS
 a| 
144MB/s



 a| 
5TB
 a| 
11,250 IOPS
 a| 
360MB/s

|===
볼륨에서 2TB의 사용 가능한 공간을 사용하고 IOPS가 4,000이고 클라이언트에서 QoS 블록 크기가 32KB로 설정된 경우 MB/PS 처리량은 128Mb/s(4,000IOPS * 32KB)/1000입니다. 이 시나리오에서는 2TB의 공간을 사용하는 볼륨의 임계값 미만에서 4,000 IOPS와 128 MB/s가 모두 사용되기 때문에 이벤트가 생성되지 않습니다.

볼륨에서 2TB의 사용 가능한 공간을 사용하고 IOPS가 4,000이고 클라이언트에서 QoS 블록 크기가 64KB로 설정된 경우 MB/s 처리량은 256MB/s(4,000IOPS * 64KB)/1000입니다. 이 경우 4,000 IOPS가 이벤트를 생성하지 않지만 256MB/s의 값이 144MB/s의 임계값을 초과하며 이벤트가 생성됩니다.

따라서 블록 크기를 포함하는 적응형 QoS 정책에 대한 MB/s 위반으로 이벤트가 트리거되면 이벤트 세부 정보 페이지의 시스템 진단 섹션에 MB/s 차트가 표시됩니다. 적응형 QoS 정책에 대한 IOPS 위반으로 이벤트가 트리거되면 시스템 진단 섹션에 IOPS 차트가 표시됩니다. IOPS와 MB/s 모두에 대해 위반이 발생한 경우 두 가지 이벤트가 발생합니다.

QoS 설정 조정에 대한 자세한 내용은 을 참조하십시오 https://["성능 관리 개요"].
