---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: IOPS 및 MB/s와 같은 일부 일반적인 성능 카운터는 모든 스토리지 개체에 대해 임계값을 설정할 수 있습니다. 특정 스토리지 객체에 대해서만 임계값을 설정할 수 있는 다른 카운터가 있습니다. 
---
= 임계값을 사용하여 추적할 수 있는 성능 카운터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IOPS 및 MB/s와 같은 일부 일반적인 성능 카운터는 모든 스토리지 개체에 대해 임계값을 설정할 수 있습니다. 특정 스토리지 객체에 대해서만 임계값을 설정할 수 있는 다른 카운터가 있습니다.



== 사용 가능한 성능 카운터

|===
| 스토리지 객체 | 성능 카운터 | 설명 


 a| 
클러스터
 a| 
IOPS
 a| 
클러스터에서 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 클러스터와 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
노드
 a| 
IOPS
 a| 
노드가 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 노드와 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
노드가 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
활용률
 a| 
사용 중인 노드의 CPU 및 RAM의 평균 백분율입니다.



 a| 
사용된 성능 용량
 a| 
노드에서 사용 중인 성능 용량의 평균 백분율입니다.



 a| 
사용된 성능 용량 - 테이크오버입니다
 a| 
노드에서 사용 중인 성능 용량과 파트너 노드의 성능 용량에 대한 평균 비율입니다.



 a| 
집계
 a| 
IOPS
 a| 
초당 집계 프로세스가 수행하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 애그리게이트로부터 초당 전송되는 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
집계가 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
활용률
 a| 
사용 중인 애그리게이트 디스크의 평균 백분율입니다.



 a| 
사용된 성능 용량
 a| 
애그리게이트에서 사용 중인 성능 용량의 평균 백분율입니다.



 a| 
스토리지 VM
 a| 
IOPS
 a| 
SVM 프로세스가 초당 수행하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 SVM과 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
SVM이 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)



 a| 
볼륨
 a| 
IOPS
 a| 
볼륨 프로세스가 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 볼륨으로부터 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
볼륨이 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
캐시 비적중 비율입니다
 a| 
캐시에서 반환되지 않고 볼륨에서 반환되는 클라이언트 애플리케이션의 읽기 요청 평균 비율입니다.



 a| 
LUN을 클릭합니다
 a| 
IOPS
 a| 
LUN이 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 LUN과 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
LUN이 애플리케이션 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
네임스페이스
 a| 
IOPS
 a| 
네임스페이스 프로세스가 초당 처리하는 평균 입출력 작업 수입니다.



 a| 
MB/s
 a| 
이 네임스페이스에서 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
지연 시간
 a| 
네임스페이스가 응용 프로그램 요청에 응답하는 데 걸리는 평균 시간(밀리초)입니다.



 a| 
포트
 a| 
대역폭 사용률
 a| 
사용 중인 포트의 가용 대역폭에 대한 평균 백분율입니다.



 a| 
MB/s
 a| 
이 포트와 초당 전송된 평균 데이터 크기(MB)입니다.



 a| 
네트워크 인터페이스(LIF)
 a| 
MB/s
 a| 
이 LIF와 초당 전송된 평균 데이터 크기(MB)입니다.

|===