---
permalink: performance-checker/reference_performance_event_analysis_and_notification.html 
sidebar: sidebar 
keywords: performance, event, analysis, notification 
summary: 성능 이벤트는 클러스터 구성 요소의 경합으로 인해 발생하는 워크로드의 I/O 성능 문제를 알려줍니다. Unified Manager에서 이벤트를 분석하여 관련 워크로드, 경합 중인 구성 요소 및 문제가 여전히 해결해야 할 문제인지 여부를 파악합니다. 
---
= 성능 이벤트 분석 및 알림
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 이벤트는 클러스터 구성 요소의 경합으로 인해 발생하는 워크로드의 I/O 성능 문제를 알려줍니다. Unified Manager에서 이벤트를 분석하여 관련 워크로드, 경합 중인 구성 요소 및 문제가 여전히 해결해야 할 문제인지 여부를 파악합니다.

Unified Manager는 클러스터의 볼륨에 대한 I/O 지연 시간(응답 시간) 및 IOPS(작업)를 모니터링합니다. 예를 들어, 다른 워크로드가 클러스터 구성 요소를 과도하게 사용하면 구성 요소의 경합이 발생할 수 있으며, 워크로드 수요를 충족하기 위해 최적의 레벨에서 성능을 발휘할 수 없습니다. 동일한 구성요소를 사용하는 다른 워크로드의 성능이 영향을 받을 수 있어 지연 시간이 증가할 수 있습니다. 지연 시간이 동적 성능 임계값을 초과하는 경우 Unified Manager가 성능 이벤트를 트리거하여 사용자에게 알립니다.



== 이벤트 분석

Unified Manager는 이전 15일간의 성능 통계를 사용하여 피해자 워크로드, 불특정 워크로드 및 이벤트와 관련된 클러스터 구성 요소를 파악합니다.

* 지연 시간이 동적 성능 임계값을 초과한 피해자 워크로드 파악, 즉 지연 시간 예측의 상한값
+
** HDD 또는 Flash Pool 하이브리드 애그리게이트(로컬 계층)의 볼륨의 경우, 지연 시간이 5밀리초(ms)보다 크고 IOPS가 초당 10개 이상의 작업(ops/sec)인 경우에만 이벤트가 트리거됩니다.
** All-SSD 애그리게이트 또는 FabricPool 애그리게이트(클라우드 계층)의 볼륨의 경우, 지연 시간이 1ms 미만이고 IOPS가 100 ops/sec를 초과할 경우에만 이벤트가 트리거됩니다


* 경합하는 클러스터 구성 요소를 식별합니다.
+
[NOTE]
====
클러스터 인터커넥트의 피해자 워크로드 지연 시간이 1ms 이상이면 Unified Manager는 이를 중요한 것으로 간주하고 클러스터 인터커넥트에 대한 이벤트를 트리거합니다.

====
* 클러스터 구성 요소를 과도하게 사용하여 경합을 일으키는 대규모 워크로드를 식별합니다.
* 클러스터 구성 요소의 활용도 또는 활동 편차에 따라 관련 워크로드의 순위를 매기하여 클러스터 구성 요소의 사용 빈도가 가장 높고 가장 큰 영향을 받는 피해자를 결정합니다.


이벤트는 잠시 동안 발생할 수 있으며, 사용 중인 구성 요소가 더 이상 충돌하지 않으면 이벤트가 자동으로 보정됩니다. 연속 이벤트는 5분 간격 내에 동일한 클러스터 구성 요소에 대해 다시 발생하고 활성 상태로 유지되는 이벤트입니다. 지속적인 이벤트의 경우, Unified Manager는 두 번의 연속 분석 간격 동안 동일한 이벤트를 감지한 후 알림을 트리거합니다.

이벤트가 해결되면 Unified Manager에서 볼륨에 대한 이전 성능 문제 레코드의 일부로 계속 사용할 수 있습니다. 각 이벤트에는 이벤트 유형과 관련된 볼륨, 클러스터 및 클러스터 구성 요소를 식별하는 고유한 ID가 있습니다.

[NOTE]
====
단일 볼륨은 동시에 여러 이벤트에 참여할 수 있습니다.

====


== 이벤트 상태입니다

이벤트는 다음 상태 중 하나일 수 있습니다.

* * 활성 *
+
성능 이벤트가 현재 활성 상태(새 이벤트 또는 확인된 이벤트)임을 나타냅니다. 이벤트를 발생시키는 문제가 자체적으로 해결되지 않았거나 해결되지 않았습니다. 스토리지 개체의 성능 카운터는 성능 임계값보다 높게 유지됩니다.

* * 사용되지 않음 *
+
이벤트가 더 이상 활성 상태가 아님을 나타냅니다. 이벤트를 발생시키는 문제가 자체적으로 해결되었거나 해결되었습니다. 스토리지 개체의 성능 카운터가 더 이상 성능 임계값을 초과하지 않습니다.





== 이벤트 알림

이벤트는 대시보드 페이지와 사용자 인터페이스의 다른 여러 페이지에 표시되며, 이러한 이벤트에 대한 알림은 지정된 이메일 주소로 전송됩니다. 이벤트에 대한 자세한 분석 정보를 보고 이벤트 세부 정보 페이지 및 워크로드 분석 페이지에서 해결 방법을 확인할 수 있습니다.



== 이벤트 상호 작용

이벤트 세부 정보 페이지와 워크로드 분석 페이지에서 다음과 같은 방법으로 이벤트와 상호 작용할 수 있습니다.

* 이벤트 위로 마우스를 이동하면 이벤트가 감지된 날짜와 시간을 표시하는 메시지가 표시됩니다.
+
동일한 기간에 여러 이벤트가 있는 경우 메시지에 이벤트 수가 표시됩니다.

* 단일 이벤트를 클릭하면 관련된 클러스터 구성 요소를 비롯하여 이벤트에 대한 자세한 정보를 보여 주는 대화 상자가 표시됩니다.
+
경합이 발생한 구성 요소에 동그라미가 표시되며 빨간색으로 강조 표시됩니다. 전체 분석 보기 * 를 클릭하여 이벤트 세부 정보 페이지에서 전체 분석을 볼 수 있습니다. 같은 기간에 여러 이벤트가 있는 경우 대화 상자에 가장 최근의 세 이벤트에 대한 세부 정보가 표시됩니다. 이벤트를 클릭하여 이벤트 세부 정보 페이지에서 이벤트 분석을 볼 수 있습니다.


