---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: 워크로드 분석기 페이지에는 작업 부하에 영향을 줄 수 있는 현재 이벤트에 대한 정보, 이벤트를 발생시키는 문제를 잠재적으로 해결할 수 있는 권장 사항, 성능 및 용량 기록 분석을 위한 차트가 표시됩니다. 
---
= 워크로드 분석기가 표시하는 데이터는 무엇입니까
:icons: font
:imagesdir: ../media/


[role="lead"]
워크로드 분석기 페이지에는 작업 부하에 영향을 줄 수 있는 현재 이벤트에 대한 정보, 이벤트를 발생시키는 문제를 잠재적으로 해결할 수 있는 권장 사항, 성능 및 용량 기록 분석을 위한 차트가 표시됩니다.

페이지 위쪽에서 분석할 워크로드(볼륨 또는 LUN)의 이름과 통계를 보려는 기간을 지정합니다. 더 짧거나 긴 기간을 보려면 언제든지 기간을 변경할 수 있습니다.

페이지의 다른 영역에는 분석 결과와 성능 및 용량 차트가 표시됩니다.

[NOTE]
====
LUN에 대한 워크로드 차트는 볼륨에 대한 해당 차트와 같은 수준의 통계를 제공하지 않으므로 이러한 두 유형의 워크로드를 분석할 때 차이가 있음을 알 수 있습니다.

====
* * 이벤트 요약 영역 *
+
시간 경과에 따라 발생한 이벤트의 수와 유형에 대한 간략한 개요를 표시합니다. 다양한 영향 영역(예: 성능 및 용량)의 이벤트가 있는 경우 이 정보가 표시되므로 관심 있는 이벤트 유형에 대한 세부 정보를 선택할 수 있습니다. 이벤트 유형 을 클릭하여 이벤트 이름 목록을 표시합니다.

+
해당 기간 동안 이벤트가 하나만 있는 경우 일부 이벤트에 대해 문제 해결을 위한 권장 사항 목록이 표시됩니다.

* * 이벤트 타임라인 *
+
지정된 기간 동안 발생한 모든 이벤트를 표시합니다. 각 이벤트 위에 커서를 올려 놓으면 이벤트 이름이 표시됩니다.

+
이벤트 세부 정보 페이지에서 * 워크로드 분석 * 버튼을 클릭하여 이 페이지에 도착한 경우 선택한 이벤트의 아이콘이 더 크게 표시되어 이벤트를 확인할 수 있습니다.

* * 성능 차트 영역 *
+
선택한 기간을 기준으로 지연 시간, 처리량(IOPS 및 MB/s 모두) 및 사용률(노드 및 애그리게이트 모두)에 대한 차트를 표시합니다. 성능 세부 정보 보기 링크를 클릭하면 추가 분석을 수행할 경우에 대비하여 작업 부하에 대한 성능 탐색기 페이지가 표시됩니다.

+
** * 지연 시간 * 선택한 기간 동안 워크로드의 지연 시간을 표시합니다. 이 차트에는 다음과 같은 세 가지 보기가 있습니다.
+
*** * 총 * 지연 시간
*** * Breakdown * 지연 시간(읽기, 쓰기 및 기타 프로세스로 구분)
*** * 클러스터 구성 요소 * 지연 시간(클러스터 구성 요소별로 표시)






을 참조하십시오 link:concept_cluster_components_and_why_they_can_be_in_contention.html["클러스터 구성 요소 및 구성 요소의 경합이 발생할 수 있는 이유"] 에 표시되는 클러스터 구성 요소에 대한 설명이 나와 있습니다. ** * Throughput * 선택한 기간 동안 워크로드의 IOPS 및 MB/s 처리량을 모두 표시합니다. 이 차트에는 다음 네 가지 보기가 있습니다. *** 총 * 처리량 *** 처리량 분석 * 처리량(읽기, 쓰기 및 기타 프로세스로 구분) *** 클라우드 처리량 * (클라우드에 데이터를 쓰고 클라우드에서 데이터를 읽는 데 사용되는 MB/s; 용량을 클라우드에 계층화하는 워크로드의 경우)*** 예측 * 을 사용한 IOPS * (기간 동안 예상되는 상위 및 하위 IOPS 처리량 값의 예측) 이 차트에는 서비스 품질(QoS) 최대 및 최소 처리량 임계값 설정도 표시됩니다(구성된 경우). 따라서 시스템이 QoS 정책을 사용하여 의도적으로 처리량을 제한하는 위치를 확인할 수 있습니다. ** * Utilization * 선택한 기간 동안 워크로드가 실행되는 집계 및 노드에 대한 활용률을 표시합니다. 여기에서 애그리게이트 또는 노드의 활용률이 너무 높은것을 확인할 수 있으며 이로 인해 지연 시간이 길어질 수 있습니다. FlexGroup 볼륨을 분석할 때 활용도 차트에 여러 노드와 여러 애그리게이트가 나열됩니다.

* * 용량 차트 영역 *
+
워크로드의 지난 1개월 동안의 데이터 용량 및 스냅샷 용량에 대한 차트를 표시합니다.

+
볼륨의 경우 View capacity details(용량 세부 정보 보기) 링크를 클릭하여 추가 분석을 수행하려는 경우 워크로드의 Health Details(상태 세부 정보) 페이지를 표시할 수 있습니다. LUN에 대한 상태 세부 정보 페이지가 없으므로 LUN에서 이 링크를 제공하지 않습니다.

+
** * Capacity View * 는 작업 부하에 할당된 총 사용 가능한 공간과 모든 NetApp 최적화 후 논리적 사용 공간을 표시합니다.
** * 스냅샷 뷰 * 는 스냅샷 복사본에 예약된 총 공간과 현재 사용 중인 공간을 표시합니다. LUN은 스냅샷 보기를 제공하지 않습니다.
** * Cloud Tier View * 는 로컬 성능 계층에서 사용되는 용량과 클라우드 계층에서 사용되는 용량을 표시합니다. 이러한 차트에는 이 워크로드에 대한 용량이 가득 차기까지의 남은 예상 시간이 포함됩니다. 이 정보는 과거 사용량을 기준으로 하며 최소 10일 이상의 데이터가 필요합니다. 유니파이드 관리자는 30일 이내에 용량을 유지할 경우 스토리지를 ""거의 꽉 참""으로 식별합니다.



