---
permalink: performance-checker/task_view_node_iops_based_on_workloads_on_local_node.html 
sidebar: sidebar 
keywords: view, node, iops, workloads, reside, only, local node 
summary: '노드 IOPS 카운터 차트는 네트워크 LIF를 사용하여 로컬 노드를 통해서만 원격 노드의 볼륨에 읽기/쓰기 작업을 수행할 수 있는 작업을 강조 표시할 수 있습니다. IOPS - “Total (Local)” 및 “Breakdown (Local)” 차트는 현재 노드에서만 로컬 볼륨에 상주하는 데이터의 IOPS를 표시합니다.' 
---
= 로컬 노드에만 있는 워크로드를 기준으로 노드 IOPS 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 IOPS 카운터 차트는 네트워크 LIF를 사용하여 로컬 노드를 통해서만 원격 노드의 볼륨에 읽기/쓰기 작업을 수행할 수 있는 작업을 강조 표시할 수 있습니다. IOPS - ""Total (Local)" 및 ""Breakdown (Local)" 차트는 현재 노드에서만 로컬 볼륨에 있는 데이터의 IOPS를 표시합니다.

이러한 카운터 차트의 ""로컬"" 버전은 로컬 볼륨에 상주하는 데이터의 통계만 표시하므로 성능 용량 및 활용도에 대한 노드 차트와 비슷합니다.

이러한 카운터 차트의 ""로컬" 버전을 이러한 카운터 차트의 일반 전체 버전과 비교하여 원격 노드의 볼륨에 액세스하기 위해 로컬 노드를 통해 많은 트래픽이 이동하는지 확인할 수 있습니다. 이 상황은 원격 노드의 볼륨에 도달하기 위해 로컬 노드를 통과하는 작업이 너무 많은 경우 노드의 높은 활용도로 인해 성능 문제가 발생할 수 있습니다. 이 경우 볼륨을 로컬 노드로 이동하거나 해당 볼륨에 액세스하는 호스트의 트래픽을 연결할 수 있는 원격 노드에 LIF를 생성할 수 있습니다.

.단계
. 선택한 노드의 * 성능/노드 탐색기 * 페이지의 IOPS 차트의 드롭다운 메뉴에서 * 합계 * 를 선택합니다.
+
IOPS - 합계 차트가 표시됩니다.

. 확대/축소 보기 * 를 클릭하여 새 브라우저 탭에 더 큰 버전의 차트를 표시합니다.
. 성능/노드 탐색기 * 페이지로 돌아가 IOPS 차트의 드롭다운 메뉴에서 * Total (Local) * 을 선택합니다.
+
IOPS - 합계(로컬) 차트가 표시됩니다.

. 확대/축소 보기 * 를 클릭하여 새 브라우저 탭에 더 큰 버전의 차트를 표시합니다.
. 두 차트를 서로 나란히 보고 IOPS 값이 상당히 다르게 나타나는 영역을 확인합니다.
. 이 영역 위로 커서를 이동하여 특정 시점의 로컬 IOPS와 총 IOPS를 비교합니다.

