---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: Unified Manager는 클러스터의 한 노드가 다른 노드보다 훨씬 더 높은 부하에서 작동 중일 때 클러스터 불균형 경고 이벤트를 발생시키며, 이로 인해 워크로드 지연 시간에 영향을 줄 수 있습니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다. 
---
= 클러스터 불균형 성능 이벤트에 대한 대응
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 클러스터의 한 노드가 다른 노드보다 훨씬 더 높은 부하에서 작동 중일 때 클러스터 불균형 경고 이벤트를 발생시키며, 이로 인해 워크로드 지연 시간에 영향을 줄 수 있습니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Unified Manager에서 클러스터의 모든 노드에 대해 사용된 성능 용량과 노드 간 로드 차이가 30%인지 비교하여 클러스터 불균형 임계값 정책 위반에 대한 경고 이벤트를 생성합니다.

다음 단계를 수행하면 고성능 워크로드를 사용률이 낮은 노드로 이동할 수 있는 다음 리소스를 식별할 수 있습니다.

* 활용이 떨어지는 동일한 클러스터의 노드
* 가장 활용도가 낮은 새 노드의 Aggregate
* 현재 노드에서 가장 높은 성능을 보이는 볼륨입니다


.단계
. 이벤트에 대한 정보를 보려면 * 이벤트 * 세부 정보 페이지를 표시합니다.
. 이벤트를 발생시킨 임계값 위반을 설명하는 * Description * 을 검토합니다.
+
예를 들어 "'사용된 성능 용량 카운터'는 클러스터 Dallas-1-8 노드 간의 로드 차이를 나타내며 시스템 임계값인 30%를 기준으로 경고 이벤트를 발생시켰습니다."라는 메시지는 노드 중 하나의 성능 용량이 과도하게 사용되고 노드 성능에 영향을 미친다는 것을 나타냅니다.

. 제안된 작업 * 의 텍스트를 검토하여 고성능 용량 사용 값이 있는 노드에서 사용된 성능 용량이 가장 낮은 노드로 고성능 볼륨을 이동합니다.
. 사용된 용량이 가장 높고 가장 낮은 노드를 식별합니다.
+
.. 이벤트 정보 * 섹션에서 소스 클러스터의 이름을 클릭합니다.
.. 클러스터/성능 요약 * 페이지의 * 관리되는 개체 * 영역에서 * 노드 * 를 클릭합니다.
.. Nodes * inventory 페이지에서 * Performance Capacity Used * 열을 기준으로 노드를 정렬합니다.
.. 사용된 성능 용량이 가장 높고 가장 낮은 노드를 식별하고 해당 이름을 기록합니다.


. 사용된 성능 용량이 가장 높은 노드에서 최대 IOPS를 사용하여 볼륨을 식별합니다.
+
.. 사용된 성능 용량이 가장 높은 노드를 클릭합니다.
.. 노드/성능 탐색기 * 페이지의 * 보기 및 비교 * 메뉴에서 이 노드의 * 집계 * 를 선택합니다.
.. 사용된 성능 용량이 가장 높은 애그리게이트를 클릭합니다.
.. Aggregate/Performance Explorer * 페이지의 * 보기 및 비교 * 메뉴에서 * 이 애그리게이트에 있는 볼륨 * 을 선택합니다.
.. IOPS * 열을 기준으로 볼륨을 정렬하고, 최대 IOPS와 볼륨이 상주하는 애그리게이트의 이름을 사용하여 볼륨의 이름을 기록합니다.


. 사용된 성능 용량이 가장 낮은 노드에서 사용률이 가장 낮은 애그리게이트 식별:
+
.. 스토리지 * > * 애그리게이트 * 를 클릭하여 * 애그리게이트 * 재고 페이지를 표시합니다.
.. 성능: 모든 애그리게이트 * 보기를 선택합니다.
.. 필터 * 버튼을 클릭하고 4단계에서 적어 내려는 성능 용량 사용 값이 가장 낮은 노드 이름과 ""노드""가 같은 필터를 추가합니다.
.. 사용된 성능 용량이 가장 낮은 애그리게이트의 이름을 기록합니다.


. 오버로드된 노드에서 새 노드의 사용률이 낮은 것으로 확인된 애그리게이트로 볼륨을 이동합니다.
+
ONTAP 시스템 관리자, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 툴의 조합을 사용하여 이동 작업을 수행할 수 있습니다.



며칠 후 이 클러스터에서 동일한 클러스터 불균형 이벤트가 발생하는지 확인합니다.
