---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 관리 작업 페이지에서는 Unified Manager에서 이벤트를 통해 통보한 문제를 해결하기 위해 Fix it 또는 Fix All 버튼을 제공합니다. 
---
= Fix it 또는 Fix All 단추가 표시되면 어떤 옵션이 있는지 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 작업 페이지에서는 Unified Manager가 이벤트를 통해 통보한 문제를 해결하기 위해 * Fix it * 또는 * Fix All * 버튼을 제공합니다.

필요한 경우 단추를 클릭하여 문제를 해결하는 것이 좋습니다. 하지만 Unified Manager에서 권장하는 대로 문제를 해결할지 잘 모를 경우 다음 작업을 수행할 수 있습니다.

|===
| 무엇을 하시겠습니까? | * 작업 * 


 a| 
Unified Manager에서 식별된 모든 개체의 문제를 해결하도록 지원
 a| 
모두 수정 * 단추를 클릭합니다.



 a| 
현재 식별된 개체에 대한 문제를 해결하지 말고 이벤트가 다시 발생할 때까지 이 관리 동작을 숨기십시오.
 a| 
아래쪽 화살표를 클릭하고 * 모두 무시 * 를 클릭합니다.



 a| 
식별된 개체 중 일부에 대해서만 문제를 해결합니다.
 a| 
관리 작업의 이름을 클릭하여 목록을 확장하고 모든 개별 * Fix it * 작업을 표시한 다음 개별 관리 작업을 수정 또는 설치 해제합니다.

|===
|===
| 무엇을 하시겠습니까? | 조치 


 a| 
Unified Manager로 문제를 해결하도록 지원
 a| 
Fix it * 버튼을 클릭합니다.



 a| 
이 때 문제를 해결하고 이벤트가 다시 발생할 때까지 이 관리 작업을 숨기십시오.
 a| 
아래쪽 화살표를 클릭하고 * Dismiss * 를 클릭합니다.



 a| 
문제를 더 잘 이해할 수 있도록 이 이벤트에 대한 세부 정보를 표시합니다.
 a| 
* Fix it * 버튼을 클릭하고 결과 대화 상자에 적용할 수정 사항을 검토합니다.
* 아래쪽 화살표를 클릭하고 * 이벤트 세부 정보 보기 * 를 클릭하여 이벤트 세부 정보 페이지를 표시합니다.


그런 다음 문제를 해결하려면 이러한 결과 페이지 중 하나에서 * Fix it * 을 클릭합니다.



 a| 
문제를 더 잘 이해할 수 있도록 이 스토리지 개체의 세부 정보를 표시합니다.
 a| 
성능 탐색기 또는 상태 세부 정보 페이지에 세부 정보를 표시하려면 스토리지 개체의 이름을 클릭합니다.

|===
경우에 따라 15분 구성 폴에 수정 사항이 반영됩니다. 구성 변경을 확인하고 이벤트가 폐기되는 데 최대 몇 시간이 걸릴 수도 있습니다.

완료 또는 진행 중인 관리 작업의 목록을 보려면 필터 아이콘을 클릭하고 * Completed * (완료됨 *) 또는 * In Progress * (진행 중 *)를 선택합니다.

모든 작업을 직렬로 수정함으로써 * In Progress * (진행 중 *) 패널을 볼 때 일부 개체는 Status * In Progress * (상태 * 진행 중 *)가 있는 반면, 다른 개체는 Status * Scheduled * (상태 * 예약됨 *)가 있는 것입니다. 이는 해당 개체가 계속 구현되기를 기다리고 있음을 의미합니다.
