---
permalink: storage-mgmt/concept_provision_and_manage_workloads.html 
sidebar: sidebar 
keywords: provision, manage, workloads 
summary: Active IQ Unified Manager의 액티브 관리 기능은 데이터 센터에서 스토리지 워크로드를 프로비저닝, 모니터링 및 관리하기 위한 성능 서비스 수준, 스토리지 효율성 정책 및 스토리지 공급자 API를 제공합니다. 
---
= 워크로드 프로비저닝 및 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager의 액티브 관리 기능은 데이터 센터에서 스토리지 워크로드를 프로비저닝, 모니터링 및 관리하기 위한 성능 서비스 수준, 스토리지 효율성 정책 및 스토리지 공급자 API를 제공합니다.

[NOTE]
====
Unified Manager는 이 기능을 기본적으로 제공합니다. 이 기능을 사용하지 않으려면 * 스토리지 관리 * > * 기능 설정 * 에서 비활성화할 수 있습니다.

====
사용하도록 설정된 경우, Unified Manager 인스턴스에서 관리하는 ONTAP 클러스터에서 워크로드를 프로비저닝할 수 있습니다. 또한 워크로드에 성능 서비스 수준 및 스토리지 효율성 정책과 같은 정책을 할당하고 이러한 정책을 기반으로 스토리지 환경을 관리할 수도 있습니다.

이 기능을 사용하면 다음 기능을 사용할 수 있습니다.

* 추가된 클러스터에서 스토리지 워크로드를 자동으로 검색하여 스토리지 워크로드를 쉽게 평가하고 구축할 수 있습니다
* NFS 및 CIFS 프로토콜을 지원하는 NAS 워크로드를 프로비저닝합니다
* iSCSI 및 FCP 프로토콜을 지원하는 SAN 워크로드 프로비저닝
* 동일한 파일 공유에서 NFS 및 CIFS 프로토콜을 모두 지원합니다
* 성능 서비스 수준 및 스토리지 효율성 정책 관리
* 스토리지 워크로드에 성능 서비스 수준 및 스토리지 효율성 정책 할당


UI의 왼쪽 창에 있는 * Provisioning *, * Storage * > * 워크로드 * 및 * Policies * 옵션을 사용하여 다양한 구성을 수정할 수 있습니다.

다음 옵션을 사용하여 다음 기능을 수행할 수 있습니다.

* 스토리지 * > * 워크로드 * 페이지에서 스토리지 워크로드를 확인합니다
* 워크로드 프로비저닝 페이지에서 스토리지 워크로드를 생성합니다
* 정책에서 성능 서비스 수준을 생성하고 관리합니다
* 정책에서 스토리지 효율성 정책을 생성하고 관리합니다
* 워크로드 페이지에서 스토리지 워크로드에 정책 할당


* 관련 정보 *

link:../config/concept_policy_based_storage_management.html["정책 기반 스토리지 관리"]
