---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: 'SEP(Storage Efficiency Policy)를 사용하면 워크로드의 스토리지 효율성 특성을 정의할 수 있습니다. 처음에 워크로드를 생성할 때 또는 나중에 워크로드를 편집하여 워크로드에 SEP를 할당할 수 있습니다.' 
---
= 스토리지 효율성 정책 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
SEP(Storage Efficiency Policy)를 사용하면 워크로드의 스토리지 효율성 특성을 정의할 수 있습니다. 처음에 워크로드를 생성할 때 또는 나중에 워크로드를 편집하여 워크로드에 SEP를 할당할 수 있습니다.

스토리지 효율성에는 스토리지 활용률을 높이고 스토리지 비용을 절감하는 씬 프로비저닝, 중복제거, 데이터 압축 등의 기술 사용이 포함됩니다. SRP를 생성하는 동안 이러한 공간 절약 기술을 개별적으로 또는 함께 사용하여 스토리지 효율성을 극대화할 수 있습니다. 정책을 스토리지 워크로드와 연결하면 지정된 정책 설정이 해당 정책에 할당됩니다. Unified Manager를 사용하면 시스템 정의 및 사용자 정의 SRP를 할당하여 데이터 센터의 스토리지 리소스를 최적화할 수 있습니다.

Unified Manager는 두 가지 시스템 정의 CDP, 즉 High와 Low를 제공합니다. 이러한 CDP는 데이터 센터의 스토리지 워크로드 대부분에 적용할 수 있지만, 시스템 정의 CDP가 요구사항을 충족하지 않는 경우 자체 정책을 생성할 수 있습니다.

시스템 정의 SEP 또는 현재 워크로드에 할당된 SEP는 수정할 수 없습니다. 워크로드에 할당된 SEP를 삭제할 수 없으며, 사용 가능한 SEP만 있는 경우 삭제할 수 없습니다.

Storage Efficiency Policies 페이지에는 사용 가능한 SRP가 나열되며, 사용자 지정된 SRP를 추가, 편집 및 삭제할 수 있습니다. 이 페이지에는 다음 정보가 표시됩니다.

|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
SEP의 이름입니다.



 a| 
유형
 a| 
정책이 시스템 정의인지 사용자 정의인지 여부



 a| 
공간 예약
 a| 
볼륨이 씬 프로비저닝되었는지 아니면 일반 프로비저닝되었는지 여부



 a| 
중복 제거
 a| 
워크로드에 중복 제거가 설정되었는지 여부:

* 인라인: 데이터 중복 제거는 워크로드에 기록되는 동안 발생합니다
* 배경: 작업 부하에서 중복 제거가 발생합니다
* 해제: 워크로드에서 중복 제거가 해제되어 있습니다




 a| 
압축
 a| 
워크로드에 데이터 압축이 활성화되어 있는지 여부:

* 인라인: 워크로드에 쓰는 동안 데이터 압축이 발생합니다
* 배경: 작업 부하에서 데이터 압축이 발생합니다
* 비활성화: 작업 부하에서 데이터 압축이 비활성화됩니다




 a| 
워크로드
 a| 
SEP에 할당된 스토리지 워크로드 수입니다

|===


== 맞춤형 스토리지 효율성 정책을 생성하기 위한 지침입니다

기존 SRP가 스토리지 워크로드의 정책 요구사항을 충족하지 않는 경우 맞춤형 SEP를 생성할 수 있습니다. 그러나 스토리지 워크로드에 시스템 정의 CDP를 사용하고 필요한 경우 맞춤형 SRP만 생성하는 것이 좋습니다.

모든 워크로드 페이지와 볼륨/상태 세부 정보 페이지에서 워크로드에 할당된 SEP를 볼 수 있습니다. 대시보드 및 용량:모든 클러스터 보기에서 용량 패널과 이러한 스토리지 효율성을 기준으로 클러스터 레벨 데이터 축소율을 볼 수 있습니다.
