---
permalink: storage-mgmt/concept_fix_ontap_issues_directly_from_unified_manager.html 
sidebar: sidebar 
keywords: fix, ontap, issues, directly, unified manager, fix it, fix-it, remediation 
summary: ONTAP System Manager 또는 ONTAP CLI를 사용하지 않고 Unified Manager 사용자 인터페이스에서 직접 특정 ONTAP 문제를 해결할 수 있습니다. “관리 작업” 옵션은 Unified Manager 이벤트를 트리거한 여러 ONTAP 문제에 대한 수정 사항을 제공합니다. 
---
= Unified Manager에서 직접 ONTAP 문제 또는 기능 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 시스템 관리자나 ONTAP CLI를 사용할 필요 없이 Unified Manager 사용자 인터페이스에서 특정 ONTAP 문제를 직접 수정하거나 특정 ONTAP 기능을 관리할 수 있습니다. ""관리 작업"" 옵션은 Unified Manager 이벤트를 발생시킨 여러 ONTAP 문제에 대한 수정 사항을 제공합니다.

왼쪽 탐색 창에서 * 관리 작업 * 옵션을 선택하여 관리 작업 페이지에서 직접 문제를 해결할 수 있습니다. 관리 작업은 왼쪽 탐색 메뉴의 대시보드, 이벤트 세부 정보 페이지 및 워크로드 분석 선택 항목에 있는 관리 작업 패널에서도 사용할 수 있습니다.

Unified Manager에서 완벽하게 진단하고 한 가지 해결 방법을 제공할 수 있는 특정 문제가 있습니다. 안티 랜섬웨어 모니터링과 같은 특정 ONTAP 기능에 대해 Unified Manager가 내부 점검을 수행하고 특정 조치를 권장합니다. 사용 가능한 경우 이러한 해결 방법은 [Fix it*] 단추로 관리 작업 에 표시됩니다. 문제를 해결하려면 * Fix it * 버튼을 클릭하십시오. 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Unified Manager가 ONTAP 명령을 클러스터에 전송하여 요청된 수정을 실행합니다. 수정이 완료되면 이벤트가 폐기됩니다.

일부 관리 작업을 통해 * 모두 수정 * 버튼을 사용하여 여러 스토리지 개체에서 동일한 문제를 해결할 수 있습니다. 예를 들어, "볼륨 자동 확장 사용"에 대한 * 모든 * 관리 수정 작업을 클릭하여 해결할 수 있는 "볼륨 공간이 가득 참" 이벤트가 있는 볼륨 5개가 있을 수 있습니다. 한 번의 클릭으로 5개의 볼륨에서 이 문제를 해결할 수 있습니다.

자동 조정을 사용하여 관리할 수 있는 ONTAP 문제 및 기능에 대한 자세한 내용은 을 참조하십시오 link:../storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html["Unified Manager로 해결할 수 있는 문제"]
