---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: 모든 워크로드 보기에는 데이터 센터의 클러스터에서 사용 가능한 모든 워크로드 목록이 표시됩니다. 
---
= 워크로드 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 워크로드 보기에는 데이터 센터의 클러스터에서 사용 가능한 모든 워크로드 목록이 표시됩니다.

모든 워크로드 보기에는 Unified Manager에서 관리하는 ONTAP 클러스터와 관련된 스토리지 워크로드가 나열됩니다. 또한 이 페이지에서는 스토리지 워크로드에 CDP(스토리지 효율성 정책) 및 PSL(성능 서비스 수준)을 할당할 수 있습니다.

Unified Manager에 클러스터를 추가하면 FlexGroup 볼륨 및 구성 구성요소를 제외한 각 클러스터의 스토리지 워크로드가 자동으로 검색되어 이 페이지에 표시됩니다.

Unified Manager는 스토리지 워크로드에서 I/O 작업이 시작된 후에만 권장 PSL(권장 PSL)에 대한 워크로드를 분석하기 시작합니다. I/O 작업이 없는 새로 발견된 스토리지 워크로드의 경우 I/O를 기다리는 중입니다. 스토리지 워크로드에서 I/O 작업이 시작되면 Unified Manager가 분석을 시작하고 워크로드 상태가 ""학습...""으로 변경됩니다. 분석이 완료되면(I/O 작업 시작 후 24시간 이내) 스토리지 워크로드에 권장되는 PSL이 표시됩니다.

워크로드 * > * 모든 워크로드 * 옵션을 사용하여 여러 작업을 수행할 수 있습니다.

* 스토리지 워크로드를 추가하거나 프로비저닝
* 워크로드 목록을 보고 필터링합니다
* 스토리지 워크로드에 PSL 할당
* 시스템 권장 PSL을 평가하고 작업 부하에 할당합니다
* 스토리지 워크로드에 CDP를 할당합니다




== 스토리지 워크로드 추가 또는 프로비저닝

지원되는 LUN(iSCSI 및 FCP 프로토콜 모두 지원), NFS 파일 공유 및 SMB 공유에 스토리지 워크로드를 추가하거나 프로비저닝할 수 있습니다.



== 워크로드 보기 및 필터링

모든 워크로드 화면에서 데이터 센터의 모든 워크로드를 확인하거나 PSL 또는 이름을 기준으로 특정 스토리지 워크로드를 검색할 수 있습니다. 필터 아이콘을 사용하여 검색에 대한 특정 조건을 입력할 수 있습니다. 호스트 클러스터나 스토리지 VM과 같은 다양한 필터 조건으로 검색할 수 있습니다. Capacity Total * 옵션을 사용하면 워크로드의 총 용량(MB 단위)으로 필터링할 수 있습니다. 그러나 이 경우 총 용량이 바이트 레벨에서 비교되기 때문에 반환되는 워크로드 수가 달라질 수 있습니다.

각 워크로드에 대해 호스트 클러스터 및 스토리지 VM과 같은 정보가 할당된 PSL 및 SEP와 함께 표시됩니다.

또한 이 페이지에서는 워크로드의 성능 세부 정보를 볼 수 있습니다. 열 선택/주문 * 버튼을 클릭하고 표시할 특정 열을 선택하여 워크로드의 IOPS, 용량, 지연 시간에 대한 자세한 정보를 볼 수 있습니다. 성능 보기 열에는 워크로드에 대한 평균 및 최대 IOPS가 표시되며, 워크로드 분석기 아이콘을 클릭하여 자세한 IOPS 분석을 볼 수 있습니다. IOPS 분석 팝업의 * 워크로드 분석 * 버튼을 누르면 워크로드 분석 페이지로 이동합니다. 이 페이지에서 시간 범위를 선택하고 선택한 워크로드의 지연 시간, 처리량, 용량 추세를 확인할 수 있습니다. 워크로드 분석기에 대한 자세한 내용은 _ 워크로드 분석기를 사용한 워크로드 문제 해결 _ 을(를) 참조하십시오



== 워크로드에 대한 성능 및 용량 기준 분석

성능 보기 * 열에서 막대 차트 아이콘을 클릭하여 문제 해결에 도움이 되는 작업 부하에 대한 성능 정보를 볼 수 있습니다. 워크로드 분석 페이지에서 성능 및 용량 차트를 보고 객체를 분석하려면 * 워크로드 분석 * 버튼을 클릭합니다.
