---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: '대시보드에서는 모니터링되는 ONTAP 시스템의 현재 상태에 대한 누적 정보를 한 눈에 확인할 수 있습니다. 대시보드에는 모니터링 중인 클러스터의 전체 용량, 성능 및 보안 상태를 평가할 수 있는 "패널"이 있습니다.' 
---
= 대시보드에서 클러스터 모니터링 및 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드에서는 모니터링되는 ONTAP 시스템의 현재 상태에 대한 누적 정보를 한 눈에 확인할 수 있습니다. 대시보드에는 모니터링 중인 클러스터의 전체 용량, 성능 및 보안 상태를 평가할 수 있는 ""패널""이 있습니다.

또한 ONTAP 시스템 관리자나 ONTAP CLI를 사용할 필요 없이 Unified Manager 사용자 인터페이스에서 직접 해결할 수 있는 특정 ONTAP 문제가 있습니다.

대시보드 상단에서 패널이 모니터링되는 모든 클러스터에 대한 정보를 표시할지 또는 개별 클러스터에 대한 정보를 표시할지를 선택할 수 있습니다. 먼저 모든 클러스터의 상태를 확인한 다음 세부 정보를 보려는 개별 클러스터로 드릴다운할 수 있습니다.

[NOTE]
====
아래 나열된 패널 중 일부는 구성에 따라 페이지에 나타나지 않을 수 있습니다.

====
|===
| 패널 | 설명 


 a| 
관리 조치
 a| 
Unified Manager에서 문제에 대한 단일 해결책을 진단하고 결정할 수 있으면 해당 해결 방법이 * Fix it * 버튼과 함께 이 패널에 표시됩니다.



 a| 
용량
 a| 
로컬 계층 및 클라우드 계층에 대한 총 용량 및 사용된 용량, 로컬 용량이 상한에 도달할 때까지 남은 일 수를 표시합니다.



 a| 
성능 용량
 a| 
각 클러스터의 성능 용량 값과 성능 용량이 상한에 도달할 때까지 남은 일 수를 표시합니다.



 a| 
워크로드 IOPS
 a| 
특정 IOPS 범위에서 현재 실행 중인 총 워크로드 수를 표시합니다.



 a| 
워크로드 성능
 a| 
정의된 각 성능 서비스 수준에 할당된 준수 및 부적합 워크로드의 총 수를 표시합니다.



 a| 
보안
 a| 
규정을 준수하거나 준수하지 않는 클러스터의 수, 규정을 준수하거나 준수하지 않는 SVM의 수, 암호화되거나 암호화되지 않은 볼륨의 수를 표시합니다.



 a| 
보호
 a| 
SVM-DR 관계에 의해 보호되는 스토리지 VM 수, SnapMirror 관계에 의해 보호되는 볼륨 및 Snapshot에 의해 보호되는 볼륨을 표시합니다.



 a| 
사용 개요
 a| 
가장 높은 IOPS, 가장 높은 처리량(MBps) 또는 가장 많이 사용되는 물리적 용량에 따라 정렬된 클러스터를 표시합니다.

|===