---
permalink: storage-mgmt/concept_mcc_svmdr_vmawareness.html 
sidebar: sidebar 
keywords: view, virtual, infrastructure, disaster, recovery, setup, datastores, metrocluster configuration 
summary: 'MetroCluster 구성 또는 스토리지 가상 시스템(스토리지 VM) SVM DR(재해 복구) 설정에서 호스팅되는 데이터 저장소의 구성 및 성능 메트릭을 확인할 수 있습니다.' 
---
= 재해 복구 설정에서 가상 인프라 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성 또는 스토리지 가상 시스템(스토리지 VM) SVM DR(재해 복구) 설정에서 호스팅되는 데이터 저장소의 구성 및 성능 메트릭을 확인할 수 있습니다.

Unified Manager에서는 vCenter Server에서 데이터 저장소로 연결된 MetroCluster 구성에서 NAS 볼륨 또는 LUN을 볼 수 있습니다. MetroCluster 구성에서 호스팅되는 데이터스토어는 표준 환경에서 데이터스토어와 동일한 토폴로지 뷰로 표시됩니다.

vCenter Server의 데이터 저장소에 매핑된 스토리지 VM 재해 복구 구성의 NAS 볼륨 또는 LUN도 볼 수 있습니다.



== MetroCluster 구성에서 데이터 저장소 보기

MetroCluster 구성에서 데이터 저장소를 보기 전에 다음 사전 요구 사항을 확인하십시오.

* 스위치오버 및 스위치백을 수행할 경우 HA 쌍의 기본 및 보조 클러스터와 vCenter Server의 검색이 완료됩니다.
* HA 쌍의 운영 클러스터와 보조 클러스터와 vCenter Server는 Unified Manager를 통해 관리해야 합니다.
* ONTAP 및 vCenter Server에서 필요한 설정을 완료해야 합니다. 자세한 내용은 ONTAP 및 vCenter 설명서를 참조하십시오.
+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]



데이터 저장소를 보려면 다음 단계를 수행하십시오.

. VMware * > * Virtual Machines * 페이지에서 데이터 저장소를 호스팅하는 VM을 클릭합니다. 워크로드 분석기 * 또는 데이터 저장소 객체 링크를 클릭합니다. 표준 시나리오에서는 볼륨 또는 LUN을 호스팅하는 운영 사이트가 예상대로 작동하는 경우 기본 사이트의 SVM 클러스터 세부 정보를 볼 수 있습니다.
. 재해 발생 시 데이터 저장소 링크는 보조 클러스터에 있는 볼륨 또는 LUN의 성능 메트릭을 가리킵니다. 이는 클러스터의 다음 주기 및 가상 서버 검색(획득)이 완료된 후에 반영됩니다.
. 스위치백을 성공적으로 완료한 후 데이터 저장소 링크는 운영 클러스터에 있는 볼륨 또는 LUN의 성능 메트릭을 다시 반영합니다. 이는 클러스터의 다음 주기 및 가상 서버 검색이 완료된 후에 반영됩니다.




== 스토리지 VM 재해 복구 구성의 데이터 저장소 보기

스토리지 VM 재해 복구 구성에서 데이터 저장소를 보기 전에 다음 사전 요구 사항을 확인하십시오.

* 스위치오버 및 스위치백을 수행할 경우 HA 쌍의 기본 및 보조 클러스터와 vCenter Server의 검색이 완료됩니다.
* 소스 및 타겟 클러스터와 스토리지 VM 피어는 모두 Unified Manager를 통해 관리해야 합니다.
* ONTAP 및 vCenter Server에서 필요한 설정을 완료해야 합니다.
+
** NAS(NFS 및 VMFS) 데이터 저장소의 경우 재해가 발생할 경우 보조 스토리지 VM을 가져와 데이터 LIF 및 경로 확인, vCenter Server에서 손실된 연결 설정 및 VM 시작 단계가 포함됩니다.
+
기본 사이트로 스위치백을 수행할 경우 기본 사이트에서 데이터 제공을 시작하기 전에 볼륨 간 데이터를 동기화해야 합니다.

** SAN(iSCSI 및 FC for VMFS) 데이터 저장소의 경우 vCenter Server는 마운트된 LUN을 VMFS 형식으로 포맷합니다. 재해 발생 시 보조 스토리지 VM을 가져와 데이터 LIF 및 경로를 확인하는 단계가 포함됩니다. iSCSI 타겟 IP가 운영 LIF와 다른 경우 수동으로 추가해야 합니다. 새 LUN은 호스트의 스토리지 어댑터의 iSCSI 어댑터 아래에 디바이스로 사용할 수 있어야 합니다. 그런 다음 새 LUN이 있는 새 VMFS 데이터 저장소를 생성하고 이전 VM을 새 이름으로 등록해야 합니다. VM이 실행 중이어야 합니다.
+
복구 시 볼륨 간 데이터를 동기화해야 합니다. 새 VMFS 데이터 저장소는 LUN과 새 이름으로 등록된 이전 VM을 사용하여 다시 생성해야 합니다.

+
설정에 대한 자세한 내용은 ONTAP and vCenter Server 설명서를 참조하십시오.

+
https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"]





데이터 저장소를 보려면 다음 단계를 수행하십시오.

. VMware * > * Virtual Machines * 페이지에서 데이터 저장소를 호스팅하는 VM 인벤토리를 클릭합니다. 데이터 저장소 객체 링크를 클릭합니다. 표준 시나리오에서는 운영 스토리지 VM에 있는 볼륨 및 LUN의 성능 데이터를 확인할 수 있습니다.
. 재해 발생 시 보조 스토리지 VM으로 연속적으로 전환하는 데이터 저장소 링크는 보조 스토리지 VM에 있는 볼륨 또는 LUN의 성능 메트릭을 가리킵니다. 이는 클러스터의 다음 주기 및 가상 서버 검색(획득)이 완료된 후에 반영됩니다.
. 스위치백을 성공적으로 완료한 후 데이터 저장소 링크는 운영 스토리지 VM의 볼륨 또는 LUN의 성능 메트릭을 다시 반영합니다. 이는 클러스터의 다음 주기 및 가상 서버 검색이 완료된 후에 반영됩니다.




== 지원되지 않는 시나리오입니다

* MetroCluster 구성의 경우 다음과 같은 제한 사항에 유의하십시오.
+
** 정상과 위시WER의 군집들만 잡게 됩니다. partial_switchover, partial_스위치백, not_reachable 등의 다른 상태는 지원되지 않습니다.
** ASO(Automatic Switch over)가 설정되어 있지 않으면 운영 클러스터가 다운되면 보조 클러스터를 검색할 수 없으며 토폴로지가 운영 클러스터의 볼륨 또는 LUN을 계속 가리킵니다.


* 스토리지 VM 재해 복구 구성의 경우 다음 제한 사항에 유의하십시오.
+
** SAN 스토리지 환경에 대해 SRM(Site Recovery Manager) 또는 SRA(Storage Replication Adapter)가 활성화된 구성은 지원되지 않습니다.



