---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: 워크로드는 볼륨 또는 LUN과 같은 스토리지 개체의 입출력 작업을 나타냅니다. 스토리지가 프로비저닝되는 방식은 예상되는 워크로드 요구 사항을 기반으로 합니다. 워크로드 통계는 스토리지 오브젝트 간에 트래픽이 있는 경우에만 Active IQ Unified Manager에서 추적합니다. 예를 들어 워크로드 IOPS 및 지연 시간 값은 사용자가 데이터베이스 또는 이메일 애플리케이션을 시작한 후에 사용할 수 있습니다. 
---
= 워크로드 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
워크로드는 볼륨 또는 LUN과 같은 스토리지 개체의 입출력 작업을 나타냅니다. 스토리지가 프로비저닝되는 방식은 예상되는 워크로드 요구 사항을 기반으로 합니다. 워크로드 통계는 스토리지 오브젝트 간에 트래픽이 있는 경우에만 Active IQ Unified Manager에서 추적합니다. 예를 들어 워크로드 IOPS 및 지연 시간 값은 사용자가 데이터베이스 또는 이메일 애플리케이션을 시작한 후에 사용할 수 있습니다.

워크로드 페이지에는 Unified Manager에서 관리하는 ONTAP 클러스터의 스토리지 워크로드가 요약되어 있습니다. Performance Service Level을 준수하는 스토리지 워크로드와 부적합 스토리지 워크로드에 대한 누적 요약 정보를 제공합니다. 또한 데이터 센터 전반에서 클러스터의 총, 사용 가능, 사용된 용량 및 성능(IOPS)을 평가할 수 있습니다.

[NOTE]
====
어떤 성능 서비스 레벨에서든 부적합, 사용 불가능 또는 관리되지 않는 스토리지 워크로드의 수를 평가하고 적합성, 용량 사용 및 IOPS를 보장하기 위해 필요한 조치를 취하는 것이 좋습니다.

====
워크로드 페이지에는 다음 두 섹션이 있습니다.

* 워크로드 개요: Unified Manager가 관리하는 ONTAP 클러스터의 스토리지 워크로드 수를 간략하게 설명합니다.
* 데이터 센터 개요: 데이터 센터 내 스토리지 워크로드의 용량 및 IOPS에 대한 개요를 제공합니다. 관련 데이터는 데이터 센터 레벨 및 개인에 대해 표시됩니다.




== 워크로드 개요 섹션을 참조하십시오

워크로드 개요 섹션에서는 스토리지 워크로드에 대한 요약 정보를 제공합니다. 스토리지 워크로드의 상태는 할당되고 할당되지 않은 성능 서비스 수준에 따라 표시됩니다.

* * 할당됨 *: 성능 서비스 수준이 할당된 스토리지 워크로드에 대해 다음 상태가 보고됩니다.
+
** * 준수 *: 스토리지 워크로드의 성능은 할당된 성능 서비스 수준을 기준으로 합니다. 스토리지 워크로드가 관련 성능 서비스 수준에 정의된 임계값 지연 시간 내에 있으면 ""준수""로 표시됩니다. 적합 워크로드는 파란색으로 표시됩니다.
** * 부적합 *: 스토리지 워크로드의 지연 시간이 관련 성능 서비스 수준에 정의된 임계값 지연 시간을 초과할 경우 성능 모니터링 중에 스토리지 워크로드가 ""부적합""으로 표시됩니다. 부적합 워크로드는 주황색으로 표시됩니다.
** * 사용할 수 없음 *: 스토리지 워크로드가 오프라인이거나 해당 클러스터에 연결할 수 없는 경우 ""사용할 수 없음""으로 표시됩니다. 사용할 수 없는 워크로드는 빨간색으로 표시됩니다.


* * 할당되지 않음 *: 성능 서비스 수준이 할당되지 않은 스토리지 워크로드는 ""할당되지 않음""으로 보고됩니다. 숫자는 정보 아이콘을 통해 전달됩니다.


총 워크로드 수는 할당되고 할당되지 않은 워크로드의 합계입니다.

이 섹션에 표시된 총 워크로드 수를 클릭하고 워크로드 페이지에서 볼 수 있습니다.

성능 서비스 수준별 준수 하위 섹션에는 사용 가능한 총 스토리지 워크로드 수가 표시됩니다.

* 각 유형의 성과 서비스 수준 준수
* 할당된 성능 수준과 권장 성능 서비스 수준이 일치하지 않습니다




== 데이터 센터 개요 섹션을 참조하십시오

데이터 센터 개요 섹션에서는 데이터 센터의 모든 클러스터에서 사용 가능한 용량과 사용된 용량 및 IOPS를 그래픽으로 보여 줍니다. 이 데이터를 사용하여 스토리지 워크로드의 용량과 IOPS를 관리해야 합니다. 이 섹션에는 모든 클러스터에서 스토리지 워크로드에 대한 다음 정보도 표시됩니다.

* 데이터 센터의 모든 클러스터에 대한 총 용량, 사용 가능 용량 및 사용된 용량입니다
* 데이터 센터의 모든 클러스터에 대해 사용 가능한 총 IOPS와 사용된 IOPS
* 각 성능 서비스 수준에 따라 사용 가능한 용량과 사용된 용량
* 각 성능 서비스 수준에 기반한 사용 가능한 IOPS 및 사용된 IOPS
* 성능 서비스 수준이 할당되지 않은 워크로드에서 사용하는 총 공간 및 IOPS


* 성능 서비스 수준을 기준으로 데이터 센터 용량과 성능을 계산하는 방법 *

사용된 용량과 IOPS는 클러스터에 있는 모든 스토리지 워크로드의 사용된 총 용량과 성능을 기준으로 검색됩니다.

사용 가능한 IOPS는 노드의 예상 지연 시간과 권장 성능 서비스 수준을 기준으로 계산됩니다. 여기에는 예상 지연 시간이 자신만의 예상 지연 시간보다 작거나 같은 모든 성능 서비스 수준에 대해 사용 가능한 IOPS가 포함됩니다.

가용 용량은 애그리게이트에서 예상되는 지연 시간과 권장되는 성능 서비스 수준을 기준으로 계산됩니다. 여기에는 예상 지연 시간이 예상 대기 시간보다 작거나 같은 모든 Performance Service 수준에 사용할 수 있는 용량이 포함됩니다.
