---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance service level, PSL, User-defined, system-defined PSL, bursty, Database PSL, extreme PSL, beyond extreme PSL 
summary: 성능 서비스 수준 계산 및 관리 
---
= 성능 서비스 레벨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PSL(성능 서비스 수준)을 사용하면 작업 부하에 대한 성능 및 스토리지 목표를 정의할 수 있습니다. 처음에 워크로드를 생성할 때 또는 작업 부하를 편집하여 작업 부하에 PSL을 할당할 수 있습니다.

스토리지 리소스의 관리 및 모니터링은 SLO(서비스 수준 목표)를 기준으로 합니다. SLO는 필요한 성능 및 용량을 기준으로 한 서비스 수준 계약에 의해 정의됩니다. Unified Manager에서 SLO는 NetApp 스토리지에서 실행되는 애플리케이션의 PSL 정의를 참조합니다. 스토리지 서비스는 기본 리소스의 성능과 활용률을 기준으로 차별화됩니다. PSL은 스토리지 서비스 목표에 대한 설명입니다. PSL을 사용하면 스토리지 공급업체가 워크로드의 성능 및 용량 목표를 지정할 수 있습니다. 작업 부하에 PSL을 할당하면 ONTAP의 해당 작업 부하가 성능 및 용량 목표에 따라 관리됩니다. 각 PSL은 최대, 예상 및 절대 최소 IOPS와 예상 지연 시간에 따라 결정됩니다.

Unified Manager에는 다음과 같은 유형의 PSL이 있습니다.

* * 시스템 정의 *: Unified Manager는 변경할 수 없는 몇 가지 미리 정의된 정책을 제공합니다. 사전 정의된 PSL은 다음과 같습니다.
+
** 최고 성능
** 성능
** 값
+
최고 성능, 성능 및 가치 PSL은 데이터 센터의 일반적인 스토리지 워크로드 대부분에 적용할 수 있습니다.

+
또한 Unified Manager는 데이터베이스 애플리케이션에 3가지 성능 서비스 수준을 제공합니다. 이러한 PSL은 폭발적으로 증가하는 IOPS를 지원하는 매우 높은 성능의 PSL로, 처리량이 가장 많은 데이터베이스 애플리케이션에 적합합니다.

** 데이터베이스 로그의 경우 극한입니다
** 데이터베이스 공유 데이터의 경우 매우 높음
** 데이터베이스 데이터의 경우 매우 높음


* * 사용자 정의 *: 사전 정의된 성능 서비스 수준이 요구 사항을 충족하지 않는 경우, 필요에 따라 새로운 PSL을 생성할 수 있습니다. 자세한 내용은 을 참조하십시오 link:../storage-mgmt/task_create_and_edit_psls.html["성능 서비스 수준 생성 및 편집"].
* 익스트림 * 그 이상 *: 익스트림 PSL은 IOP가 Extreme보다 높은 워크로드에 권장되는 시스템 권장 PSL입니다. 워크로드는 IOPS, 용량 및 지연 시간을 기준으로 내부적으로 분석되며, * Storage > 워크로드 > 모든 워크로드 * 화면에서 이러한 각 워크로드에 대해 Extreme PSL 이상을 사용하는 것이 좋습니다. 최적의 성능을 보장하기 위해 작업 부하에 PSL을 적용할 수 있습니다.
+
워크로드의 IOPS 매개 변수는 워크로드 동작에 따라 동적으로 생성되고, 'Beyond Extreme<number-(peak IOPS/TB)><number(expected IOPS/TB)>' 형식으로 Beyond Extreme PSL의 이름에 추가됩니다. 예를 들어, 시스템에서 최대 및 예상 IOP를 각각 106345 및 37929로 결정하는 경우, 해당 워크로드에 대해 생성되는 익스트림 PSL보다 더 높은 이름은 Extreme 106345 37929입니다. 시스템에서 이러한 PSL을 권장하지만 워크로드에 PSL을 할당할 때는 유형에 "사용자 정의"로 레이블이 지정됩니다.





== PSL을 할당하여 작업 부하 관리

PSL은 * Policies * > * Performance Service Levels * 페이지에서, 그리고 스토리지 공급자 API를 사용하여 액세스할 수 있습니다. 스토리지 작업 부하를 개별적으로 관리할 필요가 없으며 PSL을 할당하여 스토리지 작업 부하를 관리하는 것이 편리합니다. 모든 수정 사항은 개별적으로 관리하는 대신 다른 PSL을 다시 할당하여 관리할 수도 있습니다. Unified Manager를 사용하면 내부 평가 및 권장사항을 기반으로 워크로드에 PSL을 할당할 수 있습니다.

워크로드에 시스템 권장 PSL을 할당하는 방법에 대한 자세한 내용은 을 참조하십시오 link:..//storage-mgmt/concept_assign_policies_on_workloads.html#assigning-system-recommended-psls-to-workloads["작업 부하에 시스템 권장 PSL 할당"]

성능 서비스 수준 페이지에는 사용 가능한 PSL 정책이 나열되며 이를 추가, 편집 및 삭제할 수 있습니다.


NOTE: 시스템 정의 PSL이나 현재 워크로드에 할당된 PSL은 수정할 수 없습니다. 작업 부하에 할당된 PSL이나 사용 가능한 PSL만 삭제할 수는 없습니다.

이 페이지에는 다음 정보가 표시됩니다.

|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
PSL의 이름입니다.



 a| 
유형
 a| 
정책이 시스템 정의인지 사용자 정의인지 여부



 a| 
예상 IOPS/TB
 a| 
애플리케이션이 LUN 또는 파일 공유에 대해 수행해야 하는 최소 IOPS 수입니다. 예상 IOPS는 할당된 스토리지 개체 크기를 기준으로 할당된 최소 예상 IOPS를 지정합니다.



 a| 
최대 IOPS/TB
 a| 
애플리케이션이 LUN 또는 파일 공유에서 수행할 수 있는 최대 IOPS 수입니다. 최대 IOPS는 할당된 스토리지 객체 크기 또는 사용된 스토리지 객체 크기를 기준으로 할당된 최대 IOPS를 지정합니다.

최대 IOPS는 할당 정책을 기반으로 합니다. 할당 정책은 할당 공간 또는 사용된 공간입니다. 할당 정책을 allocated-space로 설정하면 peak IOPS는 스토리지 객체의 크기에 따라 계산됩니다. 할당 정책이 사용된 공간으로 설정된 경우, 스토리지 효율성을 고려하여 최대 IOPS는 스토리지 객체에 저장된 데이터의 양을 기준으로 계산됩니다. 기본적으로 할당 정책은 사용된 공간으로 설정됩니다.



 a| 
절대 최소 IOPS
 a| 
예상 IOPS가 이 값보다 작은 경우 절대 최소 IOPS가 재정의로 사용됩니다. 시스템 정의 PSL의 기본값은 다음과 같습니다.

* 최고 성능: 예상 IOPS >= 6144/TB인 경우 절대 최소 IOPS = 1000
* 성능: 예상 IOPS >= 2048/TB 및 < 6144/TB인 경우 절대 최소 IOPS = 500
* 값: 예상 IOPS >= 128/TB 및 < 2048/TB인 경우 절대 최소 IOPS = 75


시스템 정의 데이터베이스 PSL의 기본값은 다음과 같습니다.

* 데이터베이스 로그의 경우 매우 높음: 예상 IOPS >= 22528, 절대 최소 IOPS = 4000
* 데이터베이스 공유 데이터의 경우 매우 높음: 예상 IOPS > = 16384, 절대 최소 IOPS = 2000
* 데이터베이스 데이터의 경우 매우 높음: 예상 IOPS >= 12288이면 절대 최소 IOPS = 2000입니다


사용자 지정 PSL에 대한 절대 최소 IOPS의 값이 클수록 최대 75000이 될 수 있습니다. 낮은 값은 다음과 같이 계산됩니다.

1000/예상 지연 시간



 a| 
예상되는 지연 시간
 a| 
스토리지 IOPS에 대한 예상 지연 시간(밀리초/밀리초/작업).



 a| 
용량
 a| 
클러스터에서 사용 가능한 총 용량 및 사용된 용량입니다.



 a| 
워크로드
 a| 
PSL에 할당된 스토리지 워크로드 수입니다.

|===
ONTAP 클러스터에서 피크 IOPS와 예상 IOPS가 일관된 차별화된 성능을 달성하는 데 어떤 도움이 되는지 알아보려면 다음 KB 문서를 참조하십시오.https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["성능 예산이란 무엇입니까?"]



=== 작업 부하에 대해 생성된 이벤트가 PSL에서 정의한 임계값을 초과합니다

워크로드가 이전 시간 중 예상 지연 시간 값을 30%까지 초과할 경우 Unified Manager에서 다음 이벤트 중 하나를 생성하여 잠재적 성능 문제를 알립니다.

* 워크로드 볼륨 지연 임계값 성능 서비스 수준 정책에 정의된 대로 위반됩니다
* 워크로드 LUN 지연 임계값 성능 서비스 수준 정책에 정의된 위반


워크로드를 분석하여 지연 시간 값이 더 큰 원인이 될 수 있는 것이 무엇인지 확인할 수 있습니다.

자세한 내용은 다음 링크를 참조하십시오.

* link:../events/reference_volume_events.html#impact-area-performance["볼륨 이벤트"]
* link:../performance-checker/concept_what_happens_when_performance_threshold_policy_is_breached.html["성능 임계값 정책이 위반될 경우 발생하는 현상"]
* link:..//performance-checker/concept_how_unified_manager_uses_workload_response_time.html["Unified Manager에서 워크로드 지연 시간을 사용하여 성능 문제를 식별하는 방법"]
* link:../performance-checker/concept_what_performance_events_are.html["어떤 성능 이벤트가 있는지 확인합니다"]




=== 시스템 정의 PSL

다음 표에는 시스템 정의 PSL에 대한 정보가 나와 있습니다.

|===
| 성능 서비스 수준 | 설명 및 사용 사례 | 예상 지연 시간(ms/op) | 최대 IOPS | 예상 IOPS | 절대 최소 IOPS 


 a| 
최고 성능
 a| 
매우 짧은 지연 시간으로 매우 높은 처리량을 제공합니다

지연 시간에 민감한 애플리케이션에 적합합니다
 a| 
1
 a| 
12288
 a| 
6144
 a| 
1000입니다



 a| 
성능
 a| 
짧은 지연 시간으로 높은 처리량을 제공합니다

데이터베이스 및 가상화 애플리케이션에 적합합니다
 a| 
2
 a| 
4096
 a| 
2048
 a| 
500입니다



 a| 
값
 a| 
높은 스토리지 용량과 적절한 지연 시간을 제공합니다

이메일, 웹 콘텐츠, 파일 공유, 백업 타겟 등의 대용량 애플리케이션에 적합합니다
 a| 
17
 a| 
512
 a| 
128
 a| 
75를



 a| 
데이터베이스 로그의 경우 극한입니다
 a| 
가장 짧은 지연 시간으로 최대 처리량을 제공합니다.

데이터베이스 로그를 지원하는 데이터베이스 애플리케이션에 적합합니다. 이 PSL은 데이터베이스 로그가 폭발적으로 증가하고 로깅이 지속적으로 요구되기 때문에 가장 높은 처리량을 제공합니다.
 a| 
1
 a| 
45056
 a| 
22528
 a| 
4,000



 a| 
데이터베이스 공유 데이터의 경우 매우 높음
 a| 
가장 짧은 지연 시간으로 매우 높은 처리량을 제공합니다.

공통 데이터 저장소에 저장되지만 데이터베이스 간에 공유되는 데이터베이스 애플리케이션 데이터에 적합합니다.
 a| 
1
 a| 
32768
 a| 
16384)를 참조하십시오
 a| 
2000년



 a| 
데이터베이스 데이터의 경우 매우 높음
 a| 
가장 짧은 지연 시간으로 높은 처리량을 제공합니다.

데이터베이스 테이블 정보 및 메타데이터와 같은 데이터베이스 애플리케이션 데이터에 적합합니다.
 a| 
1
 a| 
24576)을 참조하십시오
 a| 
12288
 a| 
2000년

|===