---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: '다양한 탐색 옵션을 사용하여 모든 워크로드 페이지의 스토리지 워크로드에 CDP(스토리지 효율성 정책) 및 PSL(성능 서비스 수준)을 할당할 수 있습니다.' 
---
= 작업 부하에 정책 할당
:icons: font
:imagesdir: ../media/


[role="lead"]
다양한 탐색 옵션을 사용하여 모든 워크로드 페이지의 스토리지 워크로드에 CDP(스토리지 효율성 정책) 및 PSL(성능 서비스 수준)을 할당할 수 있습니다.



== 단일 워크로드에 정책 할당

PSL 또는 SEP 또는 둘 모두를 단일 작업 부하에 할당할 수 있습니다. 다음 단계를 수행하십시오.

. 워크로드를 선택합니다.
. 행 옆에 있는 편집 아이콘을 클릭한 다음 * 편집 * 을 클릭합니다.
+
할당된 성능 서비스 수준 * 및 * 스토리지 효율성 정책 * 필드가 활성화됩니다.

. 필요한 PSL 또는 SEP 또는 둘 다를 선택합니다.
. 확인 아이콘을 클릭하여 변경 사항을 적용합니다.


[NOTE]
====
워크로드를 선택하고 * 추가 작업 * 을 클릭하여 정책을 할당할 수도 있습니다.

====


== 여러 스토리지 워크로드에 정책 할당

여러 스토리지 작업 부하에 PSL 또는 SEP를 함께 할당할 수 있습니다. 다음 단계를 수행하십시오.

. 정책을 할당할 워크로드의 확인란을 선택하거나 데이터 센터의 모든 워크로드를 선택합니다.
. 추가 작업 * 을 클릭합니다.
. PSL을 할당하려면 * 성능 서비스 수준 할당 * 을 선택합니다. SEP를 할당하려면 * 스토리지 효율성 정책 할당 * 을 선택합니다. 정책을 선택할 수 있는 팝업이 표시됩니다.
. 적절한 정책을 선택하고 * 적용 * 을 클릭합니다. 정책이 할당된 워크로드 수가 표시됩니다. 정책이 할당되지 않은 워크로드도 원인과 함께 나열됩니다.
+
[NOTE]
====
선택한 워크로드 수에 따라 워크로드를 대량으로 정책을 적용하는 데 시간이 걸릴 수 있습니다. 백그라운드 * 실행 버튼을 클릭하여 백그라운드에서 작업이 실행되는 동안 다른 작업을 계속할 수 있습니다. 대량 할당이 완료되면 완료 상태를 볼 수 있습니다. 여러 작업 부하에 PSL을 적용하는 경우 이전 대량 할당 작업이 실행 중일 때 다른 요청을 트리거할 수 없습니다.

====




== 작업 부하에 시스템 권장 PSL 할당

PSL이 할당되지 않았거나 할당된 PSL이 시스템 권장 사항과 일치하지 않는 데이터 센터의 스토리지 워크로드에 시스템 권장 PSL을 할당할 수 있습니다. 이 기능을 사용하려면 * 시스템 권장 PSL 할당 * 버튼을 클릭합니다. 특정 워크로드를 선택할 필요가 없습니다.

권장 사항은 내부적으로 시스템 분석에 의해 결정되며, IOPS 및 기타 매개 변수가 사용 가능한 모든 PSL의 정의와 일치하지 않는 워크로드의 경우 건너뜁니다. 입출력 대기 중 및 학습 상태의 스토리지 워크로드도 제외됩니다.

[NOTE]
====
Unified Manager에서 워크로드 이름을 찾아 시스템 분석을 재정의하고 워크로드에 대해 다른 PSL을 추천하도록 하는 특수 키워드가 있습니다. 작업 부하는 이름에 ""ora""가 있으면** Extreme Performance** PSL을 사용하는 것이 좋습니다. 작업 부하에는 이름에 ""VM""이라는 글자가 있으면** 성능** PSL을 사용하는 것이 좋습니다.

====