---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: '대시보드 페이지에는 모니터링하는 클러스터의 높은 수준, 성능 및 보안 상태를 표시하는 "패널"이 있습니다. 또한 Unified Manager에서 특정 이벤트를 해결하기 위해 수행할 수 있는 수정 사항이 나열된 관리 작업 패널도 제공합니다.' 
---
= 대시보드 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드 페이지에는 모니터링하는 클러스터의 높은 수준, 성능 및 보안 상태를 표시하는 "패널"이 있습니다. 또한 Unified Manager에서 특정 이벤트를 해결하기 위해 수행할 수 있는 수정 사항이 나열된 관리 작업 패널도 제공합니다.

또한 대부분의 패널에는 해당 범주의 활성 이벤트 수와 이전 24시간 동안 추가된 새 이벤트 수가 표시됩니다. 이 정보는 이벤트를 해결하기 위해 더 자세히 분석해야 할 클러스터를 결정하는 데 도움이 됩니다. 이벤트를 클릭하면 상위 이벤트가 표시되고 해당 범주의 활성 이벤트를 표시하도록 필터링된 이벤트 관리 인벤토리 페이지로 연결되는 링크가 제공됩니다.

대시보드 맨 위에서 패널이 모니터링되는 모든 클러스터("모든 클러스터")에 대한 정보를 표시할지 또는 개별 클러스터에 대한 정보를 표시할지 여부를 선택할 수 있습니다. 먼저 모든 클러스터의 상태를 확인한 다음 세부 정보를 보려는 개별 클러스터로 드릴다운할 수 있습니다.

[NOTE]
====
아래 나열된 패널 중 일부는 구성에 따라 대시보드에 표시됩니다.

====


== 관리 작업 패널

Unified Manager에서 완벽하게 진단하고 한 가지 해결 방법을 제공할 수 있는 특정 문제가 있습니다. 사용 가능한 경우 이러한 해상도는 이 패널에 * Fix it * 또는 * Fix All * 버튼과 함께 표시됩니다. ONTAP System Manager 또는 ONTAP CLI를 사용하지 않고 Unified Manager에서 이러한 문제를 즉시 해결할 수 있습니다. 모든 문제를 보려면 참조 를 클릭합니다 link:concept_fix_ontap_issues_directly_from_unified_manager.html["Unified Manager에서 직접 ONTAP 문제 해결"] 를 참조하십시오.



== 용량 패널

모든 클러스터를 볼 때 이 패널에는 스토리지 효율성 절약 효과를 적용한 후의 물리적 사용 용량 및 각 클러스터에 대한 물리적 사용 가능한 용량(잠재적인 스토리지 효율성 절약 비율 제외)이 표시되며, 디스크가 꽉 찰 것으로 예상되는 일 수가 표시됩니다. 및 구성된 ONTAP 스토리지 효율성 설정을 기반으로 한 데이터 축소율(스냅샷 복사본 없음) 또한 구성된 모든 클라우드 계층에 사용된 용량도 나열됩니다. 막대 차트를 클릭하면 해당 클러스터의 애그리게이트 인벤토리 페이지로 이동합니다. "DAYS to Full" 텍스트를 클릭하면 남은 용량 일 수가 가장 적은 애그리게이트를 식별하는 메시지가 표시됩니다. 자세한 내용을 보려면 애그리게이트 이름을 클릭합니다.

단일 클러스터를 볼 때 이 패널에는 로컬 계층의 각 개별 디스크 유형과 클라우드 계층에 따라 정렬된 데이터 애그리게이트를 위한 물리적 사용 용량 및 물리적 사용 가능한 용량이 표시됩니다. 디스크 유형의 막대 차트를 클릭하면 해당 디스크 유형을 사용하는 볼륨의 볼륨 인벤토리 페이지로 이동합니다.



== Performance Capacity 패널

모든 클러스터를 볼 때 이 패널에는 각 클러스터의 성능 용량 값(이전 1시간 동안의 평균 성능)과 성능 용량이 상한에 도달할 때까지 남은 일 수(일별 성장률 기준)가 표시됩니다. 막대 차트를 클릭하면 해당 클러스터의 노드 인벤토리 페이지로 이동합니다. 노드 인벤토리 페이지에는 이전 72시간 동안의 평균 성능 용량이 표시됩니다. "Days to Full" 텍스트를 클릭하면 남은 성능 용량이 가장 적은 노드를 식별하는 메시지가 표시됩니다. 자세한 내용을 보려면 노드 이름을 클릭하십시오.

단일 클러스터를 볼 때 이 패널에는 사용된 클러스터 성능 용량 비율, 총 IOPS 및 총 처리량(MB/s) 값과 이 세 가지 메트릭 각각이 상한에 도달할 때까지 남은 일 수가 표시됩니다.



== 워크로드 IOPS 패널

단일 클러스터를 볼 때 이 패널에는 특정 IOPS 범위에서 현재 실행 중인 총 워크로드 수가 표시되고, 차트 위에 커서를 놓으면 각 디스크 유형의 수를 나타냅니다.



== 워크로드 성능 패널

이 패널에는 각 PSL(Performance Service Level) 정책에 할당된 준수 및 부적합 워크로드의 총 수가 표시됩니다. 또한 PSL이 할당되지 않은 워크로드의 수도 표시됩니다. 막대 차트를 클릭하면 워크로드 페이지에서 해당 정책에 할당된 적합한 워크로드로 이동합니다. 막대 차트 다음에 나오는 숫자를 클릭하면 해당 정책에 할당된 준수 및 부적합 작업 부하로 이동합니다.



== 보안 패널

보안 패널은 현재 보기에 따라 모든 클러스터 또는 단일 클러스터에 대해 높은 수준의 보안 상태를 제공합니다. 이 패널은 다음을 표시합니다.

* 지난 24시간 동안 수신된 보안 이벤트 목록입니다. 이벤트 세부 정보 페이지에서 세부 정보를 보려면 이벤트를 클릭합니다
* 클러스터 보안 상태(준수 클러스터 및 비준수 클러스터 수)
* 스토리지 VM 보안 상태(호환 및 비준수 스토리지 VM 수)
* 볼륨 암호화 상태(암호화되거나 암호화되지 않은 볼륨의 수)
* 볼륨 안티 랜섬웨어 상태(랜섬웨어 방지 기능이 활성화 또는 비활성화된 볼륨 수)


준수 및 비준수 클러스터, 스토리지 VM, 암호화 및 암호화되지 않은 볼륨, 볼륨 안티 랜섬웨어 상태의 막대 차트를 클릭하여 해당 페이지로 이동하고 필터링된 클러스터, 스토리지 VM 및 볼륨의 보안 세부 정보를 볼 수 있습니다.

규정 준수는 을 https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["ONTAP 9에 대한 NetApp 보안 강화 가이드"^]기반으로 합니다. 패널 상단의 오른쪽 화살표를 클릭하여 보안 페이지의 모든 클러스터에 대한 보안 세부 정보를 봅니다. 자세한 내용은 을 link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["클러스터 및 스토리지 VM에 대한 자세한 보안 상태 보기"]참조하십시오.



== 데이터 보호 패널

이 패널에는 데이터 센터의 단일 또는 모든 클러스터에 대한 데이터 보호 요약이 표시됩니다. 이 창에는 ONTAP에서 최근 24시간 동안 발생한 총 데이터 보호 이벤트 수, MetroCluster 이벤트 및 활성 이벤트 수가 표시됩니다. 각 이벤트의 링크를 클릭하면 이벤트 세부 정보 페이지로 이동합니다. 이벤트 관리 인벤토리 페이지에서 * 모두 보기 * 링크를 클릭하여 모든 활성 보호 이벤트를 볼 수 있습니다. 패널에 다음이 표시됩니다.

* 스냅샷 복사본으로 보호되는 데이터 센터의 클러스터 또는 모든 클러스터에 있는 볼륨 수
* SnapMirror 관계로 보호되는 데이터 센터의 클러스터 또는 모든 클러스터에 있는 볼륨 수 SnapMirror 관계의 경우 소스 클러스터의 볼륨 수가 고려됩니다.
* IP 또는 FC를 통한 MetroCluster 구성으로 보호되는 데이터 센터의 클러스터 또는 모든 클러스터 수
* 지연 상태에 따른 RPO(SnapMirror 복구 지점 목표) 지연과의 볼륨 관계 수입니다.


마우스를 가져가면 해당 개수와 범례를 볼 수 있습니다. 패널 상단의 오른쪽 화살표를 클릭하여 데이터 보호 페이지의 단일 또는 모든 클러스터에 대한 세부 정보를 볼 수 있습니다. 또한 다음을 클릭할 수도 있습니다.

* 보호되지 않는 볼륨 및 스냅샷 복사본으로 보호되는 볼륨에 대한 막대 차트를 볼륨 페이지로 이동하여 세부 정보를 확인합니다.
* MetroCluster 구성으로 보호되거나 보호되지 않는 클러스터의 막대 차트는 클러스터 페이지로 이동하여 세부 정보를 봅니다.
* 모든 관계에 대한 막대 차트는 원본 클러스터를 기준으로 세부 정보가 필터링되는 관계 페이지로 이동합니다.


자세한 내용은 을 참조하십시오 link:../data-protection/view-protection-status.html["볼륨 보호 상태 보기"].



== 사용 개요 패널

모든 클러스터를 볼 때 가장 높은 IOPS, 가장 높은 처리량(MB/s) 또는 가장 많이 사용되는 물리적 용량을 기준으로 정렬된 클러스터를 표시하도록 선택할 수 있습니다.

단일 클러스터를 볼 때 가장 높은 IOPS, 가장 높은 처리량(MB/s) 또는 가장 많이 사용되는 논리적 용량을 기준으로 워크로드를 정렬하도록 선택할 수 있습니다.

* 관련 정보 *

link:../events/task_fix_issues_using_um_automatic_remediations.html["Unified Manager 자동 수정을 사용하여 문제 해결"]

link:../performance-checker/task_display_information_about_performance_event.html["성능 이벤트에 대한 정보 표시"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["성능 용량 및 사용 가능한 IOPS 정보를 사용하여 성능 관리"]

link:../health-checker/reference_health_volume_details_page.html["볼륨/상태 세부 정보 페이지"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["성능 이벤트 분석 및 알림"]

link:../events/reference_description_of_event_severity_types.html["이벤트 심각도 유형에 대한 설명입니다"]

link:../performance-checker/concept_sources_of_performance_events.html["성능 이벤트의 소스"]

link:../health-checker/concept_manage_cluster_security_objectives.html["클러스터 보안 목표 관리"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["성능 클러스터 랜딩 페이지에서 클러스터 성능을 모니터링합니다"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["성능 인벤토리 페이지를 사용하여 성능 모니터링"]
