---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: 이 표에는 Unified Manager 사용자 인터페이스에서 Fix it 또는 Fix All 버튼을 클릭하여 직접 해결할 수 있는 ONTAP 문제가 설명되어 있습니다. 
---
= Unified Manager로 해결할 수 있는 문제
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager의 자동 수정 기능을 사용하면 Unified Manager를 통해 특정 ONTAP 문제를 해결하거나 랜섬웨어 방지 모니터링과 같은 특정 ONTAP 기능을 효과적으로 관리할 수 있습니다.

이 표에서는 ONTAP 웹 UI의 * Fix it * 또는 * Fix All * 버튼을 통해 직접 관리할 수 있는 문제 또는 기능에 대해 설명합니다.

|===
| 이벤트 이름 및 설명 | 관리 조치 | "Fix it" 작업 


 a| 
볼륨 공간이 가득 찼습니다

볼륨에 공간이 거의 없어 용량 최대 임계값을 위반했습니다. 이 임계값은 기본적으로 볼륨 크기의 90%로 설정되어 있습니다.
 a| 
볼륨 자동 확장 활성화
 a| 
Unified Manager에서 볼륨 자동 확장이 이 볼륨에 구성되지 않음을 확인할 수 있으므로 이 기능을 사용하면 필요할 때 볼륨 용량이 증가합니다.



 a| 
inode가 꽉 찼습니다

이 볼륨은 inode가 부족하며 새 파일을 수락할 수 없습니다.
 a| 
볼륨의 inode 수를 늘립니다
 a| 
볼륨의 inode 수를 2% 늘립니다.



 a| 
스토리지 계층 정책 불일치가 발견되었습니다

볼륨에 비활성 데이터가 많이 있고 현재 계층화 정책이 "스냅샷 전용" 또는 "없음"으로 설정되어 있습니다.
 a| 
자동 클라우드 계층화 지원
 a| 
볼륨이 이미 FabricPool에 있으므로 비활성 데이터가 저비용 클라우드 계층으로 이동하도록 계층화 정책을 "자동"으로 변경합니다.



 a| 
스토리지 계층 불일치가 발견되었습니다

볼륨에 비활성 데이터가 많이 있지만 클라우드 지원 스토리지 계층(FabricPool)에 상주하지 않는 경우
 a| 
볼륨의 스토리지 계층을 변경합니다
 a| 
볼륨을 클라우드 지원 스토리지 계층으로 이동하고 계층화 정책을 "자동"으로 설정하여 비활성 데이터를 클라우드 계층으로 이동합니다.



 a| 
감사 로그 사용 안 함

스토리지 VM에 대해 감사 로그가 설정되지 않았습니다
 a| 
스토리지 VM에 대한 감사 로깅을 설정합니다
 a| 
스토리지 VM에 대한 감사 로깅을 설정합니다.

스토리지 VM에는 이미 로컬 또는 원격 감사 로그 위치가 구성되어 있어야 합니다.



 a| 
로그인 배너 사용 안 함

액세스 제한을 명확히 하여 보안을 강화하려면 클러스터의 로그인 배너를 활성화해야 합니다.
 a| 
클러스터의 로그인 배너를 설정합니다
 a| 
클러스터 로그인 배너를 "'권한 있는 사용자로 액세스 제한'으로 설정합니다.



 a| 
로그인 배너 사용 안 함

스토리지 VM의 로그인 배너는 액세스 제한을 명확히 하여 보안을 강화하도록 설정해야 합니다.
 a| 
스토리지 VM의 로그인 배너를 설정합니다
 a| 
스토리지 VM 로그인 배너를 "권한이 있는 사용자로 액세스 제한"으로 설정합니다.



 a| 
SSH가 보안 암호 를 사용하고 있습니다

"-CBC"라는 접미사가 있는 Cipherers는 안전하지 않은 것으로 간주됩니다.
 a| 
클러스터에서 안전하지 않은 암호를 제거합니다
 a| 
클러스터에서 AES192-CBC 및 aes128-CBC와 같은 안전하지 않은 암호를 제거합니다.



 a| 
SSH가 보안 암호 를 사용하고 있습니다

"-CBC"라는 접미사가 있는 Cipherers는 안전하지 않은 것으로 간주됩니다.
 a| 
스토리지 VM에서 안전하지 않은 암호를 제거합니다
 a| 
스토리지 VM에서 AES192-CBC 및 aes128-CBC와 같은 안전하지 않은 암호를 제거합니다.



 a| 
AutoSupport HTTPS 전송이 비활성화되었습니다

AutoSupport 메시지를 기술 지원 부서에 보내는 데 사용되는 전송 프로토콜을 암호화해야 합니다.
 a| 
HTTPS를 AutoSupport 메시지의 전송 프로토콜로 설정합니다
 a| 
HTTPS를 클러스터의 AutoSupport 메시지에 대한 전송 프로토콜로 설정합니다.



 a| 
클러스터 로드 불균형 임계값이 위반되었습니다

클러스터의 노드 간에 로드가 균형 조정되지 않음을 나타냅니다. 이 이벤트는 노드 간 사용된 성능 용량의 차이가 30%를 초과할 때 생성됩니다.
 a| 
클러스터 워크로드의 균형 조정
 a| 
Unified Manager에서는 불균형을 줄이기 위해 한 노드에서 다른 노드로 이동하는 데 가장 적합한 볼륨을 식별한 후 볼륨을 이동합니다.



 a| 
클러스터 용량 불균형 임계값이 위반되었습니다

클러스터의 애그리게이트 간에 용량이 불균형임을 나타냅니다. 이 이벤트는 사용된 용량의 차이가 애그리게이트 간에 70% 이상일 때 생성됩니다.
 a| 
클러스터 용량의 균형을 맞춥니다
 a| 
Unified Manager에서는 불균형을 줄이기 위해 애그리게이트 간에 이동하는 데 가장 적합한 볼륨을 식별한 후 볼륨을 이동합니다.



 a| 
사용된 성능 용량 임계값 위반

사용률이 1개 이상의 매우 높은 워크로드까지 감소하지 않을 경우 노드의 부하가 과도하게 사용될 수 있음을 나타냅니다. 이 이벤트는 사용된 노드 성능 용량이 12시간 이상 100% 이상인 경우 생성됩니다.
 a| 
노드의 최대 부하 제한
 a| 
Unified Manager는 가장 높은 IOPS를 가진 볼륨을 식별하고 기간별 예상 및 최대 IOPS 수준을 사용하여 QoS 정책을 적용하여 노드의 부하를 줄입니다.



 a| 
동적 이벤트 경고 임계값이 위반되었습니다

일부 워크로드의 비정상적으로 높은 부하로 인해 노드가 이미 과부하된 상태로 작동하고 있음을 나타냅니다.
 a| 
노드의 과부하 감소
 a| 
Unified Manager는 가장 높은 IOPS를 가진 볼륨을 식별하고 기간별 예상 및 최대 IOPS 수준을 사용하여 QoS 정책을 적용하여 노드의 부하를 줄입니다.



 a| 
테이크오버가 가능하지 않습니다

페일오버를 현재 사용할 수 없으므로 중단 또는 재부팅 중 노드의 리소스에 대한 액세스는 노드를 다시 사용할 수 있을 때까지 손실됩니다.
 a| 
노드 페일오버 설정
 a| 
Unified Manager가 적절한 명령을 전송하여 클러스터의 모든 노드에서 페일오버를 사용하도록 설정합니다.



 a| 
옵션 cf.takeover.on_panic이 off로 구성됩니다

노드 쉘의 옵션 "cf.Takeover.on_panic"은 * off * 로 설정되어 HA 구성 시스템에서 문제를 일으킬 수 있습니다.
 a| 
패닉 시 Takeover를 설정합니다
 a| 
Unified Manager가 적절한 명령을 클러스터에 전송하여 이 설정을 * On * 으로 변경합니다.



 a| 
nodesell 옵션 SnapMirror.enable을 비활성화합니다

이전 노드 쉘의 옵션 "SnapMirror.enable"은 * On * 으로 설정되어 ONTAP 9.3 이상으로 업그레이드한 후 부팅 중에 문제가 발생할 수 있습니다.
 a| 
SnapMirror.enable 옵션을 off로 설정합니다
 a| 
Unified Manager가 적절한 명령을 클러스터에 전송하여 이 설정을 * 꺼짐 * 으로 변경합니다.



 a| 
텔넷이 활성화되었습니다

텔넷이 안전하지 않고 암호화되지 않은 방식으로 데이터를 전달하므로 잠재적인 보안 문제를 나타냅니다.
 a| 
텔넷을 비활성화합니다
 a| 
Unified Manager가 텔넷을 사용하지 않도록 클러스터에 적절한 명령을 보냅니다.



 a| 
스토리지 VM 안티 랜섬웨어 학습 구성

랜섬웨어 방지 모니터링 라이센스가 있는 클러스터를 주기적으로 확인합니다. 스토리지 VM이 해당 클러스터에서 NFS 또는 SMB 볼륨만 지원하는지 확인합니다.
 a| 
스토리지 VM을 랜섬웨어 방지 모니터링의 '학습' 모드로 전환합니다
 a| 
Unified Manager는 클러스터 관리 콘솔을 통해 스토리지 VM의 랜섬웨어 방지 모니터링을 '학습' 상태로 설정합니다. 스토리지 VM에서 생성된 모든 새 볼륨의 랜섬웨어 방지 모니터링은 학습 모드로 자동으로 이동됩니다. ONTAP는 이러한 지원을 통해 볼륨에서 활동 패턴을 학습하고 잠재적인 악성 공격으로 인한 이상 징후를 감지할 수 있습니다.



 a| 
볼륨 안티 랜섬웨어 학습을 구성하십시오

랜섬웨어 방지 모니터링 라이센스가 있는 클러스터를 주기적으로 확인합니다. 볼륨이 해당 클러스터에서 NFS 또는 SMB 서비스만 지원하는지 확인합니다.
 a| 
볼륨을 안티 랜섬웨어 모니터링의 '학습' 모드로 전환하십시오
 a| 
Unified Manager는 클러스터 관리 콘솔을 통해 볼륨에 대한 안티 랜섬웨어 모니터링을 '학습' 상태로 설정합니다. ONTAP는 이러한 지원을 통해 볼륨에서 활동 패턴을 학습하고 잠재적인 악성 공격으로 인한 이상 징후를 감지할 수 있습니다.



 a| 
볼륨 안티 랜섬웨어 기능을 활성화하십시오

랜섬웨어 방지 모니터링 라이센스가 있는 클러스터를 주기적으로 확인합니다. 볼륨이 45일 이상 안티 랜섬웨어 모니터링의 '학습' 모드에 있는지 여부를 감지하고 해당 볼륨을 액티브 모드로 전환할 가능성을 결정합니다.
 a| 
볼륨을 랜섬웨어 방지 모니터링의 활성 모드로 설정합니다
 a| 
Unified Manager는 클러스터 관리 콘솔을 통해 볼륨에 대한 안티 랜섬웨어 모니터링을 '활성'으로 설정합니다. ONTAP는 이러한 지원을 통해 볼륨에서 활동 패턴을 학습하고 잠재적인 악성 공격으로 인한 이상 징후를 탐지하고 데이터 보호 작업에 대한 경고를 생성할 수 있습니다.



 a| 
볼륨 안티 랜섬웨어를 비활성화합니다

랜섬웨어 방지 모니터링 라이센스가 있는 클러스터를 주기적으로 확인합니다. 볼륨에서 액티브 안티 랜섬웨어 모니터링 중에 반복적인 알림을 감지합니다(예: 잠재적인 랜섬웨어 공격에 대한 여러 경고는 30일 이상 반환됨).
 a| 
볼륨에 대한 랜섬웨어 방지 모니터링을 비활성화합니다
 a| 
Unified Manager는 클러스터 관리 콘솔을 통해 볼륨에 대한 안티 랜섬웨어 모니터링을 비활성화합니다.

|===