---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: 데이터를 미러링하는 동안 논리 연결의 전체 상태를 모니터링하고 진단할 수 있습니다. 애그리게이트, 노드, 스토리지 가상 머신 등과 같은 클러스터 구성 요소의 미러링을 중단하는 문제 또는 위험을 식별할 수 있습니다. 
---
= MetroCluster 복제 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터를 미러링하는 동안 논리 연결의 전체 상태를 모니터링하고 진단할 수 있습니다. 애그리게이트, 노드, 스토리지 가상 머신 등과 같은 클러스터 구성 요소의 미러링을 중단하는 문제 또는 위험을 식별할 수 있습니다.

Unified Manager는 시스템 상태 알림을 사용하여 MetroCluster 구성에서 구성 요소 및 연결 상태를 모니터링합니다.

* 필요한 것 *

MetroCluster 구성의 로컬 클러스터와 원격 클러스터를 모두 Unified Manager에 추가해야 합니다



== IP를 통한 MetroCluster 구성에 대한 복제 보기

MetroCluster over IP 구성의 경우 Unified Manager의 왼쪽 탐색 창에서 다음 뷰에서 IP를 통해 MetroCluster로 보호되는 클러스터의 토폴로지 피킹 뷰(topology peeking view)에 데이터 복제 상태가 표시됩니다.

* * 스토리지 * > * 클러스터 * > * 보호:MetroCluster * 보기
* * 보호 * > * 관계 * > * 관계: MetroCluster * 보기


자세한 내용은 을 참조하십시오 link:../storage-mgmt/task_monitor_metrocluster_configurations.html#monitor-connectivity-issues-in-metrocluster-over-ip["MetroCluster over IP의 연결 문제를 모니터링합니다"].



== FC를 통한 MetroCluster 구성에 대한 복제 보기

다음 단계에 따라 MetroCluster over FC 구성의 데이터 복제에 문제가 있는지 확인합니다.

.단계
. 왼쪽 탐색 창에서 * 스토리지 * > * 클러스터 * 를 클릭합니다.
+
모니터링되는 클러스터의 목록이 표시됩니다.

. 상태: 모든 클러스터 * 보기에서 MetroCluster 복제 세부 정보를 보려는 클러스터의 이름을 클릭합니다. 클러스터/상태 세부 정보 * 페이지에서 * MetroCluster 복제 * 탭을 클릭합니다.
+
복제할 MetroCluster 구성의 토폴로지는 데이터가 미러링되는 원격 사이트에 대한 정보와 함께 해당 클러스터 개체 영역의 로컬 사이트에 표시됩니다. 아이콘 위로 포인터를 이동하면 생성된 이벤트에 대한 자세한 정보를 볼 수 있습니다.



에 표시된 정보를 사용하여 복제 문제를 해결할 수 있습니다. MetroCluster 구성에서 미러링 문제를 발견한 경우, System Manager에 로그인하거나 ONTAP CLI에 액세스하여 문제를 해결해야 합니다.

* 관련 정보 *

link:../health-checker/reference_health_cluster_details_page.html["클러스터/상태 세부 정보 페이지"]
