---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: '프로비저닝 워크로드 페이지에서 기존 클러스터 및 스토리지 가상 머신(스토리지 VM)에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 파일 공유 볼륨을 생성할 수 있습니다.' 
---
= 파일 공유 볼륨 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로비저닝 워크로드 페이지에서 기존 클러스터 및 스토리지 가상 머신(스토리지 VM)에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 파일 공유 볼륨을 생성할 수 있습니다.

* 필요한 것 *

* 스토리지 VM에 파일 공유 볼륨을 프로비저닝할 수 있는 공간이 있어야 합니다.
* 스토리지 VM에서 SMB 및 NFS 서비스 중 하나 또는 둘 다 활성화해야 합니다.
* 작업 부하에서 PSL(Performance Service Level) 및 SEP(Storage Efficiency Policy)를 선택하고 할당하려면 워크로드를 생성하기 전에 정책을 생성해야 합니다.


.단계
. Provision Workload * 페이지에서 생성할 워크로드 이름을 추가한 다음 Available 목록에서 클러스터를 선택합니다.
. 선택한 클러스터에 따라 * 스토리지 VM * 필드가 해당 클러스터에 대해 사용 가능한 스토리지 VM을 필터링합니다. 목록에서 필요한 스토리지 VM을 선택합니다.
+
스토리지 VM에서 지원되는 SMB 및 NFS 서비스에 따라 호스트 정보 섹션에서 NAS 옵션이 설정됩니다.

. 스토리지 및 최적화 섹션에서 스토리지 용량 및 PSL을 할당하고 선택적으로 워크로드에 대한 SEP를 할당합니다.
+
SEP에 대한 사양은 LUN에 할당되며 PSL에 대한 정의는 생성 시 워크로드에 적용됩니다.

. 작업 부하에 할당한 PSL을 적용하려면 * 성능 제한 강제 적용 * 확인란을 선택합니다.
+
작업 부하에 PSL을 할당하면 워크로드가 생성되는 총계를 통해 해당 정책에 정의된 성능 및 용량 목표를 지원할 수 있습니다. 예를 들어, 워크로드에 "최고 성능" PSL이 할당된 경우 워크로드를 프로비저닝할 집계 시 SSD 스토리지와 같은 "최고 성능" 정책의 성능 및 용량 목표를 지원할 수 있어야 합니다.

+
[NOTE]
====
이 확인란을 선택하지 않으면 PSL이 작업 부하에 적용되지 않고 대시보드의 작업 부하 상태가 미할당 상태로 나타납니다.

====
. NAS * 옵션을 선택합니다.
+
nas * 옵션이 설정되어 있지 않으면 선택한 스토리지 VM이 SMB 또는 NFS를 지원하는지 확인하십시오.

+
[NOTE]
====
스토리지 VM이 SMB 및 NFS 서비스 모두에 대해 활성화된 경우 * Share by NFS * 및 * Share by SMB * 확인란을 선택하고 NFS 및 SMB 프로토콜을 모두 지원하는 파일 공유를 생성할 수 있습니다. SMB 또는 CIFS 공유를 생성하려면 해당 확인란만 선택합니다.

====
. NFS 파일 공유 볼륨의 경우 파일 공유 볼륨을 액세스할 호스트 또는 네트워크의 IP 주소를 지정합니다. 여러 호스트에 대해 쉼표로 구분된 값을 입력할 수 있습니다.
+
호스트 IP 주소를 추가할 때 호스트 세부 정보를 스토리지 VM과 일치시키기 위해 내부 검사가 실행되고 해당 호스트에 대한 엑스포트 정책이 생성되거나 기존 정책이 있는 경우 다시 사용됩니다. 동일한 호스트에 대해 여러 개의 NFS 공유가 생성된 경우 동일한 호스트에 대해 사용 가능한 내보내기 정책이 모든 파일 공유에 다시 사용됩니다. API를 사용하여 NFS 공유를 프로비저닝할 때 개별 정책의 규칙을 지정하거나 특정 정책 키를 제공하여 정책을 재사용하는 기능을 사용할 수 있습니다.

. SMB 공유의 경우 SMB 공유에 액세스할 수 있는 사용자 또는 사용자 그룹을 지정하고 필요한 권한을 할당합니다. 각 사용자 그룹에 대해 파일 공유를 생성하는 동안 새 ACL(액세스 제어 목록)이 생성됩니다.
. 저장 * 을 클릭합니다.
+
스토리지 워크로드 목록에 워크로드가 추가됩니다.


