---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: '프로비저닝 워크로드 페이지에서 기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 LUN을 생성할 수 있습니다.' 
---
= LUN 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로비저닝 워크로드 페이지에서 기존 클러스터와 스토리지 가상 머신(스토리지 VM)에서 CIFS/SMB 및 NFS 프로토콜을 지원하는 LUN을 생성할 수 있습니다.

* 필요한 것 *

* 스토리지 VM에 LUN 프로비저닝을 위한 공간이 있어야 합니다.
* LUN을 생성하는 스토리지 VM에서 iSCSI와 FCP를 모두 사용하도록 설정해야 합니다.
* 작업 부하에서 PSL(Performance Service Level) 및 SEP(Storage Efficiency Policy)를 선택하고 할당하려면 워크로드를 생성하기 전에 정책을 생성해야 합니다.


.단계
. Provision Workload * 페이지에서 생성할 워크로드 이름을 추가한 다음 Available 목록에서 클러스터를 선택합니다.
+
선택한 클러스터에 따라 * 스토리지 VM * 필드가 해당 클러스터에 대해 사용 가능한 스토리지 VM을 필터링합니다.

. iSCSI 및 FCP 서비스를 지원하는 목록에서 스토리지 VM을 선택합니다.
+
선택한 내용에 따라 호스트 정보 섹션에서 SAN 옵션이 활성화됩니다.

. 스토리지 및 최적화 * 섹션에서 스토리지 용량 및 PSL을 할당하고 선택적으로 워크로드에 대한 SEP를 할당합니다.
+
SEP에 대한 사양은 LUN에 할당되며 PSL에 대한 정의는 생성 시 워크로드에 적용됩니다.

. 작업량에 할당된 PSL을 적용하려는 경우 * 성능 제한 적용 * 확인란을 선택합니다.
+
작업 부하에 PSL을 할당하면 워크로드가 생성되는 총계를 통해 해당 정책에 정의된 성능 및 용량 목표를 지원할 수 있습니다. 예를 들어, 워크로드에 "최고 성능" PSL이 할당된 경우 워크로드를 프로비저닝할 집계 시 SSD 스토리지와 같은 "최고 성능" 정책의 성능 및 용량 목표를 지원할 수 있어야 합니다.

+
[NOTE]
====
이 확인란을 선택하지 않으면 PSL이 작업 부하에 적용되지 않고 대시보드의 작업 부하 상태가 '할당되지 않음'으로 나타납니다.

====
. SAN * 옵션을 선택합니다. SAN * 옵션이 설정되어 있지 않으면 선택한 스토리지 VM이 iSCSI 및 FCP를 지원하는지 확인하십시오.
. 호스트 OS를 선택합니다.
. LUN에 대한 이니시에이터의 액세스를 제어할 호스트 매핑을 지정합니다. 기존 이니시에이터 그룹(igroup)을 지정하거나 새 igroup을 정의 및 매핑할 수 있습니다.
+
[NOTE]
====
LUN을 프로비저닝하는 동안 새로운 igroup을 생성하는 경우 다음 검색 주기(최대 15분)까지 기다려야 합니다. 따라서 사용 가능한 igroup 목록에서 기존 igroup을 사용하는 것이 좋습니다.

====
+
새 igroup을 생성하려면 * Create a new initiator group * 버튼을 선택하고 igroup에 대한 정보를 입력합니다.

. 저장 * 을 클릭합니다.
+
LUN이 스토리지 워크로드 목록에 추가됩니다.


