---
permalink: storage-mgmt/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 클러스터를 모니터링할 수 있도록 Active IQ Unified Manager에 클러스터를 추가할 수 있습니다. 여기에는 발생할 수 있는 문제를 찾아 해결할 수 있도록 클러스터의 상태, 용량, 성능, 구성 등과 같은 클러스터 정보를 가져오는 기능도 포함됩니다. 
---
= 클러스터 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 모니터링할 수 있도록 Active IQ Unified Manager에 클러스터를 추가할 수 있습니다. 여기에는 발생할 수 있는 문제를 찾아 해결할 수 있도록 클러스터의 상태, 용량, 성능, 구성 등과 같은 클러스터 정보를 가져오는 기능도 포함됩니다.

* 필요한 것 *

* 애플리케이션 관리자 역할 또는 스토리지 관리자 역할이 있어야 합니다.
* 클러스터에 대한 호스트 이름 또는 클러스터 관리 IP 주소(IPv4 또는 IPv6)가 있어야 합니다.
+
호스트 이름을 사용할 때는 클러스터 관리 LIF의 클러스터 관리 IP 주소로 해석해야 합니다. 노드 관리 LIF를 사용하면 작업이 실패합니다.

* 클러스터에 액세스하려면 사용자 이름과 암호가 있어야 합니다.
+
이 계정에는 응용 프로그램 액세스 권한이 _ontapi_, _console_ 및 _http_로 설정된 _admin_역할이 있어야 합니다.

* HTTPS 프로토콜(일반적으로 포트 443)을 사용하여 클러스터에 연결하려면 포트 번호를 알아야 합니다.
* 클러스터에서 ONTAP 버전 9.1 소프트웨어 이상을 실행해야 합니다.
* Unified Manager 서버에 적절한 공간이 있어야 합니다. 90% 이상의 공간이 이미 사용된 경우 서버에 클러스터를 추가할 수 없습니다.
* 필요한 인증서가 있습니다. Unified Manager는 클러스터를 추가할 때 보안 인증서를 설치합니다.
+
* 서버 인증서 *: 이 인증서는 Unified Manager에서 소유합니다. Unified Manager를 새로 설치하면 자체 서명된 기본 SSL(HTTPS) 인증서가 생성됩니다. 보안을 강화하기 위해 CA 서명 인증서로 업그레이드하는 것이 좋습니다. 서버 인증서가 만료되면 해당 인증서를 다시 생성하고 Unified Manager를 다시 시작하여 새 인증서를 통합하는 서비스를 수행해야 합니다. SSL 인증서 재생성에 대한 자세한 내용은 을 참조하십시오 link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS 보안 인증서를 생성하는 중입니다"].

+
* 상호 TLS 통신을 위한 인증서 *: Unified Manager와 ONTAP 간의 상호 TLS 통신 중에 사용됩니다. 인증서 기반 인증은 ONTAP 버전에 따라 클러스터에 대해 설정됩니다. ONTAP 버전을 실행하는 클러스터가 9.5보다 낮은 경우 인증서 기반 인증이 활성화되지 않습니다.

+
이전 버전의 Unified Manager를 Unified Manager 9.12로 업데이트하는 경우 클러스터에 대해 인증서 기반 인증이 자동으로 활성화되지 않습니다. 그러나 클러스터 세부 정보를 수정 및 저장하여 이 기능을 사용하도록 설정할 수 있습니다. 인증서가 만료되면 인증서를 다시 생성하여 새 인증서를 통합해야 합니다. 인증서 보기 및 재생에 대한 자세한 내용은 을 참조하십시오 link:../storage-mgmt/task_edit_clusters.html["클러스터 편집"].

+
[NOTE]
====
** 웹 UI에서 클러스터를 추가하면 인증서 기반 인증이 자동으로 활성화됩니다. 유지보수 콘솔에서 클러스터를 추가하면 인증서 기반 인증이 사용되지 않습니다.
** 클러스터에 대해 인증서 기반 인증을 사용하고 서버에서 Unified Manager 백업을 수행한 후 호스트 이름 또는 IP 주소가 변경된 다른 Unified Manager 서버로 복원하면 클러스터 모니터링이 실패할 수 있습니다. 이 문제를 방지하려면 클러스터 세부 정보를 편집하고 저장합니다. 클러스터 세부 정보 편집에 대한 자세한 내용은 을 참조하십시오 link:../storage-mgmt/task_edit_clusters.html["클러스터 편집"].


====
+
* 클라이언트 인증서 *: ONTAP로부터 수신한 EMS 메시지에 대한 인증 중에 사용됩니다. 이 인증서는 ONTAP에서 소유하며 ONTAP 클러스터를 Unified Manager에 추가할 때 필요합니다. 만료된 인증서가 있는 클러스터는 Unified Manager에 추가할 수 없으며, 클라이언트 인증서가 이미 만료된 경우 클러스터를 추가하기 전에 다시 생성해야 합니다. 그러나 이미 추가된 클러스터에 대해 이 인증서가 만료되어 Unified Manager에서 사용 중인 경우 EMS 메시징은 만료된 인증서에서 계속 작동합니다. 인증서 생성에 대한 자세한 내용은 기술 자료(KB) 문서를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["System Manager 사용자 인터페이스에서 ONTAP 자체 서명된 인증서를 갱신하는 방법"].

* Unified Manager의 단일 인스턴스에서 특정 수의 노드를 지원할 수 있습니다. 지원되는 노드 수를 초과하는 환경을 모니터링해야 하는 경우, 일부 클러스터를 모니터링하려면 Unified Manager의 추가 인스턴스를 설치해야 합니다.
* Unified Manager의 각 인스턴스가 다른 LIF를 통해 연결되도록 클러스터에 두 번째 클러스터 관리 LIF를 구성한 경우, Unified Manager의 두 인스턴스를 통해 단일 클러스터를 모니터링할 수 있습니다.


.단계
. 왼쪽 탐색 창에서 * 스토리지 관리 * > * 클러스터 설정 * 을 클릭합니다.
. 클러스터 설정 페이지에서 * 추가 * 를 클릭합니다.
. 클러스터 추가 대화 상자에서 필요에 따라 값을 지정한 다음 * 제출 * 을 클릭합니다.
. 호스트 인증 대화 상자에서 * 인증서 보기 * 를 클릭하여 클러스터에 대한 인증서 정보를 확인합니다.
. 예 * 를 클릭합니다.
+
Unified Manager 9.12에서 클러스터 세부 정보를 저장한 후에는 클러스터의 상호 TLS 통신에 대한 인증서를 볼 수 있습니다.

+
인증서 기반 인증이 활성화되지 않은 경우 Unified Manager는 클러스터가 처음에 추가될 때만 인증서를 확인합니다. Unified Manager에서는 ONTAP에 대한 각 API 호출의 인증서를 확인하지 않습니다.



새 클러스터의 모든 객체가 검색된 후 Unified Manager가 이전 15일 동안 기간별 성능 데이터를 수집하기 시작합니다. 이러한 통계는 데이터 연속성 수집 기능을 사용하여 수집됩니다. 이 기능은 클러스터를 추가한 직후 2주 이상의 클러스터 성능 정보를 제공합니다. 데이터 연속성 수집 주기가 완료되면 기본적으로 5분마다 실시간 클러스터 성능 데이터가 수집됩니다.

[NOTE]
====
15일간의 성능 데이터 수집은 CPU를 많이 사용하므로 데이터 연속성 수집 폴이 너무 많은 클러스터에서 동시에 실행되지 않도록 새 클러스터를 추가하는 시차를 두는 것이 좋습니다. 또한, 데이터 연속성 수집 기간 동안 Unified Manager를 다시 시작하면 수집이 중단되고 성능 차트의 누락된 시간 간격이 표시됩니다.

====
[TIP]
====
클러스터를 추가할 수 없다는 오류 메시지가 표시되면 다음 문제가 있는지 확인하십시오.

* 두 시스템의 시계가 동기화되지 않고 Unified Manager HTTPS 인증서 시작 날짜가 클러스터의 날짜보다 이후인 경우 NTP 또는 이와 유사한 서비스를 사용하여 시계가 동기화되었는지 확인해야 합니다.
* 클러스터가 최대 EMS 알림 대상 수에 도달하면 Unified Manager 주소를 추가할 수 없습니다. 기본적으로 클러스터에 20개의 EMS 알림 대상만 정의할 수 있습니다.


====
* 관련 정보 *

link:../config/task_add_users.html["사용자 추가"]

link:../health-checker/task_view_cluster_list_and_details.html["클러스터 목록 및 세부 정보 보기"]

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["서명되고 반환된 HTTPS 인증서를 설치하는 중입니다"]
