---
permalink: storage-mgmt/task_export_storage_data_as_reports.html 
sidebar: sidebar 
keywords: export, storage, data, reports 
summary: 다양한 출력 형식으로 저장소 데이터를 내보낸 다음 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 문제를 해결할 수 있는 관리자에게 보고서를 보낼 수 있습니다. 
---
= 스토리지 데이터를 보고서로 내보내기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다양한 출력 형식으로 저장소 데이터를 내보낸 다음 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 문제를 해결할 수 있는 관리자에게 보고서를 보낼 수 있습니다.

Storage * 및 * Network * 재고 페이지에서 ".csv" 파일, .xlsx" 파일 또는 ".pdf" 문서로 데이터를 내보내고 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다. 제품에는 .csv 또는 .pdf 파일만 생성할 수 있는 다른 위치가 있습니다.

.단계
. 다음 작업 중 하나를 수행합니다.
+
|===
| 내보내려는 경우... | 수행할 작업... 


 a| 
스토리지 객체 인벤토리 세부 정보입니다
 a| 
왼쪽 탐색 메뉴에서 * 스토리지 * 또는 * 네트워크 * 를 클릭한 다음 스토리지 객체를 선택합니다. 시스템에서 제공하는 보기 중 하나 또는 사용자가 만든 사용자 지정 보기를 선택합니다.



 a| 
QoS 정책 그룹 세부 정보
 a| 
왼쪽 탐색 메뉴에서 * 스토리지 * > * QoS 정책 그룹 * 을 클릭합니다.



 a| 
스토리지 용량 및 보호 기록 세부 정보
 a| 
스토리지 * > * 애그리게이트 * 또는 * 스토리지 * > * 볼륨 * 을 클릭한 다음 단일 애그리게이트 또는 볼륨을 선택합니다.



 a| 
이벤트 세부 정보
 a| 
왼쪽 탐색 메뉴에서 * 이벤트 관리 * 를 클릭합니다.



 a| 
스토리지 객체 10가지 성능 세부 정보
 a| 
Storage * > * Clusters * > * Performance: All Clusters * 를 클릭한 다음 클러스터를 선택하고 * Top Performers * 탭을 선택합니다. 그런 다음 스토리지 오브젝트 및 성능 카운터를 선택합니다.

|===
. 보고서 * 버튼(또는 일부 UI 페이지의 * 내보내기 * 버튼)을 클릭합니다.
. CSV * 다운로드, * PDF 다운로드 * 또는 * Excel * 다운로드 를 클릭하여 내보내기 요청을 확인합니다.
+
Top Performers 탭에서 보고 있는 단일 클러스터의 통계 보고서 또는 데이터 센터의 모든 클러스터에 대한 통계 보고서를 다운로드할 수 있습니다.

+
파일이 다운로드됩니다.

. 해당 응용 프로그램에서 파일을 엽니다.


* 관련 정보 *

link:["상태/클러스터 인벤토리 페이지입니다"]

link:../reporting/task_schedule_report.html["보고서 예약"]
