---
permalink: storage-mgmt/task_change_time_um_retains_event_performance_data.html 
sidebar: sidebar 
keywords: change, length, time, unified manager, retains, event, performance, data 
summary: 기본적으로 Unified Manager는 모니터링되는 모든 클러스터에 대해 6개월 동안 이벤트 데이터 및 성능 데이터를 저장합니다. 이 시간이 지나면 새 데이터를 저장할 공간을 만들기 위해 오래된 데이터가 자동으로 삭제됩니다. 이 기본 일정은 대부분의 구성에서 잘 작동하지만, 많은 클러스터와 노드가 있는 매우 큰 구성에서는 Unified Manager가 최적으로 작동하도록 보존 기간을 줄여야 할 수 있습니다. 
---
= Unified Manager가 이벤트 및 성능 데이터를 유지하는 기간을 변경합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 Unified Manager는 모니터링되는 모든 클러스터에 대해 6개월 동안 이벤트 데이터 및 성능 데이터를 저장합니다. 이 시간이 지나면 새 데이터를 저장할 공간을 만들기 위해 오래된 데이터가 자동으로 삭제됩니다. 이 기본 일정은 대부분의 구성에서 잘 작동하지만, 많은 클러스터와 노드가 있는 매우 큰 구성에서는 Unified Manager가 최적으로 작동하도록 보존 기간을 줄여야 할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 역할이 있어야 합니다.

데이터 보존 페이지에서 이러한 두 가지 데이터 유형의 보존 기간을 변경할 수 있습니다. 이러한 설정은 Unified Manager의 이 인스턴스가 모니터링하는 모든 클러스터의 데이터 보존에 영향을 줍니다.

[NOTE]
====
Unified Manager는 5분마다 성능 통계를 수집합니다. 매일 5분 통계가 매시간 성능 통계로 요약됩니다. 이 기능을 사용하면 30일 동안 5분 동안의 기간별 성능 데이터와 6개월 분량의 시간별 요약 성능 데이터를 유지할 수 있습니다(기본값).

====
공간이 부족하거나 백업 및 기타 작업을 완료하는 데 시간이 매우 오래 걸리는 경우에만 보존 기간을 줄여야 합니다. 보존 기간을 줄이면 다음과 같은 효과가 있습니다.

* 자정 이후 이전 성능 데이터가 Unified Manager 데이터베이스에서 삭제됩니다.
* 이전 이벤트 데이터가 Unified Manager 데이터베이스에서 즉시 삭제됩니다.
* 보존 기간 이전의 이벤트는 더 이상 사용자 인터페이스에서 볼 수 없습니다.
* UI에서 시간별 성능 통계가 표시되는 위치는 보존 기간 전에 비어 있습니다.
* 이벤트 보존 기간이 성능 데이터 보존 기간을 초과하는 경우 성능 슬라이더 아래에 오래된 성능 이벤트에 연결된 차트의 데이터가 백업되지 않을 수 있다는 메시지가 표시됩니다.


.단계
. 왼쪽 탐색 창에서 * Policies * > * Data Retention * 을 클릭합니다.
. Data Retention * 페이지의 Event Retention 또는 Performance Data Retention 영역에서 슬라이더 도구를 선택하고 데이터를 보존할 개월 수로 이동한 다음 * Save * 를 클릭합니다.

