---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: Active IQ Unified Manager는 iSCSI 프로토콜을 사용하는 LUN의 도움으로 Windows 운영 체제에서 NetApp 스냅샷을 사용하여 백업 및 복원을 지원합니다. 
---
= Active IQ Unified Manager에서 Windows 백업 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager는 iSCSI 프로토콜을 사용하는 LUN의 도움으로 Windows 운영 체제에서 NetApp 스냅샷을 사용하여 백업 및 복원을 지원합니다.

모든 Unified Manager 서비스가 실행되는 동안 스냅샷 기반 백업을 수행할 수 있습니다. 백업이 전체 데이터베이스에 글로벌 읽기 잠금을 설정하면 동시 쓰기를 방지할 수 있으므로 스냅샷의 일부로 데이터베이스의 정합성이 보장되는 상태가 캡처됩니다. Windows OS에 설치된 Unified Manager 시스템에서 NetApp Snapshot을 사용하여 백업 및 복원을 수행하려면 먼저 유지보수 콘솔을 사용하여 Unified Manager 백업을 Snapshot에 구성해야 합니다.

Unified Manager에서 스냅샷 복사본을 생성하도록 구성하기 전에 다음 구성 작업을 수행해야 합니다.

* ONTAP 클러스터를 구성합니다
* Windows 호스트 시스템을 구성합니다




[[configure-a-backup-location-for-active-iq-unified-manager-on-windows]]
== Windows에서 Active IQ Unified Manager의 백업 위치 구성

Windows에서 Unified Manager를 백업한 후 Snapshot 복사본을 저장할 볼륨을 구성해야 합니다.

.시작하기 전에
클러스터, 스토리지 VM 및 볼륨은 다음 요구사항을 충족해야 합니다.

* 클러스터 요구 사항:
+
** ONTAP 9.3 이상을 설치해야 합니다
** Unified Manager 서버와 지리적으로 가까운 곳에 있어야 합니다
** Unified Manager에서 모니터링합니다


* 스토리지 VM 요구 사항:
+
** ONTAP 클러스터의 iSCSI 접속 구성
** 구성된 시스템에 대해 iSCSI 프로토콜을 활성화해야 합니다
** 백업 구성을 위해서는 전용 볼륨과 LUN이 있어야 합니다. 선택한 볼륨에는 LUN이 하나만 포함되어야 하며 다른 볼륨은 없어야 합니다.
** LUN 크기는 9.9 Active IQ Unified Manager에서 처리할 것으로 예상되는 데이터 크기의 2배 이상이어야 합니다.
+
그러면 볼륨에도 동일한 크기 요구 사항이 설정됩니다.

** 모든 읽기/쓰기 권한이 선택되어 있는지 확인합니다
** 수출 정책에서 슈퍼유저 액세스가 ""모두""로 설정되어 있는지 확인하십시오


* 볼륨 및 LUN 요구 사항:
+
** 이 볼륨은 Unified Manager MySQL 데이터 디렉토리의 최소 2배가 되어야 합니다.
** 보안 스타일을 Windows로 설정해야 합니다
** 로컬 스냅샷 정책을 해제해야 합니다
** 볼륨 자동 크기 조정이 활성화되어야 합니다
** 고성능 서비스 수준은 높은 IOPS와 낮은 지연 시간(예: "Extreme")을 가진 정책으로 설정해야 합니다.






[[configure-an-ontap-cluster-for-backup-and-restore-in-active-iq-unified-manager]]
== Active IQ Unified Manager에서 백업 및 복원을 위한 ONTAP 클러스터 구성

ONTAP 시스템에서 스냅샷 복사본을 사용하여 Active IQ Unified Manager를 백업 및 복원하려면 먼저 Windows 클러스터에서 몇 가지 사전 구성 단계를 수행해야 합니다.

명령 프롬프트나 System Manager 사용자 인터페이스를 사용하여 ONTAP 클러스터를 구성할 수 있습니다. ONTAP 클러스터를 구성하려면 스토리지 VM에 iSCSI LIF로 할당할 수 있도록 데이터 LIF를 구성해야 합니다. 다음 단계는 System Manager 사용자 인터페이스를 사용하여 iSCSI 지원 스토리지 VM을 구성하는 것입니다. LIF가 아웃바운드 트래픽에 네트워크를 사용하는 방법을 제어하려면 이 스토리지 VM에 대한 정적 네트워크 경로를 구성해야 합니다.

[NOTE]
====
백업 구성을 위해서는 전용 볼륨과 LUN이 있어야 합니다. 선택한 볼륨에 LUN이 하나만 포함되어야 합니다. LUN 크기는 Active IQ Unified Manager에서 처리할 수 있을 것으로 예상되는 데이터 크기의 2배 이상이어야 합니다.

====
다음 구성을 수행해야 합니다.

.단계
. iSCSI 지원 스토리지 VM을 구성하거나 동일한 구성을 가진 기존 스토리지 VM을 사용합니다.
. 구성된 스토리지 VM에 대한 네트워크 라우트를 구성합니다.
. 볼륨이 이 LUN 전용인지 확인하기 위해 적절한 용량의 볼륨과 내부의 단일 LUN을 구성합니다.
+

NOTE: System Manager에서 LUN을 생성할 때 LUN 매핑을 해제하면 igroup이 삭제되고 복원이 실패할 수 있습니다. 이 시나리오를 방지하려면 LUN을 생성하는 동안 LUN이 명시적으로 생성되고 LUN이 매핑 해제될 때 삭제되지 않도록 해야 합니다.

. 스토리지 VM에서 이니시에이터 그룹을 구성합니다.
. 포트 세트를 구성합니다.
. igroup을 포트셋 통합
. LUN을 igroup에 매핑합니다.




[[configure-a-windows-host-machine-in-active-iq-unified-manager]]
== Active IQ Unified Manager에서 Windows 호스트 머신 구성

NetApp Snapshot을 사용하여 Active IQ Unified Manager를 백업 및 복원하려면 Windows 호스트 시스템을 구성해야 합니다. Windows 호스트 시스템에서 Microsoft iSCSI 초기자를 시작하려면 검색 표시줄에 ""iSCSI""를 입력하고 * iSCSI 초기자 * 를 클릭합니다.

.시작하기 전에
호스트 시스템에서 이전 구성을 정리해야 합니다.

Windows를 새로 설치할 때 iSCSI 초기자를 시작하려고 하면 확인 메시지가 표시되고 확인 메시지가 표시되면 iSCSI 속성 대화 상자가 표시됩니다. 기존 Windows 설치인 경우 iSCSI 속성 대화 상자가 비활성이거나 연결을 시도하는 대상과 함께 표시됩니다. 따라서 Windows 호스트의 이전 구성이 모두 제거되었는지 확인해야 합니다.

.단계
. 호스트 시스템에서 이전 구성을 모두 정리합니다.
. 대상 포털을 검색합니다.
. 대상 포털에 연결합니다.
. 대상 포털에 다중 경로를 사용하여 연결합니다.
. 두 LIF를 모두 확인하십시오.
. Windows 시스템에서 디바이스로 구성된 LUN을 검색합니다.
. Windows에서 검색된 LUN을 새 볼륨 드라이브로 구성합니다.




[[specify-the-destination-location-for-snapshot-copies-on-windows-in-active-iq-unified-manager]]
== Active IQ Unified Manager에서 Windows의 스냅샷 복사본 대상 위치를 지정합니다

ONTAP 클러스터 중 하나에 이미 구성되어 있는 볼륨의 Active IQ Unified Manager 스냅샷 복사본에 대한 대상 위치를 구성해야 합니다. 유지보수 콘솔을 사용하여 위치를 정의해야 합니다.

* Active IQ Unified Manager가 설치된 Windows 호스트에 대한 관리자 권한이 있어야 합니다.
* Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.
* 클러스터 관리 IP 주소, 스토리지 VM 이름, 볼륨 이름, LUN 이름 및 스토리지 시스템 사용자 이름과 암호가 있어야 합니다.
* Active IQ Unified Manager 호스트에 볼륨을 네트워크 드라이브로 마운트해야 하며 마운트 드라이브가 있어야 합니다.


.단계
. Power Shell을 사용하여 Active IQ Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
. 유지보수 사용자(umadmin) 이름 및 암호를 사용하여 시스템에 로그인합니다.
. mainf유지보수_console 명령을 입력하고 Enter 키를 누릅니다.
. 유지보수 콘솔 * 메인 메뉴 * 에서 * 백업 복원 * 옵션의 번호를 입력합니다.
. Configure NetApp Snapshot Backup * 의 번호를 입력합니다.
. iSCSI를 구성할 번호를 입력합니다.
. 제공해야 할 정보를 검토한 다음 * 백업 구성 세부 정보 입력 * 에 대한 번호를 입력합니다.
. 스냅샷을 기록할 볼륨을 식별하려면 클러스터 관리 인터페이스의 IP 주소, 스토리지 VM 이름, 볼륨 이름, LUN 이름, 스토리지 시스템 사용자 이름 및 암호, 마운트 드라이브를 입력합니다.
. 이 정보를 확인하고 y를 입력합니다.
+
시스템은 다음 작업을 수행합니다.

+
** 스토리지 VM이 검증되었습니다
** 볼륨이 확인되었습니다
** 드라이브 마운트 및 상태가 확인되었습니다
** LUN 존재 및 상태입니다
** 네트워크 드라이브가 있습니다
** 마운트된 볼륨에 권장 공간(MySQL 데이터 디렉토리의 2배 이상)이 있는지 확인합니다
** 볼륨의 전용 LUN에 해당하는 LUN 경로입니다
** iGroup 이름입니다
** 네트워크 드라이브가 마운트된 볼륨의 GUID입니다
** ONTAP와 통신하는 데 사용되는 iSCSI 이니시에이터입니다


. 유지보수 콘솔을 종료하고 Active IQ Unified Manager 인터페이스를 실행하여 스냅샷 복사본의 일정을 생성합니다.

