---
permalink: health-checker/concept_configure_backup_for_linux.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies, linux, operate, system, configure, backup 
summary: Active IQ Unified Manager가 Linux 시스템에 설치된 경우 NetApp Snapshot을 사용하여 백업 및 복원을 구성할 수 있습니다. 
---
= Active IQ Unified Manager에서 Linux의 백업 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager가 Linux 시스템에 설치된 경우 NetApp Snapshot을 사용하여 백업 및 복원을 구성할 수 있습니다.

Snapshot 복사본은 보통 몇 분 정도밖에 걸리지 않으며, Unified Manager 데이터베이스가 매우 짧은 시간 동안 잠겨 있으므로 설치가 중단되는 것이 거의 없습니다. 마지막 스냅샷 복사본이 생성된 이후 파일에 대한 변경사항만 기록하므로 이미지는 최소한의 스토리지 공간을 소비하고 무시할 만한 성능 오버헤드를 발생시킵니다. ONTAP 클러스터에서 스냅샷이 생성되므로, 필요한 경우 SnapMirror와 같은 다른 NetApp 기능을 활용하여 2차 보호를 생성할 수 있습니다.

백업 작업을 시작하기 전에 Unified Manager에서 무결성 검사를 수행하여 대상 시스템을 사용할 수 있는지 확인합니다.

[NOTE]
====
* 동일한 버전의 Active IQ Unified Manager에서만 스냅샷 복사본을 복원할 수 있습니다.
+
예를 들어 Unified Manager 9.18에서 백업을 만든 경우 해당 백업은 Unified Manager 9.18 시스템에서만 복원할 수 있습니다.

* 스냅샷 구성이 변경된 경우 스냅샷이 잘못될 수 있습니다.


====


[[configure-snapshot-copy-location-in-active-iq-unified-manager]]
== Active IQ Unified Manager에서 스냅샷 복사본 위치 구성

ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 ONTAP 클러스터 중 하나에서 스냅샷 복사본이 저장될 볼륨을 구성할 수 있습니다.

.시작하기 전에
클러스터, 스토리지 VM 및 볼륨은 다음 요구사항을 충족해야 합니다.

* 클러스터 요구 사항:
+
** ONTAP 9.3 이상을 설치해야 합니다
** Unified Manager 서버와 지리적으로 가까운 곳에 있어야 합니다
** Unified Manager를 통해 모니터링할 수 있지만 반드시 필요한 것은 아닙니다


* 스토리지 VM 요구 사항:
+
** 이름 스위치와 이름 매핑은 ""파일""을 사용하도록 설정되어야 합니다.
** 클라이언트 측 사용자와 일치하도록 생성된 로컬 사용자입니다
** 모든 읽기/쓰기 권한이 선택되어 있는지 확인합니다
** 수출 정책에서 슈퍼유저 액세스가 ""모두""로 설정되어 있는지 확인하십시오
** Linux용 NetApp Snapshot용 NFS
** NFSv4는 클라이언트 및 스토리지 VM에 지정된 NFS 서버 및 NFSv4 ID 도메인에서 설정해야 합니다
** 이 볼륨은 Unified Manager/opt/NetApp/data 디렉토리의 최소 2배가 되어야 합니다
+
du-sh/opt/netapp/data/ 명령을 사용하여 현재 크기를 확인합니다.



* 볼륨 요구 사항:
+
** 이 볼륨은 Unified Manager/opt/NetApp/data 디렉토리의 최소 2배가 되어야 합니다
** 보안 스타일을 UNIX로 설정해야 합니다
** 로컬 스냅샷 정책을 해제해야 합니다
** 볼륨 자동 크기 조정이 활성화되어야 합니다
** 고성능 서비스 수준은 높은 IOPS와 낮은 지연 시간(예: "Extreme")을 가진 정책으로 설정해야 합니다.




NFS 볼륨을 생성하는 자세한 단계는 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["ONTAP 9에서 NFSv4를 구성하는 방법"] 및 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["ONTAP 9 NFS 구성 익스프레스 가이드 를 참조하십시오"].



[[specify-the-destination-location-for-snapshot-copies-in-active-iq-unified-manager]]
== Active IQ Unified Manager에서 스냅샷 복사본의 대상 위치를 지정합니다

ONTAP 클러스터 중 하나에 이미 구성되어 있는 볼륨의 Active IQ Unified Manager 스냅샷 복사본에 대한 대상 위치를 구성해야 합니다. 유지보수 콘솔을 사용하여 위치를 정의해야 합니다.

* Active IQ Unified Manager가 설치된 Linux 호스트에 대한 루트 사용자 자격 증명이 있어야 합니다.
* Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.
* 클러스터 관리 IP 주소, 스토리지 VM 이름, 볼륨 이름 및 스토리지 시스템 사용자 이름과 암호가 있어야 합니다.
* Active IQ Unified Manager 호스트에 볼륨을 마운트해야 하며 마운트 경로가 있어야 합니다.


.단계
. 보안 셸을 사용하여 Active IQ Unified Manager 시스템의 IP 주소 또는 FQDN에 연결합니다.
. 유지보수 사용자(umadmin) 이름 및 암호를 사용하여 시스템에 로그인합니다.
. mainf유지보수_console 명령을 입력하고 Enter 키를 누릅니다.
. 유지보수 콘솔 * 메인 메뉴 * 에서 * 백업 복원 * 옵션의 번호를 입력합니다.
. Configure NetApp Snapshot Backup * 의 번호를 입력합니다.
. NFS를 구성할 번호를 입력합니다.
. 제공해야 할 정보를 검토한 다음 * 백업 구성 세부 정보 입력 * 에 대한 번호를 입력합니다.
. 스냅샷을 기록할 볼륨을 식별하려면 클러스터 관리 인터페이스의 IP 주소, 스토리지 VM 이름, 볼륨 이름, LUN 이름, 스토리지 시스템 사용자 이름 및 암호, 마운트 경로를 입력합니다.
. 이 정보를 확인하고 y를 입력합니다.
+
시스템은 다음 작업을 수행합니다.

+
** 클러스터에 대한 연결을 설정합니다
** 모든 서비스를 중지합니다
** 볼륨에 새 디렉토리를 생성하고 Active IQ Unified Manager 데이터베이스 구성 파일을 복사합니다
** Active IQ Unified Manager에서 파일을 삭제하고 새 데이터베이스 디렉터리에 대한 symlink를 만듭니다
** 모든 서비스를 다시 시작합니다


. 아직 시작하지 않은 경우 유지보수 콘솔을 종료하고 Active IQ Unified Manager 인터페이스를 시작하여 스냅샷 복사본에 대한 일정을 생성합니다.

