---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 수 및 백업 일정을 설정할 수 있습니다. 매일 또는 매주 예약된 백업을 설정할 수 있습니다. 기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다. 
---
= 데이터베이스 덤프 백업의 대상 및 일정을 구성합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 데이터베이스 덤프 백업 설정을 구성하여 데이터베이스 백업 경로, 보존 수 및 백업 일정을 설정할 수 있습니다. 매일 또는 매주 예약된 백업을 설정할 수 있습니다. 기본적으로 예약된 백업은 비활성화되어 있지만 백업 일정을 설정해야 합니다.

.시작하기 전에
* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 백업 경로로 정의한 위치에서 최소 150GB의 공간을 사용할 수 있어야 합니다.
+
Unified Manager 호스트 시스템 외부에 있는 원격 위치를 사용하는 것이 좋습니다.

* Linux 시스템에 Unified Manager가 설치되어 있고 MySQL 백업을 사용하는 경우 백업 디렉토리에 다음 사용 권한 및 소유권이 설정되어 있는지 확인하십시오.
+
권한: 0750, 소유권: jboss: 유지 보수

* Unified Manager가 Windows 시스템에 설치되어 있고 MySQL 백업을 사용하는 경우 관리자만 백업 디렉토리에 액세스할 수 있어야 합니다.


첫 번째 백업은 전체 백업이므로 백업을 처음 수행할 때보다 더 많은 시간이 필요합니다. 전체 백업은 1GB가 넘고 3~4시간이 소요될 수 있습니다. 후속 백업은 증분 백업이므로 더 적은 시간이 필요합니다.

[NOTE]
====
* 백업용으로 할당된 공간에 비해 증분 백업 파일 수가 너무 많은 경우 주기적으로 전체 백업을 수행하여 이전 백업과 해당 증분 파일을 대체할 수 있습니다. 다른 옵션으로 Snapshot 복사본을 사용하여 백업을 수행할 수 있습니다.
* 새 클러스터를 추가한 후 처음 15일 동안 수행된 백업은 성능 기록 데이터를 가져올 정도로 정확하지 않을 수 있습니다.


====
.단계
. 왼쪽 탐색 창에서 * 일반 * > * 데이터베이스 백업 * 을 클릭합니다.
. 데이터베이스 백업 * 페이지에서 * 백업 설정 * 을 클릭합니다.
. 백업 경로, 보존 수 및 스케줄에 대한 적절한 값을 구성합니다.
+
보존 수의 기본값은 10이며 무제한 백업을 생성하는 데 0을 사용할 수 있습니다.

. Scheduled Daily * 또는 * Scheduled Weekly * 버튼을 선택한 후 일정 세부 정보를 지정합니다.
. 적용 * 을 클릭합니다.


데이터베이스 덤프 백업 파일은 일정에 따라 생성됩니다. 데이터베이스 백업 페이지에서 사용 가능한 백업 파일을 볼 수 있습니다.
