---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: 'Unified Manager와 관련된 몇 가지 일반적인 관리 워크플로우 및 작업으로는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 손실된 데이터 복원, 볼륨 구성 및 관리, 기술 지원(필요한 경우)에 진단 데이터를 번들로 제공 및 전송하는 작업이 있습니다.' 
---
= 공통 Unified Manager 상태 워크플로우 및 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager와 관련된 몇 가지 일반적인 관리 워크플로우 및 작업으로는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 손실된 데이터 복원, 볼륨 구성 및 관리, 기술 지원(필요한 경우)에 진단 데이터를 번들로 제공 및 전송하는 작업이 있습니다.

스토리지 관리자는 Unified Manager를 사용하여 대시보드를 확인하고, 관리되는 스토리지 클러스터의 전체 용량, 가용성 및 보호 상태를 평가한 다음, 발생할 수 있는 특정 문제를 신속하게 식별, 검색, 진단 및 할당하여 해결할 수 있습니다.

스토리지 용량 또는 관리 대상 스토리지 오브젝트의 데이터 가용성에 영향을 미치는 클러스터, SVM(스토리지 가상 시스템), 볼륨 또는 FlexGroup 볼륨과 관련된 가장 중요한 문제는 대시보드 페이지의 시스템 상태 그래프 및 이벤트에 표시됩니다. 중요한 문제가 식별되면 이 페이지에서는 적절한 문제 해결 워크플로를 지원하는 링크를 제공합니다.

WFA(OnCommand Workflow Automation)와 같은 관련 관리 도구가 포함된 워크플로우에 Unified Manager를 포함하여 스토리지 리소스를 직접 구성할 수도 있습니다.

이 문서에서는 다음과 같은 관리 작업과 관련된 일반적인 워크플로에 대해 설명합니다.

* 가용성 문제 진단 및 관리
+
하드웨어 장애 또는 스토리지 리소스 구성 문제로 인해 대시보드 페이지에 데이터 가용성 이벤트가 표시되는 경우 스토리지 관리자는 포함된 링크를 따라 영향을 받는 스토리지 리소스에 대한 연결 정보를 확인하고 문제 해결 조언을 확인하고 다른 관리자에게 문제 해결 방법을 할당할 수 있습니다.

* 성능 인시던트 구성 및 모니터링
+
관리자는 모니터링 중인 스토리지 시스템 리소스의 성능을 모니터링하고 관리할 수 있습니다. 를 참조하십시오 link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Active IQ Unified Manager 성능 모니터링 소개"] 를 참조하십시오.

* 볼륨 용량 문제 진단 및 관리
+
대시보드 페이지에 볼륨 스토리지 용량 문제가 표시되는 경우 스토리지 관리자는 포함된 링크를 따라 영향을 받는 볼륨의 스토리지 용량과 관련된 현재 및 과거 추세를 확인하고, 문제 해결 조언을 확인하고, 다른 관리자에게 문제 해결 방법을 할당할 수 있습니다.

* 보호 관계 문제 구성, 모니터링 및 진단
+
보호 관계를 생성 및 구성한 후에는 스토리지 관리자가 보호 관계, 보호 관계의 현재 상태, 영향을 받는 관계에 대한 현재 및 과거의 보호 작업 성공 정보 및 문제 해결 조언과 관련된 잠재적인 문제를 볼 수 있습니다. 를 참조하십시오 link:../data-protection/concept_create_and_monitor_protection_relationships.html["보호 관계 생성, 모니터링 및 문제 해결"] 를 참조하십시오.

* 백업 파일을 생성하고 백업 파일에서 데이터를 복원합니다.
* 스토리지 객체를 주석과 연관
+
스토리지 객체를 주석과 연결하여 스토리지 관리자는 스토리지 객체와 관련된 이벤트를 필터링하고 볼 수 있으므로 스토리지 관리자가 이벤트와 관련된 문제의 우선 순위를 지정하고 해결할 수 있습니다.

* REST API를 사용하여 Unified Manager에서 캡처한 상태, 용량 및 성능 정보를 확인하여 클러스터를 관리할 수 있습니다. 을 참조하십시오 link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST API 시작하기"] 를 참조하십시오.
* 기술 지원 팀에 지원 번들 보내기
+
스토리지 관리자는 유지 관리 콘솔을 사용하여 지원 번들을 검색하고 기술 지원에 보낼 수 있습니다. 문제가 AutoSupport 메시지가 제공하는 것보다 더 자세한 진단 및 문제 해결이 필요한 경우 지원 번들을 기술 지원 부서에 보내야 합니다.


