---
permalink: health-checker/concept_introduction_to_unified_manager_health_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, health, monitor 
summary: 'Active IQ Unified Manager(이전의 OnCommand Unified Manager)를 사용하면 중앙 집중식 사용자 인터페이스를 통해 ONTAP 소프트웨어를 실행하는 수많은 시스템을 모니터링할 수 있습니다. Unified Manager 서버 인프라는 확장성, 지원 가능성 및 향상된 모니터링 및 알림 기능을 제공합니다.' 
---
= Active IQ Unified Manager 상태 모니터링 소개
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager(이전의 OnCommand Unified Manager)를 사용하면 중앙 집중식 사용자 인터페이스를 통해 ONTAP 소프트웨어를 실행하는 수많은 시스템을 모니터링할 수 있습니다. Unified Manager 서버 인프라는 확장성, 지원 가능성 및 향상된 모니터링 및 알림 기능을 제공합니다.

Unified Manager의 주요 기능으로는 모니터링, 경고, 클러스터의 가용성 및 용량 관리, 보호 기능 관리, 진단 데이터의 번들 구성, 기술 지원 부서에 전송 등이 있습니다.

Unified Manager를 사용하여 클러스터를 모니터링할 수 있습니다. 클러스터에서 문제가 발생하면 Unified Manager가 이벤트를 통해 해당 문제의 세부 정보를 통지합니다. 또한 일부 이벤트는 문제를 해결하기 위해 취할 수 있는 개선 조치를 제공합니다. 문제가 발생할 때 전자 메일 및 SNMP 트랩을 통해 알림을 받도록 이벤트에 대한 알림을 구성할 수 있습니다.

Unified Manager를 사용하여 스토리지 객체를 주석과 연계하여 사용자 환경의 스토리지 객체를 관리할 수 있습니다. 맞춤형 주석을 생성하고 규칙을 통해 클러스터, SVM(스토리지 가상 머신), 볼륨을 주석과 함께 동적으로 연결할 수 있습니다.

또한 용량 및 상태 차트에 제공된 정보를 사용하여 각 클러스터 개체에 대한 클러스터 개체의 스토리지 요구 사항을 계획할 수 있습니다.



== 물리적 및 논리적 용량

Unified Manager에서는 ONTAP 스토리지 객체에 사용되는 물리적/논리적 공간의 개념을 사용합니다.

* 물리적 용량: 물리적 공간은 볼륨에 사용된 스토리지의 물리적 블록을 나타냅니다. "물리적 사용 용량"은 일반적으로 중복 제거 및 압축과 같은 스토리지 효율성 기능에서 데이터 감소로 인해 논리적 사용 용량보다 작습니다.
* 논리적 용량: 논리적 공간은 볼륨의 사용 가능한 공간(논리적 블록)을 나타냅니다. 논리적 공간은 중복제거 또는 압축 결과를 고려하지 않고 이론적 공간을 사용할 수 있는 방법을 나타냅니다. "사용된 논리적 공간"은 사용된 물리적 공간과 함께 구성된 스토리지 효율성 기능(예: 중복제거 및 압축)의 절약 효과를 더한 것입니다. 이 측정치는 Snapshot 복사본, 클론 및 기타 구성 요소를 포함하므로 물리적 사용된 용량보다 더 크게 표시되는 경우가 많으며 데이터 압축 및 물리적 공간의 기타 감소는 반영되지 않습니다. 따라서 총 논리적 용량이 프로비저닝된 공간보다 클 수 있습니다.




== 용량 측정 단위

Unified Manager에서는 1024바이트(2^10^)바이트의 이진 단위를 기준으로 스토리지 용량을 계산합니다. ONTAP 9.10.0 이전 버전에서는 이러한 유닛이 KB, MB, GB, TB 및 PB로 표시되었습니다. ONTAP 9.10.1부터는 Unified Manager에 KiB, MiB, GiB, TiB 및 PiB로 표시됩니다. 참고: 처리량에 사용되는 단위는 모든 ONTAP 릴리스에 대해 초당 킬로바이트(Kbps), 초당 메가바이트(Mbps), 초당 기가바이트(Gbps) 또는 초당 테라바이트(Tbps) 등으로 계속 사용됩니다.

[cols="4*"]
|===
| 용량 단위는 ONTAP 9.10.0 이하 버전에 대해 Unified Manager에 표시됩니다 | Unified Manager for ONTAP 9.10.1에 용량 단위가 표시됩니다 | 계산 | 바이트 단위의 값입니다 


 a| 
KB를 클릭합니다
 a| 
KiB
 a| 
1024
 a| 
1024바이트



 a| 
MB
 a| 
MIB
 a| 
1024 * 1024
 a| 
1,048,576바이트



 a| 
GB
 a| 
GiB
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824바이트



 a| 
TB
 a| 
TiB
 a| 
1024 * 1024 * 1024
 a| 
1,099,511,627,776바이트

|===