---
permalink: health-checker/reference_cluster_compliance_categories.html 
sidebar: sidebar 
keywords: cluster compliance, categories 
summary: 이 표에는 Unified Manager가 평가하는 클러스터 보안 규정 준수 매개 변수, NetApp 권장 사항 및 매개 변수가 불만 제기인지 여부와 관련된 클러스터의 전반적인 결정에 영향을 미치는지 여부가 정리되어 있습니다. 
---
= 클러스터 규정 준수 범주
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 표에는 Unified Manager가 평가하는 클러스터 보안 규정 준수 매개 변수, NetApp 권장 사항 및 매개 변수가 불만 제기인지 여부와 관련된 클러스터의 전반적인 결정에 영향을 미치는지 여부가 정리되어 있습니다.

클러스터에서 규정을 준수하지 않는 SVM이 존재할 경우 클러스터의 규정 준수 값에 영향을 미칩니다. 따라서 클러스터 보안이 규정 준수 상태로 인식되기 전에 SVM에서 보안 문제를 해결해야 하는 경우도 있습니다.

아래 나열된 모든 매개변수가 모든 설치에 나타나는 것은 아닙니다. 예를 들어 피어링된 클러스터가 없거나 클러스터에서 AutoSupport를 비활성화한 경우 UI 페이지에 클러스터 피어링 또는 AutoSupport HTTPS 전송 항목이 표시되지 않습니다.

[cols="4*"]
|===
| 매개 변수 | 설명 | 권장 사항 | 클러스터 규정 준수에 영향을 줍니다 


 a| 
글로벌 FIPS
 a| 
글로벌 FIPS(Federal Information Processing Standard) 140-2 준수 모드가 활성화되어 있는지 여부를 나타냅니다. FIPS가 활성화되면 TLSv1 및 SSLv3이 비활성화되고 TLSv1.1 및 TLSv1.2만 허용됩니다.
 a| 
활성화됨
 a| 
예



 a| 
텔넷
 a| 
시스템에 대한 텔넷 액세스가 활성화되었는지 여부를 나타냅니다. 보안 원격 액세스를 위해 SSH(Secure Shell)를 사용하는 것이 좋습니다.
 a| 
사용 안 함
 a| 
예



 a| 
안전하지 않은 SSH 설정
 a| 
SSH가 * CBC로 시작하는 암호 등의 안전하지 않은 암호를 사용하는지 여부를 나타냅니다.
 a| 
아니요
 a| 
예



 a| 
로그인 배너
 a| 
시스템에 액세스하는 사용자가 로그인 배너를 사용할 수 있는지 여부를 나타냅니다.
 a| 
활성화됨
 a| 
예



 a| 
클러스터 피어링
 a| 
피어링된 클러스터 간의 통신이 암호화되었는지 또는 암호화되지 않았음을 나타냅니다. 이 매개 변수를 준수하는 것으로 간주하려면 소스 클러스터와 대상 클러스터 모두에서 암호화를 구성해야 합니다.
 a| 
암호화
 a| 
예



 a| 
Network Time Protocol의 약어입니다
 a| 
클러스터에 구성된 NTP 서버가 하나 이상 있는지 여부를 나타냅니다. 이중화 및 최적의 서비스를 위해 최소 3개의 NTP 서버를 클러스터에 연결하는 것이 좋습니다.
 a| 
구성됨
 a| 
예



 a| 
OCSP
 a| 
9.14.1부터 Active IQ Unified Manager은 스토리지 가상 머신(SVM, 이전의 Vserver) 레벨에서 OCSP(온라인 인증서 상태 프로토콜) 상태 정보를 제공합니다. 즉, OCSP 검증이 SVM에 대한 모든 SSL/TLS 연결에 적용되며 이러한 연결에 사용된 인증서의 무결성과 유효성을 보장합니다.
 a| 
활성화됨
 a| 
아니요



 a| 
원격 감사 로깅
 a| 
로그 전달(Syslog)이 암호화되었는지 또는 암호화되지 않았음을 나타냅니다.
 a| 
암호화
 a| 
예



 a| 
AutoSupport HTTPS 전송
 a| 
HTTPS가 NetApp 지원으로 AutoSupport 메시지를 보내기 위한 기본 전송 프로토콜로 사용되는지 여부를 나타냅니다.
 a| 
활성화됨
 a| 
예



 a| 
기본 관리자 사용자입니다
 a| 
기본 관리자 사용자(기본 제공)가 활성화 또는 비활성화되었는지 여부를 나타냅니다. 불필요한 내장 계정을 잠금(비활성화)하는 것이 좋습니다.
 a| 
사용 안 함
 a| 
예



 a| 
SAML 사용자
 a| 
SAML이 구성되었는지 여부를 나타냅니다. SAML을 사용하면 SSO(Single Sign-On)에 대한 로그인 방법으로 MFA(Multi-Factor Authentication)를 구성할 수 있습니다.
 a| 
아니요
 a| 
아니요



 a| 
Active Directory 사용자
 a| 
Active Directory가 구성되었는지 여부를 나타냅니다. Active Directory 및 LDAP는 클러스터에 액세스하는 사용자가 선호하는 인증 메커니즘입니다.
 a| 
아니요
 a| 
아니요



 a| 
LDAP 사용자
 a| 
LDAP가 구성되었는지 여부를 나타냅니다. Active Directory 및 LDAP는 로컬 사용자를 통해 클러스터를 관리하는 사용자에게 권장되는 인증 메커니즘입니다.
 a| 
아니요
 a| 
아니요



 a| 
인증서 사용자
 a| 
인증서 사용자가 클러스터에 로그인하도록 구성되었는지 여부를 나타냅니다.
 a| 
아니요
 a| 
아니요



 a| 
로컬 사용자
 a| 
로컬 사용자가 클러스터에 로그인하도록 구성되었는지 여부를 나타냅니다.
 a| 
아니요
 a| 
아니요



 a| 
원격 셸
 a| 
RSH가 활성화되었는지 여부를 나타냅니다. 보안상의 이유로 RSH를 비활성화해야 합니다. 보안 원격 액세스를 위한 SSH(Secure Shell)가 권장됩니다.
 a| 
사용 안 함
 a| 
예



 a| 
MD5가 사용 중입니다
 a| 
ONTAP 사용자 계정이 덜 안전한 MD5 해시 기능을 사용하고 있는지 여부를 나타냅니다. MD5 해시 사용자 계정을 SHA-512와 같은 보다 안전한 암호화 해시 기능으로 마이그레이션하는 것이 좋습니다.
 a| 
아니요
 a| 
예



 a| 
인증서 발급자 유형
 a| 
사용된 디지털 인증서의 유형을 나타냅니다.
 a| 
CA 서명
 a| 
아니요

|===