---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: AutoSupport 페이지에서는 사전 정의된 요청 시 AutoSupport 메시지를 기술 지원 팀에 전송하여 운영 환경을 올바르게 운영하고 환경의 무결성을 유지할 수 있도록 지원합니다. AutoSupport는 기본적으로 활성화되어 있으며NetApp Active IQ의 이점을 누릴 수 있도록 비활성화되어서는 안 됩니다. 
---
= 기술 지원 팀에 AutoSupport 메시지 및 지원 번들 보내기
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 페이지에서는 사전 정의된 요청 시 AutoSupport 메시지를 기술 지원 팀에 전송하여 운영 환경을 올바르게 운영하고 환경의 무결성을 유지할 수 있도록 지원합니다. AutoSupport는 기본적으로 활성화되어 있으며NetApp Active IQ의 이점을 누릴 수 있도록 비활성화되어서는 안 됩니다.

Unified Manager 서버에 대한 진단 시스템 정보 및 세부 데이터를 필요한 경우 메시지로 보내거나, 주기적으로 메시지를 보내거나, 기술 지원 팀에 지원 번들을 생성하고 보낼 수 있습니다.

[NOTE]
====
스토리지 관리자 역할을 가진 사용자는 주문형 AutoSupport 메시지 및 지원 번들을 생성하여 기술 지원으로 보낼 수 있습니다. 그러나 관리자 또는 유지 관리 사용자만 주기적인 AutoSupport를 활성화 또는 비활성화하고 HTTP 프록시 서버 설정 섹션에 설명된 대로 HTTP 설정을 구성할 수 있습니다. HTTP 프록시 서버를 사용해야 하는 환경에서는 스토리지 관리자가 주문형 AutoSupport 메시지 및 지원 번들을 기술 지원에 보내기 전에 구성을 완료해야 합니다.

====


== 주문형 AutoSupport 메시지 보내기

주문형 메시지를 생성하여 기술 지원 부서 또는 지정된 이메일 수신자 또는 두 사람에게 보낼 수 있습니다.

.단계
. 일반 * > * AutoSupport * 로 이동하여 다음 작업 중 하나 또는 모두를 수행합니다.
. 기술 지원 부서에 AutoSupport 메시지를 보내려면 * 기술 지원 부서로 전송 * 확인란을 선택합니다.
. 특정 이메일 수신자에게 AutoSupport 메시지를 보내려면 * 이메일 수신자에게 전송 * 확인란을 선택하고 수신자의 이메일 주소를 입력합니다.
. 저장 * 을 클릭합니다.
. AutoSupport 생성 및 전송 * 을 클릭합니다.




== Periodic AutoSupport 활성화

정기적으로 문제 진단 및 해결을 위해 기술 지원 부서에 사전 정의된 특정 메시지를 보낼 수 있습니다. 이 기능은 기본적으로 활성화되어 있습니다. 비활성화된 경우 관리자 또는 유지 관리 사용자가 설정을 활성화할 수 있습니다.

.단계
. 일반 * > * AutoSupport * 로 이동합니다.
. Periodic AutoSupport(주기적 데이터) 섹션에서 AutoSupport*에 주기적으로 Active IQ 데이터 전송 사용 확인란을 선택합니다.
. 필요한 경우 HTTP 프록시 서버 설정 섹션에 설명된 대로 HTTP 프록시 서버의 이름, 포트 및 인증 정보를 정의합니다.
. 저장 * 을 클릭합니다.




== 주문형 지원 번들 업로드

문제 해결 요구사항에 따라 지원 번들을 생성하고 기술 지원 팀에 보낼 수 있습니다. Unified Manager에서는 가장 최근에 생성된 2개의 지원 번들만 저장합니다. 이전 지원 번들은 시스템에서 삭제됩니다.

일부 지원 데이터 유형에서는 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 시간이 오래 걸릴 수 있으므로 전체 지원 번들을 선택할 때 특정 데이터 유형을 포함하거나 제외하여 지원 번들 크기를 줄일 수 있습니다. 또한 30일 동안의 로그 및 구성 데이터베이스 레코드를 포함하는 경량 지원 번들을 생성할 수 있습니다. 성능 데이터, 획득 기록 파일 및 서버 힙 덤프는 제외됩니다.

.단계
. 일반 * > * AutoSupport * 로 이동합니다.
. 주문형 지원 번들 섹션에서 * 지원 번들 생성 및 전송 * 을 클릭합니다.
. 기술 지원 부서에 가벼운 지원 번들을 보내려면 지원 번들 생성 및 전송 팝업에서 ** 가벼운 지원 번들 생성** 확인란을 선택합니다.
. 또는 전체 지원 번들을 보내려면 * 전체 지원 번들 생성 * 확인란을 선택합니다. 지원 번들에 포함하거나 제외할 특정 데이터 유형을 선택합니다.
+
[NOTE]
====
데이터 유형을 선택하지 않더라도 지원 번들은 다른 Unified Manager 데이터와 함께 생성됩니다.

====
. 번들을 생성하여 기술 지원 부서에 보내려면 * 기술 지원 부서에 번들 보내기 * 확인란을 선택합니다. 이 확인란을 선택하지 않으면 번들은 Unified Manager 서버에 로컬로 생성되고 저장됩니다. 생성된 지원 번들은 나중에 VMware 시스템의 /support 디렉토리, Linux 시스템의 경우 '/opt/netapp/data/support/', Windows 시스템의 경우 'ProgramData\NetApp\OnCommandAppData\ocum\support'에서 사용할 수 있습니다.
. 보내기 * 를 클릭합니다.




== HTTP 프록시 서버 설정 중

환경에서 Unified Manager 서버로부터 직접 액세스할 수 없는 경우 AutoSupport 콘텐츠를 지원하도록 인터넷 액세스를 제공하는 프록시를 지정할 수 있습니다. 이 섹션은 관리자 및 유지 보수 사용자만 사용할 수 있습니다.

* * HTTP 프록시 사용 *
+
HTTP 프록시로 사용 중인 서버를 식별하려면 이 확인란을 선택합니다.

+
프록시 서버의 호스트 이름 또는 IP 주소와 서버 연결에 사용되는 포트 번호를 입력합니다.

* * 인증 사용 *
+
HTTP 프록시로 사용 중인 서버에 액세스하기 위한 인증 정보를 제공해야 하는 경우 이 확인란을 선택합니다.

+
HTTP 프록시로 인증하는 데 필요한 사용자 이름과 암호를 입력합니다.



[NOTE]
====
기본 인증만 제공하는 HTTP 프록시는 지원되지 않습니다.

====