---
permalink: health-checker/task_restore_mysql_db_on_linux_or_centos.html 
sidebar: sidebar 
keywords: restore, linux system, mysql, database, backup 
summary: 데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지 관리 콘솔을 사용하여 Unified Manager 데이터베이스를 로컬 또는 원격 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다. 
---
= Linux 시스템에서 MySQL 데이터베이스 백업을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지 관리 콘솔을 사용하여 Unified Manager 데이터베이스를 로컬 또는 원격 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다.

* 필요한 것 *

* Unified Manager가 설치된 Linux 호스트에 대한 루트 사용자 자격 증명이 있어야 합니다.
* Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.
* Unified Manager 백업 파일과 데이터베이스 저장소 디렉터리의 내용을 복구 작업을 수행할 시스템에 복사해야 합니다.
+
백업 파일을 기본 디렉토리 /data/ocum'-backup에 복사하는 것이 좋습니다. 데이터베이스 리포지토리 파일은 /'ocum-backup' 디렉토리 아래의 / database-dumps-repo 하위 디렉토리에 복사해야 합니다.

* 백업 파일은 반드시 .7z 형식이어야 합니다.


복원 기능은 플랫폼별 및 버전에 따라 다릅니다. Unified Manager 백업은 동일한 Unified Manager 버전에서만 복원할 수 있습니다. Linux 백업 파일 또는 가상 어플라이언스 백업 파일을 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다.

[TIP]
====
백업 폴더 이름에 공백이 포함된 경우 절대 경로 또는 상대 경로를 큰따옴표로 묶어야 합니다.

====
.단계
. 새 서버로 복원을 수행하는 경우 Unified Manager를 설치한 후 설치가 완료될 때 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.
. Secure Shell을 사용하여 Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
. 유지보수 사용자(umadmin) 이름 및 암호를 사용하여 시스템에 로그인합니다.
. mainf유지보수_console 명령을 입력하고 Enter 키를 누릅니다.
. 유지보수 콘솔 * 메인 메뉴 * 에서 * 백업 복원 * 옵션의 번호를 입력합니다.
. Restore MySQL Backup * 의 번호를 입력합니다.
. 메시지가 표시되면 백업 파일의 절대 경로를 입력합니다.
+
[listing]
----
Bundle to restore from: /data/ocum-backup/UM_9.8.N151113.1348_backup_rhel_02-20-2020-04-45.7z
----
+
복원 작업이 완료되면 Unified Manager에 로그인할 수 있습니다.



백업을 복원한 후 OnCommand Workflow Automation 서버가 작동하지 않으면 다음 단계를 수행하십시오.

. Workflow Automation 서버에서 Unified Manager 서버의 IP 주소를 최신 시스템을 가리키도록 변경합니다.
. 1단계에서 획득에 실패한 경우 Unified Manager 서버에서 데이터베이스 암호를 재설정합니다.

