---
permalink: health-checker/task_create_volume_where_backups_are_stored.html 
sidebar: sidebar 
keywords: configure, snapshot, backup location 
summary: ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 ONTAP 클러스터 중 하나에 스냅샷 백업이 저장될 볼륨을 구성할 수 있습니다. 
---
= 스냅샷 백업 위치를 구성하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 시스템 관리자 또는 ONTAP CLI를 사용하여 ONTAP 클러스터 중 하나에 스냅샷 백업이 저장될 볼륨을 구성할 수 있습니다.

* 필요한 것 *

클러스터, 스토리지 VM 및 볼륨은 다음 요구사항을 충족해야 합니다.

* 클러스터 요구 사항:
+
** ONTAP 9.3 이상을 설치해야 합니다
** Unified Manager 서버와 지리적으로 가까운 곳에 있어야 합니다
** Unified Manager를 통해 모니터링할 수 있지만 반드시 필요한 것은 아닙니다


* 스토리지 VM 요구 사항:
+
** 이름 스위치와 이름 매핑은 ""파일""을 사용하도록 설정되어야 합니다.
** 클라이언트 측 사용자와 일치하도록 생성된 로컬 사용자입니다
** 모든 읽기/쓰기 권한이 선택되어 있는지 확인합니다
** 수출 정책에서 슈퍼유저 액세스가 ""모두""로 설정되어 있는지 확인하십시오
** Linux용 NetApp Snapshot용 NFS
** NFSv4는 클라이언트 및 스토리지 VM에 지정된 NFS 서버 및 NFSv4 ID 도메인에서 설정해야 합니다
** 이 볼륨은 Unified Manager/opt/NetApp/data 디렉토리의 최소 2배가 되어야 합니다
+
du-sh/opt/netapp/data/ 명령을 사용하여 현재 크기를 확인합니다.



* 볼륨 요구 사항:
+
** 이 볼륨은 Unified Manager/opt/NetApp/data 디렉토리의 최소 2배가 되어야 합니다
** 보안 스타일을 UNIX로 설정해야 합니다
** 로컬 스냅샷 정책을 해제해야 합니다
** 볼륨 자동 크기 조정이 활성화되어야 합니다
** 고성능 서비스 수준은 높은 IOPS와 낮은 지연 시간(예: "Extreme")을 가진 정책으로 설정해야 합니다.




NFS 볼륨을 생성하는 자세한 단계는 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["ONTAP 9에서 NFSv4를 구성하는 방법"] 및.
