---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: 문제 해결 지원을 위해 기술 지원 부서에 보낼 수 있도록 진단 정보가 포함된 지원 번들을 생성할 수 있습니다. Unified Manager 9.8부터 Unified Manager 서버가 인터넷에 연결되어 있는 경우, 유지보수 콘솔에서 지원 번들을 NetApp에 업로드할 수도 있습니다. 
---
= 지원 번들 생성 및 업로드
:icons: font
:imagesdir: ../media/


[role="lead"]
문제 해결 지원을 위해 기술 지원 부서에 보낼 수 있도록 진단 정보가 포함된 지원 번들을 생성할 수 있습니다. Unified Manager 9.8부터 Unified Manager 서버가 인터넷에 연결되어 있는 경우, 유지보수 콘솔에서 지원 번들을 NetApp에 업로드할 수도 있습니다.

* 필요한 것 *

유지보수 사용자로서 유지보수 콘솔에 액세스할 수 있어야 합니다.

일부 유형의 지원 데이터는 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 시간이 오래 걸릴 수 있으므로, 전체 지원 번들을 선택할 때 포함 또는 제외할 데이터 유형을 지정하여 지원 번들 크기를 줄일 수 있습니다. 또한 30일 동안의 로그 및 구성 데이터베이스 레코드를 포함하는 경량 지원 번들을 생성할 수 있습니다. 성능 데이터, 획득 기록 파일 및 서버 힙 덤프는 제외됩니다.

Unified Manager에서는 가장 최근에 생성된 2개의 지원 번들만 저장합니다. 이전 지원 번들은 시스템에서 삭제됩니다.

.단계
. 유지보수 콘솔 * 주 메뉴 * 에서 * 지원/진단 * 을 선택합니다.
. 지원 번들에서 원하는 세부 정보 수준에 따라 * Generate Light Support Bundle * 또는 * Generate Support Bundle * 을 선택합니다.
. 전체 지원 번들을 선택하는 경우 지원 번들에 포함하거나 제외할 다음 데이터 유형을 선택하거나 선택 취소합니다.
+
** * 데이터베이스 덤프 *
+
MySQL Server 데이터베이스의 덤프.

** * 힙 덤프 *
+
기본 Unified Manager 서버 프로세스 상태의 스냅샷 이 옵션은 기본적으로 비활성화되어 있으며 고객 지원 부서에서 요청할 때만 선택해야 합니다.

** * 촬영 녹화 *
+
Unified Manager와 모니터링되는 클러스터 간의 모든 통신 내용을 기록하는 것입니다.



+
[NOTE]
====
모든 데이터 유형의 선택을 취소하면 지원 번들이 다른 Unified Manager 데이터와 함께 계속 생성됩니다.

====
. 'g'를 입력한 다음 Enter 키를 눌러 지원 번들을 생성합니다.
+
지원 번들 생성은 메모리를 많이 사용하는 작업이므로 지원 번들을 생성할지 확인하는 메시지가 표시됩니다.

. 'y'를 입력한 다음 Enter 키를 눌러 지원 번들을 생성합니다.
+
현재 지원 번들을 생성하지 않으려면 "n"을 입력한 다음 Enter 키를 누릅니다.

. 전체 지원 번들에 데이터베이스 덤프 파일을 포함하는 경우 성능 통계를 포함할 기간을 지정하라는 메시지가 표시됩니다. 성능 통계를 포함시키면 많은 시간과 공간이 소요되므로 성능 통계를 포함하지 않고 데이터베이스를 덤프할 수도 있습니다.
+
.. YYYYMMDD 형식으로 시작 날짜를 입력합니다.
+
예를 들어, 2021년 1월 1일에 20210101을 입력합니다. 성능 통계를 포함하지 않으려면 n을 입력합니다.

.. 오전 12시부터 통계 일수를 입력합니다 지정된 시작 날짜에.
+
1부터 10까지의 숫자를 입력할 수 있습니다.



+
성능 통계를 포함하는 경우 성능 통계를 수집하는 기간이 표시됩니다.

. 지원 번들이 생성되면 NetApp에 업로드할 것인지 묻는 메시지가 표시됩니다. y를 입력한 다음 Enter 키를 누릅니다.
+
지원 케이스 번호를 입력하라는 메시지가 표시됩니다.

. 케이스 번호가 이미 있는 경우 번호를 입력하고 Enter 키를 누릅니다. 그렇지 않으면 Enter 키를 누릅니다.
+
지원 번들은 NetApp에 업로드됩니다.



Unified Manager 서버가 인터넷에 연결되어 있지 않거나 다른 이유로 지원 번들을 업로드할 수 없는 경우 검색할 수 있으며 수동으로 전송할 수 있습니다. SFTP 클라이언트를 사용하거나 UNIX 또는 Linux CLI 명령을 사용하여 검색할 수 있습니다. Windows 설치에서 RDP(원격 데스크톱)를 사용하여 지원 번들을 검색할 수 있습니다.

생성된 지원 번들은 VMware 시스템의 /support 디렉토리, Linux 시스템의 /opt/netapp/data/support/및 Windows 시스템의 ProgramData\NetApp\OnCommandAppData\ocum\support에 있습니다.

* 관련 정보 *

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager 사용자 역할 및 기능"]
