---
permalink: health-checker/task_resolve_volume_offline_issues.html 
sidebar: sidebar 
keywords: resolve, volume, offline issues 
summary: 이 워크플로우에서는 Unified Manager가 이벤트 관리 인벤토리 페이지에 표시할 수 있는 볼륨 오프라인 이벤트를 평가하고 해결하는 방법의 예를 제공합니다. 이 시나리오에서는 Unified Manager를 사용하여 하나 이상의 볼륨 오프라인 이벤트 문제를 해결할 수 있습니다. 
---
= 볼륨 오프라인 문제 해결
:icons: font
:imagesdir: ../media/


[role="lead"]
이 워크플로우에서는 Unified Manager가 이벤트 관리 인벤토리 페이지에 표시할 수 있는 볼륨 오프라인 이벤트를 평가하고 해결하는 방법의 예를 제공합니다. 이 시나리오에서는 Unified Manager를 사용하여 하나 이상의 볼륨 오프라인 이벤트 문제를 해결할 수 있습니다.

* 필요한 것 *

운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

다음과 같은 여러 가지 이유로 볼륨이 오프라인 상태로 보고될 수 있습니다.

* SVM 관리자가 볼륨을 오프라인으로 고의적으로 전환했습니다.
* 볼륨의 호스팅 클러스터 노드가 다운되고 HA 쌍 파트너에 대한 스토리지 페일오버도 실패합니다.
* 해당 SVM의 루트 볼륨을 호스팅하는 노드가 다운되었기 때문에 볼륨의 호스팅 스토리지 가상 시스템(SVM)이 중지됩니다.
* 2개의 RAID 디스크에서 동시에 발생한 장애로 인해 볼륨의 호스팅 애그리게이트는 다운되었습니다.


이벤트 관리 인벤토리 페이지와 클러스터/상태, 스토리지 VM/상태 및 볼륨/상태 세부 정보 페이지를 사용하여 이러한 가능성 중 하나 이상을 확인하거나 제거할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 * 이벤트 관리 * 를 클릭합니다.
. 이벤트 관리 * 재고 페이지에서 * 활성 가용성 이벤트 * 를 선택합니다.
. 볼륨 오프라인 이벤트에 대해 표시되는 하이퍼텍스트 링크를 클릭합니다.
+
가용성 인시던트에 대한 이벤트 세부 정보 페이지가 표시됩니다.

. 이 페이지에서 SVM 관리자가 해당 볼륨을 오프라인으로 전환했음을 나타내는 메모가 있는지 확인합니다.
. 이벤트 * 세부 정보 페이지에서 다음 작업 중 하나 이상에 대한 정보를 검토할 수 있습니다.
+
** 원인 필드에 표시되는 정보를 검토하여 가능한 진단 지침을 확인합니다.
+
이 예에서 원인 필드의 정보는 볼륨이 오프라인 상태임을 알려줍니다.

** 참고 및 업데이트 영역에서 SVM 관리자가 문제의 볼륨을 오프라인으로 설정했음을 나타내는 표시를 확인하십시오.
** 이벤트 소스(이 경우 오프라인으로 보고된 볼륨)를 클릭하여 해당 볼륨에 대한 자세한 정보를 확인합니다.
** 관리자에게 이벤트를 할당합니다.
** 이벤트를 확인하거나 해당하는 경우 해결됨으로 표시합니다.



