---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, linux, snapshot, backup, windows 
summary: 데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지보수 콘솔을 사용하여 Unified Manager 스냅샷 데이터베이스를 로컬 또는 원격 운영 체제로 복원할 수 있습니다. 
---
= Linux 및 Windows용 스냅샷 백업 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지보수 콘솔을 사용하여 Unified Manager 스냅샷 데이터베이스를 로컬 또는 원격 운영 체제로 복원할 수 있습니다.

* 필요한 것 *

* Linux 호스트에 대한 루트 사용자 자격 증명과 Unified Manager가 설치된 Windows 호스트 시스템에 대한 관리 권한이 있어야 합니다.
* Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.


복원 기능은 플랫폼별 및 버전에 따라 다릅니다. Unified Manager 백업은 동일한 Unified Manager 버전에서만 복원할 수 있습니다.

.단계
. Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
+
|===


 a| 
Linux *



 a| 
보안 셸



 a| 
* Windows *



 a| 
Power Shell을 선택합니다

|===
. 루트 사용자 자격 증명을 사용하여 시스템에 로그인합니다.
. mainf유지보수_console 명령을 입력하고 Enter 키를 누릅니다.
. 유지보수 콘솔 * 메인 메뉴 * 에서 * 백업 복원 * 옵션의 번호를 입력합니다.
. NetApp Snapshot * 을 사용하여 백업 및 복원 * 에 대한 번호를 입력합니다.
+
새 서버로 복원을 수행하는 경우 Unified Manager를 설치한 후 설치가 완료될 때 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. Configure NetApp Snapshot Backup * 에 대한 번호를 입력하고 원래 시스템에 구성되었던 스냅샷 백업 설정을 구성합니다.

. NetApp Snapshot * 을 사용하여 복원 * 에 대한 번호를 입력합니다.
. 복원하려는 스냅샷 백업 파일을 선택하고 * Enter * 를 누릅니다.
. 복원 프로세스가 완료되면 Unified Manager 사용자 인터페이스에 로그인합니다.


백업을 복원한 후 Workflow Automation 서버가 작동하지 않으면 다음 단계를 수행하십시오.

. Workflow Automation 서버에서 Unified Manager 서버의 IP 주소를 최신 시스템을 가리키도록 변경합니다.
. 1단계에서 획득에 실패한 경우 Unified Manager 서버에서 데이터베이스 암호를 재설정합니다.

