---
permalink: health-checker/task_add_scripts.html 
sidebar: sidebar 
keywords: add, scripts 
summary: Unified Manager에 스크립트를 추가하고 스크립트를 알림에 연결할 수 있습니다. 이러한 스크립트는 경고가 생성될 때 자동으로 실행되며, 이벤트를 생성할 스토리지 개체에 대한 정보를 가져올 수 있습니다. 
---
= 스크립트 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에 스크립트를 추가하고 스크립트를 알림에 연결할 수 있습니다. 이러한 스크립트는 경고가 생성될 때 자동으로 실행되며, 이벤트를 생성할 스토리지 개체에 대한 정보를 가져올 수 있습니다.

* 필요한 것 *

* Unified Manager 서버에 추가할 스크립트를 작성하여 저장해야 합니다.
* 스크립트에 지원되는 파일 형식은 Perl, Shell, PowerShell, Python 및 .bat입니다.
+
[cols="2*"]
|===
| Unified Manager가 설치된 플랫폼입니다 | 지원되는 언어 


 a| 
VMware
 a| 
Perl 및 Shell 스크립트



 a| 
리눅스
 a| 
Perl, Python 및 Shell 스크립트



 a| 
Windows
 a| 
PowerShell, Perl, Python 및 .bat 스크립트

|===
+
** Perl 스크립트의 경우, Perl을 Unified Manager 서버에 설치해야 합니다. VMware 설치의 경우 Perl 5가 기본적으로 설치되며 스크립트는 Perl 5가 지원하는 것만 지원합니다. Unified Manager 후에 Perl이 설치된 경우 Unified Manager 서버를 다시 시작해야 합니다.
** PowerShell 스크립트의 경우 스크립트를 실행할 수 있도록 Windows 서버에 적절한 PowerShell 실행 정책을 설정해야 합니다.


+
[NOTE]
====
스크립트가 알림 스크립트 진행률을 추적하기 위해 로그 파일을 생성할 경우 Unified Manager 설치 폴더 내 로그 파일이 생성되지 않도록 해야 합니다.

====
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


사용자 지정 스크립트를 업로드하고 알림에 대한 이벤트 세부 정보를 수집할 수 있습니다.

[NOTE]
====
사용자 인터페이스에서 이 기능을 사용할 수 없는 경우 관리자가 해당 기능을 비활성화했기 때문입니다. 필요한 경우 * 스토리지 관리 * > * 기능 설정 * 에서 이 기능을 활성화할 수 있습니다.

====
.단계
. 왼쪽 탐색 창에서 * 스토리지 관리 * > * 스크립트 * 를 클릭합니다.
. 스크립트 * 페이지에서 * 추가 * 를 클릭합니다.
. 스크립트 * 추가 대화 상자에서 * 찾아보기 * 를 클릭하여 스크립트 파일을 선택합니다.
. 선택한 스크립트에 대한 설명을 입력합니다.
. 추가 * 를 클릭합니다.

