---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_or_centos_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: Unified Manager를 실행하는 호스트 운영 체제를 변경하려면 Unified Manager MySQL 데이터베이스 덤프 백업을 가상 어플라이언스에서 Red Hat Enterprise Linux 또는 CentOS Linux 시스템으로 복구할 수 있습니다. 
---
= Unified Manager 가상 어플라이언스를 Linux 시스템으로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 실행하는 호스트 운영 체제를 변경하려면 Unified Manager MySQL 데이터베이스 덤프 백업을 가상 어플라이언스에서 Red Hat Enterprise Linux 또는 CentOS Linux 시스템으로 복구할 수 있습니다.

* 필요한 것 *

* 가상 어플라이언스:
+
** 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
** 복원 작업에 사용할 Unified Manager 유지보수 사용자의 이름을 알아야 합니다.


* Linux 시스템에서 다음을 수행합니다.
+
** 의 지침에 따라 Linux 서버에 Unified Manager를 설치해야 합니다 link:../install-linux/concept_install_unified_manager_on_rhel_or_centos.html["Linux 시스템에 Unified Manager 설치"].
** 이 서버의 Unified Manager 버전은 백업 파일을 사용하는 가상 어플라이언스의 버전과 동일해야 합니다.
** 설치 후 Linux 시스템에서 UI를 시작하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.
** Linux 호스트에 대한 루트 사용자 자격 증명이 있어야 합니다.




다음 단계에서는 가상 어플라이언스에 백업 파일을 생성하고 백업 파일을 Red Hat Enterprise Linux 또는 CentOS 시스템에 복사한 다음 데이터베이스 백업을 새 시스템으로 복원하는 방법을 설명합니다.

.단계
. 가상 어플라이언스에서 * 관리 * > * 데이터베이스 백업 * 을 클릭합니다.
. 데이터베이스 백업 * 페이지에서 * 백업 설정 * 을 클릭합니다.
. 백업 경로를 /jail/support로 변경합니다.
. Schedule 섹션에서 * Scheduled Daily * 를 선택하고 현재 시간 이후 몇 분 동안 백업을 생성할 시간을 입력합니다.
. 적용 * 을 클릭합니다.
. 백업이 생성될 때까지 몇 시간 정도 기다립니다.
+
전체 백업은 1GB가 넘고 완료하는 데 3~4시간이 걸릴 수 있습니다.

. Unified Manager가 설치된 Linux 호스트에 루트 사용자로 로그인하고 SCP를 사용하여 가상 어플라이언스에 대한 지원/지원 파일에서 백업 파일을 복사합니다.' root@<rhel_server>:/#scp -r admin@<vapp_server_ip_address>:/support/ *
+
'root@ocum_rhel-21:/#scp-r admin@10.10.10.10:/support/ *.

+
/database-dumps-repo 하위 디렉터리에 .7z 백업 파일과 모든 .7z 리포지토리 파일을 복사했는지 확인합니다.

. 명령 프롬프트에서 'um backup restore -f/<backup_file_path>/<backup_file_name>' 백업을 복구합니다
+
'um backup restore-f/UM_9.7.N151113.1348_backup_UNIX_02-12-2019-04-16.7z

. 복원 작업이 완료되면 Unified Manager 웹 UI에 로그인합니다.


다음 작업을 수행해야 합니다.

* 새 HTTPS 보안 인증서를 생성하고 Unified Manager 서버를 다시 시작합니다.
* Linux 시스템에 /jail/support 경로가 없기 때문에 백업 경로를 Linux 시스템의 기본 설정(/data/ocum-backup) 또는 선택한 새 경로로 변경합니다.
* WFA를 사용 중인 경우 Workflow Automation 연결의 양측을 다시 구성하십시오.
* SAML을 사용하는 경우 SAML 인증 설정을 다시 구성하십시오.


Linux 시스템에서 모든 기능이 예상대로 실행되고 있는지 확인한 후 Unified Manager 가상 어플라이언스를 종료 및 제거할 수 있습니다.
