---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: '상태: 모든 노드 보기를 사용하여 클러스터의 노드 목록을 볼 수 있습니다. 클러스터/상태 세부 정보 페이지를 사용하여 모니터링되는 클러스터의 일부인 노드에 대한 자세한 정보를 볼 수 있습니다.' 
---
= 노드 목록 및 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태: 모든 노드 보기를 사용하여 클러스터의 노드 목록을 볼 수 있습니다. 클러스터/상태 세부 정보 페이지를 사용하여 모니터링되는 클러스터의 일부인 노드에 대한 자세한 정보를 볼 수 있습니다.

.시작하기 전에
운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

노드 상태, 노드가 포함된 클러스터, 애그리게이트 용량 세부 정보(사용된 용량 및 총 용량), 물리적 용량 세부 정보(사용 가능, 스페어, 총 용량)와 같은 세부 정보를 볼 수 있습니다. HA 쌍, 디스크 쉘프 및 포트에 대한 정보도 얻을 수 있습니다.

.단계
. 왼쪽 탐색 창에서 * 스토리지 * > * 노드 * 를 클릭합니다.
. 상태: 모든 노드 * 보기에서 세부 정보를 보려는 노드를 클릭합니다.
+
선택한 노드에 대한 자세한 정보가 클러스터/상태 세부 정보 페이지에 표시됩니다. 왼쪽 창에는 HA 쌍 목록이 표시됩니다. 기본적으로 HA Details는 열려 있어 HA 상태 세부 정보와 선택한 HA 쌍과 관련된 이벤트를 표시합니다.

. 노드에 대한 다른 세부 정보를 보려면 적절한 작업을 수행합니다.
+
[cols="2*"]
|===
| 보기... | 클릭... 


 a| 
디스크 쉘프 세부 정보
 a| 
디스크 쉘프 *.



 a| 
포트 관련 정보입니다
 a| 
포트 *.

|===


자세한 내용은 다음을 참조하십시오.

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["성능: 모든 노드 보기"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["노드 및 애그리게이트 가용 IOPS 값 보기"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["사용된 노드 및 총 성능 용량 값 보기"]

