---
permalink: health-checker/task_view_detailed_security_status_for_clusters_and_svms.html 
sidebar: sidebar 
keywords: view, cluster security status, svm security status, volume encryption status 
summary: 보안 페이지에는 모든 클러스터에 대한 높은 수준의 보안 상태 및 개별 클러스터에 대한 자세한 보안 상태가 표시됩니다. 상세 클러스터 상태에는 클러스터 규정 준수, SVM 규정 준수, 볼륨 암호화 준수가 포함됩니다. 
---
= 클러스터 및 스토리지 VM에 대한 자세한 보안 상태 보기
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 페이지에는 모든 클러스터에 대한 높은 수준의 보안 상태 및 개별 클러스터에 대한 자세한 보안 상태가 표시됩니다.

시스템 관리자는 * 보안 * 페이지를 사용하여 데이터 센터 및 사이트 수준에서 ONTAP 클러스터와 스토리지 VM의 보안 강도를 파악할 수 있습니다.

정의된 매개 변수를 기반으로 정보를 수집 및 분석하여 모니터링된 클러스터 및 스토리지 VM에서 의심스러운 동작 또는 승인되지 않은 시스템 변경을 감지할 수 있습니다.

상세 클러스터 상태에는 클러스터 규정 준수, SVM 규정 준수, 볼륨 암호화 준수가 포함됩니다.

클러스터/보안 세부 정보 페이지는 글로벌 FIPS, Telnet, 비보안 SSH 설정, 로그인 배너, 네트워크 시간 프로토콜 등의 보안 매개 변수를 확인하여 클러스터의 보안 규정 준수에 대한 기본 보기를 제공합니다. AutoSupport HTTPS 전송 및 기본 관리자.

스토리지 VM/보안 세부 정보 페이지는 스토리지 VM, 클러스터, 로그인 배너, 감사 로그, 비보안 SSH 설정 등의 보안 매개 변수를 확인하여 스토리지 VM의 보안 규정 준수에 대한 기본 보기를 제공합니다.

클러스터 및 스토리지 VM 세부 정보 페이지에서도 보안 규정 준수 보고서를 생성, 예약 및 다운로드할 수 있습니다.

보안 대시보드 * 에서 * 클러스터 규정 준수 * 및 * 스토리지 VM 규정 준수 * 카드의 * 보고서 보기 * 를 클릭합니다.

.단계
. 왼쪽 탐색 창에서 * 대시보드 * 를 클릭합니다.
. 모니터링되는 모든 클러스터에 대한 보안 상태를 볼 것인지 또는 단일 클러스터에 대한 보안 상태를 볼 것인지 여부에 따라 * All Clusters * 를 선택하거나 드롭다운 메뉴에서 단일 클러스터를 선택합니다.
. Security * 패널에서 오른쪽 화살표를 클릭합니다.
+
보안 페이지에는 다음 정보가 표시됩니다.

+
** 클러스터 보안 상태(규정을 준수하거나 준수하지 않는 클러스터 수)
** SVM 보안 상태(규정을 준수하거나 준수하지 않는 SVM 수)
** 볼륨 암호화 상태(암호화되거나 암호화되지 않은 볼륨 수)
** 각 클러스터에서 사용 중인 클러스터 인증 방법입니다


. 을 참조하십시오 http://www.netapp.com/us/media/tr-4569.pdf["ONTAP 9에 대한 NetApp 보안 강화 가이드"] 모든 클러스터, SVM 및 볼륨을 NetApp 보안 권장 사항을 준수하는 방법에 대한 지침은 를 참조하십시오.

