---
permalink: health-checker/task_view_cluster_list_and_details.html 
sidebar: sidebar 
keywords: view, cluster list, details 
summary: '상태: 모든 클러스터 보기를 사용하여 클러스터의 인벤토리를 볼 수 있습니다. Capacity:All Clusters 보기를 사용하면 모든 클러스터의 스토리지 용량 및 활용도에 대한 요약된 정보를 볼 수 있습니다.' 
---
= 클러스터 목록 및 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태: 모든 클러스터 보기를 사용하여 클러스터의 인벤토리를 볼 수 있습니다. Capacity:All Clusters 보기를 사용하면 모든 클러스터의 스토리지 용량 및 활용도에 대한 요약된 정보를 볼 수 있습니다.

* 필요한 것 *

운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

또한 클러스터 상태, 용량, 구성, LIF, 노드 등과 같은 개별 클러스터에 대한 세부 정보를 볼 수 있습니다. 클러스터/상태 세부 정보 페이지를 사용하여 해당 클러스터의 디스크를 확인합니다.

상태: 모든 클러스터 보기, 용량: 모든 클러스터 보기 및 클러스터/상태 세부 정보 페이지의 세부 정보를 통해 스토리지를 계획할 수 있습니다. 예를 들어 새 Aggregate를 프로비저닝하기 전에 Health: All Clusters 보기에서 특정 클러스터를 선택하고 용량 세부 정보를 확인하여 클러스터에 필요한 공간이 있는지 확인할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 * 스토리지 * > * 클러스터 * 를 클릭합니다.
. 보기 메뉴에서 * 상태: 모든 클러스터 * 보기를 선택하여 상태 정보를 보거나 * 용량: 모든 클러스터 * 보기를 선택하여 모든 클러스터의 스토리지 용량 및 활용도에 대한 세부 정보를 봅니다.
. 클러스터 이름을 클릭하면 * Cluster/Health * 세부 정보 페이지에서 클러스터의 전체 세부 정보를 볼 수 있습니다.


* 관련 정보 *

* link:../health-checker/reference_health_cluster_details_page.html["클러스터/상태 세부 정보 페이지"]
* link:../performance-checker/performance-view-all.html#performance-all-clusters-view["성능: 모든 클러스터 보기"]
* link:../storage-mgmt/task_monitor_metrocluster_configurations.html["MetroCluster 구성 모니터링"]
* link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["클러스터 및 스토리지 VM의 보안 상태 보기"]
* link:../health-checker/concept_what_security_criteria_is_being_evaluated.html["평가 대상 보안 기준"]

