---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: 하나 이상의 볼륨에 대한 볼륨 용량, 증가, 할당량 및 공간 예비 공간에 대한 상태 임계값 설정을 편집할 수 있습니다. 임계값이 초과되면 알림이 생성되고 알림이 수신됩니다. 이러한 알림은 생성된 이벤트를 기반으로 예방 조치를 취하는 데 도움이 됩니다. 
---
= 개별 볼륨 상태 임계값 설정 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 이상의 볼륨에 대한 볼륨 용량, 증가, 할당량 및 공간 예비 공간에 대한 상태 임계값 설정을 편집할 수 있습니다. 임계값이 초과되면 알림이 생성되고 알림이 수신됩니다. 이러한 알림은 생성된 이벤트를 기반으로 예방 조치를 취하는 데 도움이 됩니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

임계값 변경에 따라 다음 모니터링 주기에서 이벤트가 생성되거나 폐기됩니다.

볼륨에 대해 Autogrow를 사용하도록 설정한 경우 원래 볼륨 크기를 기준으로 하지 않고 자동으로 설정된 최대 볼륨 크기에 따라 용량 임계값이 위반된 것으로 간주됩니다.

[NOTE]
====
스냅샷 복사본 1000개의 기본값은 ONTAP 버전이 9.4 이상인 경우 FlexVol 볼륨에만, ONTAP 버전이 9.8 이상인 경우 FlexGroup 볼륨에만 적용됩니다. 이전 버전의 ONTAP 소프트웨어와 함께 설치된 클러스터의 경우 최대 250개의 스냅샷 복사본이 볼륨당 가능합니다. 이전 버전에서는 Unified Manager가 이 1000번(및 1000에서 250번 사이의 숫자)을 250으로 해석합니다. 즉, 스냅샷 복사본 수가 250개에 도달하면 계속 이벤트를 받게 됩니다. 이러한 이전 버전에 대해 이 임계값을 250개 미만으로 설정하려면 여기에서 상태: 모든 볼륨 보기 또는 볼륨/상태 세부 정보 페이지에서 임계값을 250개 이하로 설정해야 합니다.

====
.단계
. 왼쪽 탐색 창에서 * 스토리지 * > * 볼륨 * 을 클릭합니다.
. 상태: 모든 볼륨 * 보기에서 하나 이상의 볼륨을 선택한 다음 * 임계값 편집 * 을 클릭합니다.
. 볼륨 임계값 편집 * 대화 상자에서 적절한 확인란을 선택한 다음 설정을 수정하여 용량, 스냅샷 복사본, qtree 할당량, 증가 또는 inode 중 하나의 임계값 설정을 편집합니다.
. 저장 * 을 클릭합니다.


* 관련 정보 *

link:../config/task_add_users.html["사용자 추가"]
