---
permalink: health-checker/task_define_schedule_for_snapshot_backups.html 
sidebar: sidebar 
keywords: define, backup, schedule, linux, windows, snapshot copy, copies 
summary: Unified Manager UI를 사용하여 Unified Manager 스냅샷 복사본이 생성되는 일정을 구성할 수 있습니다. 
---
= Linux 및 Windows에 대한 백업 일정 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager UI를 사용하여 Unified Manager 스냅샷 복사본이 생성되는 일정을 구성할 수 있습니다.

* 필요한 것 *

* 운영자, 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 스냅샷을 생성할 대상을 식별하려면 유지보수 콘솔에서 스냅샷 복사본을 생성하기 위한 설정을 구성해야 합니다.


Snapshot 복사본은 몇 분 내에 생성되며 Unified Manager 데이터베이스는 몇 초 동안만 잠깁니다.

[NOTE]
====
새 클러스터를 추가한 후 처음 15일 동안 수행된 백업은 성능 기록 데이터를 가져올 정도로 정확하지 않을 수 있습니다.

====
.단계
. 왼쪽 탐색 창에서 * 일반 * > * 데이터베이스 백업 * 을 클릭합니다.
. 데이터베이스 백업 * 페이지에서 * 백업 설정 * 을 클릭합니다.
. Retention Count * 필드에 유지할 최대 스냅샷 복사본 수를 입력합니다.
+
보존 수의 기본값은 10입니다. 최대 스냅샷 복사본 수는 클러스터의 ONTAP 소프트웨어 버전에 따라 결정됩니다. 이 필드를 비워 두면 ONTAP 버전에 관계없이 최대값을 구현할 수 있습니다.

. Scheduled Daily * 또는 * Scheduled Weekly * 버튼을 선택한 후 일정 세부 정보를 지정합니다.
. 적용 * 을 클릭합니다.


스냅샷 복사본은 일정에 따라 생성됩니다. 데이터베이스 백업 페이지에서 사용 가능한 백업 파일을 볼 수 있습니다.

이 볼륨과 스냅샷의 중요성으로 인해 이 볼륨에 대해 한두 개의 알림을 생성하여 다음 중 하나가 발생할 때 알림을 받을 수 있습니다.

* 볼륨 공간이 90% 찼습니다. 볼륨 공간이 가득 참 * 이벤트를 사용하여 경고를 설정합니다.
+
ONTAP System Manager 또는 ONTAP CLI를 사용하여 볼륨에 용량을 추가하면 Unified Manager 데이터베이스의 공간이 부족하지 않게 됩니다.

* 스냅샷 수가 최대 수에 근접합니다. 이벤트 * 너무 많은 Snapshot 복사본 * 을 사용하여 알림을 설정합니다.
+
ONTAP System Manager 또는 ONTAP CLI를 사용하여 이전 스냅샷을 삭제할 수 있으므로 항상 새 스냅샷 복사본을 저장할 공간이 있습니다.



경고 설정 페이지에서 경고를 구성합니다.
