---
permalink: health-checker/task_view_fabricpool_capacity_information.html 
sidebar: sidebar 
keywords: view, fabricPool, cloud tier, mirror tier, capacity, information 
summary: 용량 및 성능 인벤토리에서 클러스터, 애그리게이트 및 볼륨의 FabricPool 용량 정보와 이러한 개체에 대한 세부 정보 페이지를 볼 수 있습니다. 이 페이지에는 미러 계층이 구성된 경우 FabricPool 미러 정보도 표시됩니다. 
---
= FabricPool 용량 정보 보기
:icons: font
:imagesdir: ../media/


[role="lead"]
용량 및 성능 인벤토리에서 클러스터, 애그리게이트 및 볼륨의 FabricPool 용량 정보와 이러한 개체에 대한 세부 정보 페이지를 볼 수 있습니다. 이 페이지에는 미러 계층이 구성된 경우 FabricPool 미러 정보도 표시됩니다.

이 페이지에는 로컬 성능 계층 및 클라우드 계층에서 사용 가능한 용량, 두 계층에서 사용 중인 용량, 애그리게이트가 클라우드 계층에 연결된 용량 등의 정보가 표시됩니다. 어떤 볼륨이 특정 정보를 클라우드 계층으로 이동하여 FabricPool 기능을 구현할지,

클라우드 계층이 다른 클라우드 공급자("미러 계층")로 미러링되면 두 클라우드 계층이 모두 애그리게이트/상태 세부 정보 페이지에 표시됩니다.

.단계
. 다음 중 하나를 수행합니다.
+
[cols="2*"]
|===
| 용량 정보를 보려면... | 수행할 작업... 


 a| 
클러스터
 a| 
.. Capacity: All Clusters(용량: 모든 클러스터) 보기에서 클러스터를 클릭합니다.
.. 클러스터/상태 세부 정보 페이지에서 * 구성 * 탭을 클릭합니다.
+
이 화면에는 이 클러스터가 연결된 모든 클라우드 계층의 이름이 표시됩니다.





 a| 
애그리게이트
 a| 
.. Capacity:All Aggregates 보기에서 Type 필드에 "SSD(FabricPool)" 또는 "HDD(FabricPool)"가 표시된 애그리게이트를 클릭합니다.
.. 집계/상태 세부 정보 페이지에서 * 용량 * 탭을 클릭합니다.
+
이 화면에는 클라우드 계층에서 사용된 총 용량이 표시됩니다.

.. 디스크 정보 * 탭을 클릭합니다.
+
이 화면에는 클라우드 계층의 이름과 사용된 용량이 표시됩니다.

.. Configuration * 탭을 클릭합니다.
+
이 화면에는 클라우드 계층의 이름과 클라우드 계층에 대한 기타 자세한 정보가 표시됩니다.





 a| 
볼륨
 a| 
.. Capacity:All Volumes 보기에서 "Tiering Policy" 필드에 정책 이름이 표시되는 볼륨을 클릭합니다.
.. 볼륨/상태 세부 정보 페이지에서 * 구성 * 탭을 클릭합니다.
+
이 화면에는 볼륨에 할당된 FabricPool 계층화 정책의 이름이 표시됩니다.



|===
. Workload Analysis * 페이지에서 * Capacity Trend * 영역에서 ""클라우드 계층 보기"를 선택하여 이전 달의 로컬 성능 계층과 클라우드 계층에서 사용되는 용량을 확인할 수 있습니다.


FabricPool Aggregate에 대한 자세한 내용은 _ONTAP 9 디스크 및 집계 전원 가이드_를 참조하십시오.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ONTAP 9 디스크 및 애그리게이트 전원 가이드"]
