---
permalink: health-checker/task_configure_global_volume_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, volume, health, threshold values 
summary: 모든 볼륨에 대한 글로벌 상태 임계값을 구성하여 모든 임계값 위반을 추적할 수 있습니다. 상태 임계값 위반에 대한 적절한 이벤트가 생성되고 이러한 이벤트를 기반으로 예방 조치를 취할 수 있습니다. 모니터링되는 모든 볼륨에 적용되는 임계값에 대한 Best Practice 설정을 기반으로 글로벌 값을 구성할 수 있습니다. 
---
= 글로벌 볼륨 상태 임계값을 구성하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 볼륨에 대한 글로벌 상태 임계값을 구성하여 모든 임계값 위반을 추적할 수 있습니다. 상태 임계값 위반에 대한 적절한 이벤트가 생성되고 이러한 이벤트를 기반으로 예방 조치를 취할 수 있습니다. 모니터링되는 모든 볼륨에 적용되는 임계값에 대한 Best Practice 설정을 기반으로 글로벌 값을 구성할 수 있습니다.

* 필요한 것 *

애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

대부분의 임계값 옵션에는 더 나은 모니터링을 위한 기본값이 있습니다. 그러나 환경의 요구 사항에 맞게 값을 변경할 수 있습니다.

볼륨에 대해 Autogrow를 사용하도록 설정한 경우 원래 볼륨 크기를 기준으로 하지 않고 자동으로 설정된 최대 볼륨 크기에 따라 용량 임계값이 위반된 것으로 간주됩니다.

[NOTE]
====
스냅샷 복사본 1000개의 기본값은 ONTAP 버전이 9.4 이상인 경우 FlexVol 볼륨에만, ONTAP 버전이 9.8 이상인 경우 FlexGroup 볼륨에만 적용됩니다. 이전 버전의 ONTAP 소프트웨어와 함께 설치된 클러스터의 경우 최대 250개의 스냅샷 복사본이 볼륨당 가능합니다. 이전 버전에서는 Unified Manager가 이 1000번(및 1000에서 250번 사이의 숫자)을 250으로 해석합니다. 즉, 스냅샷 복사본 수가 250개에 도달하면 계속 이벤트를 받게 됩니다. 이러한 이전 버전에 대해 이 임계값을 250개 미만으로 설정하려면 여기에서 상태: 모든 볼륨 보기 또는 볼륨/상태 세부 정보 페이지에서 임계값을 250개 이하로 설정해야 합니다.

====
.단계
. 왼쪽 탐색 창에서 * 이벤트 임계값 * > * 볼륨 * 을 클릭합니다.
. 용량, 스냅샷 복사본, qtree 할당량, 볼륨 증가, inode에 대한 적절한 임계값을 구성합니다.
. 저장 * 을 클릭합니다.


* 관련 정보 *

link:../config/task_add_users.html["사용자 추가"]
