---
permalink: install-vapp/concept_virtual_infrastructure_or_hardware_system_requirements.html 
sidebar: sidebar 
keywords: virtual, infrastructure, hardware, system, requirements, virtual appliance 
summary: 가상 인프라 또는 물리적 시스템에 Unified Manager를 설치하려면 메모리, CPU 및 디스크 공간에 대한 최소 요구사항을 충족해야 합니다. 
---
= 가상 인프라 및 하드웨어 시스템 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 인프라 또는 물리적 시스템에 Unified Manager를 설치하려면 메모리, CPU 및 디스크 공간에 대한 최소 요구사항을 충족해야 합니다.

다음 표에는 메모리, CPU 및 디스크 공간 리소스에 권장되는 값이 나와 있습니다. 이러한 값은 Unified Manager가 허용 가능한 성능 수준을 충족할 수 있도록 검증을 받았습니다.

[cols="2*"]
|===
| 하드웨어 구성 | 권장 설정 


 a| 
RAM
 a| 
12GB(최소 요구 사항 8GB)



 a| 
프로세서
 a| 
CPU 4개



 a| 
CPU 사이클 용량입니다
 a| 
총 9572MHz(최소 요구 사항 9572MHz)



 a| 
사용 가능한 디스크 공간
 a| 
* 5GB(씬 프로비저닝)
* 152GB(씩 프로비저닝)


|===
적은 용량의 메모리가 있는 시스템에 Unified Manager를 설치할 수 있지만 권장되는 12GB RAM을 사용하면 최적의 성능을 위해 충분한 메모리를 사용할 수 있으며, 따라서 시스템이 구성 증가에 따라 추가 클러스터 및 스토리지 오브젝트를 수용할 수 있습니다. Unified Manager가 구축된 VM에서 메모리 제한을 설정하지 말아야 하며, 시스템에서 할당된 메모리를 소프트웨어가 활용하지 못하는 기능(예: 풍선 벌루닝)을 사용하면 안 됩니다.

또한 Unified Manager의 두 번째 인스턴스를 설치하기 전에 Unified Manager의 단일 인스턴스에서 모니터링할 수 있는 노드 수에 제한이 있습니다. 자세한 내용은 을 참조하십시오 link:http://www.netapp.com/us/media/tr-4621.pdf["Unified Manager 모범 사례 가이드"]

메모리 페이지 스와핑은 시스템 및 관리 응용 프로그램의 성능에 부정적인 영향을 줍니다. 전체 호스트 활용률로 인해 CPU 리소스를 사용하지 않는 경우 성능이 저하될 수 있습니다.



== 전용 요구사항

Unified Manager를 설치하는 물리적 또는 가상 시스템은 Unified Manager에만 사용해야 하며 다른 애플리케이션과 공유해서는 안 됩니다. 다른 애플리케이션은 시스템 리소스를 소모하며 Unified Manager의 성능을 크게 줄일 수 있습니다.



== 백업에 필요한 공간 요구 사항

Unified Manager 백업 및 복원 기능을 사용하려면 "데이터" 디렉토리나 디스크에 150GB의 공간이 있도록 추가 용량을 할당합니다. 백업은 로컬 대상 또는 원격 대상에 쓸 수 있습니다. 모범 사례는 최소 150GB의 공간이 있는 Unified Manager 호스트 시스템 외부의 원격 위치를 식별하는 것입니다.



== 호스트 접속 구성 요구 사항

Unified Manager를 설치하는 물리적 시스템 또는 가상 시스템은 호스트 자체에서 호스트 이름을 성공적으로 "핑"할 수 있도록 구성해야 합니다. IPv6 구성의 경우 Unified Manager 설치가 성공적으로 수행되도록 호스트 이름에 대한 ping6(ping6)이 성공했는지 확인해야 합니다.

호스트 이름(또는 호스트 IP 주소)을 사용하여 제품 웹 UI에 액세스할 수 있습니다. 배포 중에 네트워크에 대한 정적 IP 주소를 구성한 경우 네트워크 호스트의 이름을 지정합니다. DHCP를 사용하여 네트워크를 구성한 경우 DNS에서 호스트 이름을 얻어야 합니다.

사용자가 FQDN(정규화된 도메인 이름) 또는 IP 주소를 사용하는 대신 짧은 이름을 사용하여 Unified Manager에 액세스할 수 있도록 하려는 경우 네트워크 구성에서 이 짧은 이름을 유효한 FQDN으로 해석해야 합니다.
