---
permalink: install-vapp/task_upgrade_unified_manager_virtual_appliance_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager, virtual, appliance 
summary: Unified Manager 가상 어플라이언스를 업그레이드할 수 있습니다 
---
= Unified Manager 가상 어플라이언스 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 가상 어플라이언스를 릴리스 9.9 또는 9.10에서 9.11로 업그레이드할 수 있습니다.

* 필요한 것 *

다음을 확인합니다.

* 업그레이드 파일인 ISO 이미지를 NetApp Support 사이트에서 다운로드했습니다.
* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구사항을 충족합니다.
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["가상 인프라 요구 사항"]

+
link:reference_vmware_software_and_installation_requirements.html["VMware 소프트웨어 및 설치 요구 사항"]

* vSphere 6.5 이상 사용자의 경우 VMware Remote Console(VMRC)을 설치했습니다.
* 업그레이드하는 동안 성능 데이터를 13개월 동안 유지하기 위한 이전 기본 설정을 유지할지 아니면 6개월로 변경할지 묻는 메시지가 표시될 수 있습니다. 확인 시, 기록 성능 데이터는 6개월 후에 삭제됩니다.
* 다음 정보가 있습니다.
+
** NetApp Support 사이트의 로그인 자격 증명
** VMware vCenter Server 및 vSphere Web Client에 액세스하기 위한 자격 증명
** Unified Manager 유지보수 사용자의 자격 증명




업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없습니다. Unified Manager를 업그레이드하기 전에 실행 중인 작업을 완료해야 합니다.

Workflow Automation과 Unified Manager가 페어링된 경우 Workflow Automation에서 호스트 이름을 수동으로 업데이트해야 합니다.

.단계
. vSphere Client에서 * Home * > * Inventory * > * VMs and Templates * 를 클릭합니다.
. Unified Manager 가상 어플라이언스가 설치된 가상 머신(VM)을 선택합니다.
. Unified Manager VM이 실행 중인 경우 * 요약 * > * 명령 * > * 게스트 종료 * 로 이동합니다.
. 애플리케이션 정합성 보장 백업을 생성하기 위해 Unified Manager VM의 스냅샷 또는 클론 같은 백업 복사본을 생성합니다.
. vSphere Client에서 Unified Manager VM의 전원을 켭니다.
. VMware Remote Console을 시작합니다.
. CDROM * 아이콘을 클릭하고 * 디스크 이미지 파일에 연결 (.iso) * 을 선택합니다.
. 'ActiveIQUnifiedManager-<version>-virtual-update.iso' 파일을 선택하고 * Open * 을 클릭합니다.
. Console * 탭을 클릭합니다.
. Unified Manager 유지보수 콘솔에 로그인합니다.
. 주 메뉴에서 * 업그레이드 * 를 선택합니다.
+
업그레이드 프로세스 중에 Unified Manager를 사용할 수 없으며 작업이 완료된 후 다시 시작된다는 메시지가 표시됩니다.

. 계속하려면 y를 입력하십시오.
+
가상 어플라이언스가 상주하는 가상 머신을 백업하도록 알리는 경고가 표시됩니다.

. 계속하려면 y를 입력하십시오.
+
업그레이드 프로세스와 Unified Manager 서비스를 다시 시작하는 데 몇 분 정도 걸릴 수 있습니다.

. 계속하려면 아무 키나 누르십시오.
+
유지보수 콘솔에서 자동으로 로그아웃됩니다.

. * 선택 사항: * 유지보수 콘솔에 로그인하여 Unified Manager 버전을 확인합니다.


업그레이드된 버전의 Unified Manager를 사용하려면 웹 UI에 로그인할 수 있습니다. UI에서 작업을 수행하기 전에 검색 프로세스가 완료될 때까지 기다려야 합니다.
