---
permalink: install-windows/reference_windows_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: windows, software, installation, requirements, system 
summary: Windows에 Unified Manager를 성공적으로 설치하려면 Unified Manager가 설치된 시스템이 소프트웨어 요구사항을 충족하는지 확인해야 합니다. 
---
= Windows 소프트웨어 및 설치 요구 사항
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Windows에 Unified Manager를 성공적으로 설치하려면 Unified Manager가 설치된 시스템이 소프트웨어 요구사항을 충족하는지 확인해야 합니다.



== 운영 체제 소프트웨어

Unified Manager는 * Microsoft Windows Server 2016 Standard 및 Datacenter Edition * Microsoft Windows Server 2019 Standard 및 Datacenter Edition에 설치할 수 있습니다

Unified Manager는 64비트 Windows 운영 체제에서 다음 언어로 지원됩니다.

* 영어
* 일본어
* 중국어 간체


지원되는 Windows 버전의 전체 최신 목록은 상호 운용성 매트릭스 를 참조하십시오.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

서버는 Unified Manager 실행 전용으로 사용되어야 합니다. 서버에 다른 응용 프로그램을 설치할 수 없습니다.



== 타사 소프트웨어

다음 타사 패키지는 Unified Manager와 함께 번들로 제공됩니다. 타사 패키지가 시스템에 설치되어 있지 않은 경우, Unified Manager에서 이를 설치의 일부로 설치합니다.

* Microsoft Visual C&#43;&#43; 2015 재배포 가능 패키지 버전 14.26.28720.3
* Microsoft Visual C&#43;&#43; Visual Studio 2013 버전 12.0.40660.0용 재배포 가능 패키지
* MySQL Community Edition 버전 8.0.27
* Python 3.9.x
* OpenJDK 버전 11.0.12
* p7zip 버전 18.05 이상


[NOTE]
====
Unified Manager 9.5부터 OpenJDK는 Unified Manager 설치 패키지에 제공되어 자동으로 설치됩니다. Oracle Java는 Unified Manager 9.5부터 지원되지 않습니다.

====
MySQL이 사전 설치된 경우 다음 사항을 확인해야 합니다.

* 기본 포트를 사용하고 있습니다.
* 샘플 데이터베이스가 설치되지 않았습니다.
* 서비스명은 MYSQL8.


Unified Manager는 WildFly 웹 서버에 구축되어 있습니다. WildFly 19.0.0은 Unified Manager에서 번들로 제공되며 구성됩니다.

[NOTE]
====
타사 소프트웨어를 업그레이드하기 전에 Unified Manager를 실행 중인 인스턴스를 종료해야 합니다. 타사 소프트웨어 설치가 완료되면 Unified Manager를 다시 시작할 수 있습니다.

====


== 설치 요구 사항

* Microsoft .NET 4.5.2 이상이 설치되어 있어야 합니다.
* 임시 디렉터리는 설치 파일 압축을 풀 수 있도록 2GB의 디스크 공간으로 구성해야 합니다. 디렉토리가 생성되었는지 확인하려면 명령줄 인터페이스에서 ' echo %temp% ' 명령을 실행합니다
* Unified Manager MSI 파일을 캐시하려면 Windows 드라이브에 2GB의 디스크 공간을 예약해야 합니다.
* Unified Manager를 설치할 Microsoft Windows Server는 호스트 이름 및 FQDN에 대한 "ping" 응답이 성공하도록 FQDN(정규화된 도메인 이름)으로 구성해야 합니다.
* Microsoft IIS Worldwide 웹 게시 서비스를 비활성화하고 포트 80 및 443이 사용 가능한지 확인해야 합니다.
* 설치 중에 ""Windows Installer RDS 호환성""에 대한 원격 데스크톱 세션 호스트 설정이 비활성화되어 있는지 확인해야 합니다.
* UDP 포트 514는 사용 가능한 상태여야 하며 다른 서비스에서 사용하지 않아야 합니다.


[NOTE]
====
Unified Manager 설치 프로그램은 Windows Defender에서 다음 제외 사항을 구성합니다.

* Unified Manager 데이터 디렉토리입니다
* Unified Manager 설치 디렉토리
* MySQL 데이터 디렉토리


서버에 다른 바이러스 백신 스캐너가 설치되어 있는 경우 이러한 제외 항목을 수동으로 구성해야 합니다.

====