---
permalink: install-windows/task_upgrade_openjdk_on_windows_ocum.html 
sidebar: sidebar 
keywords: openjdk, jre, upgrade 
summary: Unified Manager가 설치된 Windows 서버에서 최신 버전의 OpenJDK로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 
---
= OpenJDK 업그레이드 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 설치된 Windows 서버에서 최신 버전의 OpenJDK로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다.

.시작하기 전에
Unified Manager가 설치된 시스템에 대한 Windows 관리자 권한이 있어야 합니다.

릴리스 제품군 내에서 OpenJDK 릴리스를 업데이트할 수 있습니다. 예를 들어 OpenJDK 11.0.16에서 OpenJDK 11.0.18로 업그레이드할 수 있지만 OpenJDK 11에서 OpenJDK 12로 직접 업데이트할 수는 없습니다.

.단계
. Unified Manager 호스트 시스템에서 admin 사용자로 로그인합니다.
. OpenJDK 사이트에서 대상 시스템으로 적절한 버전의 OpenJDK(64비트)를 다운로드합니다.
+
예를 들어, 다운로드 를 선택합니다 `jdk-11.0.18_windows-x64_bin.zip from https://www.oracle.com/in/java/technologies/javase/jdk11-archive-downloads.html`.

+

NOTE:  파일을 다운로드하려면 Oracle 계정이 필요합니다. Oracle 계정이 없는 경우 로 이동합니다 link:https://login.oracle.com/mysso/signon.jsp?request_id=007["Oracle 계정 로그인"] 페이지를 만듭니다.

. Windows 서비스 콘솔을 사용하여 다음 Unified Manager 서비스를 중지합니다.
+
** NetApp Active IQ 구입 서비스(Ocie-au)
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)


. zip 파일을 확장합니다.
. 결과로 생성된 디렉토리와 파일을 복사합니다 `jdk` 디렉터리(예: `jdk-11.0.18` Java가 설치된 위치로 이동합니다. 예: `C:\Program Files\NetApp\JDK\`
. Windows 서비스 콘솔을 사용하여 Unified Manager 서비스를 시작합니다.
+
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)
** NetApp Active IQ 구입 서비스(Ocie-au)



