---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 설치 중에 설정된 인스턴스별 JBoss 암호를 재설정할 수 있습니다. 사이트에 Unified Manager 설치 설정을 재정의하는 데 이 보안 기능이 필요한 경우 암호를 선택적으로 재설정할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다. 
---
= JBoss 암호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 중에 설정된 인스턴스별 JBoss 암호를 재설정할 수 있습니다. 사이트에 Unified Manager 설치 설정을 재정의하는 데 이 보안 기능이 필요한 경우 암호를 선택적으로 재설정할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다.

* 필요한 것 *

* Unified Manager가 설치된 시스템에 대한 Windows 관리자 권한이 있어야 합니다.
* MySQL root 사용자의 암호가 있어야 합니다.
* NetApp에서 제공한 password.bat" 스크립트에 디렉토리에서 액세스할 수 있어야 합니다
+
'C:\Program Files\NetApp\Essentials\bin'을 선택합니다.



.단계
. Unified Manager 호스트 시스템에서 admin 사용자로 로그인합니다.
. Windows 서비스 콘솔을 사용하여 다음 Unified Manager 서비스를 중지합니다.
+
** NetApp Active IQ 구입 서비스(Ocie-au)
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)


. password.bat 스크립트를 실행하여 암호 변경 프로세스를 시작합니다.
+
'C:\Program Files\NetApp\Essentials\bin> password.bat resetJBossPassword'를 참조하십시오

. 메시지가 표시되면 MySQL root 사용자 암호를 입력합니다.
. 메시지가 표시되면 새 JBoss 사용자 암호를 입력한 다음 확인을 위해 다시 입력합니다.
+
암호는 8자에서 16자 사이여야 하며 숫자, 대문자, 소문자 및 다음 특수 문자 중 하나 이상을 포함해야 합니다.

+
'+!@%^ * -_+=[]:<>.?/~+'

. 스크립트가 완료되면 Windows 서비스 콘솔을 사용하여 Unified Manager 서비스를 시작합니다.
+
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)
** NetApp Active IQ 구입 서비스(Ocie-au)


. 모든 서비스가 시작되면 Unified Manager UI에 로그인할 수 있습니다.

