---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 감사 로그를 사용하여 감사 로그가 손상되었는지 여부를 감지할 수 있습니다. 사용자가 수행하는 모든 작업은 감사 로그에 모니터링 및 기록됩니다. 감사는 Active IQ Unified Manager의 모든 사용자 인터페이스 및 공개적으로 노출된 API 기능에 대해 수행됩니다. 
---
= 로깅 감사
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그를 사용하여 감사 로그가 손상되었는지 여부를 감지할 수 있습니다. 사용자가 수행하는 모든 작업은 감사 로그에 모니터링 및 기록됩니다. 감사는 Active IQ Unified Manager의 모든 사용자 인터페이스 및 공개적으로 노출된 API 기능에 대해 수행됩니다.

감사 로그: 파일 보기를 사용하여 Active IQ Unified Manager에서 사용 가능한 모든 감사 로그 파일을 보고 액세스할 수 있습니다. Audit Log: File View(감사 로그: 파일 보기)의 파일은 생성 날짜를 기준으로 나열됩니다. 이 보기에는 설치 또는 업그레이드 시 캡처된 모든 감사 로그의 정보가 시스템에 있는 것으로 표시됩니다. Unified Manager에서 작업을 수행할 때마다 정보가 업데이트되고 로그에서 사용할 수 있습니다. 각 로그 파일의 상태는 로그 파일의 변조 또는 삭제를 감지하기 위해 능동적으로 모니터링되는 ""파일 무결성 상태"" 속성을 사용하여 캡처됩니다. 시스템에서 감사 로그를 사용할 수 있는 경우 감사 로그에 다음 상태 중 하나가 포함될 수 있습니다.

[cols="2*"]
|===
| 상태 | 설명 


 a| 
활성
 a| 
로그가 현재 로그되고 있는 파일입니다.



 a| 
정상
 a| 
비활성, 압축 및 시스템에 저장된 파일입니다.



 a| 
변조되었습니다
 a| 
파일을 수동으로 편집한 사용자에 의해 손상된 파일입니다.



 a| 
manual_delete(수동 삭제)
 a| 
권한이 있는 사용자가 삭제한 파일입니다.



 a| 
롤오버_삭제
 a| 
롤링 구성 정책에 따라 롤오프로 인해 삭제된 파일입니다.



 a| 
Unexpected_delete를 선택합니다
 a| 
알 수 없는 이유로 삭제된 파일입니다.

|===
감사 로그 페이지에는 다음과 같은 명령 단추가 있습니다.

* 구성
* 삭제
* 다운로드


delete * 버튼을 사용하면 Audit Logs 보기에 나열된 감사 로그를 삭제할 수 있습니다. 감사 로그를 삭제하고 나중에 유효한 삭제를 확인하는 데 도움이 되는 파일을 삭제할 이유를 선택적으로 제공할 수 있습니다. Reason 열에는 삭제 작업을 수행한 사용자의 이름과 함께 이유가 나열됩니다.

[NOTE]
====
로그 파일을 삭제하면 시스템에서 파일이 삭제되지만 DB 테이블의 항목은 삭제되지 않습니다.

====
감사 로그 섹션의 * 다운로드 * 버튼을 사용하여 Active IQ Unified Manager에서 감사 로그를 다운로드하고 감사 로그 파일을 내보낼 수 있습니다. "보통" 또는 "무단 변경"으로 표시된 파일은 압축된 .gzip 형식으로 다운로드됩니다.

전체 AutoSupport 번들이 생성되면 지원 번들에는 아카이빙 및 액티브 감사 로그 파일이 모두 포함됩니다. 하지만 간단한 지원 번들이 생성되면 활성 감사 로그만 포함됩니다. 보관된 감사 로그는 포함되지 않습니다.
