---
permalink: config/concept_install_https_certificate_generated_using_external_tools.html 
sidebar: sidebar 
keywords: install, HTTPS, certificate, generated from external tools 
summary: 자체 서명 또는 CA 서명된 인증서를 설치할 수 있으며 OpenSSL, BoringSSL, LetsEncrypt와 같은 외부 도구를 사용하여 생성할 수 있습니다. 
---
= 외부 도구를 사용하여 생성된 HTTPS 인증서 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자체 서명 또는 CA 서명된 인증서를 설치할 수 있으며 OpenSSL, BoringSSL, LetsEncrypt와 같은 외부 도구를 사용하여 생성할 수 있습니다.

이러한 인증서는 외부에서 생성된 공개-개인 키 쌍이므로 인증서 체인과 함께 개인 키를 로드해야 합니다. 허용된 키 쌍 알고리즘은 "RSA"와 "EC"입니다. HTTPS 인증서 설치 * 옵션은 일반 섹션의 HTTPS 인증서 페이지에서 사용할 수 있습니다. 업로드하는 파일은 다음과 같은 입력 형식이어야 합니다.

. Active IQ Unified Manager 호스트에 속한 서버의 개인 키입니다
. 개인 키와 일치하는 서버의 인증서입니다
. 위의 인증서에 서명하는 데 사용되는 루트까지 CA의 인증서가 반대입니다




== EC 키 쌍을 사용하여 인증서를 로드하는 형식입니다

허용되는 곡선은 프리메256v1, 에코384r1입니다. 외부에서 생성된 EC 쌍이 있는 인증서 샘플:

[listing]
----
 -----BEGIN EC PRIVATE KEY-----
<EC private key of Server>
-----END EC PRIVATE KEY-----
----
[listing]
----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----


== RSA 키 쌍을 사용하여 인증서를 로드하는 형식입니다

호스트 인증서에 속하는 RSA 키 쌍에 허용되는 키 크기는 2048, 3072 및 4096입니다. 외부에서 생성된 * RSA 키 쌍이 포함된 인증서 *:

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
 <RSA private key of Server>
 -----END RSA PRIVATE KEY-----
 -----BEGIN CERTIFICATE-----
 <Server certificate>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #1 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Intermediate certificate #2 (if present)>
 -----END CERTIFICATE-----
 -----BEGIN CERTIFICATE-----
 <Root signing certificate>
 -----END CERTIFICATE-----
----
인증서가 업로드되면 Active IQ Unified Manager 인스턴스를 다시 시작하여 변경 내용을 적용해야 합니다.



== 외부에서 생성된 인증서를 업로드하는 동안 확인합니다

시스템은 외부 툴을 사용하여 생성된 인증서를 업로드하는 동안 검사를 수행합니다. 확인 중 하나라도 실패하면 인증서가 거부됩니다. 또한 제품 내에서 CSR에서 생성된 인증서 및 외부 도구를 사용하여 생성된 인증서에 대한 유효성 검사가 포함되어 있습니다.

* 입력의 개인 키는 입력의 호스트 인증서에 대해 유효성이 검사됩니다.
* 호스트 인증서의 CN(일반 이름)이 호스트의 FQDN에 대해 확인됩니다.
* 호스트 인증서의 CN(일반 이름)은 비어 있거나 비어 있어서는 안 되며 localhost로 설정해서는 안 됩니다.
* 유효 시작 날짜는 미래일 수 없으며 인증서의 유효 기간이 과거일 수 없습니다.
* 중간 CA 또는 CA가 있는 경우 인증서의 유효 시작 날짜는 미래일 수 없으며 유효 기간 만료 날짜는 과거일 수 없습니다.


[NOTE]
====
입력의 개인 키는 암호화해서는 안 됩니다. 암호화된 개인 키가 있으면 시스템에서 거부됩니다.

====
예 1

[listing]
----
----BEGIN ENCRYPTED PRIVATE KEY-----
<Encrypted private key>
-----END ENCRYPTED PRIVATE KEY-----
----
예 2

[listing]
----
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END RSA PRIVATE KEY-----
----
예 3

[listing]
----
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
<content here>
-----END EC PRIVATE KEY-----
----