---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: '정책 기반 스토리지 관리 옵션을 사용하면 SLO(서비스 수준 목표)를 기준으로 스토리지를 관리할 수 있습니다. 이 옵션은 기본적으로 활성화되어 있습니다.' 
---
= 정책 기반 스토리지 관리 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정책 기반 스토리지 관리 * 옵션을 사용하면 서비스 수준 목표(SLO)를 기준으로 스토리지를 관리할 수 있습니다. 이 옵션은 기본적으로 활성화되어 있습니다.

이 기능을 활성화하면 Active IQ Unified Manager 인스턴스에 추가된 ONTAP 클러스터에서 스토리지 워크로드를 프로비저닝하고 할당된 성능 서비스 수준 및 스토리지 효율성 정책을 기반으로 이러한 워크로드를 관리할 수 있습니다.

이 기능은 * 일반 * > * 기능 설정 * > * 정책 기반 스토리지 관리 * 에서 활성화 또는 비활성화할 수 있습니다. 이 기능을 활성화하면 다음 페이지를 작동 및 모니터링할 수 있습니다.

* 프로비저닝(스토리지 워크로드 프로비저닝)
* * 정책 * > * 성능 서비스 수준 *
* * 정책 * > * 스토리지 효율성 *
* 클러스터 설정 페이지의 성능 서비스 수준별로 관리되는 작업 부하 열
* Dashboard * 의 워크로드 성능 패널입니다


화면에서 성능 서비스 수준 및 스토리지 효율성 정책을 생성하고 스토리지 워크로드를 프로비저닝할 수 있습니다. 또한, 할당된 성능 서비스 수준과 부적합 사항을 준수하는 스토리지 워크로드를 모니터링할 수 있습니다. 또한 워크로드 성능 및 워크로드 IOPS 패널을 사용하면 프로비저닝된 스토리지 워크로드를 기준으로 데이터 센터 전체의 클러스터에서 사용 가능한 총 용량 및 성능(IOPS)을 평가할 수 있습니다.

이 기능을 활성화한 후 Unified Manager REST API를 실행하여 이러한 기능 중 일부를 * Menu Bar * > * Help 버튼 * > * API Documentation * > * storage-provider * 범주에서 수행할 수 있습니다. 또는 호스트 이름 또는 IP 주소와 URL을 입력하여 REST API 페이지에 액세스할 수 있습니다. 형식은 +https://<hostname>/docs/api/+ 입니다

API에 대한 자세한 내용은 _Active IQ Unified Manager API 개발자 가이드_를 참조하십시오.

link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager API 개발자 가이드 를 참조하십시오"]
