---
permalink: config/reference_additional_menu_options.html 
sidebar: sidebar 
keywords: additional menu, options 
summary: 다음 메뉴 옵션을 사용하여 Unified Manager 서버에서 다양한 관리 작업을 수행할 수 있습니다. 
---
= 추가 메뉴 옵션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 메뉴 옵션을 사용하여 Unified Manager 서버에서 다양한 관리 작업을 수행할 수 있습니다.

다음 메뉴를 선택할 수 있습니다.

* * 서버 인증서 재설정 * 을 선택합니다
+
HTTPS 서버 인증서를 재생성합니다.

+
Unified Manager GUI에서 * 일반 * > * HTTPS 인증서 * > * HTTPS 인증서 다시 생성 * 을 클릭하여 서버 인증서를 다시 생성할 수 있습니다.

* * SAML 인증 비활성화 *
+
ID 공급자(IDP)가 Unified Manager GUI에 액세스하는 사용자에 대해 로그인 인증을 더 이상 제공하지 않도록 SAML 인증을 비활성화합니다. 이 콘솔 옵션은 일반적으로 IDP 서버 또는 SAML 구성 문제로 인해 사용자가 Unified Manager GUI에 액세스하지 못하게 되는 경우에 사용됩니다.

* * 외부 데이터 공급자 *
+
Unified Manager를 외부 데이터 공급자에 연결하는 옵션을 제공합니다. 연결을 설정하면 성능 데이터가 외부 서버로 전송되므로 스토리지 성능 전문가가 타사 소프트웨어를 사용하여 성능 메트릭을 차트로 작성할 수 있습니다. 다음 옵션이 표시됩니다.

+
** * Display Server Configuration * -- 외부 데이터 공급자에 대한 현재 연결 및 구성 설정을 표시합니다.
** * 서버 연결 추가/수정 * -- 외부 데이터 공급자에 대한 새 연결 설정을 입력하거나 기존 설정을 변경할 수 있습니다.
** * 서버 구성 수정 * -- 외부 데이터 공급자에 대한 새 구성 설정을 입력하거나 기존 설정을 변경할 수 있습니다.
** * 서버 연결 삭제 * -- 외부 데이터 공급자에 대한 연결을 삭제합니다.
+
연결이 삭제된 후 Unified Manager는 외부 서버와의 연결이 끊어집니다.



* * 백업 복원 *
+
자세한 내용은 의 항목을 참조하십시오 link:../health-checker/concept_manage_backup_and_restore_operations.html["백업 및 복원 작업 관리"].

* * 성능 폴링 간격 구성 *
+
Unified Manager가 클러스터에서 성능 통계 데이터를 수집하는 빈도를 구성할 수 있는 옵션을 제공합니다. 기본 수집 간격은 5분입니다.

+
대규모 클러스터의 컬렉션이 적시에 완료되지 않는 경우 이 간격을 10분 또는 15분으로 변경할 수 있습니다.

* * 응용 프로그램 포트 보기/변경 *
+
Unified Manager에서 보안에 필요한 경우 HTTP 및 HTTPS 프로토콜에 사용하는 기본 포트를 변경하는 옵션을 제공합니다. 기본 포트는 HTTP의 경우 80이고 HTTPS의 경우 443입니다.

* * MySQL 포트 3306 * 에 대한 액세스를 제어합니다
+
기본 MySQL 포트 3306에 대한 호스트 액세스를 제어합니다. 보안상의 이유로 Linux, Windows 및 VMware vSphere 시스템에 Unified Manager를 새로 설치하는 동안에만 이 포트를 통한 액세스가 localhost로 제한됩니다. 이 옵션을 사용하면 로컬 호스트 및 원격 호스트 간에 이 포트의 표시 여부를 전환할 수 있습니다. 즉, 사용자 환경에서 localhost만 사용하도록 설정된 경우 이 포트를 원격 호스트에서도 사용할 수 있도록 설정할 수 있습니다. 또는 모든 호스트에 대해 활성화된 경우 이 포트의 액세스를 localhost 전용으로 제한할 수 있습니다. 이전에 원격 호스트에서 액세스가 설정된 경우 구성은 업그레이드 시나리오에서 유지됩니다.

* * 종료 *
+
유지보수 콘솔 메뉴를 종료합니다.


