---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: HTTPS 인증서 다시 생성 대화 상자에서는 보안 정보를 사용자 지정한 다음 해당 정보로 새 HTTPS 인증서를 생성할 수 있습니다. 
---
= HTTPS 인증서 재생성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HTTPS 인증서 다시 생성 대화 상자에서는 보안 정보를 사용자 지정한 다음 해당 정보로 새 HTTPS 인증서를 생성할 수 있습니다.

현재 인증서 정보가 이 페이지에 나타납니다.

""현재 인증서 특성을 사용하여 재생성" 및 ""현재 인증서 특성 업데이트" 선택 항목을 사용하면 현재 정보로 인증서를 다시 생성하거나 새 정보로 인증서를 생성할 수 있습니다.

* * 일반 이름 *
+
필수 요소입니다. 보안하려는 FQDN(정규화된 도메인 이름)입니다.

+
Unified Manager 고가용성 구성에서 가상 IP 주소를 사용합니다.

* * 이메일 *
+
선택 사항. 조직에 연락할 이메일 주소. 일반적으로 인증서 관리자 또는 IT 부서의 이메일 주소입니다.

* * 회사 *
+
선택 사항. 일반적으로 회사의 통합 이름입니다.

* * 부서 *
+
선택 사항. 회사의 부서 이름입니다.

* * 시 *
+
선택 사항. 회사의 도시 위치입니다.

* * 시/도 *
+
선택 사항. 회사의 시/도 위치(약어로 표시되지 않음)입니다.

* * 국가 *
+
선택 사항. 회사의 국가 위치입니다. 이 코드는 일반적으로 해당 국가의 2자리 ISO 코드입니다.

* * 대체 이름 *
+
필수 요소입니다. 기존 localhost 또는 기타 네트워크 주소 외에 이 서버에 액세스하는 데 사용할 수 있는 추가, 비 기본 도메인 이름입니다. 각 대체 이름을 쉼표로 구분합니다.

+
인증서의 대체 이름 필드에서 로컬 식별 정보를 제거하려면 "'로컬 식별 정보 제외(예: localhost)'" 확인란을 선택합니다. 이 확인란을 선택하면 필드에 입력한 항목만 대체 이름 필드에 사용됩니다. 공백으로 두면 결과 인증서에 대체 이름 필드가 전혀 없습니다.

* * 키 크기(키 알고리즘: RSA) *
+
키 알고리즘은 RSA로 설정됩니다. 2048, 3072 또는 4096비트의 키 크기 중 하나를 선택할 수 있습니다. 기본 키 크기는 2048비트로 설정됩니다.

* * 유효 기간 *
+
기본 유효 기간은 397일입니다. 이전 버전에서 업그레이드한 경우 이전 인증서 유효성이 변경되지 않은 상태로 표시될 수 있습니다.



자세한 내용은 을 참조하십시오 link:../config/task_generate_an_https_security_certificate_ocf.html["HTTPS 인증서를 생성하는 중입니다"].
