---
permalink: config/task_add_authentication_servers.html 
sidebar: sidebar 
keywords: add, authentication servers 
summary: 인증 서버를 추가하고 관리 서버에서 원격 인증을 설정하여 인증 서버 내의 원격 사용자가 Unified Manager에 액세스할 수 있도록 할 수 있습니다. 
---
= 인증 서버를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인증 서버를 추가하고 관리 서버에서 원격 인증을 설정하여 인증 서버 내의 원격 사용자가 Unified Manager에 액세스할 수 있도록 할 수 있습니다.

.시작하기 전에
* 다음 정보를 사용할 수 있어야 합니다.
+
** 인증 서버의 호스트 이름 또는 IP 주소입니다
** 인증 서버의 포트 번호입니다


* 관리 서버가 인증 서버의 원격 사용자 또는 그룹을 인증할 수 있도록 원격 인증을 활성화하고 인증 서비스를 구성해야 합니다.
* 애플리케이션 관리자 역할이 있어야 합니다.


추가하려는 인증 서버가 동일한 데이터베이스를 사용하는 고가용성(HA) 쌍의 일부인 경우 파트너 인증 서버를 추가할 수도 있습니다. 이렇게 하면 인증 서버 중 하나에 연결할 수 없을 때 관리 서버가 파트너와 통신할 수 있습니다.

.단계
. 왼쪽 탐색 창에서 * 일반 * > * 원격 인증 * 을 클릭합니다.
. 보안 연결 사용 * 옵션을 활성화 또는 비활성화합니다.
+
[cols="2*"]
|===
| 원하는 작업 | 다음을 수행하십시오. 


 a| 
활성화
 a| 
.. 보안 연결 사용 * 옵션을 선택합니다.
.. Authentication Servers 영역에서 * Add * 를 클릭합니다.
.. Add Authentication Server 대화 상자에서 서버의 인증 이름 또는 IP 주소(IPv4 또는 IPv6)를 입력합니다.
.. 호스트 권한 부여 대화 상자에서 인증서 보기를 클릭합니다.
.. 인증서 보기 대화 상자에서 인증서 정보를 확인한 다음 * 닫기 * 를 클릭합니다.
.. 호스트 권한 부여 대화 상자에서 * 예 * 를 클릭합니다.
+
[NOTE]
====
보안 연결 인증 사용 * 옵션을 활성화하면 Unified Manager가 인증 서버와 통신하고 인증서를 표시합니다. Unified Manager는 보안 통신을 위한 기본 포트로 636을 사용하고 비보안 통신을 위한 포트 번호 389를 사용합니다.

====




 a| 
비활성화합니다
 a| 
.. 보안 연결 사용 * 옵션의 선택을 취소합니다.
.. Authentication Servers 영역에서 * Add * 를 클릭합니다.
.. Add Authentication Server 대화 상자에서 서버의 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)와 포트 세부 정보를 지정합니다.
.. 추가 * 를 클릭합니다.


|===
+
추가한 인증 서버가 Servers 영역에 표시됩니다.

. 테스트 인증을 수행하여 추가한 인증 서버에서 사용자를 인증할 수 있는지 확인합니다.

