---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: 이벤트가 생성되거나 이벤트가 사용자에게 할당될 때 알림을 보내도록 Unified Manager를 구성할 수 있습니다. 알림을 보내는 데 사용되는 SMTP 서버를 구성할 수 있으며, 알림 알림을 e-메일 또는 SNMP 트랩으로 보낼 수 있는 등 다양한 알림 메커니즘을 설정할 수 있습니다. 
---
= 이벤트 알림 설정을 구성하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트가 생성되거나 이벤트가 사용자에게 할당될 때 알림을 보내도록 Unified Manager를 구성할 수 있습니다. 알림을 보내는 데 사용되는 SMTP 서버를 구성할 수 있으며, 다양한 알림 메커니즘을 설정할 수 있습니다. 예를 들어, 알림 알림을 e-메일 또는 SNMP 트랩으로 보낼 수 있습니다.

* 필요한 것 *

다음 정보가 있어야 합니다.

* 알림 메시지가 전송되는 이메일 주소입니다
+
보낸 알림 알림의 ""보낸 사람" 필드에 이메일 주소가 나타납니다. 어떤 이유로든 이메일을 전달할 수 없는 경우 이 이메일 주소는 배달 불가능한 메일의 받는 사람으로도 사용됩니다.

* SMTP 서버 호스트 이름 및 서버에 액세스하기 위한 사용자 이름 및 암호
* SNMP 버전, 아웃바운드 트랩 포트, 커뮤니티 및 기타 필수 SNMP 구성 값과 함께 SNMP 트랩을 수신할 트랩 대상 호스트의 호스트 이름 또는 IP 주소입니다
+
여러 트랩 대상을 지정하려면 각 호스트를 쉼표로 구분합니다. 이 경우 버전 및 아웃바운드 트랩 포트와 같은 다른 모든 SNMP 설정은 목록의 모든 호스트에 대해 동일해야 합니다.



애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

.단계
. 왼쪽 탐색 창에서 * 일반 * > * 알림 * 을 클릭합니다.
. 알림 페이지에서 적절한 설정을 구성하고 * 저장 * 을 클릭합니다.
+
* 참고: *

+
** 보낸 사람 주소에 "+ActiveIQUnifiedManager@localhost.com+" 주소가 미리 입력된 경우, 모든 이메일 알림이 성공적으로 전송되도록 실제 작업 이메일 주소로 변경해야 합니다.
** SMTP 서버의 호스트 이름을 확인할 수 없는 경우 호스트 이름 대신 SMTP 서버의 IP 주소(IPv4 또는 IPv6)를 지정할 수 있습니다.



