---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: 감사 로그 구성 대화 상자에서 원격 로깅 사용 확인란을 선택하여 원격 감사 로깅을 활성화할 수 있습니다. 이 기능을 사용하여 감사 로그를 원격 Syslog 서버로 전송할 수 있습니다. 이렇게 하면 공간 제약 조건이 있을 때 감사 로그를 관리할 수 있습니다. 
---
= 감사 로그의 원격 로깅 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그 구성 대화 상자에서 * 원격 로깅 사용 * 확인란을 선택하여 원격 감사 로깅을 활성화할 수 있습니다. 이 기능을 사용하여 감사 로그를 원격 Syslog 서버로 전송할 수 있습니다. 이렇게 하면 공간 제약 조건이 있을 때 감사 로그를 관리할 수 있습니다.

감사 로그의 원격 로깅은 Active IQ Unified Manager 서버의 감사 로그 파일이 변조될 경우에 대비하여 변조 불가능한 백업을 제공합니다.

.단계
. 감사 로그 구성 * 대화 상자에서 * 원격 로깅 사용 * 확인란을 선택합니다.
+
원격 로깅을 구성하는 추가 필드가 표시됩니다.

. 연결할 원격 서버의 * HOSTNAME * 및 * 포트 * 를 입력합니다.
. server CA certificate * 필드에서 * browse * 를 클릭하여 대상 서버의 공용 인증서를 선택합니다.
+
인증서는 '.pem' 형식으로 업로드되어야 합니다. 이 인증서는 대상 Syslog 서버에서 받아야 하며 만료되지 않아야 합니다. 인증서는 선택한 "hostname"을 'subjectAltName'(SAN) 속성의 일부로 포함해야 합니다.

. * CHARSET *, * CONNECTION TIMEOUT *, * 재연결 지연 * 필드에 값을 입력합니다.
+
이러한 필드의 값은 밀리초 단위입니다.

. 필요한 Syslog 형식과 TLS 프로토콜 버전을 * format * 및 * protocol * 필드에서 선택합니다.
. 대상 Syslog 서버에 인증서 기반 인증이 필요한 경우 * 클라이언트 인증 활성화 * 확인란을 선택합니다.
+
감사 로그 구성을 저장하기 전에 클라이언트 인증 인증서를 다운로드하여 Syslog 서버에 업로드해야 합니다. 그렇지 않으면 연결이 실패합니다. Syslog 서버의 유형에 따라 클라이언트 인증 인증서의 해시를 만들어야 할 수도 있습니다.

+
예: syslog-ng를 사용하려면 ' openssl x509 -noout -hash -in cert.pem' 명령을 사용하여 인증서의 <hash>를 만들어야 합니다. 그런 다음 클라이언트 인증 인증서를 <hash>.0 뒤에 명명된 파일에 상징적으로 연결해야 합니다.

. 저장 * 을 클릭하여 서버와의 연결을 구성하고 원격 로깅을 활성화합니다.
+
감사 로그 페이지로 리디렉션됩니다.

+
[NOTE]
====
연결 시간 초과 * 값은 구성에 영향을 줄 수 있습니다. 설정에 정의된 값보다 응답하는 데 시간이 오래 걸리는 경우 연결 오류로 인해 구성 오류가 발생할 수 있습니다. 성공적으로 연결하려면 * 연결 시간 초과 * 값을 늘리고 구성을 다시 시도하십시오.

====

