---
permalink: config/task_change_ports_um_uses_for_http_and_https_protocols.html 
sidebar: sidebar 
keywords: change, ports, unified manager, uses, http, https, protocols 
summary: Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 기본 포트는 보안에 필요한 경우 설치 후 변경할 수 있습니다. 기본 포트는 HTTP의 경우 80이고 HTTPS의 경우 443입니다. 
---
= Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 포트를 변경합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 HTTP 및 HTTPS 프로토콜에 사용하는 기본 포트는 보안에 필요한 경우 설치 후 변경할 수 있습니다. 기본 포트는 HTTP의 경우 80이고 HTTPS의 경우 443입니다.

* 필요한 것 *

Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.

[NOTE]
====
Mozilla Firefox 또는 Google Chrome 브라우저를 사용할 때 안전하지 않은 것으로 간주되는 포트가 있습니다. HTTP 및 HTTPS 트래픽에 새 포트 번호를 할당하기 전에 브라우저를 통해 확인하십시오. 안전하지 않은 포트를 선택하면 시스템에 액세스할 수 없게 될 수 있으므로 고객 지원 센터에 문의하여 문제를 해결해야 합니다.

====
포트를 변경한 후에는 Unified Manager 인스턴스가 자동으로 다시 시작되므로 시스템을 잠시 중단해 보십시오.

. SSH를 사용하여 Unified Manager 호스트에 대한 유지보수 사용자로 로그인합니다.
+
Unified Managermaintenance 콘솔 프롬프트가 표시됩니다.

. 응용 프로그램 포트 보기/변경 * 이라고 표시된 메뉴 옵션의 번호를 입력한 다음 Enter 키를 누릅니다.
. 메시지가 표시되면 유지보수 사용자 암호를 다시 입력합니다.
. HTTP 및 HTTPS 포트의 새 포트 번호를 입력한 다음 Enter 키를 누릅니다.
+
포트 번호를 비워 두면 프로토콜의 기본 포트가 할당됩니다.

+
지금 포트를 변경하고 Unified Manager를 다시 시작할지 묻는 메시지가 표시됩니다.

. 포트를 변경하고 Unified Manager를 다시 시작하려면 * y * 를 입력합니다.
. 유지보수 콘솔을 종료합니다.


변경 후에는 Unified Manager 웹 UI에 액세스할 수 있도록 URL에 새 포트 번호를 포함해야 합니다(예: +https://host.company.com:1234+, +https://12.13.14.15:1122+ 또는 +https://[2001:db8:0:1]:2123+).
