---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: Active IQ Unified Manager를 처음 설치하면 기본 HTTPS 인증서가 설치됩니다. 기존 인증서를 대체하는 새 HTTPS 보안 인증서를 생성할 수 있습니다. 
---
= HTTPS 보안 인증서를 생성하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager를 처음 설치하면 기본 HTTPS 인증서가 설치됩니다. 기존 인증서를 대체하는 새 HTTPS 보안 인증서를 생성할 수 있습니다.

* 필요한 것 *

애플리케이션 관리자 역할이 있어야 합니다.

고유 이름(DN)에 더 나은 값을 사용하거나 키 크기를 더 늘리거나 만료 기간을 연장하거나 현재 인증서가 만료된 경우와 같이 인증서를 다시 생성해야 하는 이유는 여러 가지가 있습니다.

Unified Manager 웹 UI에 액세스할 수 없는 경우 유지보수 콘솔을 사용하여 동일한 값으로 HTTPS 인증서를 다시 생성할 수 있습니다. 인증서를 재생성하는 동안 키 크기와 키의 유효 기간을 정의할 수 있습니다. 유지보수 콘솔에서 '서버 인증서 재설정' 옵션을 사용하는 경우 397일 동안 유효한 새 HTTPS 인증서가 생성됩니다. 이 인증서에는 2048비트 크기의 RSA 키가 있습니다.

.단계
. 왼쪽 탐색 창에서 * 일반 * > * HTTPS 인증서 * 를 클릭합니다.
. HTTPS 인증서 다시 생성 * 을 클릭합니다.
+
HTTPS 인증서 재생성 대화 상자가 표시됩니다.

. 인증서를 생성하는 방법에 따라 다음 옵션 중 하나를 선택합니다.
+
[cols="2*"]
|===
| 원하는 작업 | 수행할 작업... 


 a| 
현재 값을 사용하여 인증서를 다시 생성합니다
 a| 
현재 인증서 특성을 사용하여 다시 생성 * 옵션을 클릭합니다.



 a| 
다른 값을 사용하여 인증서를 생성합니다
 a| 
현재 인증서 특성 업데이트 * 옵션을 클릭합니다.

새 값을 입력하지 않으면 일반 이름 및 대체 이름 필드에 기존 인증서의 값이 사용됩니다. "공통 이름"은 호스트의 FQDN으로 설정되어야 합니다. 다른 필드에는 값이 필요하지 않지만 전자 메일, 회사, 부서 등의 값을 입력할 수 있습니다. 인증서에 해당 값을 채우려는 경우 시/도/Country를 선택합니다. 사용 가능한 키 크기(키 알고리즘은 ""RSA"")와 유효 기간 중에서 선택할 수도 있습니다.

[NOTE]
====
** 키 크기에 허용되는 값은 2048 3072 4096입니다.
** 유효 기간은 최소 1일에서 최대 36500일입니다.
+
유효 기간 36500일이 허용되지만 유효 기간은 397일 또는 13개월을 넘지 않는 것이 좋습니다. 397일 이상의 유효 기간을 선택하고 이 인증서에 대해 CSR을 내보내고 잘 알려진 CA가 서명한 경우 CA에서 반환한 서명된 인증서의 유효 기간이 397일로 줄어듭니다.

** 인증서의 대체 이름 필드에서 로컬 식별 정보를 제거하려면 "로컬 식별 정보 제외(예: localhost)" 확인란을 선택할 수 있습니다. 이 확인란을 선택하면 필드에 입력한 항목만 대체 이름 필드에 사용됩니다. 공백으로 두면 결과 인증서에 대체 이름 필드가 전혀 없습니다.


====
|===
. 예 * 를 클릭하여 인증서를 다시 생성합니다.
. 새 인증서가 적용되도록 Unified Manager 서버를 다시 시작합니다.
. HTTPS 인증서를 확인하여 새 인증서 정보를 확인합니다.

