---
permalink: install-linux/reference_red_hat_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제 및 지원 소프트웨어가 필요합니다. 
---
= Linux 소프트웨어 및 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제 및 지원 소프트웨어가 필요합니다.



== 운영 체제 소프트웨어

Linux 시스템에는 다음 버전의 운영 체제와 지원 소프트웨어가 설치되어 있어야 합니다.

* x86_64 아키텍처를 기반으로 하는 Red Hat Enterprise Linux 버전 8.x 및 9.6.


지원되는 Red Hat Enterprise Linux 버전의 전체 최신 목록은 상호 운용성 매트릭스 를 참조하십시오.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

서버는 Unified Manager 실행 전용으로 사용되어야 합니다. 서버에 다른 응용 프로그램을 설치할 수 없습니다. 회사 규정으로 인해 Qualys와 같은 취약점 검사가 Linux 시스템에 설치될 수 있습니다. 설치가 실패하지 않도록 Unified Manager를 설치하기 전에 취약점 검사기를 비활성화해야 합니다.


NOTE: 취약점 스캐너(예: Qualys)는 내부(Unified Manager 및 취약점 스캐너가 동일한 VM에 설치된 VM) 또는 외부 중 가상 시스템(VM)을 검사할 때 CPU 사용량이 높을 수 있습니다 (Unified Manager와 취약점 검사기가 두 서버에 설치되고 취약점 검사기가 Unified Manager가 설치된 VM을 검사하는 경우). 이 문제로 인해 VM이 응답하지 않게 되고 Unified Manager 서비스에 영향을 미치는 경우가 많습니다. 따라서 NetApp Unified Manager가 설치된 VM에서 취약점 검사기를 사용하지 않도록 설정하는 것이 좋습니다. 스캐너를 비활성화할 수 없는 경우 업무 시간이 아닌 시간에 VM을 스캔하고 스캔이 완료된 후 서비스를 다시 시작합니다.



== 타사 소프트웨어

Unified Manager는 WildFly 웹 서버에 구축되어 있습니다. WildFly 26.1.3은 Unified Manager와 함께 번들로 제공되며 구성됩니다.

다음 타사 패키지는 필수이지만 Unified Manager에 포함되어 있지 않습니다. 이러한 패키지는 다음 섹션에서 설명한 대로 리포지토리를 구성한 경우 설치 중에 'yum' 설치 관리자에 의해 자동으로 설치됩니다.

* MySQL Community Edition 버전 8.4.7(MySQL 저장소에서)
* OpenJDK 버전 17.0.14+6(Red Hat Extra Enterprise Linux 서버 저장소에서)
* Python 3.13.3 (Red Hat Extra Enterprise Linux Server 저장소에서 가져옴)
* 7zip 버전 7z2301-linux-x64. 더 자세한 정보를 보려면 다음을 참조하세요. link:task_configure_7zip_package.html["7-zip 소프트웨어 패키지를 구성합니다."].


[NOTE]
====
타사 소프트웨어를 업그레이드하기 전에 Unified Manager를 실행 중인 인스턴스를 종료해야 합니다. 타사 소프트웨어 설치가 완료되면 Unified Manager를 다시 시작할 수 있습니다.

====


== 사용자 인증 요구 사항

Linux 시스템에 Unified Manager를 설치하는 작업은 루트 사용자 또는 비루트 사용자가 'sudo' 명령을 사용하여 수행할 수 있습니다.

또한 기본 Unified Manager 설치에는 디렉토리에 umadmin 사용자(기본 유지 관리 사용자)와 sudoers 파일  및 `ocie_sudoers`의 `/etc/sudoers.d/` JBoss 사용자가 (`ocum_sudoers`포함됩니다. 보안 정책 또는 보안 모니터링 도구로 인해 사용자 환경에서 이 콘텐츠를 제거하는 경우 해당 콘텐츠를 다시 추가해야 합니다. 일부 Unified Manager 작업에서는 sudo 권한이 필요하므로 sudoers 구성을 유지해야 합니다.



== 설치 요구 사항

시스템에 Red Hat Enterprise Linux 및 관련 리포지토리를 설치하는 모범 사례는 다음과 같습니다. 다르게 설치 또는 구성되거나 오프 프레미스(클라우드)를 배포한 시스템은 추가 단계가 필요할 수 있으며, Unified Manager가 이러한 배포에서 제대로 실행되지 않을 수 있습니다.

* Red Hat 모범 사례에 따라 Red Hat Enterprise Linux를 설치해야 하며, 다음 기본 옵션을 선택해야 합니다. 이 경우 "'GUI 기반 서버' 기본 환경을 선택해야 합니다.
* Red Hat Enterprise Linux에 Unified Manager를 설치하는 동안 설치 프로그램이 필요한 모든 소프트웨어 종속 항목에 액세스하고 설치할 수 있도록 시스템이 해당 저장소에 액세스할 수 있어야 합니다.
* 'yum' 설치 관리자가 Red Hat Enterprise Linux 리포지토리에서 종속 소프트웨어를 찾으려면 Red Hat Enterprise Linux 설치 중에 또는 유효한 Red Hat 서브스크립션을 사용하여 시스템을 등록해야 합니다.
+
Red Hat 서브스크립션 관리자에 대한 자세한 내용은 Red Hat 설명서를 참조하십시오.

* 시스템에 필요한 타사 유틸리티를 설치하려면 EPEL(Enterprise Linux) 리포지토리용 추가 패키지를 활성화해야 합니다.
+
EPEL 리포지토리가 시스템에 구성되어 있지 않은 경우 리포지토리를 수동으로 다운로드하고 구성해야 합니다.

+
을 참조하십시오 link:task_manually_configure_epel_repository.html["EPEL 리포지토리를 수동으로 구성합니다"].

* 올바른 버전의 MySQL이 설치되어 있지 않은 경우 MySQL 리포지토리를 활성화하여 시스템에 MySQL 소프트웨어를 성공적으로 설치해야 합니다.
+
MySQL 리포지토리가 시스템에 구성되어 있지 않은 경우 리포지토리를 수동으로 다운로드하고 구성해야 합니다.

+
을 참조하십시오 link:task_manually_configure_mysql_repository.html["MySQL 리포지토리를 수동으로 구성합니다"].

* Unified Manager 호스트에 하나의 Java 버전만 설치해야 합니다. 그렇지 않으면 시스템에서 사용할 버전을 확인하지 못할 수 있습니다. 을 https://kb.netapp.com/data-mgmt/AIQUM/AIQUM_Kbs/After_updating_Java_on_the_Active_IQ_Unified_Manager_host_services_will_not_start["Active IQ Unified Manager 호스트에서 Java를 업데이트한 후 서비스가 시작되지 않습니다"]참조하십시오.


시스템에 인터넷 액세스가 없고 저장소가 인터넷에 연결된 시스템에서 연결되지 않은 시스템으로 미러링되지 않은 경우 설치 지침에 따라 시스템의 외부 소프트웨어 종속성을 결정해야 합니다. 그런 다음, 인터넷에 연결된 시스템에 필요한 소프트웨어를 다운로드하고 Unified Manager를 설치할 시스템에 파일을 복사할 수 있습니다 `.rpm`. 아티팩트 및 패키지를 다운로드하려면 명령을 사용해야 `yum install` 합니다. 두 시스템에서 동일한 운영 체제 버전을 실행하고 서브스크립션 라이센스가 해당 Red Hat Enterprise Linux에 대한 것인지 확인해야 합니다.

[NOTE]
====
여기에 나열된 리포지토리가 아닌 리포지토리에서 필요한 타사 소프트웨어를 설치해서는 안 됩니다. Red Hat 리포지토리에서 설치되는 소프트웨어는 Red Hat Enterprise Linux용으로 명시적으로 설계되었으며 Red Hat 모범 사례(디렉터리 레이아웃, 권한 등)를 준수합니다. 다른 지역의 소프트웨어는 이러한 지침을 따르지 않을 수 있으며, 이로 인해 Unified Manager 설치가 실패하거나 향후 업그레이드에 문제가 발생할 수 있습니다.

====


== 포트 443 요구 사항

Red Hat Enterprise Linux의 일반 이미지는 포트 443에 대한 외부 액세스를 차단할 수 있습니다. 이러한 제한으로 인해 Unified Manager를 설치한 후 관리자 웹 UI에 연결할 수 없을 수 있습니다. 다음 명령을 실행하면 일반 Red Hat Enterprise Linux의 모든 외부 사용자 및 애플리케이션에 대한 포트 443에 액세스할 수 있습니다.

`#firewall-cmd--zone=public--add-port=443/tcp--permanent;firewall-cmd--reload'

Red Hat Enterprise Linux를 "GUI를 갖춘 서버" 기본 환경으로 설치해야 합니다. Unified Manager 설치 지침에 사용되는 명령을 제공합니다. 다른 기본 환경에서는 설치를 검증 또는 완료하기 위해 추가 명령을 설치해야 할 수도 있습니다. 시스템에서 를 사용할 수 없는 경우 `firewall-cmd` 다음 명령을 실행하여 설치해야 합니다.

'#sudo yum install firewalld'

명령을 실행하기 전에 IT 부서에 문의하여 보안 정책에 다른 절차가 필요한지 확인하십시오.

[NOTE]
====
Red Hat 시스템에서는 THP(Transparent Huge Pages)를 비활성화해야 합니다. 이 옵션을 사용하면 특정 프로세스에서 너무 많은 메모리를 사용하고 프로세스가 종료될 때 Unified Manager를 종료하는 경우가 있습니다.

====