---
permalink: install-linux/task_upgrade_host_os_from_rhel_6_x_to_7_x.html 
sidebar: sidebar 
keywords: upgrade, host OS, red hat enterprise, linux 7.x, 8.x 
summary: 이전에 Red Hat Enterprise Linux 7.x 시스템에 Unified Manager를 설치했으며 Red Hat Enterprise Linux 8.x로 업그레이드해야 하는 경우 이 항목에 나열된 절차 중 하나를 따라야 합니다. 두 경우 모두 Red Hat Enterprise Linux 7.x 시스템에서 Unified Manager 백업을 생성한 다음 Red Hat Enterprise Linux 8.x 시스템으로 백업을 복원해야 합니다. 
---
= Red Hat Enterprise Linux 7.x에서 8.x로 호스트 OS 업그레이드
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 Red Hat Enterprise Linux 7.x 시스템에 Unified Manager를 설치했으며 Red Hat Enterprise Linux 8.x로 업그레이드해야 하는 경우 이 항목에 나열된 절차 중 하나를 따라야 합니다. 두 경우 모두 Red Hat Enterprise Linux 7.x 시스템에서 Unified Manager 백업을 생성한 다음 Red Hat Enterprise Linux 8.x 시스템으로 백업을 복원해야 합니다.

아래 나열된 두 옵션의 차이점은 한 가지 경우에서 Unified Manager 복원을 새 8.x 서버로 수행하고 다른 경우에는 동일한 서버에서 복원 작업을 수행하고 있다는 것입니다.

이 작업을 수행하려면 Red Hat Enterprise Linux 7.x 시스템에 Unified Manager의 백업을 만들어야 하므로 전체 업그레이드 프로세스를 완료할 준비가 된 경우에만 Unified Manager가 가장 짧은 기간 동안 오프라인 상태가 되도록 백업을 만들어야 합니다. 수집된 데이터의 격차가 Unified Manager UI에 나타나는 것은 Red Hat Enterprise Linux 7.x 시스템이 종료되는 기간이며 새로운 Red Hat Enterprise Linux 8.x가 시작되기 전입니다.

백업 및 복원 프로세스에 대한 자세한 지침을 검토해야 하는 경우 _Active IQ Unified Manager 온라인 도움말_을 참조하십시오.

* 새 서버를 사용하여 호스트 OS 업그레이드 *

Red Hat Enterprise Linux 8.x 소프트웨어를 설치할 수 있는 예비 시스템이 있는 경우, Red Hat Enterprise Linux 7.x 시스템을 사용할 수 있는 동안 해당 시스템에서 Unified Manager 복원을 수행할 수 있도록 다음 단계를 따르십시오.

. Red Hat Enterprise Linux 8.x 소프트웨어로 새 서버를 설치하고 구성합니다.
+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Red Hat 소프트웨어 및 설치 요구 사항"]

. Red Hat Enterprise Linux 8.x 시스템에서 기존 Red Hat Enterprise Linux 7.x 시스템에 있는 것과 동일한 버전의 Unified Manager 소프트웨어를 설치합니다.
+
link:concept_install_unified_manager_on_rhel_or_centos.html["Red Hat Enterprise Linux에 Unified Manager 설치"]

+
설치가 완료되면 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.

. Red Hat Enterprise Linux 7.x 시스템의 웹 UI의 관리 메뉴에서 Unified Manager 백업을 만든 다음 백업 파일(.7z 파일)과 데이터베이스 리포지토리 디렉토리("/database-dumps-repo" 하위 디렉토리)의 내용을 외부 위치로 복사합니다.
. Red Hat Enterprise Linux 7.x 시스템에서 Unified Manager를 종료합니다.
. Red Hat Enterprise Linux 8.x 시스템에서 백업 파일(.7z)을 외부 위치에서 '/opt/netapp/data/ocum-backup/'으로, 데이터베이스 리포지토리 파일을 '/ocum-backup' 디렉토리 아래의 '/database-dumps-repo' 하위 디렉토리로 복사합니다.
. 다음 명령을 입력하여 백업 파일에서 Unified Manager 데이터베이스를 복원합니다.
+
''um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>'

. 웹 브라우저에 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음 시스템에 로그인합니다.


시스템이 올바르게 작동하는지 확인한 후에는 Red Hat Enterprise Linux 7.x 시스템에서 Unified Manager를 제거할 수 있습니다.

* 동일한 서버에서 호스트 OS 업그레이드 *

Red Hat Enterprise Linux 8.x 소프트웨어를 설치할 수 있는 예비 시스템이 없는 경우 다음 단계를 따르십시오.

. 웹 UI의 관리 메뉴에서 Unified Manager 백업을 생성한 다음 백업 파일(.7z' 파일)과 데이터베이스 저장소 디렉터리('/database-dumps-repo' 하위 디렉터리)의 내용을 외부 위치로 복사합니다.
. 시스템에서 Red Hat Enterprise Linux 7.x 이미지를 제거하고 시스템을 완전히 초기화하십시오.
. 동일한 시스템에 Red Hat Enterprise Linux 8.x 소프트웨어를 설치하고 구성합니다.
+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Red Hat 소프트웨어 및 설치 요구 사항"]

. Red Hat Enterprise Linux 8.x 시스템에서 Red Hat Enterprise Linux 7.x 시스템에 있는 것과 동일한 버전의 Unified Manager 소프트웨어를 설치합니다.
+
link:concept_install_unified_manager_on_rhel_or_centos.html["Red Hat Enterprise Linux에 Unified Manager 설치"]

+
설치가 완료되면 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.

. 외부 위치에서 '/opt/netapp/data/ocum-backup/'으로 백업 파일('.7z')을 복사하고 데이터베이스 저장소 파일은 '/ocum-backup' 디렉토리 아래의 '/database-dumps-repo' 하위 디렉토리로 복사합니다.
. 다음 명령을 입력하여 백업 파일에서 Unified Manager 데이터베이스를 복원합니다.
+
''um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>'

. 웹 브라우저에 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음 시스템에 로그인합니다.

