---
permalink: install-linux/task_remove_unified_manager.html 
sidebar: sidebar 
keywords: remove, unified manager 
summary: 단일 명령으로 Red Hat Enterprise Linux 또는 CentOS 호스트에서 Unified Manager를 중지하고 제거할 수 있습니다. 
---
= Unified Manager를 제거하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 명령으로 Red Hat Enterprise Linux 또는 CentOS 호스트에서 Unified Manager를 중지하고 제거할 수 있습니다.

* 필요한 것 *

* Unified Manager를 제거할 서버에 대한 루트 사용자 액세스 권한이 있어야 합니다.
* Linux 시스템에서 SELinux(Security-Enhanced Linux)를 비활성화해야 합니다. 을 사용하여 SELinux 런타임 모드를 ""허용""으로 변경합니다 `setenforce 0` 명령.
* 소프트웨어를 제거하기 전에 모든 클러스터(데이터 소스)를 Unified Manager 서버에서 제거해야 합니다.
* MySQL 포트 3306을 허용하거나 차단할 수 있도록 만들어진 방화벽 규칙을 수동으로 삭제해야 합니다. 방화벽 규칙은 자동으로 삭제되지 않습니다.


.단계
. Unified Manager를 제거할 서버에 루트 사용자로 로그인합니다.
. 서버에서 Unified Manager를 중지하고 제거합니다.
+
"rpm -e NetApp -um"

+
이 단계에서는 관련된 모든 NetApp RPM 패키지를 제거합니다. Java, MySQL 및 p7zip 같은 필수 소프트웨어 모듈은 제거하지 않습니다.

. * 선택 사항: * 필요한 경우 Java, MySQL 및 p7zip 같은 지원 소프트웨어 모듈을 제거합니다.
+
rpm -e p7zip mysql -community -client mysql -community -server mysql -common mysql -community -libs java -x. y



이 작업이 완료되면 소프트웨어가 제거됩니다. 제거 후 "/opt/netapp/data" 디렉토리의 모든 데이터가 "/opt/netapp/data/backup" 폴더로 이동됩니다. Unified Manager를 제거하면 Java 및 MySQL 패키지도 제거됩니다. 단, 시스템의 다른 애플리케이션에서 패키지가 필요하고 사용되지 않습니다. 그러나 MySQL 데이터는 삭제되지 않습니다.
