---
permalink: install-linux/task_upgrade_unified_manager.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Linux 플랫폼에서 설치 파일을 다운로드하여 실행하여 Unified Manager를 업그레이드할 수 있습니다. 
---
= Unified Manager 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 플랫폼에서 설치 파일을 다운로드하여 실행하여 Unified Manager 9.11 또는 9.12에서 9.13으로 업그레이드할 수 있습니다.

* 필요한 것 *

* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구사항을 충족해야 합니다.
+
을 참조하십시오 link:concept_virtual_infrastructure_or_hardware_system_requirements.html["하드웨어 시스템 요구 사항"].

+
을 참조하십시오 link:reference_red_hat_and_centos_software_and_installation_requirements.html["Linux 소프트웨어 및 설치 요구 사항"].

* Red Hat Enterprise Linux Subscription Manager에 가입해야 합니다.
* Unified Manager를 업그레이드하기 전에 올바른 버전의 OpenJDK를 설치하거나 업그레이드해야 합니다.
+
을 참조하십시오 link:task_upgrade_openjdk_on_linux_ocum.html["Linux에서 JRE 업그레이드"].

* 업그레이드 중에 문제가 발생할 경우 데이터 손실을 방지하려면 Unified Manager 데이터베이스의 백업을 생성해야 합니다. 에서 백업 파일을 이동하는 것이 좋습니다 `/opt/netapp/data` 외부 위치에 대한 디렉터리입니다.
* 업그레이드하는 동안 성능 데이터를 13개월 동안 유지하기 위한 이전 기본 설정을 유지할지 아니면 6개월로 변경할지 묻는 메시지가 표시될 수 있습니다. 확인 시, 기록 성능 데이터는 6개월 후에 삭제됩니다.
* 업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없으므로 실행 중인 작업을 모두 완료해야 합니다.
* MySQL Community Edition은 Unified Manager 업그레이드 중에 자동으로 업그레이드됩니다. 시스템에 설치된 MySQL 버전이 8.0.32 이전 버전인 경우 Unified Manager 업그레이드 프로세스에서 MySQL을 8.0.32로 자동 업그레이드합니다.


.단계
. 대상 Red Hat Enterprise Linux 또는 CentOS 서버에 로그인합니다.
. 서버에 Unified Manager 번들을 다운로드합니다.
+
을 참조하십시오 link:task_download_unified_manager.html["Linux용 Unified Manager 다운로드 중"].

. 타겟 디렉토리로 이동하고 Unified Manager 번들을 확장합니다.
+
'ActiveIQUnifiedManager-<version>.zip의 압축을 풉니다.

+
Unified Manager에 필요한 RPM 모듈의 압축이 대상 디렉토리에 풀립니다.

. 디렉토리에서 다음 모듈을 사용할 수 있는지 확인합니다.
+
"ls *.rpm"

+
'netapp-um <version>.x86_64.rpm'

. 사전 설치 스크립트를 실행하여 업그레이드와 충돌할 수 있는 시스템 구성 설정이나 설치된 소프트웨어가 없는지 확인합니다.
+
'SUDO./PRE_INSTALL_CHECK.sh'를 선택합니다

+
사전 설치 스크립트는 시스템에 유효한 Red Hat Enterprise Linux 서브스크립션이 있으며 필요한 소프트웨어 저장소에 대한 액세스 권한이 있는지 확인합니다. 스크립트에서 문제가 식별되면 문제를 해결하고 업그레이드를 계속 수행해야 합니다.

+
누락된 패키지가 발견되면 에 설명된 단계를 수행합니다 link:../install-linux/task_upgrade_unified_manager.html#additional-steps-to-perform-for-missing-packages["누락된 패키지에 대해 수행할 추가 단계입니다"]. 누락된 패키지가 없는 경우 다음 단계를 계속합니다.

. 다음 스크립트를 사용하여 Unified Manager 업그레이드:
+
업그레이드.sh

+
이 스크립트는 RPM 모듈을 자동으로 실행하여 필요한 지원 소프트웨어 및 실행 중인 Unified Manager 모듈을 업그레이드합니다. 또한 업그레이드 스크립트는 업그레이드와 충돌할 수 있는 시스템 구성 설정이나 설치된 소프트웨어가 있는지 확인합니다. 스크립트에서 문제가 식별되면 Unified Manager를 업그레이드하기 전에 문제를 해결해야 합니다. Unified Manager를 업그레이드하기 전에 _net-snmp_와 같은 패키지를 이전에 설치한 경우 MySQL 종속성이 업그레이드 중에 패키지를 제거할 수 있습니다. 계속 사용하려면 패키지를 수동으로 다시 설치해야 합니다.

. 업그레이드가 완료된 후 Unified Manager 웹 UI의 IP 주소 또는 URL, 유지보수 사용자 이름(umadmin) 및 기본 암호가 표시된 메시지가 나타날 때까지 메시지를 다시 스크롤합니다.
+
이 메시지는 다음과 유사합니다.

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----


지원되는 웹 브라우저의 새 창에 지정된 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음, 앞서 설정한 유지보수 사용자 이름(umadmin) 및 암호를 사용하여 로그인합니다.



== 누락된 패키지에 대해 수행할 추가 단계입니다

업그레이드 중 사이트에서 누락된 패키지가 발견되거나 시스템이 인터넷에 연결되어 있지 않거나 Red Hat Enterprise Linux 리포지토리를 사용하지 않는 경우 다음 단계를 수행하여 필요한 패키지가 있는지 확인하고 패키지를 다운로드하십시오.


NOTE: 이러한 단계는 주 절차의 _5_단계 이후에 수행해야 합니다. 이 절차를 수행하면 Unified Manager가 업그레이드되며 업그레이드를 위해 추가 단계를 실행할 필요가 없습니다.

. 사용 가능한 패키지 및 사용할 수 없는 패키지 목록을 봅니다.
+
'yum install netapp-um <version>.x86_64.rpm --assulmeno'

+
""설치 중:"" 섹션의 항목은 현재 디렉터리에서 사용할 수 있는 패키지이며 ""종속성 설치:"" 섹션의 항목은 시스템에 없는 패키지입니다.

. 인터넷에 액세스할 수 있는 다른 시스템에서 다음 명령을 실행하여 누락된 패키지를 다운로드합니다.
+
''yum install package_name -- downloadonly -- downlopaddr=.'

+
패키지는 '--downlodaddr='으로 지정된 디렉토리에 다운로드됩니다.

+
플러그인 ""yum-plugin-downloadonly""가 Red Hat Enterprise Linux 시스템에서 항상 활성화되어 있는 것은 아니므로 패키지를 설치하지 않고 패키지를 다운로드할 수 있도록 기능을 설정해야 할 수 있습니다.

+
'yum install yum-plugin-downloadonly

. 다운로드한 패키지를 설치 시스템에서 Unified Manager 번들의 압축을 푼 디렉토리에 복사합니다.
. 디렉토리를 해당 디렉토리로 변경하고 다음 명령을 실행하여 누락된 패키지를 해당 종속성에 따라 설치합니다.
+
'yum install *.rpm'입니다

. Unified Manager 서버를 시작합니다. 다음 명령을 실행합니다.
+
'스타ctl start socie'입니다

+
'신조 시작 조숙자'



이 프로세스는 Unified Manager 업그레이드 프로세스를 완료합니다. 지원되는 웹 브라우저의 새 창에 지정된 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음, 앞서 설정한 유지보수 사용자 이름(umadmin) 및 암호를 사용하여 로그인합니다.
