---
permalink: install-linux/task_upgrade_mysql_on_linux.html 
sidebar: sidebar 
keywords: upgrade, mysql, linux 
summary: Unified Manager가 설치된 Linux 서버에서 최신 버전의 MySQL으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 
---
= Linux에서 MySQL 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 설치된 Linux 서버에서 최신 버전의 MySQL으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 시스템에 설치된 MySQL 버전이 8.0.28 이전인 경우 Unified Manager 9.11 업그레이드 프로세스는 MySQL을 8.0.28로 자동 업그레이드합니다. MySQL의 독립 실행형 업그레이드를 이전 버전에서 8.0.28로 실행해서는 안 됩니다.

* 필요한 것 *

Unified Manager가 설치된 Linux 시스템에 대한 루트 권한이 있어야 합니다.

마이너 업데이트에만 MySQL 8.0.28의 기본 버전을 이후 버전으로 업그레이드할 수 있습니다.

.단계
. Unified Manager 호스트 시스템에서 루트 사용자로 로그인합니다.
. 대상 시스템에서 최신 MySQL Community Server의 .rpm 번들을 다운로드합니다.
. 번들을 대상 시스템의 디렉토리에 압축을 풉니다.
. 번들을 언타어링한 후 디렉토리에 여러 `.rpm' 패키지가 있지만 Unified Manager에서는 다음 rpm 패키지만 필요합니다.
+
** mysql-community-client-8.0.28
** MySQL - 커뮤니티 - libs - 8.0.28
** mysql-community-server-8.0.28
** mysql-community-common-8.0.28
** MySQL-community-client-plugins-8.0.28 다른 모든 .rpm 패키지를 삭제합니다. 그러나 RPM 번들에 모든 패키지를 설치해도 오류가 발생하지 않습니다.


. Unified Manager 서비스 및 관련 MySQL 소프트웨어를 표시된 순서대로 중지합니다.
+
'스타치틀스조우'

+
'스ystemtl stop socie'

+
'스타emctl stop mysqld'

. 다음 명령을 사용하여 MySQL 업그레이드를 호출합니다.
+
'yum install *.rpm'입니다

+
rpm은 MySQL의 새 버전을 다운로드한 디렉토리에 있는 .rpm 패키지를 의미합니다.

. 다음 순서대로 Unified Manager를 시작합니다.
+
'스타emctl start mysqld'

+
'스타ctl start socie'입니다

+
'신조 시작 조숙자'


