---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: NAS 또는 SAN 장치에 /opt/NetApp 또는 /opt/NetApp/데이터를 마운트하고 SELinux를 사용하도록 설정한 경우 다음 사항을 고려해야 합니다. 
---
= NFS 및 CIFS 공유에 대한 SELinux 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NAS 또는 SAN 장치에 '/opt/netapp' 또는 '/opt/netapp/data'를 마운트하고 SELinux를 활성화한 경우 몇 가지 고려 사항을 염두에 두어야 합니다.

루트 파일 시스템이 아닌 다른 곳에서 '/opt/netapp' 또는 '/opt/netapp/data'를 마운트하고 사용자 환경에서 SELinux를 활성화한 경우 마운트된 디렉토리에 대한 올바른 컨텍스트를 설정해야 합니다. 사용자 환경의 해당 시나리오에 대해 올바른 SELinux 컨텍스트를 설정하고 확인하려면 다음 단계를 수행하십시오.



== /opt/netapp/data가 마운트된 경우 SELinux 컨텍스트 구성

시스템에 '/opt/netapp/data'를 마운트하고 SELinux가 'Enforcing'으로 설정된 경우, 데이터베이스 파일 위치의 기본 컨텍스트 요소인 '/opt/netapp/data'에 대한 SELinux context type이 'mysqld_db_t'로 설정되어 있는지 확인하십시오.

. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
'ls-dZ/opt/netapp/data'

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: 이 출력에서 컨텍스트는 ddefault_t입니다. 이 컨텍스트를 mysqld_db_t로 변경해야 합니다.

. 다음 단계를 수행하여 '/opt/netapp/data'를 마운트한 방법에 따라 컨텍스트를 설정합니다.
+
.. 다음 명령을 실행하여 컨텍스트를 mysqld_db_t로 설정합니다.




[listing]
----
semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
restorecon -R -v /opt/netapp/data
----
. '/etc/fstab'에서 '/opt/netapp/data'를 구성한 경우 '/etc/fstab' 파일을 편집해야 합니다. '/opt/netapp/data/' 마운트 옵션의 경우 MySQL 레이블을 다음과 같이 추가합니다.
+
'CONTEXT=system_u:object_r:mysqld_db_t:s0'

. 컨텍스트를 설정하려면 '/opt/netapp/data/'를 마운트 해제하고 다시 마운트하십시오.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 mysqld_db_t로 설정합니다.
+
'<nfsshare>:/<mountpoint>/opt/netapp/data-o context=system_u:object_r:mysqld_db_t:s0'. 컨텍스트가 올바르게 설정되었는지 확인합니다.



'ls-dZ/opt/netapp/data/'

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


== /opt/NetApp이 마운트되면 SELinux 컨텍스트를 구성하고 /opt/netapp/data/도 별도로 마운트합니다

이 시나리오에서는 먼저 이전 섹션에서 설명한 대로 '/opt/netapp/data/'의 컨텍스트를 설정해야 합니다. '/opt/netapp/data/'에 대한 올바른 컨텍스트를 설정한 후 부모 디렉토리 '/opt/netapp'에 SELinux 컨텍스트가 ' file_t'로 설정되어 있지 않은지 확인합니다.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
'ls-dZ/opt/netapp'

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
이 출력에서 컨텍스트는 file_t가 변경되어야 합니다. 다음 명령어를 실행하면 해당 컨텍스트가 usr_t로 설정됩니다. 보안 요구 사항에 따라 context를 file_t 이외의 값으로 설정할 수 있습니다.

. 다음 단계를 수행하여 '/opt/NetApp'을(를) 마운트한 방법에 따라 컨텍스트를 설정합니다.
+
.. 다음 명령을 실행하여 컨텍스트를 설정합니다.




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. '/etc/fstab'에서 '/opt/netapp'를 구성한 경우 '/etc/fstab' 파일을 편집해야 합니다. '/opt/netapp' 마운트 옵션에 MySQL 레이블을 다음과 같이 추가합니다.
+
'CONTEXT=system_u:object_r:usr_t:s0'

. 마운트 해제한 다음 컨텍스트를 사용하도록 다시 `/opt/netapp'을 마운트합니다.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다.
+
mount <nfsshare>:/<mountpoint>/opt/netapp-o context=system_u:object_r:usr_t:s0'

+
.. 컨텍스트가 올바르게 설정되었는지 확인합니다.
+
'ls-dZ/opt/netapp'

+
샘플 출력입니다





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


== /opt/NetApp이 마운트되고 /opt/netapp/data/가 별도로 마운트되지 않은 경우 SELinux 컨텍스트를 구성합니다

시스템에 '/opt/netapp'를 마운트하고 SELinux가 'Enforcing'으로 설정된 경우, 데이터베이스 파일 위치의 기본 컨텍스트 요소인 '/opt/NetApp'에 대한 SELinux context type이 mysqld_db_t'로 설정되어 있는지 확인하십시오.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
'ls-dZ/opt/netapp'

+
샘플 출력:



[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----

NOTE: 이 출력에서 컨텍스트는 ddefault_t입니다. 이 컨텍스트를 mysqld_db_t로 변경해야 합니다.

. 다음 단계를 수행하여 '/opt/NetApp'을(를) 마운트한 방법에 따라 컨텍스트를 설정합니다.
+
.. 다음 명령을 실행하여 컨텍스트를 mysqld_db_t로 설정합니다.




[listing]
----
semanage fcontext -a -t mysqld_db_t "/opt/netapp"
restorecon -R -v /opt/netapp
----
. '/etc/fstab'에서 '/opt/netapp'를 구성한 경우 '/etc/fstab' 파일을 편집합니다. '/opt/netapp/' 마운트 옵션의 경우 MySQL 레이블을 다음과 같이 추가합니다.


[listing]
----
context=system_u:object_r:mysqld_db_t:s0
----
. 마운트 해제한 다음 컨텍스트를 사용하도록 다시 `/opt/netapp/'를 마운트합니다.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 mysqld_db_t로 설정합니다.


[listing]
----
mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0
----
. 컨텍스트가 올바르게 설정되었는지 확인합니다.
+
'ls-dZ/opt/netapp/'

+
샘플 출력:



[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''