---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: 설치 중에 설정된 인스턴스별 JBoss 암호를 재설정할 수 있습니다. 사이트에 Unified Manager 설치 설정을 재정의하는 데 이 보안 기능이 필요한 경우 암호를 선택적으로 재설정할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다. 
---
= JBoss 비밀번호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 중에 설정된 인스턴스별 JBoss 암호를 재설정할 수 있습니다. 사이트에 Unified Manager 설치 설정을 재정의하는 데 이 보안 기능이 필요한 경우 암호를 선택적으로 재설정할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다.

* Unified Manager가 설치된 Red Hat Enterprise Linux 시스템에 대한 루트 사용자 액세스 권한이 있어야 합니다.
* 디렉토리 '/opt/netapp/Essentials/bin'에서 NetApp에서 제공한 password.sh' 스크립트에 액세스할 수 있어야 합니다.


.단계
. 시스템에서 루트 사용자로 로그인합니다.
. 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 중지합니다.
+
'스타치틀스조우'

+
'스ystemtl stop socie'

+
연결된 MySQL 소프트웨어를 중지하지 마십시오.

. 다음 명령을 입력하여 암호 변경 프로세스를 시작합니다.
+
'/opt/netapp/essentials/bin/password.sh resetJBossPassword'

. 메시지가 표시되면 새 JBoss 암호를 입력한 다음 다시 입력하여 확인합니다.
+
암호는 8자에서 16자 사이여야 하며 숫자, 대문자, 소문자 및 다음 특수 문자 중 하나 이상을 포함해야 합니다.

+
'+!@%^ * -_+=[]:<>.?/~+'

. 스크립트가 완료되면 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 시작합니다.
+
'스타ctl start socie'입니다

+
'신조 시작 조숙자'

. 모든 서비스가 시작되면 Unified Manager UI에 로그인할 수 있습니다.

