---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: 'Unified Manager를 설치하려면 NetApp Support 사이트에서 Unified Manager ".zip" 파일을 다운로드해야 합니다.' 
---
= Unified Manager 다운로드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하려면 NetApp Support 사이트에서 Unified Manager '.zip' 파일을 다운로드해야 합니다.

.시작하기 전에
NetApp Support 사이트에 대한 로그인 자격 증명이 있어야 합니다.

Red Hat Enterprise Linux 시스템용 Unified Manager 설치 패키지를 다운로드합니다.

.단계
. NetApp Support 사이트에 로그인하고 Unified Manager의 다운로드 페이지로 이동합니다.
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp Support 사이트"]

. Unified Manager의 필수 버전을 선택하고 최종 사용자 라이센스 계약(EULA)에 동의합니다.
. Linux용 Unified Manager 설치 프로그램 파일을 다운로드하고 대상 시스템의 디렉토리에 .zip 파일을 저장합니다.
+
[NOTE]
====
** Red Hat Enterprise Linux 시스템에 맞는 설치 관리자 파일 버전을 다운로드했는지 확인합니다. Red Hat Enterprise Linux 8 또는 9의 설치 여부에 따라 적절한 버전의 Unified Manager 파일을 다운로드했는지 확인하십시오 `.zip`.
** 코드 서명 인증서를 다운로드할 것을 권장합니다 (`.pem`) 및 디지털 서명 (`.sig`)를 참조하십시오 `.zip` 파일.


====
. 다운로드한 소프트웨어의 무결성 체크섬을 확인합니다.
. 코드 서명 인증서와 디지털 서명을 다운로드한 경우 설치 프로그램 파일의 무결성을 확인할 수 있습니다. 다음 명령을 사용하여 설치 프로그램 파일의 무결성을 확인할 수 있습니다.
+
** 이 명령은 코드 서명 인증서에서 공개 키로 파일을 만듭니다.
+
[listing]
----
openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>
----
+
*** 여기서 * AIQUM-RHEL-CLIENT-INTER-ROOT.PEM * 은 코드 서명 인증서가 들어 있는 파일입니다.


** 이 명령은 설치 프로그램 파일의 서명을 확인합니다.
+
[listing]
----
openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip
----
+
메시지가 와 유사합니다 `Verified Ok` 설치 프로그램 파일을 사용해도 안전한지 확인합니다.




