---
permalink: events/concept_what_active_iq_platform_events_are.html 
sidebar: sidebar 
keywords: active iq, platform, events 
summary: Unified Manager는 Active IQ 플랫폼에서 검색된 이벤트를 표시할 수 있습니다. 이러한 이벤트는 Unified Manager가 모니터링하는 모든 스토리지 시스템에서 생성되는 AutoSupport 메시지에 대해 일련의 규칙을 실행하여 생성됩니다. 
---
= Active IQ 플랫폼 이벤트란 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 Active IQ 플랫폼에서 검색된 이벤트를 표시할 수 있습니다. 이러한 이벤트는 Unified Manager가 모니터링하는 모든 스토리지 시스템에서 생성되는 AutoSupport 메시지에 대해 일련의 규칙을 실행하여 생성됩니다.

자세한 내용은 을 참조하십시오 link:../events/concept_how_active_iq_platform_events_are_generated.html["Active IQ 플랫폼 이벤트 생성 방법"].

Unified Manager는 새 규칙 파일을 자동으로 확인하고 새 규칙이 있을 때만 새 파일을 다운로드합니다. 외부 네트워크에 액세스할 수 없는 사이트에서는 * 스토리지 관리 * > * 이벤트 설정 * > * 규칙 업로드 * 에서 수동으로 규칙을 업로드해야 합니다.

Active IQ 이벤트는 기존 Unified Manager 이벤트와 중복되지 않으며 시스템 구성, 케이블 연결, 모범 사례 및 가용성 문제와 관련된 인시던트나 위험을 식별합니다.

플랫폼 이벤트 활성화에 대한 자세한 내용은 을 참조하십시오 link:../config/concept_active_iq_platform_events.html["Active IQ 포털 이벤트 활성화"]. 규칙 파일 업로드에 대한 자세한 내용은 을 참조하십시오 link:../events/task_upload_new_active_iq_rules_file.html["새 Active IQ 규칙 파일을 업로드하는 중입니다"].

NetApp Active IQ는 예측 분석 및 능동적 지원을 제공하여 NetApp 하이브리드 클라우드 전반에서 스토리지 시스템 운영을 최적화하는 클라우드 기반 서비스입니다. 을 참조하십시오 https://["NetApp Active IQ를 참조하십시오"] 를 참조하십시오.
