---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 이벤트 세부 정보 페이지에서 이벤트 심각도, 영향 수준, 영향 영역 및 이벤트 소스와 같은 선택한 이벤트의 세부 정보를 볼 수 있습니다. 문제 해결을 위해 가능한 해결 방법에 대한 추가 정보도 볼 수 있습니다. 
---
= 이벤트 세부 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 세부 정보 페이지에서 이벤트 심각도, 영향 수준, 영향 영역 및 이벤트 소스와 같은 선택한 이벤트의 세부 정보를 볼 수 있습니다. 문제 해결을 위해 가능한 해결 방법에 대한 추가 정보도 볼 수 있습니다.

* * 이벤트 이름 *
+
이벤트의 이름과 이벤트가 마지막으로 표시된 시간입니다.

+
비성능 이벤트의 경우 이벤트가 New 또는 Acknowledged 상태에 있는 동안에는 마지막으로 본 정보를 알 수 없으므로 숨겨집니다.

* * 이벤트 설명 *
+
이벤트에 대한 간략한 설명입니다.

+
경우에 따라 이벤트 설명에 이벤트가 트리거되는 이유가 제공됩니다.

* * 경합의 요소 *
+
동적 성능 이벤트의 경우 이 섹션에는 클러스터의 논리적 및 물리적 구성요소를 나타내는 아이콘이 표시됩니다. 구성 요소의 경합이 발생한 경우 해당 아이콘이 빨간색 원으로 강조 표시됩니다.

+
여기에 표시된 구성 요소에 대한 설명은 _Cluster 구성 요소 및 구성 요소가 경합이 가능한 이유_를 참조하십시오.



이벤트 정보, 시스템 진단 및 권장 조치 섹션은 기타 항목에서 설명합니다.



== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 메모 아이콘 *
+
이벤트에 대한 메모를 추가하거나 업데이트하고 다른 사용자가 남긴 모든 메모를 검토할 수 있습니다.



* 작업 메뉴 *

* * 나에게 할당 *
+
사용자에게 이벤트를 할당합니다.

* 다른 사람에게 할당 *
+
소유자 할당 대화 상자를 엽니다. 이 대화 상자에서 다른 사용자에게 이벤트를 할당하거나 다시 할당할 수 있습니다.

+
사용자에게 이벤트를 할당하면 사용자의 이름과 이벤트가 할당된 시간이 선택한 이벤트의 이벤트 목록에 추가됩니다.

+
소유권 필드를 비워 두면 이벤트 할당을 취소할 수도 있습니다.

* * 확인 *
+
반복 경고 알림을 계속 수신하지 않도록 선택한 이벤트를 확인합니다.

+
이벤트를 확인하면 선택한 이벤트의 이벤트 목록(에 의해 확인됨)에 사용자 이름과 이벤트가 추가됩니다. 이벤트를 인지하면 해당 이벤트를 관리할 책임이 있습니다.

* * 해결됨으로 표시 *
+
이벤트 상태를 Resolved 로 변경할 수 있습니다.

+
이벤트를 해결할 때 사용자 이름과 이벤트를 해결한 시간이 선택한 이벤트의 이벤트 목록(에서 해결)에 추가됩니다. 이벤트에 대한 수정 조치를 취한 후에는 해당 이벤트를 '해결됨'으로 표시해야 합니다.

* * 알림 추가 *
+
선택한 이벤트에 대한 경고를 추가할 수 있는 경고 추가 대화 상자를 표시합니다.


