---
permalink: events/reference_logical_interface_events.html 
sidebar: sidebar 
keywords: 'network, interface, (lif) events, impact area, availability, configuration, performance' 
summary: '네트워크 인터페이스 이벤트는 잠재적인 문제를 모니터링할 수 있도록 네트워크 인터페이스(LIF) 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.' 
---
= 네트워크 인터페이스(LIF) 이벤트입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 인터페이스 이벤트는 잠재적인 문제를 모니터링할 수 있도록 네트워크 인터페이스(LIF) 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
네트워크 인터페이스 상태 작동 중지(ocumEvtLifStatusDown)
 a| 
위험입니다
 a| 
인터페이스
 a| 
오류



 a| 
FC/FCoE 네트워크 인터페이스 상태 다운(문서 FCLifStatusDown)
 a| 
위험입니다
 a| 
인터페이스
 a| 
오류



 a| 
네트워크 인터페이스 장애 조치를 수행할 수 없습니다(문서: LiftFailoverNotPosable).
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
네트워크 인터페이스가 홈 포트에 없음(문서 번호: EvtLifNotAtHomePort)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고

|===


== 충격 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
네트워크 인터페이스 경로가 구성되지 않음(해당 없음)
 a| 
이벤트
 a| 
인터페이스
 a| 
정보

|===


== 충격 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
네트워크 인터페이스 MB/s 심각한 임계값 위반(문서 네트워크 수명 장애)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
네트워크 인터페이스 MB/s 경고 임계값 위반(문서 네트워크 수명 경고)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
FC 네트워크 인터페이스 MB/s 심각한 임계값 위반(문서 FcpLifmbpsIncident)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
FC 네트워크 인터페이스 MB/s 경고 임계값 위반(문서 수명경고)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
NVMf FC 네트워크 인터페이스 MB/s 중요 임계값 위반(문서 NvmfcLifmpsIncident)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
NVMf FC 네트워크 인터페이스 MB/s 경고 임계값 위반(문서 NvmfcLifmpsWarning)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고

|===