---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: 스토리지 관리자는 CLI 명령을 사용하여 클러스터, 애그리게이트, 볼륨 등의 스토리지 개체에 대한 쿼리를 수행할 수 있습니다. qtree 및 LUN, 
---
= 지원되는 Unified Manager CLI 명령
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 관리자는 CLI 명령을 사용하여 클러스터, 애그리게이트, 볼륨 등의 스토리지 개체에 대한 쿼리를 수행할 수 있습니다. qtree 및 LUN, CLI 명령을 사용하여 Unified Manager 내부 데이터베이스와 ONTAP 데이터베이스를 쿼리할 수 있습니다. 작업 시작 또는 종료 시 실행되는 스크립트에서 CLI 명령을 사용하거나 경고가 트리거될 때 실행할 수도 있습니다.

모든 명령에는 'um CLI login' 명령어와 유효한 사용자 이름 및 인증 패스워드가 선행되어야 한다.


NOTE: um run_command를 실행하려면 계정에 _console_application 액세스 권한이 있는지 확인하십시오.

|===
| CLI 명령 | 설명 | 출력 


 a| 
'um CLI login -u <username>[-p <password>]'
 a| 
CLI에 로그인합니다. 보안 관련 문제 때문에 "-u" 옵션 다음에 사용자 이름만 입력해야 합니다. 이러한 방식으로 사용하면 암호를 입력하라는 메시지가 표시되며 암호는 기록 또는 프로세스 테이블에서 캡처되지 않습니다. 이 세션은 로그인 후 3시간 후에 만료되며, 그 이후에는 사용자가 다시 로그인해야 합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
um CLI 로그아웃
 a| 
CLI에서 로그아웃합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
염원이다
 a| 
모든 1단계 하위 명령을 표시합니다.
 a| 
모든 1단계 하위 명령을 표시합니다.



 a| 
'<um run cmd[-t<timeout>]<cluster><command>'
 a| 
하나 이상의 호스트에서 명령을 실행하는 가장 간단한 방법입니다. ONTAP에서 작업을 가져오기 또는 수행하기 위해 주로 알림 스크립팅에 사용됩니다. 선택적 timeout 인수는 클라이언트에서 명령이 완료될 수 있는 최대 시간 제한(초)을 설정합니다. 기본값은 0(계속 대기)입니다.
 a| 
ONTAP로부터 수신한 경우



 a| 
'um run query <sql command>'
 a| 
SQL 쿼리를 실행합니다. 데이터베이스에서 읽은 쿼리만 허용됩니다. 업데이트, 삽입 또는 삭제 작업은 지원되지 않습니다.
 a| 
결과는 표 형식으로 표시됩니다. 빈 집합이 반환되거나 구문 오류 또는 잘못된 요청이 있으면 적절한 오류 메시지가 표시됩니다.



 a| 
''um datasource add -u <username> -P <password>[-t <protocol>][-p <port>] <hostname- or -ip>'
 a| 
관리되는 스토리지 시스템 목록에 데이터 소스를 추가합니다. 데이터 소스는 스토리지 시스템에 대한 접속 방식을 설명합니다. 데이터 소스를 추가할 때 -u(사용자 이름) 및 -P(암호) 옵션을 지정해야 합니다. t(프로토콜) 옵션은 클러스터(http 또는 https)와 통신하는 데 사용되는 프로토콜을 지정합니다. 프로토콜을 지정하지 않으면 두 프로토콜 모두 -p(포트) 옵션이 클러스터와 통신하는 데 사용되는 포트를 지정합니다. 포트를 지정하지 않으면 해당 프로토콜의 기본값이 시도됩니다. 이 명령은 스토리지 관리자만 실행할 수 있습니다.
 a| 
사용자에게 인증서를 수락하라는 메시지가 표시되고 해당 메시지가 인쇄됩니다.



 a| 
'<datasource-id>' 데이터 소스 목록 [<datasource-id>]'
 a| 
관리되는 스토리지 시스템의 데이터 소스를 표시합니다.
 a| 
'ID Address Port, Protocol Acquisition Status, Analysis Status, Communication Status, Acquisition Message, 및 분석 메시지'를 참조하십시오.



 a| 
'<datasource modify[-h<hostname-or-ip>] [-u<username>] [-P<password>] [-t<protocol>] [-p <port>] <datasource-id>'
 a| 
하나 이상의 데이터 소스 옵션을 수정합니다. 스토리지 관리자만 실행할 수 있습니다.
 a| 
해당 메시지를 표시합니다.



 a| 
'um datasource remove <datasource-id>'
 a| 
Unified Manager에서 데이터 소스(클러스터)를 제거합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
'<옵션 목록[<옵션>. ]
 a| 
에는 set 명령을 사용하여 구성할 수 있는 모든 옵션이 나와 있습니다.
 a| 
이름, 값, 기본값, 다시 시작 필요 등의 값을 표 형식으로 표시합니다



 a| 
``um option set <option-name>=<option-value>[<option-name>=<option-value>... ]
 a| 
하나 이상의 옵션을 설정합니다. 명령은 스토리지 관리자만 실행할 수 있습니다.
 a| 
해당 메시지를 표시합니다.



 a| 
UM 버전
 a| 
Unified Manager 소프트웨어 버전을 표시합니다.
 a| 
버전 ("9.6")



 a| 
``um LUN list[-q][-ObjectType<object-id>]'
 a| 
지정된 객체에서 필터링한 후 LUN을 나열합니다. q는 헤더를 표시하지 않는 모든 명령에 적용할 수 있습니다. ObjectType은 LUN, qtree, 클러스터, 볼륨, 할당량, 또는 svm.

예를 들면 다음과 같습니다.

* "um LUN list-cluster 1" *

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 LUN이 ID 1로 나열됩니다.
 a| 
표 형식으로 ID와 LUN 경로를 표시합니다



 a| 
''um svm list[-q][-ObjectType<object-id>]'
 a| 
지정된 객체에서 필터링한 후 스토리지 VM을 나열합니다. ObjectType은 LUN, qtree, 클러스터, 볼륨, 할당량, 또는 svm.

예를 들면 다음과 같습니다.

* ''um svm list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 스토리지 VM이 ID 1로 나열됩니다.
 a| 
Name과 Cluster ID를 표 형식으로 표시합니다



 a| 
''um qtree list[-q][-ObjectType<object-id>]'
 a| 
지정된 객체에서 필터링한 후 qtree를 나열합니다. q는 헤더를 표시하지 않는 모든 명령에 적용할 수 있습니다. ObjectType은 LUN, qtree, 클러스터, 볼륨, 할당량, 또는 svm.

예를 들면 다음과 같습니다.

* 'um qtree list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 명령은 클러스터 내의 모든 qtree를 ID 1로 나열합니다.
 a| 
표 형식으로 Qtree ID와 Qtree Name의 값을 표시합니다



 a| 
'<um disk list[-q][-ObjectType<object-id>]'
 a| 
지정된 개체에서 필터링한 후 디스크를 나열합니다. ObjectType은 디스크, 집계, 노드 또는 클러스터일 수 있습니다.

예를 들면 다음과 같습니다.

* "um disk list - cluster 1" *

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 디스크가 ID 1과 함께 나열됩니다.
 a| 
다음 값을 표 형식 "ObjectType and object-id"로 표시합니다.



 a| 
``um 클러스터 목록[-q][-ObjectType<object-id>]'
 a| 
지정된 개체에서 필터링한 후 클러스터가 나열됩니다. ObjectType은 디스크, 집계, 노드, 클러스터, LUN, Qtree, 볼륨, 할당량 또는 svm.

예를 들면 다음과 같습니다.

* 'um cluster list-aggr 1'

이 예제에서 "-aggr"은 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 ID가 1인 애그리게이트가 속해 있는 클러스터가 나열됩니다.
 a| 
Name, Full Name, Serial Number, DataSource ID, Last Refresh Time, 및 리소스 키'를 선택합니다.



 a| 
''um cluster node list[-q][-ObjectType<object-id>]'
 a| 
지정된 객체에서 필터링한 후 클러스터 노드를 나열합니다. ObjectType은 디스크, 집계, 노드 또는 클러스터일 수 있습니다.

예를 들면 다음과 같습니다.

* 'um cluster node list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 명령은 클러스터 내의 모든 노드를 ID 1로 나열합니다.
 a| 
다음 값을 표 형식 '이름 및 클러스터 ID'로 표시합니다.



 a| 
'<um volume list[-q][-ObjectType<object-id>]'
 a| 
지정된 개체에서 필터링한 후 볼륨을 나열합니다. ObjectType은 LUN, qtree, 클러스터, 볼륨, 할당량, SVM 또는 애그리게이트.

예를 들면 다음과 같습니다.

* 'um volume list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 볼륨이 ID 1로 나열됩니다.
 a| 
다음 값을 표 형식 '볼륨 ID 및 볼륨 이름'으로 표시합니다.



 a| 
''um quota user list[-q][-ObjectType<object-id>]'
 a| 
지정된 개체에서 필터링한 후 할당량 사용자를 나열합니다. ObjectType은 qtree, 클러스터, 볼륨, 할당량 또는 svm일 수 있습니다.

예를 들면 다음과 같습니다.

* 'um quota user list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 할당량 사용자에게 ID가 1로 표시됩니다.
 a| 
ID, 이름, SID, 이메일 등 표 형식으로 다음 값을 표시합니다.



 a| 
''um aggr list[-q][-ObjectType<object-id>]'
 a| 
지정된 개체에서 필터링한 후 애그리게이트를 나열합니다. ObjectType은 디스크, 집계, 노드, 클러스터 또는 볼륨일 수 있습니다.

예를 들면 다음과 같습니다.

* 'um aggr list-cluster 1'

이 예제에서 "-cluster"는 objectType 이고 "1"은 objectId입니다. 이 명령을 실행하면 클러스터 내의 모든 애그리게이트가 ID 1로 나열됩니다.
 a| 
다음 값을 표 형식 '애그리게이트 ID 및 애그리게이트 이름'으로 표시합니다.



 a| 
'um event ack <event-ids>'
 a| 
하나 이상의 이벤트를 승인합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
'<event-ids>'um event resolve<event-ids>'
 a| 
하나 이상의 이벤트를 확인합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
'<사용자 이름><event-id>' 이벤트가 발생합니다
 a| 
사용자에게 이벤트를 할당합니다.
 a| 
해당 메시지를 표시합니다.



 a| 
'<um event list[-s<source>][-S<event-state-filter-list>. ] [<event-id>. ]
 a| 
시스템 또는 사용자가 생성한 이벤트를 나열합니다. 소스, 상태 및 ID를 기준으로 이벤트를 필터링합니다.
 a| 
표 형식 '소스, 소스 유형, 이름, 심각도, 상태'로 다음 값을 표시합니다. User and Timestamp'(사용자 및 타임스탬프)를 선택합니다.



 a| 
'um backup restore -f <backup_file_path_and_name>'
 a| 
7z 파일을 사용하여 MySQL 데이터베이스 백업을 복원합니다.
 a| 
해당 메시지를 표시합니다.

|===