---
permalink: events/reference_snapmirror_and_vault_relationship_events.html 
sidebar: sidebar 
keywords: asynchronous, mirror, vault, relationship, events, impact area, protection 
summary: 비동기식 미러 및 볼트 관계 이벤트는 비동기식 SnapMirror 및 볼트 관계의 상태에 대한 정보를 제공하여 잠재적인 문제를 모니터링할 수 있도록 합니다. 볼륨 및 스토리지 VM 보호 관계 모두에 대해 비동기식 미러 및 볼트 관계 이벤트가 지원됩니다. 그러나 저장소 VM 재해 복구에는 볼트 관계만 지원되지 않습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= 비동기식 미러 및 볼트 관계 이벤트입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기식 미러 및 볼트 관계 이벤트는 비동기식 SnapMirror 및 볼트 관계의 상태에 대한 정보를 제공하여 잠재적인 문제를 모니터링할 수 있도록 합니다. 볼륨 및 스토리지 VM 보호 관계 모두에 대해 비동기식 미러 및 볼트 관계 이벤트가 지원됩니다. 그러나 저장소 VM 재해 복구에는 볼트 관계만 지원되지 않습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 충격 영역: 보호

[NOTE]
====
또한 스토리지 VM 재해 복구에서 보호되지만 구성요소 오브젝트 관계에서는 보호되지 않는 스토리지 VM에 대해 SnapMirror 및 Vault 관계 이벤트가 생성됩니다.

====
|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
비동기 미러와 볼트가 비정상(문서 대칭 복사됨 RelationshipUnhealthy)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트 연결이 끊어짐(문서:EvtMirrorVaultRelationshipStateBrokenoff)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 초기화 실패(문서 대칭 복사 VaultRelationshipInitializeFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 업데이트 실패(문서 대칭 복사. RelationshipUpdateFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 오류(문서 대칭 복사. RelationshipLagError)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 미러 및 볼트 지연 경고(문서 대칭 복사. RelationshipLagWarning)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 미러 및 볼트 재동기화 실패(문서 대칭 복사. RelationshipResyncFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류

|===
[NOTE]
====
"SnapMirror 업데이트 실패" 이벤트가 Active IQ 포털(Config Advisor)에 의해 발생합니다.

====