---
permalink: events/reference_what_suggested_actions_section_displays.html 
sidebar: sidebar 
keywords: suggest, actions, section, displays 
summary: 이벤트 세부 정보 페이지의 권장 조치 섹션에서는 이벤트에 대해 가능한 원인을 제공하고 사용자가 직접 이벤트를 해결할 수 있도록 몇 가지 조치를 제안합니다. 제안된 작업은 위반된 이벤트 유형 또는 임계값 유형에 따라 사용자 정의됩니다. 
---
= 권장 조치 섹션이 표시되는 내용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 세부 정보 페이지의 권장 조치 섹션에서는 이벤트에 대해 가능한 원인을 제공하고 사용자가 직접 이벤트를 해결할 수 있도록 몇 가지 조치를 제안합니다. 제안된 작업은 위반된 이벤트 유형 또는 임계값 유형에 따라 사용자 정의됩니다.

이 영역은 일부 이벤트 유형에 대해서만 표시됩니다.

경우에 따라 특정 작업 수행 지침을 포함하여 제안된 여러 작업에 대한 추가 정보를 참조하는 * 도움말 * 링크가 페이지에 제공됩니다. 그 중에는 Unified Manager, ONTAP System Manager, OnCommand Workflow Automation, ONTAP CLI 명령 또는 이러한 툴의 조합을 사용하는 것도 포함될 수 있습니다.

이 이벤트를 해결하기 위한 지침으로만 여기에서 제안하는 조치를 고려해야 합니다. 이 이벤트를 해결하기 위해 취하는 조치는 사용자 환경의 컨텍스트를 기반으로 해야 합니다.

객체 및 이벤트를 자세히 분석하려면 * 워크로드 분석 * 버튼을 클릭하여 워크로드 분석 페이지를 표시합니다.

Unified Manager에서 완벽하게 진단하고 단일 해결책을 제공할 수 있는 특별한 이벤트가 있습니다. 사용 가능한 경우 해당 해상도는 * Fix it * 버튼과 함께 표시됩니다. Unified Manager에서 이벤트를 발생시키는 문제를 해결하도록 하려면 이 버튼을 클릭합니다.

Active IQ 플랫폼 이벤트의 경우 이 섹션에는 문제 및 가능한 해결책을 설명하는 NetApp 기술 자료 문서(있는 경우)에 대한 링크가 포함될 수 있습니다. 외부 네트워크에 액세스할 수 없는 사이트에서는 Knowledgebase 문서의 PDF가 로컬로 열립니다. PDF는 Unified Manager 인스턴스로 수동으로 다운로드하는 규칙 파일의 일부입니다.
