---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, snapmirror business continuity, smbc, sm-bc 
summary: 데이터 스토리지 토폴로지 구축에 따라 Unified Manager를 사용하여 다양한 유형의 SnapMirror 보호 관계를 구성할 수 있습니다. SnapMirror 보호의 모든 변형 기능은 페일오버 재해 복구 보호를 제공하지만 성능, 버전 유연성 및 다중 백업 복사본 보호에 있어 다른 기능을 제공합니다. 
---
= SnapMirror 보호 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 스토리지 토폴로지 구축에 따라 Unified Manager를 사용하여 다양한 유형의 SnapMirror 보호 관계를 구성할 수 있습니다. SnapMirror 보호의 모든 변형 기능은 페일오버 재해 복구 보호를 제공하지만 성능, 버전 유연성 및 다중 백업 복사본 보호에 있어 다른 기능을 제공합니다.



== 기존의 SnapMirror 비동기식 보호 관계

기존의 SnapMirror 비동기식 보호 기능은 소스 볼륨과 타겟 볼륨 간의 블록 복제 미러 보호 기능을 제공합니다.

기존 SnapMirror 관계에서는 미러 작업이 블록 복제를 기반으로 하므로 미러 작업이 대체 SnapMirror 관계보다 더 빠르게 실행됩니다. 그러나 기존 SnapMirror 보호에서는 동일한 주요 릴리즈(예: 버전 8.x에서 8.x 또는 9.x에서 9.x)내의 소스 볼륨과 동일한 부 버전 이상의 ONTAP 소프트웨어에서 타겟 볼륨을 실행해야 합니다. 대상이 이전 주 버전을 실행하고 있으므로 9.1 소스에서 9.0 대상으로 복제하는 것은 지원되지 않습니다.



== 버전에 상관없이 유연하게 복제할 수 있는 SnapMirror 비동기식 보호

버전에 상관없이 유연하게 복제할 수 있는 SnapMirror 비동기식 보호 기능은 소스 볼륨과 타겟 볼륨 간에 논리적 복제 미러 보호 기능을 제공합니다. 이는 서로 다른 버전의 ONTAP 8.3.1, 8.3.1에서 9.1, 9.2.2 에서 9.2 등)로 실행 중인 볼륨에서도 마찬가지입니다.

버전에 상관없이 유연하게 복제 가능한 SnapMirror 관계에서는 미러링 작업이 기존 SnapMirror 관계에서와 같이 빠르게 실행되지 않습니다.

느린 실행 속도 때문에 버전에 상관없이 유연하게 복제 보호를 지원하는 SnapMirror는 다음 중 하나를 구현하는 데 적합하지 않습니다.

* 소스 객체에는 보호할 파일이 1,000만 개 이상 있습니다.
* 보호 데이터에 대한 복구 지점 목표는 2시간 이하입니다. 즉, 대상에는 항상 소스의 데이터보다 2시간 이상 오래된 미러링된 복구 가능한 데이터가 포함되어 있어야 합니다.


나열된 상황 중 하나에서 기본 SnapMirror 보호의 신속한 블록 복제 기반 실행이 필요합니다.



== 버전에 상관없이 유연하게 복제 및 백업 옵션을 사용하는 SnapMirror 비동기 보호

버전에 상관없이 유연하게 복제 및 백업 옵션을 사용하는 SnapMirror 비동기 보호 기능은 소스 볼륨과 타겟 볼륨 간의 미러링 보호 기능과 미러링된 데이터의 여러 복사본을 대상에 저장하는 기능을 제공합니다.

스토리지 관리자는 소스에서 타겟으로 미러링되는 스냅샷 복사본을 지정할 수 있으며, 복사본이 소스에서 삭제되더라도 해당 복사본을 대상에서 보존할 기간을 지정할 수도 있습니다.

버전에 상관없이 유연한 복제 및 백업 옵션과 SnapMirror 관계를 사용하면 기존 SnapMirror 관계에서와 같이 미러링 작업이 신속하게 실행되지 않습니다.



== SnapMirror 유니파이드 복제(미러링 및 소산)

SnapMirror 통합 복제를 사용하면 동일한 대상 볼륨에 재해 복구 및 아카이빙을 구성할 수 있습니다. SnapMirror와 마찬가지로 통합 데이터 보호는 처음 호출할 때 기본 전송을 수행합니다. 기본 통합 데이터 보호 정책 ""MirorAndVault""에 따른 기본 전송은 소스 볼륨의 스냅샷 복사본을 만든 다음, 해당 복사본과 데이터 블록이 대상 볼륨에 참조되도록 전송합니다. SnapVault와 마찬가지로, 통합 데이터 보호에도 이전 Snapshot 복사본이 기본 안에 포함되지 않습니다.



== SnapMirror Synchronous 보호 및 엄격한 동기화

"사전" 동기화로 SnapMirror Synchronous를 활용하면 1차 볼륨과 2차 볼륨이 항상 서로 진정한 복제본으로 유지됩니다. 보조 볼륨에 데이터를 쓰려고 할 때 복제 실패가 발생하면 운영 볼륨에 대한 클라이언트 입출력이 중단됩니다.



== SnapMirror Synchronous 보호 - 정기적인 동기화

"리큘러" 동기화를 통한 SnapMirror Synchronous 보호에서는 1차 볼륨과 2차 볼륨이 항상 서로 진정한 복사본일 필요가 없으며, 따라서 1차 볼륨의 가용성이 보장됩니다. 보조 볼륨에 데이터를 쓰려고 할 때 복제 실패가 발생하면 운영 볼륨과 보조 볼륨이 동기화되지 않고 클라이언트 입출력이 운영 볼륨으로 계속됩니다.

[NOTE]
====
상태: 모든 볼륨 보기 또는 볼륨/상태 세부 정보 페이지에서 동기 보호 관계를 모니터링할 때는 복원 단추와 관계 작업 단추를 사용할 수 없습니다.

====


== SnapMirror Synchronous 비즈니스 연속성

ONTAP 9.8 이상에서는 SnapMirror SM-BC(비즈니스 연속성) 기능을 사용할 수 있으며, 이 기능을 사용하여 LUN이 있는 애플리케이션을 보호할 수 있으므로 애플리케이션이 투명하게 페일오버할 수 있으므로 재해 발생 시 비즈니스 연속성을 보장할 수 있습니다.

Unified Manager에서 클러스터 및 스토리지 가상 머신에서 사용 가능한 CG(Consistency Group)를 위한 동기식 SnapMirror 관계를 검색하고 모니터링할 수 있습니다. SM-BC는 AFF 클러스터 또는 모든 ASA(SAN 어레이) 클러스터에서 지원되며, 운영 클러스터와 보조 클러스터는 AFF 또는 ASA가 될 수 있습니다. SM-BC는 iSCSI 또는 FCP LUN을 사용하여 애플리케이션을 보호합니다.

SM-BC 관계에 의해 보호되는 볼륨 및 LUN을 볼 때 보호 관계, 볼륨 인벤토리의 정합성 보장 그룹, 정합성 보장 그룹 관계의 보호 토폴로지 보기, 정합성 보장 그룹 관계에 대한 기간별 데이터 보기 등을 통합적으로 확인할 수 있습니다. 보고서를 다운로드할 수도 있습니다. 또한 정합성 보장 그룹 관계 요약, 정합성 보장 그룹 관계 검색 지원 및 정합성 보장 그룹에 의해 보호되는 볼륨에 대한 정보를 확인할 수 있습니다.

관계 페이지에서 소스 및 대상 스토리지 객체와 정합성 보장 그룹에 의해 보호되는 해당 관계의 보호를 정렬, 필터링 및 확장할 수도 있습니다.

SnapMirror Synchronous 비즈니스 연속성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap/smbc/index.html["SM-BC용 ONTAP 9 문서"].
