---
permalink: data-protection/reference_relationship_last_1_month_transfer_status_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer status, view 
summary: 관계: 지난 1개월 전송 상태 보기를 사용하면 비동기 관계의 볼륨 및 스토리지 VM에 대한 일정 기간 동안의 전송 추세를 분석할 수 있습니다. 이 페이지에는 전송이 성공 또는 실패인지 여부도 표시됩니다. 
---
= 관계: 최근 1개월 전송 상태 보기
:icons: font
:imagesdir: ../media/


[role="lead"]
관계: 지난 1개월 전송 상태 보기를 사용하면 비동기 관계의 볼륨 및 스토리지 VM에 대한 일정 기간 동안의 전송 추세를 분석할 수 있습니다. 이 페이지에는 전송이 성공 또는 실패인지 여부도 표시됩니다.

페이지 위쪽에 있는 컨트롤을 사용하면 특정 개체를 찾고, 필터를 만들고, 적용하여 표시된 데이터 목록의 범위를 좁히고, 페이지에서 열을 추가/제거/재정렬하고, 페이지의 데이터를 ".csv", ".pdf" 또는 ".xlsx" 파일로 내보낼 수 있습니다. 페이지를 사용자 지정한 후 결과를 사용자 정의 보기로 저장한 다음 이 데이터의 보고서를 정기적으로 생성 및 이메일로 전송할 수 있습니다. Filter * 옵션을 사용하면 볼륨 또는 스토리지 VM과 같이 선택한 스토리지 시스템만 볼 수 있습니다. 동일한 보고서가 스토리지 페이지와 선택한 스토리지 엔티티에 대해서만 표시됩니다. 예를 들어 볼륨 관계를 보려면 * 스토리지 * > * 스토리지 VM * > * 관계: 지난 1개월 전송 상태 * 메뉴 또는 * 보호 * > * 관계 * > * 관계: Last 1 Month Transfer Status * (지난 1개월 전송 상태 *) 메뉴에서 * Filter * (필터 *)를 사용하여 볼륨에 대한 데이터만 볼 수 있습니다.

* * 소스 볼륨 *
+
소스 볼륨 이름을 표시합니다.

* * 대상 볼륨 *
+
대상 볼륨 이름을 표시합니다.

* * 작업 유형 *
+
볼륨 전송 유형을 표시합니다.

* * 작업 결과 *
+
볼륨 전송 성공 여부를 표시합니다.

* * 전송 시작 시간 *
+
볼륨 전송 시작 시간을 표시합니다.

* * 전송 종료 시간 *
+
볼륨 전송 종료 시간을 표시합니다.

* * 전송 기간 *
+
볼륨 전송을 완료하는 데 소요된 시간(시간)을 표시합니다.

* * 전송 크기 *
+
전송된 볼륨의 크기(MB)를 표시합니다.

* * 소스 SVM *
+
SVM(스토리지 가상 시스템) 이름을 표시합니다.

* * 소스 클러스터 *
+
소스 클러스터 이름을 표시합니다.

* * 대상 SVM *
+
대상 SVM 이름을 표시합니다.

* * 대상 클러스터 *
+
대상 클러스터 이름을 표시합니다.


