---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: 스토리지 VM 연결 페이지에서는 소스 및 대상 스토리지 VM 간의 기존 스토리지 VM 연결을 볼 수 있습니다. 
---
= 스토리지 VM 연결 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 머신(스토리지 VM)은 리소스 선택 및 2차 볼륨 프로비저닝을 위해 파트너 애플리케이션이 사용하는 소스 스토리지 VM에서 대상 스토리지 VM으로 매핑되는 것입니다.

대상 스토리지 VM이 보조 대상인지 또는 3차 대상인지에 관계없이 소스 스토리지 VM과 대상 스토리지 VM 간에 연결이 생성됩니다. 2차 대상 스토리지 VM을 소스로 사용하여 3차 대상 스토리지 VM과 연결을 생성할 수 없습니다.

애플리케이션 관리자 또는 스토리지 관리자는 * 보호 * > * 스토리지 VM 연결 * 페이지에서 사용자 환경의 스토리지 VM 연결을 볼 수 있습니다.

SVM은 다음 세 가지 방법으로 연결할 수 있습니다.

* * 모든 스토리지 VM 연결 *: 운영 소스 스토리지 VM과 하나 이상의 타겟 SVM 간에 연결을 생성할 수 있습니다. 즉, 현재 보호가 필요한 모든 기존 SVM과 향후에 생성된 SVM이 지정된 타겟 SVM과 연결됩니다. 예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 한 위치의 하나 이상의 대상 SVM에 백업할 수 있습니다.
* * 특정 스토리지 VM 연결 *: 특정 소스 스토리지 VM과 하나 이상의 특정 타겟 SVM 간에 연결을 생성할 수 있습니다. 예를 들어, 데이터가 서로 분리되어 있어야 하는 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하여 특정 소스 스토리지 VM을 해당 클라이언트에만 할당된 특정 대상 스토리지 VM에 연결할 수 있습니다.
* * 외부 스토리지 VM과 연결 *: 소스 스토리지 VM과 대상 스토리지 VM의 유연한 외부 볼륨 간에 연결을 생성할 수 있습니다.




== 스토리지 VM 연결을 생성합니다

스토리지 가상 시스템 연결 생성 마법사를 사용하면 파트너 보호 애플리케이션에서 소스 스토리지 VM을 대상 스토리지 VM에 연결하여 SnapMirror 및 SnapVault 관계에 사용할 수 있습니다. 파트너 애플리케이션은 대상 볼륨의 초기 프로비저닝 시 이러한 연결을 사용하여 선택할 리소스를 결정합니다

.시작하기 전에
* 연결하려는 스토리지 VM이 이미 있어야 합니다.
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


모든 소스 스토리지 VM 및 관계 유형에 대해 각 타겟 클러스터에서 하나의 대상 스토리지 VM만 선택할 수 있습니다.

삭제 및 생성 기능을 사용하여 연결을 변경하면 이후 프로비저닝 작업에만 영향을 줍니다. 기존 타겟 볼륨은 이동하지 않습니다.

.단계
. 왼쪽 탐색 창에서 * 보호 * > * 스토리지 VM 연결 * 을 클릭합니다.
. 스토리지 VM 연결 * 페이지에서 * 생성 * 을 클릭합니다.
+
스토리지 가상 머신 연결 생성 * 마법사가 시작됩니다.

. 다음 소스 중 하나를 선택합니다.
+
** * 모두 *
+
운영 스토리지 VM 소스와 하나 이상의 대상 스토리지 VM 간의 연결을 생성하려는 경우 이 옵션을 선택합니다. 즉, 현재 보호가 필요한 모든 기존 스토리지 VM과 향후에 생성되는 모든 스토리지 VM이 지정된 대상 스토리지 VM에 연결됩니다. 예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 한 위치에 있는 하나 이상의 대상 스토리지 VM에 백업할 수 있습니다.

** * 단일 *
+
하나 이상의 대상 스토리지 VM에 연결된 특정 소스 스토리지 VM을 선택하려면 이 옵션을 선택합니다. 예를 들어, 데이터가 서로 분리되어 있어야 하는 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하여 특정 스토리지 VM 소스를 해당 클라이언트에만 할당된 특정 스토리지 VM 대상에 연결합니다.

** * 없음(외부) *
+
소스 스토리지 VM과 대상 스토리지 VM의 유연한 외부 볼륨 간에 연결을 생성하려는 경우 이 옵션을 선택합니다.



. 생성할 보호 관계 유형 중 하나 또는 둘 모두를 선택합니다.
+
** * SnapMirror *
** * SnapVault *


. 다음 * 을 클릭합니다.
. 하나 이상의 스토리지 VM 보호 대상을 선택합니다.
. 마침 * 을 클릭합니다.




== 스토리지 VM 연결을 삭제합니다

파트너 애플리케이션에 대한 스토리지 VM 연결을 삭제하여 소스 및 대상 스토리지 VM 간의 보조 프로비저닝 관계를 제거할 수 있습니다. 예를 들어, 대상 스토리지 VM이 가득 차서 새 스토리지 VM 보호 연결을 생성하려는 경우 이 작업을 수행할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

스토리지 VM 연결을 하나 이상 선택할 때까지 * Delete * 버튼이 비활성화됩니다. 삭제 및 생성 기능을 사용하여 연결을 변경하면 향후 프로비저닝 작업에만 영향을 미치며 기존 대상 볼륨은 이동하지 않습니다.

.단계
. 왼쪽 탐색 창에서 * 보호 * > * 스토리지 VM 연결 * 을 클릭합니다.
. 스토리지 VM 연결을 하나 이상 선택합니다.
+
삭제 * 버튼이 활성화됩니다.

. 삭제 * 를 클릭합니다
+
경고 대화 상자가 표시됩니다.

. 계속하려면 * 예 * 를 클릭하십시오.
+
선택한 스토리지 VM 연결이 목록에서 제거됩니다.


