---
permalink: data-protection/task_restore_data_use_health_volume_details_page.html 
sidebar: sidebar 
keywords: restore, data, volume, health details page 
summary: 볼륨/상태 세부 정보 페이지의 복원 기능을 사용하여 스냅샷 복사본에서 덮어쓰기 또는 삭제된 파일, 디렉토리 또는 전체 볼륨을 복원할 수 있습니다. 
---
= 볼륨 및 볼륨/상태 세부 정보 페이지를 사용하여 데이터 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 및 볼륨/상태 세부 정보 페이지의 복원 기능을 사용하여 스냅샷 복사본에서 덮어쓰기 또는 삭제된 파일, 디렉토리 또는 전체 볼륨을 복원할 수 있습니다.

.시작하기 전에
애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


NOTE: 다음 사항을 참고하십시오.

* NTFS 파일 스트림은 복원할 수 없습니다.
* 다음과 같은 경우에는 복원 옵션을 사용할 수 없습니다.
+
** 볼륨 ID는 알 수 없습니다. 예를 들어, 인터클러스터 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우입니다.
** 볼륨은 SnapMirror Synchronous 복제에 대해 구성됩니다.




.단계
. 왼쪽 탐색 창에서 * 스토리지 > 볼륨 * 으로 이동합니다.
. 볼륨을 선택하고 * 복원 * 버튼을 클릭합니다. 또는 볼륨을 클릭하여 * 볼륨/상태 세부 정보 > 작업 > 복원 * 으로 이동합니다. Restore(복원) 대화 상자가 표시됩니다. 이 페이지에 대한 자세한 내용은 을 참조하십시오 link:../data-protection/reference_restore_dialog_box.html["복원 대화 상자"].
. 기본값과 다른 경우 데이터를 복원할 볼륨 및 스냅샷 복사본을 선택합니다.
. 소스 LUN과 같이 복구할 항목을 선택합니다.
+
전체 볼륨을 복원하거나 복원할 폴더 및 파일을 지정할 수 있습니다.

. 선택한 항목을 복원할 위치를 * 원래 위치 * 또는 * 대체 기존 위치 * 중에서 선택합니다.
. 기존 위치를 다른 위치로 선택하는 경우 다음 중 하나를 수행합니다.
+
** Restore Path(복원 경로) 텍스트 필드에 데이터를 복원할 위치의 경로를 입력한 다음 * Select Directory(디렉터리 선택) * 를 클릭합니다.
** 찾아보기 * 를 클릭하여 디렉터리 찾아보기 대화 상자를 시작하고 다음 단계를 완료합니다.
+
... 복원할 대상 클러스터, 스토리지 VM(SVM) 및 볼륨을 선택합니다.
... 이름 테이블에서 복원해야 하는 디렉터리 이름을 선택합니다.
... 디렉터리 선택 * 을 클릭합니다.




. 복원 * 을 클릭합니다.
+
복원 프로세스가 시작됩니다. 백엔드에서 작업을 생성하여 복원 프로세스를 완료합니다.

. 작업 진행률을 보려면 왼쪽 탐색 창에서 * 보호 > 작업 * 으로 이동하여 작업 목록에서 복원 작업의 상태를 확인합니다.
+
[NOTE]
====
NDMP 오류가 있는 Cloud Volumes ONTAP HA 클러스터 간에 복구 작업이 실패할 경우 대상이 소스 시스템의 클러스터 관리 LIF와 통신할 수 있도록 타겟 클러스터에 명시적 AWS 경로를 추가해야 할 수 있습니다. BlueXP를 사용하여 이 구성 단계를 수행합니다.

====

