---
permalink: data-protection/task_configure_connection_between_workflow_automation_um.html 
sidebar: sidebar 
keywords: configure, connection, workflow, automation, unified manager 
summary: 'WFA(OnCommand Workflow Automation)와 Unified Manager 간에 보안 연결을 구성할 수 있습니다. Workflow Automation에 연결하면 SnapMirror 및 SnapVault 구성 워크플로우와 같은 보호 기능을 사용할 수 있으며 SnapMirror 관계를 관리하는 데 필요한 명령을 사용할 수 있습니다.' 
---
= Workflow Automation과 Unified Manager 간 연결 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation)와 Unified Manager 간에 보안 연결을 구성할 수 있습니다. Workflow Automation에 연결하면 SnapMirror 및 SnapVault 구성 워크플로우와 같은 보호 기능을 사용할 수 있으며 SnapMirror 관계를 관리하는 데 필요한 명령을 사용할 수 있습니다.

* 필요한 것 *

* Workflow Automation의 설치 버전은 5.1 이상이어야 합니다.
+
[NOTE]
====
WFA 5.1에는 "'Clustered Data ONTAP를 관리하기 위한 WFA 팩'이 포함되어 있으므로 NetApp Storage Automation Store에서 이 팩을 다운로드하여 이전에 필요한 WFA 서버에 별도로 설치할 필요가 없습니다.  https://["ONTAP 관리를 위한 WFA 팩"]

====
* WFA 및 Unified Manager 연결을 지원하려면 Unified Manager에서 생성한 데이터베이스 사용자의 이름이 있어야 합니다.
+
이 데이터베이스 사용자에게 통합 스키마 사용자 역할이 할당되어야 합니다.

* Workflow Automation에서 관리자 역할 또는 설계자 역할을 할당해야 합니다.
* Workflow Automation 설정을 사용하려면 호스트 주소, 포트 번호 443, 사용자 이름 및 암호가 있어야 합니다.
* 애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.


.단계
. 왼쪽 탐색 창에서 * 일반 * > * Workflow Automation * 을 클릭합니다.
. Workflow Automation 페이지 * 의 * 데이터베이스 사용자 * 영역에서 이름을 선택하고 Unified Manager 및 Workflow Automation 연결을 지원하기 위해 생성한 데이터베이스 사용자의 암호를 입력합니다.
. 페이지의 * Workflow Automation Credentials * 영역에서 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)와 Workflow Automation 설정의 사용자 이름 및 암호를 입력합니다.
+
Unified Manager 서버 포트(포트 443)를 사용해야 합니다.

. 저장 * 을 클릭합니다.
. 자체 서명된 인증서를 사용하는 경우 * 예 * 를 클릭하여 보안 인증서를 승인합니다.
+
Workflow Automation 페이지가 표시됩니다.

. 웹 UI를 다시 로드하고 Workflow Automation 기능을 추가하려면 * 예 * 를 클릭합니다.


* 관련 정보 *

http://["NetApp 설명서: OnCommand Workflow Automation(최신 릴리즈)"]
