---
permalink: data-protection/view-lun-relationships.html 
sidebar: sidebar 
keywords: LUN, SM-BC, SnapMirror Business Continuity, Consistency Group, CG 
summary: SM-BC로 보호되는 LUN의 통합 뷰 
---
= 정합성 보장 그룹 관계에서 LUN 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 환경에서 LUN을 사용하여 애플리케이션을 보호하기 위해 SM-BC(SnapMirror 비즈니스 연속성)를 지원하는 경우 Active IQ Unified Manager에서 해당 LUN을 보고 모니터링할 수 있습니다.

SM-BC는 SAN 환경의 페일오버 중에 RTO(복구 시간 목표)를 0으로 보장합니다. SM-BC를 지원하는 일반적인 구축 환경에서는 볼륨의 LUN이 정합성 보장 그룹 관계에 의해 보호됩니다.

이러한 운영 LUN과 보조 LUN은 복합 LUN이거나 UUID와 일련 번호가 같은 복제본 LUN 쌍입니다. 입출력 작업(읽기 및 쓰기 모두)은 이러한 복합 LUN의 소스 및 대상 사이트에서 멀티플렉싱되므로 투명성이 보장됩니다.

복합 LUN을 보려면 정합성 보장 그룹 관계의 일부인 LUN이 포함된 운영 클러스터와 보조 클러스터를 Unified Manager에서 추가하고 검색해야 합니다. iSCSI 및 FCP LUN만 지원됩니다.

SM-BC에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap/smbc/index.html["SM-BC용 ONTAP 9 문서"].

환경에서 복합 LUN을 보려면 다음 단계를 수행하십시오.

.단계
. 왼쪽 탐색 창에서 * 스토리지 * > * LUN * 을 클릭합니다.
. 보기 메뉴에서 * 관계 * > * 모든 LUN * 을 선택합니다.
+
관계: 모든 LUN 보기가 표시됩니다.



LUN 이름, 볼륨, LUN을 호스팅하는 스토리지 VM, 클러스터, 일관성 그룹 및 파트너 LUN과 같은 LUN 세부 정보를 볼 수 있습니다. 각 구성 요소를 클릭하여 세부 보기로 드릴다운할 수 있습니다. 정합성 보장 그룹을 클릭하면 관계 페이지로 이동합니다.

파트너 LUN을 클릭하면 파트너 LUN이 호스팅되는 스토리지 VM에 대한 스토리지 VM 세부 정보 페이지의 SAN 탭에서 구성 세부 정보를 볼 수 있습니다. 이니시에이터, 이니시에이터 그룹 등의 정보와 파트너 LUN의 다른 측면이 표시됩니다.

사용자 환경에서 보호된 LUN에 대한 보고서를 정렬, 필터링, 생성 및 업로드하는 표준 그리드 레벨 기능을 수행할 수 있습니다.
