---
permalink: data-protection/view-protection-status.html 
sidebar: sidebar 
keywords: view, volume, protection status, dashboard protection card, protection panel, protection widget 
summary: 데이터 보호 페이지는 데이터 센터의 모든 보호된 볼륨에 대한 데이터 보호 세부 사항에 대한 종합적인 뷰를 제공합니다. 
---
= 볼륨 보호 상태 보기
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 페이지는 단일 클러스터의 모든 보호된 볼륨 또는 데이터 센터의 모든 클러스터에 대한 데이터 보호 세부 정보에 대한 종합적인 뷰를 제공합니다.

대시보드의 데이터 보호 패널 맨 위에 있는 오른쪽 화살표를 클릭하면 이러한 세부 정보를 볼 수 있습니다. 이 화면에는 두 개의 섹션이 있습니다. 대시보드에서 모든 클러스터를 선택하면 * 모든 클러스터 * 섹션에 SnapMirror 관계 및 Snapshot 복사본으로 보호되는 데이터 센터 수준에서 모든 클러스터의 보호 상태가 표시됩니다. 개별 클러스터 * 섹션에서 특정 클러스터를 선택하여 해당 클러스터의 보호된 볼륨 상태를 볼 수 있습니다.

대시보드에서 단일 클러스터를 선택하면 이 페이지에 해당 클러스터의 보호된 볼륨에 대한 세부 정보가 표시됩니다.

각 막대 차트 위에 마우스를 올려 놓으면 각 카운트를 볼 수 있습니다. 막대 차트를 클릭하면 각 볼륨이 선택된 Volumes(볼륨) 화면으로 이동합니다. 각 이벤트의 링크를 클릭하면 이벤트 세부 정보 페이지로 이동합니다. 이벤트 관리 인벤토리 페이지에서 * 모두 보기 * 링크를 클릭하여 모든 활성 보호 이벤트를 볼 수 있습니다.

.단계
. 왼쪽 탐색 창에서 * 대시보드 * 를 클릭합니다.
. 모니터링되는 모든 클러스터에 대한 데이터 보호 상태를 볼 것인지 또는 단일 클러스터에 대한 데이터 보호 상태를 볼 것인지 여부에 따라 * All Clusters * 를 선택하거나 드롭다운 메뉴에서 단일 클러스터를 선택합니다.
. Data Protection 패널에서 오른쪽 화살표를 클릭합니다.




== 데이터 보호 페이지를 참조하십시오

데이터 보호 페이지에는 모든 클러스터의 보호된 볼륨에 대한 다음 패널이 표시됩니다.


NOTE: 스냅샷 복사본의 볼륨 수에 따라 소스 볼륨과 타겟 볼륨이 모두 고려됩니다. SnapMirror 관계의 경우 읽기 및 쓰기가 가능한 소스 볼륨이 계산됩니다. 대상 및 루트 볼륨은 고려되지 않습니다. SnapMirror 개수에는 동일한 클러스터 또는 다른 클러스터에 소스 및 대상이 있는 볼륨 수가 포함됩니다.

* * 스냅샷 개요 *: 다음과 같이 스냅샷 복사본으로 보호되는 볼륨에 대한 개요:
+
** Snapshot 복사본으로 보호되고 보호되지 않는 총 볼륨 수입니다.
+

NOTE: 볼륨을 보호됨 으로 고려하려면 볼륨의 스냅샷 복사본에 대한 일정을 설정해야 합니다.

** 스냅샷 복사본을 위해 예약 공간을 사용 중이거나 초과하는 총 볼륨 수입니다. 이 값은 사용된 디스크 공간의 양을 보거나 하나 이상의 스냅샷 복사본이 삭제된 경우 회수할 수 있는 공간을 계산하는 데 중요합니다.


* * SnapMirror 개요 *: 다음과 같이 SnapMirror 정책으로 보호되는 볼륨에 대한 개요:
+
** 볼륨 SnapMirror 관계, 스토리지 VM 재해 복구(SVM-DR), 조합 등 각 SnapMirror 정책으로 보호되는 볼륨 수
** SnapMirror 관계가 지연되는 총 볼륨 수 볼륨에 SnapMirror 관계가 여러 개인 경우 가장 심각한 지연이 선택됩니다.




개별 클러스터 목록에는 특정 클러스터에 대한 SnapMirror 관계 및 Snapshot 보호 상태가 표시됩니다.

* * Snapshot 복사본 분석 * 은 다음 정보를 자세히 설명합니다.
+
** 지난 24시간 동안 발생한 이벤트를 비롯하여 스냅샷 복사본에 대한 개별 이벤트입니다.
** 스냅샷 복사본으로 보호되고 보호되지 않는 볼륨에 대한 자세한 차트
** 예약된 스냅샷 복사본 용량을 사용, 사용하지 않음 및 위반한 볼륨 이 정보를 사용하여 하나 이상의 스냅샷 복사본이 삭제된 경우 활용되거나 재확보된 공간을 계산할 수 있습니다.
** 스냅샷 복사본 수를 기준으로 볼륨 수를 세분합니다. 반환되는 스냅샷 복사본 수는 온라인 상태이고 사용 가능한 볼륨에 대해서만 제공됩니다.


* * SnapMirror 분석 * 은 다음 정보를 자세히 설명합니다.
+
** 지난 24시간 동안 발생한 이벤트를 포함하여 SnapMirror 관계에 대해 발생한 개별 이벤트입니다
** 볼륨 SnapMirror 관계, 스토리지 VM 재해 복구(SVM-DR), 조합 등 각 SnapMirror 정책으로 보호되는 볼륨 수입니다.
** 비동기 미러, 비동기 볼트, 비동기 MirrorVault, StrictSync, SMBC(SnapMirror Business Continuity) 일관성 그룹 및 동기화와 같이 SnapMirror 관계 유형으로 보호되는 볼륨 수입니다.
** 정상 또는 비정상 상태의 볼륨 수입니다. 모든 SnapMirror 관계가 정상인 경우에만 볼륨이 양호한 것으로 간주됩니다.
** RPO(Recovery Point Objective) 지연 기간에 따른 볼륨 카운트의 브레이크업



